book: {
    # 起始场景
    init: '',

    # 场景列表
    scene_list:
      [
        'M01_S01_luoyuezhen_pomiao',
        'M01_S01_luoyuezhen_Time',
        'M01_S01_luoyuezhen_pomiaomenko',
        'M01_S02_luoyuezhen_hutongkou',
        'M01_S03_luoyuezhen_juminjie',
        'M01_S04_luoyuezhen_dalukou',
        'M01_S05_luoyuezhen_nanjieshi',
        'M01_S06_luoyuezhen_jishiyijiao',
      ],
  }
