book: {
    # 场景目录定位，YML新增必须在这里记录
    # 起始场景
    init: '',

    # 场景列表
    scene_list:
      [
        "scene_wzxx",
        "WZXX_[Chapters]",
        "WZXX_[START]",
        "WZXX_M1_N1_C001A_V",
        "WZXX_M1_N1_C001B_V",
        "WZXX_M1_N1_C001C_V",
        "WZXX_M1_N1_C001V",
        "WZXX_M1_N1_C002A_V",
        "WZXX_M1_N1_C002A_V1",
        "WZXX_M1_N1_C002V",
        "WZXX_M1_N1_C002B_V",
        "WZXX_M1_N1_C002C_V",
        "WZXX_M1_N1_C005_V",
        "WZXX_MasterEventVar_01",
        "WZXX_NormalEventVar_01",
      ],
      
    # 收集列表
    collect_list: [
      'collect_1',
      'collect_2',
    ],
    
  }
