book: {
    # 场景目录定位，YML新增必须在这里记录
    # 起始场景
    init: '',

    # 场景列表
    scene_list:
      [
        "scene_wzxx",
        "WZXX_[Chapters]",
        "WZXX_[START]",
        "WZXX_M1_N1_C000A_V",
        "WZXX_M1_N1_C000B_V",
        "WZXX_M1_N1_C000B_VA",
        "WZXX_M1_N1_C001A_V",
        "WZXX_M1_N1_C001B_V",
        "WZXX_M1_N1_C001C_V",
        "WZXX_M1_N1_C001V",
        "WZXX_M1_N1_C002A_V",
        "WZXX_M1_N1_C002B_V",
        "WZXX_M1_N1_C002C_V",
        "WZXX_M1_N1_C002V",
        "WZXX_M1_N1_C005_V",
        "WZXX_M1_N1_C005_VA",
        "WZXX_M1_N1_C006_V",
        "WZXX_M1_N1_C0017_V",
        "WZXX_M1_N1_C0018_V",
        "WZXX_M1_N1_C0018_VA",
        "WZXX_M1_N1_C0019_V",
        "WZXX_M1_N1_C0020_V",
        "WZXX_M1_N1_C0021_V",
        "WZXX_M1_N1_C0022_V",
        "WZXX_M1_N1_C0023_V",
        "WZXX_M1_N1_C0024_V",
        "WZXX_M1_N1_C0025_V",
        "WZXX_M1_N1_C0026_V",
        "WZXX_M1_N1_C0027_V",
        "WZXX_M1_N1_C0029_V",
        "WZXX_MasterEventVar_01",
        "WZXX_NormalEventVar_01",
        
      ],
      
    # 收集列表
    collect_list: [
      'collect_1',
      'collect_2',
      'collect_3',
      'collect_4',
    ],
    
  }
