book: {
    # 场景目录定位，YML新增必须在这里记录
    # 起始场景
    init: "",

    # 场景列表
    scene_list:
      ["scene_wzxx", "WZXX_[START]", "WZXX_[Variables]", "WZXX_M1_N1_C001V", "WZXX_M1_N1_C001VA",
 
      ],
  }
