# 目录
directory: [
  {
    id: 1, 
    title: '第一至二十章',
    map: [
      { point: [0, 3], title: '第一章上篇脱身', toChapter: 'WZXX_[Chapters]/WZXX_M1_N1_C001', links: [[0, 2], ] },
      { point: [0, 2], title: '接续第一章 我有秘籍？', toChapter: 'WZXX_[Chapters]/WZXX_M1_N1_C001A', links: [[0, 1], ] },
      { point: [0, 1], title: '第一章 分支 选择先回城', toChapter: 'WZXX_[Chapters]/WZXX_M1_N1_C001B_[A1]', links: [[0, 0],[-1, 0],[1, 0],[0, -1],] },
      { point: [-2, 0], title: '第一章 分支B2 选择寻找物品', toChapter: 'WZXX_[Chapters]/WZXX_M1_N1_C001B_[B1]', links: [[-1, 0], ] },
      { point: [-1, 0], title: '第一章 分支B 选择寻找物品', toChapter: 'WZXX_[Chapters]/WZXX_M1_N1_C001B_[B2]', links: [[0, -1], ] },
      { point: [1, 0], title: '第一章 分支C 选择跟踪', toChapter: 'WZXX_[Chapters]/WZXX_M1_N1_C001B_[C1]', links: [[0, -1],[2, 0], ] },
      { point: [2, 0], title: '第一章 分支C2 跟踪结束', toChapter: 'WZXX_[Chapters]/WZXX_M1_N1_C001B_[C2]', links: [[]] },
      { point: [0, -1], title: '第一章 中篇 行动', toChapter: 'WZXX_[Chapters]/WZXX_M1_N1_C001B', links: [[-1, -2],[0, -2],[1, -2],[0, 1], ] },
      { point: [-1, -2], title: '第一章 分支 选择身份记忆1 修真世家', toChapter: 'WZXX_[Chapters]/WZXX_M1_N1_C001C_[N1]', links: [[0, -3]] },
      { point: [0, -2], title: '第一章 分支 选择身份2 ', toChapter: 'WZXX_[Chapters]/WZXX_M1_N1_C001C_[N2]', links: [[0, -3]] },
      { point: [1, -2], title: '第一章 分支 选择身份记忆3白府远亲', toChapter: 'WZXX_[Chapters]/WZXX_M1_N1_C001C_[N3]', links: [[0, -3]] },
      { point: [0, -3], title: '第一章 下篇 进入白城', toChapter: 'WZXX_[Chapters]/WZXX_M1_N1_C001C', links: [[0, -4]] },
      { point: [0, -4], title: '第二章N1回忆开始', toChapter: 'WZXX_[Chapters]/WZXX_M1_N1_C002_[N1]', links: [[0, -5]] },
      { point: [0, -5], title: '第二章N2猫', toChapter: 'WZXX_[Chapters]/WZXX_M1_N1_C002_[N2]', links: [[0, -6]] },
      { point: [0, -6], title: '第二章N3追杀', toChapter: 'WZXX_[Chapters]/WZXX_M1_N1_C002_[N3]', links: [[-1, -7], [1, -7],[0, -8]], },
      { point: [-1, -7], title: '第三章N1白马分庄', toChapter: 'WZXX_[Chapters]/WZXX_M1_N1_C003_[N1]', links: [[0, -8],] },
      { point: [1, -7], title: '第三章N2白月光闺房', toChapter: 'WZXX_[Chapters]/WZXX_M1_N1_C003_[N2]', links: [[0, -8]], },
      { point: [0, -8], title: '第四章N1灵修界', toChapter: 'WZXX_[Chapters]/WZXX_M1_N1_C004_[N1]', links: [[0, -9],[0, -6], ] },
      { point: [0, -9], title: '第四章N2拒绝拜师', toChapter: 'WZXX_[Chapters]/WZXX_M1_N1_C004_[N2]', links: [[0, -10]],  },
      { point: [0, -10], title: '第五章N1小师弟', toChapter: 'WZXX_[Chapters]/WZXX_M1_N1_C005_[N1]', links: [[0, -11]] },
      { point: [0, -11], title: '第五章N2打斗', toChapter: 'WZXX_[Chapters]/WZXX_M1_N1_C005_[N2]', links: [[0, -12]], },
      { point: [0, -12], title: '第六章初见陶老', toChapter: 'WZXX_[Chapters]/WZXX_M1_N1_C006_[N0]', links: [[0, -13], ] },
      { point: [0, -13], title: '第七章修炼', toChapter: 'WZXX_[Chapters]/WZXX_M1_N1_C007_[N0]', links: [[0, -14]] },
      { point: [0, -14], title: '第八章坊市中毒', toChapter: 'WZXX_[Chapters]/WZXX_M1_N1_C008_[N0]', links: [[0, -15], ] },
      { point: [0, -15], title: '第九章解决恶灵', toChapter: 'WZXX_[Chapters]/WZXX_M1_N1_C009_[V2]', links: [[-1, -16],[1, -16],[0, -18]],  },
      { point: [-1, -16], title: '第十章 上 守夜 版本1 N1 ', toChapter: 'WZXX_[Chapters]/WZXX_M1_N1_C010_[V1][N1]', links: [[-2, -16], [0, -18]] },
      { point: [-2, -16], title: '第十章 大战红衣女灵 下 N2 ', toChapter: 'WZXX_[Chapters]/WZXX_M1_N1_C010_[V1][N2]', links: [[], ] },
      { point: [1, -16], title: '第十章 上 守夜 版本2 N1', toChapter: 'WZXX_[Chapters]/WZXX_M1_N1_C010_[V2][N1]', links: [[0, -17],[2, -16], ] },
      { point: [2, -16], title: '第十章 大战红衣女灵 N2', toChapter: 'WZXX_[Chapters]/WZXX_M1_N1_C010_[V2][N2]', links: [[]],  },
      { point: [0, -17], title: '第十一章三只阴灵', toChapter: 'WZXX_[Chapters]/WZXX_M1_N1_C011_[V0]', links: [[0, -18],[0, -15], ] },
      { point: [0, -18], title: '第十二章神识', toChapter: 'WZXX_[Chapters]/WZXX_M1_N1_C012_[V0]', links: [[0, -19]], },
      { point: [0, -19], title: '第十三章 挑战成功', toChapter: 'WZXX_[Chapters]/WZXX_M1_N1_C013_[V0]', links: [[0, -20]], },
      { point: [0, -20], title: '第十五章再遇陶老', toChapter: 'WZXX_[Chapters]/WZXX_M1_N1_C015_[V0]', links: [[0, -21]] },
      { point: [0, -21], title: '第十六章突破炼气四重', toChapter: 'WZXX_[Chapters]/WZXX_M1_N1_C016_[V0]', links: [[0, -22]],  },
      { point: [0, -22], title: '第十七章锻骨灵液N1', toChapter: 'WZXX_[Chapters]/WZXX_M1_N1_C017_[N1]', links: [[0, -23]],  },
      { point: [0, -23], title: '第十七章找陶老N2', toChapter: 'WZXX_[Chapters]/WZXX_M1_N1_C017_[N2]', links: [[0, -24]],  },
      { point: [0, -24], title: '第十八章对话陶老N1', toChapter: 'WZXX_[Chapters]/WZXX_M1_N1_C018_[N1]', links: [[0, -25]],  },
      { point: [0, -25], title: '第十八章怒怼陶老N2', toChapter: 'WZXX_[Chapters]/WZXX_M1_N1_C018_[N2]', links: [[0, -26]],  },
      { point: [0, -26], title: '第十九章用灵液N1', toChapter: 'WZXX_[Chapters]/WZXX_M1_N1_C019_[N1]', links: [[0, -27]],  },
      { point: [0, -27], title: '第十九章恶犬恶主N2', toChapter: 'WZXX_[Chapters]/WZXX_M1_N1_C019_[N2]', links: [[0, -28]],  },
      { point: [0, -28], title: '第二十章暴打黑光', toChapter: 'WZXX_[Chapters]/WZXX_M1_N1_C020', links: [[]],  },
    
   


    ]
  },

  {
    id: 2, 
    title: '二十章到四十章',
    map: [
      { point: [0, 0], title: '起点', toChapter: 'WZXX_M1_N1_C001', links: [[0, 1], [0, -1], [-1, 0], [1, 0]] },
      { point: [0, 1], title: '选择世界', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [] },
      { point: [1, 0], title: '向右', lock: true, toSctoChapterene: 'WZXX_M1_N1_C001B_[C2]', links: [[0, -1], [0, 1]] },
      { point: [0, -1], title: '沉浸式阅读', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [], path: [[1, -1], [1, -2], [1, -3], [1, -4], [0, -4], [-1, -4]] },
      { point: [-1, 0], title: '向左', lock: true, toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[0, 1], [0, -1]] },
      { point: [-2, 0], title: '我有秘籍, 要继续？', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, 0]], path: [[-2, 1], [-1, 1], [0, 1]] },
      { point: [-1, -1], title: '开始游戏', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, 0], [0, -1], [-1, -2]] },
      { point: [-1, -2], title: '选择副本', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, -3]], path: [[0, -2], [0, -1]] },
      { point: [-1, -3], title: '击杀怪物', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, -4]] },
      { point: [-1, -4], title: '获得奖励', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [], path: [[-2, -4], [-2, -3], [-2, -2], [-2, -1], [-2, 0]] },
    ]
  },

  {
    id: 3, 
    title: '未开启',
    map: [
      { point: [0, 0], title: '起点', toChapter: 'WZXX_M1_N1_C001', links: [[0, 1], [0, -1], [-1, 0], [1, 0]] },
      { point: [0, 1], title: '选择世界', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [] },
      { point: [1, 0], title: '向右', lock: true, toSctoChapterene: 'WZXX_M1_N1_C001B_[C2]', links: [[0, -1], [0, 1]] },
      { point: [0, -1], title: '沉浸式阅读', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [], path: [[1, -1], [1, -2], [1, -3], [1, -4], [0, -4], [-1, -4]] },
      { point: [-1, 0], title: '向左', lock: true, toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[0, 1], [0, -1]] },
      { point: [-2, 0], title: '我有秘籍, 要继续？', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, 0]], path: [[-2, 1], [-1, 1], [0, 1]] },
      { point: [-1, -1], title: '开始游戏', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, 0], [0, -1], [-1, -2]] },
      { point: [-1, -2], title: '选择副本', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, -3]], path: [[0, -2], [0, -1]] },
      { point: [-1, -3], title: '击杀怪物', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, -4]] },
      { point: [-1, -4], title: '获得奖励', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [], path: [[-2, -4], [-2, -3], [-2, -2], [-2, -1], [-2, 0]] },
    ]
  },

  {
    id: 4, 
    title: '未开启',
    map: [
      { point: [0, 0], title: '起点', toChapter: 'WZXX_M1_N1_C001', links: [[0, 1], [0, -1], [-1, 0], [1, 0]] },
      { point: [0, 1], title: '选择世界', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [] },
      { point: [1, 0], title: '向右', lock: true, toSctoChapterene: 'WZXX_M1_N1_C001B_[C2]', links: [[0, -1], [0, 1]] },
      { point: [0, -1], title: '沉浸式阅读', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [], path: [[1, -1], [1, -2], [1, -3], [1, -4], [0, -4], [-1, -4]] },
      { point: [-1, 0], title: '向左', lock: true, toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[0, 1], [0, -1]] },
      { point: [-2, 0], title: '我有秘籍, 要继续？', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, 0]], path: [[-2, 1], [-1, 1], [0, 1]] },
      { point: [-1, -1], title: '开始游戏', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, 0], [0, -1], [-1, -2]] },
      { point: [-1, -2], title: '选择副本', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, -3]], path: [[0, -2], [0, -1]] },
      { point: [-1, -3], title: '击杀怪物', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, -4]] },
      { point: [-1, -4], title: '获得奖励', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [], path: [[-2, -4], [-2, -3], [-2, -2], [-2, -1], [-2, 0]] },
    ]
  },

  {
    id: 5, 
    title: '未开启',
    map: [
      { point: [0, 0], title: '起点', toChapter: 'WZXX_M1_N1_C001', links: [[0, 1], [0, -1], [-1, 0], [1, 0]] },
      { point: [0, 1], title: '选择世界', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [] },
      { point: [1, 0], title: '向右', lock: true, toSctoChapterene: 'WZXX_M1_N1_C001B_[C2]', links: [[0, -1], [0, 1]] },
      { point: [0, -1], title: '沉浸式阅读', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [], path: [[1, -1], [1, -2], [1, -3], [1, -4], [0, -4], [-1, -4]] },
      { point: [-1, 0], title: '向左', lock: true, toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[0, 1], [0, -1]] },
      { point: [-2, 0], title: '我有秘籍, 要继续？', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, 0]], path: [[-2, 1], [-1, 1], [0, 1]] },
      { point: [-1, -1], title: '开始游戏', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, 0], [0, -1], [-1, -2]] },
      { point: [-1, -2], title: '选择副本', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, -3]], path: [[0, -2], [0, -1]] },
      { point: [-1, -3], title: '击杀怪物', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, -4]] },
      { point: [-1, -4], title: '获得奖励', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [], path: [[-2, -4], [-2, -3], [-2, -2], [-2, -1], [-2, 0]] },
    ]
  },

  {
    id: 6, 
    title: '未开启',
    map: [
      { point: [0, 0], title: '起点', toChapter: 'WZXX_M1_N1_C001', links: [[0, 1], [0, -1], [-1, 0], [1, 0]] },
      { point: [0, 1], title: '选择世界', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [] },
      { point: [1, 0], title: '向右', toSctoChapterene: 'WZXX_M1_N1_C001B_[C2]', links: [[0, -1], [0, 1]] },
      { point: [0, -1], title: '沉浸式阅读', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [], path: [[1, -1], [1, -2], [1, -3], [1, -4], [0, -4], [-1, -4]] },
      { point: [-1, 0], title: '向左', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[0, 1], [0, -1]] },
      { point: [-2, 0], title: '我有秘籍, 要继续？', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, 0]], path: [[-2, 1], [-1, 1], [0, 1]] },
      { point: [-1, -1], title: '开始游戏', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, 0], [0, -1], [-1, -2]] },
      { point: [-1, -2], title: '选择副本', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, -3]], path: [[0, -2], [0, -1]] },
      { point: [-1, -3], title: '击杀怪物', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, -4]] },
      { point: [-1, -4], title: '获得奖励', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [], path: [[-2, -4], [-2, -3], [-2, -2], [-2, -1], [-2, 0]] },
    ]
  },

  {
    id: 7, 
    title: '未开启',
    map: [
      { point: [0, 0], title: '起点', toChapter: 'WZXX_M1_N1_C001', links: [[0, 1], [0, -1], [-1, 0], [1, 0]] },
      { point: [0, 1], title: '选择世界', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [] },
      { point: [1, 0], title: '向右', toSctoChapterene: 'WZXX_M1_N1_C001B_[C2]', links: [[0, -1], [0, 1]] },
      { point: [0, -1], title: '沉浸式阅读', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [], path: [[1, -1], [1, -2], [1, -3], [1, -4], [0, -4], [-1, -4]] },
      { point: [-1, 0], title: '向左', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[0, 1], [0, -1]] },
      { point: [-2, 0], title: '我有秘籍, 要继续？', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, 0]], path: [[-2, 1], [-1, 1], [0, 1]] },
      { point: [-1, -1], title: '开始游戏', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, 0], [0, -1], [-1, -2]] },
      { point: [-1, -2], title: '选择副本', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, -3]], path: [[0, -2], [0, -1]] },
      { point: [-1, -3], title: '击杀怪物', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, -4]] },
      { point: [-1, -4], title: '获得奖励', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [], path: [[-2, -4], [-2, -3], [-2, -2], [-2, -1], [-2, 0]] },
    ]
  },

  {
    id: 8, 
    title: '未开启',
    map: [
      { point: [0, 0], title: '起点', toChapter: 'WZXX_M1_N1_C001', links: [[0, 1], [0, -1], [-1, 0], [1, 0]] },
      { point: [0, 1], title: '选择世界', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [] },
      { point: [1, 0], title: '向右', toSctoChapterene: 'WZXX_M1_N1_C001B_[C2]', links: [[0, -1], [0, 1]] },
      { point: [0, -1], title: '沉浸式阅读', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [], path: [[1, -1], [1, -2], [1, -3], [1, -4], [0, -4], [-1, -4]] },
      { point: [-1, 0], title: '向左', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[0, 1], [0, -1]] },
      { point: [-2, 0], title: '我有秘籍, 要继续？', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, 0]], path: [[-2, 1], [-1, 1], [0, 1]] },
      { point: [-1, -1], title: '开始游戏', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, 0], [0, -1], [-1, -2]] },
      { point: [-1, -2], title: '选择副本', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, -3]], path: [[0, -2], [0, -1]] },
      { point: [-1, -3], title: '击杀怪物', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, -4]] },
      { point: [-1, -4], title: '获得奖励', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [], path: [[-2, -4], [-2, -3], [-2, -2], [-2, -1], [-2, 0]] },
    ]
  },

  {
    id: 9, 
    title: '未开启',
    map: [
      { point: [0, 0], title: '起点', toChapter: 'WZXX_M1_N1_C001', links: [[0, 1], [0, -1], [-1, 0], [1, 0]] },
      { point: [0, 1], title: '选择世界', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [] },
      { point: [1, 0], title: '向右', toSctoChapterene: 'WZXX_M1_N1_C001B_[C2]', links: [[0, -1], [0, 1]] },
      { point: [0, -1], title: '沉浸式阅读', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [], path: [[1, -1], [1, -2], [1, -3], [1, -4], [0, -4], [-1, -4]] },
      { point: [-1, 0], title: '向左', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[0, 1], [0, -1]] },
      { point: [-2, 0], title: '我有秘籍, 要继续？', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, 0]], path: [[-2, 1], [-1, 1], [0, 1]] },
      { point: [-1, -1], title: '开始游戏', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, 0], [0, -1], [-1, -2]] },
      { point: [-1, -2], title: '选择副本', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, -3]], path: [[0, -2], [0, -1]] },
      { point: [-1, -3], title: '击杀怪物', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, -4]] },
      { point: [-1, -4], title: '获得奖励', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [], path: [[-2, -4], [-2, -3], [-2, -2], [-2, -1], [-2, 0]] },
    ]
  },

  {
    id: 10, 
    title: '未开启',
    map: [
      { point: [0, 0], title: '起点', toChapter: 'WZXX_M1_N1_C001', links: [[0, 1], [0, -1], [-1, 0], [1, 0]] },
      { point: [0, 1], title: '选择世界', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [] },
      { point: [1, 0], title: '向右', toSctoChapterene: 'WZXX_M1_N1_C001B_[C2]', links: [[0, -1], [0, 1]] },
      { point: [0, -1], title: '沉浸式阅读', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [], path: [[1, -1], [1, -2], [1, -3], [1, -4], [0, -4], [-1, -4]] },
      { point: [-1, 0], title: '向左', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[0, 1], [0, -1]] },
      { point: [-2, 0], title: '我有秘籍, 要继续？', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, 0]], path: [[-2, 1], [-1, 1], [0, 1]] },
      { point: [-1, -1], title: '开始游戏', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, 0], [0, -1], [-1, -2]] },
      { point: [-1, -2], title: '选择副本', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, -3]], path: [[0, -2], [0, -1]] },
      { point: [-1, -3], title: '击杀怪物', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, -4]] },
      { point: [-1, -4], title: '获得奖励', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [], path: [[-2, -4], [-2, -3], [-2, -2], [-2, -1], [-2, 0]] },
    ]
  },
]
