# 目录
directory: [
  {
    id: 1, 
    title: '第一卷',
    map: [
      { point: [0, 0], title: '起点', toChapter: 'WZXX_M1_N1_C001', links: [[0, 1], [0, -1]] },
      { point: [0, 1], title: '选择世界', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [] },
      { point: [0, -1], title: '沉浸式阅读', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [], path: [] },
    ]
  },

  {
    id: 2, 
    title: '第二卷',
    map: [
      { point: [0, 0], title: '起点', toChapter: 'WZXX_M1_N1_C001', links: [[0, 1], [0, -1], [-1, 0], [1, 0]] },
      { point: [0, 1], title: '选择世界', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [] },
      { point: [1, 0], title: '向右', toSctoChapterene: 'WZXX_M1_N1_C001B_[C2]', links: [[0, -1], [0, 1]] },
      { point: [0, -1], title: '沉浸式阅读', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [], path: [[1, -1], [1, -2], [1, -3], [1, -4], [0, -4], [-1, -4]] },
      { point: [-1, 0], title: '向左', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[0, 1], [0, -1]] },
      { point: [-2, 0], title: '我有秘籍, 要继续？', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, 0]], path: [[-2, 1], [-1, 1], [0, 1]] },
      { point: [-1, -1], title: '开始游戏', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, 0], [0, -1], [-1, -2]] },
      { point: [-1, -2], title: '选择副本', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, -3]], path: [[0, -2], [0, -1]] },
      { point: [-1, -3], title: '击杀怪物', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, -4]] },
      { point: [-1, -4], title: '获得奖励', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [], path: [[-2, -4], [-2, -3], [-2, -2], [-2, -1], [-2, 0]] },
    ]
  },

  {
    id: 3, 
    title: '第三卷',
    map: [
      { point: [0, 0], title: '起点', toChapter: 'WZXX_M1_N1_C001', links: [[0, 1], [0, -1], [-1, 0], [1, 0]] },
      { point: [0, 1], title: '选择世界', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [] },
      { point: [1, 0], title: '向右', toSctoChapterene: 'WZXX_M1_N1_C001B_[C2]', links: [[0, -1], [0, 1]] },
      { point: [0, -1], title: '沉浸式阅读', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [], path: [[1, -1], [1, -2], [1, -3], [1, -4], [0, -4], [-1, -4]] },
      { point: [-1, 0], title: '向左', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[0, 1], [0, -1]] },
      { point: [-2, 0], title: '我有秘籍, 要继续？', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, 0]], path: [[-2, 1], [-1, 1], [0, 1]] },
      { point: [-1, -1], title: '开始游戏', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, 0], [0, -1], [-1, -2]] },
      { point: [-1, -2], title: '选择副本', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, -3]], path: [[0, -2], [0, -1]] },
      { point: [-1, -3], title: '击杀怪物', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, -4]] },
      { point: [-1, -4], title: '获得奖励', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [], path: [[-2, -4], [-2, -3], [-2, -2], [-2, -1], [-2, 0]] },
    ]
  },

  {
    id: 4, 
    title: '第四卷',
    map: [
      { point: [0, 0], title: '起点', toChapter: 'WZXX_M1_N1_C001', links: [[0, 1], [0, -1], [-1, 0], [1, 0]] },
      { point: [0, 1], title: '选择世界', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [] },
      { point: [1, 0], title: '向右', toSctoChapterene: 'WZXX_M1_N1_C001B_[C2]', links: [[0, -1], [0, 1]] },
      { point: [0, -1], title: '沉浸式阅读', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [], path: [[1, -1], [1, -2], [1, -3], [1, -4], [0, -4], [-1, -4]] },
      { point: [-1, 0], title: '向左', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[0, 1], [0, -1]] },
      { point: [-2, 0], title: '我有秘籍, 要继续？', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, 0]], path: [[-2, 1], [-1, 1], [0, 1]] },
      { point: [-1, -1], title: '开始游戏', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, 0], [0, -1], [-1, -2]] },
      { point: [-1, -2], title: '选择副本', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, -3]], path: [[0, -2], [0, -1]] },
      { point: [-1, -3], title: '击杀怪物', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, -4]] },
      { point: [-1, -4], title: '获得奖励', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [], path: [[-2, -4], [-2, -3], [-2, -2], [-2, -1], [-2, 0]] },
    ]
  },

  {
    id: 5, 
    title: '第五卷',
    map: [
      { point: [0, 0], title: '起点', toChapter: 'WZXX_M1_N1_C001', links: [[0, 1], [0, -1], [-1, 0], [1, 0]] },
      { point: [0, 1], title: '选择世界', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [] },
      { point: [1, 0], title: '向右', toSctoChapterene: 'WZXX_M1_N1_C001B_[C2]', links: [[0, -1], [0, 1]] },
      { point: [0, -1], title: '沉浸式阅读', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [], path: [[1, -1], [1, -2], [1, -3], [1, -4], [0, -4], [-1, -4]] },
      { point: [-1, 0], title: '向左', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[0, 1], [0, -1]] },
      { point: [-2, 0], title: '我有秘籍, 要继续？', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, 0]], path: [[-2, 1], [-1, 1], [0, 1]] },
      { point: [-1, -1], title: '开始游戏', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, 0], [0, -1], [-1, -2]] },
      { point: [-1, -2], title: '选择副本', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, -3]], path: [[0, -2], [0, -1]] },
      { point: [-1, -3], title: '击杀怪物', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, -4]] },
      { point: [-1, -4], title: '获得奖励', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [], path: [[-2, -4], [-2, -3], [-2, -2], [-2, -1], [-2, 0]] },
    ]
  },

  {
    id: 6, 
    title: '第六卷',
    map: [
      { point: [0, 0], title: '起点', toChapter: 'WZXX_M1_N1_C001', links: [[0, 1], [0, -1], [-1, 0], [1, 0]] },
      { point: [0, 1], title: '选择世界', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [] },
      { point: [1, 0], title: '向右', toSctoChapterene: 'WZXX_M1_N1_C001B_[C2]', links: [[0, -1], [0, 1]] },
      { point: [0, -1], title: '沉浸式阅读', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [], path: [[1, -1], [1, -2], [1, -3], [1, -4], [0, -4], [-1, -4]] },
      { point: [-1, 0], title: '向左', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[0, 1], [0, -1]] },
      { point: [-2, 0], title: '我有秘籍, 要继续？', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, 0]], path: [[-2, 1], [-1, 1], [0, 1]] },
      { point: [-1, -1], title: '开始游戏', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, 0], [0, -1], [-1, -2]] },
      { point: [-1, -2], title: '选择副本', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, -3]], path: [[0, -2], [0, -1]] },
      { point: [-1, -3], title: '击杀怪物', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, -4]] },
      { point: [-1, -4], title: '获得奖励', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [], path: [[-2, -4], [-2, -3], [-2, -2], [-2, -1], [-2, 0]] },
    ]
  },

  {
    id: 7, 
    title: '第七卷',
    map: [
      { point: [0, 0], title: '起点', toChapter: 'WZXX_M1_N1_C001', links: [[0, 1], [0, -1], [-1, 0], [1, 0]] },
      { point: [0, 1], title: '选择世界', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [] },
      { point: [1, 0], title: '向右', toSctoChapterene: 'WZXX_M1_N1_C001B_[C2]', links: [[0, -1], [0, 1]] },
      { point: [0, -1], title: '沉浸式阅读', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [], path: [[1, -1], [1, -2], [1, -3], [1, -4], [0, -4], [-1, -4]] },
      { point: [-1, 0], title: '向左', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[0, 1], [0, -1]] },
      { point: [-2, 0], title: '我有秘籍, 要继续？', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, 0]], path: [[-2, 1], [-1, 1], [0, 1]] },
      { point: [-1, -1], title: '开始游戏', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, 0], [0, -1], [-1, -2]] },
      { point: [-1, -2], title: '选择副本', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, -3]], path: [[0, -2], [0, -1]] },
      { point: [-1, -3], title: '击杀怪物', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, -4]] },
      { point: [-1, -4], title: '获得奖励', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [], path: [[-2, -4], [-2, -3], [-2, -2], [-2, -1], [-2, 0]] },
    ]
  },

  {
    id: 8, 
    title: '第八卷',
    map: [
      { point: [0, 0], title: '起点', toChapter: 'WZXX_M1_N1_C001', links: [[0, 1], [0, -1], [-1, 0], [1, 0]] },
      { point: [0, 1], title: '选择世界', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [] },
      { point: [1, 0], title: '向右', toSctoChapterene: 'WZXX_M1_N1_C001B_[C2]', links: [[0, -1], [0, 1]] },
      { point: [0, -1], title: '沉浸式阅读', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [], path: [[1, -1], [1, -2], [1, -3], [1, -4], [0, -4], [-1, -4]] },
      { point: [-1, 0], title: '向左', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[0, 1], [0, -1]] },
      { point: [-2, 0], title: '我有秘籍, 要继续？', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, 0]], path: [[-2, 1], [-1, 1], [0, 1]] },
      { point: [-1, -1], title: '开始游戏', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, 0], [0, -1], [-1, -2]] },
      { point: [-1, -2], title: '选择副本', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, -3]], path: [[0, -2], [0, -1]] },
      { point: [-1, -3], title: '击杀怪物', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, -4]] },
      { point: [-1, -4], title: '获得奖励', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [], path: [[-2, -4], [-2, -3], [-2, -2], [-2, -1], [-2, 0]] },
    ]
  },

  {
    id: 9, 
    title: '第九卷',
    map: [
      { point: [0, 0], title: '起点', toChapter: 'WZXX_M1_N1_C001', links: [[0, 1], [0, -1], [-1, 0], [1, 0]] },
      { point: [0, 1], title: '选择世界', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [] },
      { point: [1, 0], title: '向右', toSctoChapterene: 'WZXX_M1_N1_C001B_[C2]', links: [[0, -1], [0, 1]] },
      { point: [0, -1], title: '沉浸式阅读', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [], path: [[1, -1], [1, -2], [1, -3], [1, -4], [0, -4], [-1, -4]] },
      { point: [-1, 0], title: '向左', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[0, 1], [0, -1]] },
      { point: [-2, 0], title: '我有秘籍, 要继续？', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, 0]], path: [[-2, 1], [-1, 1], [0, 1]] },
      { point: [-1, -1], title: '开始游戏', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, 0], [0, -1], [-1, -2]] },
      { point: [-1, -2], title: '选择副本', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, -3]], path: [[0, -2], [0, -1]] },
      { point: [-1, -3], title: '击杀怪物', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, -4]] },
      { point: [-1, -4], title: '获得奖励', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [], path: [[-2, -4], [-2, -3], [-2, -2], [-2, -1], [-2, 0]] },
    ]
  },

  {
    id: 10, 
    title: '第十卷',
    map: [
      { point: [0, 0], title: '起点', toChapter: 'WZXX_M1_N1_C001', links: [[0, 1], [0, -1], [-1, 0], [1, 0]] },
      { point: [0, 1], title: '选择世界', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [] },
      { point: [1, 0], title: '向右', toSctoChapterene: 'WZXX_M1_N1_C001B_[C2]', links: [[0, -1], [0, 1]] },
      { point: [0, -1], title: '沉浸式阅读', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [], path: [[1, -1], [1, -2], [1, -3], [1, -4], [0, -4], [-1, -4]] },
      { point: [-1, 0], title: '向左', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[0, 1], [0, -1]] },
      { point: [-2, 0], title: '我有秘籍, 要继续？', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, 0]], path: [[-2, 1], [-1, 1], [0, 1]] },
      { point: [-1, -1], title: '开始游戏', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, 0], [0, -1], [-1, -2]] },
      { point: [-1, -2], title: '选择副本', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, -3]], path: [[0, -2], [0, -1]] },
      { point: [-1, -3], title: '击杀怪物', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [[-1, -4]] },
      { point: [-1, -4], title: '获得奖励', toChapter: 'WZXX_M1_N1_C001B_[C2]', links: [], path: [[-2, -4], [-2, -3], [-2, -2], [-2, -1], [-2, 0]] },
    ]
  },
]
