// 音频资源
export const SOUND_RESOURCES = [
    // ================音乐===============================
    { id: 'BGM_B_0002', source: require('../../../assets/sound/BGM/BGM_B_0002.mp3') },
    { id: 'BGM_B_0003', source: require('../../../assets/sound/BGM/BGM_B_0003.mp3') },
    { id: 'BGM_C_0001', source: require('../../../assets/sound/BGM/BGM_C_0001.mp3') },
    { id: 'BGM_C_0002', source: require('../../../assets/sound/BGM/BGM_C_0002.mp3') },
    { id: 'BGM_C_0003', source: require('../../../assets/sound/BGM/BGM_C_0003.mp3') },
    { id: 'BGM_C_0004', source: require('../../../assets/sound/BGM/BGM_C_0004.mp3') },
    { id: 'BGM_Q_0001', source: require('../../../assets/sound/BGM/BGM_Q_0001.mp3') },
    { id: 'BGM_Q_0002', source: require('../../../assets/sound/BGM/BGM_Q_0002.mp3') },
    { id: 'BGM_Q_0003', source: require('../../../assets/sound/BGM/BGM_Q_0003.mp3') },
    { id: 'BGM_Q_0004', source: require('../../../assets/sound/BGM/BGM_Q_0004.mp3') },
    { id: 'BGM_R_0001', source: require('../../../assets/sound/BGM/BGM_R_0001.mp3') },
    { id: 'BGM_R_0002', source: require('../../../assets/sound/BGM/BGM_R_0002.mp3') },
    { id: 'BGM_R_0003', source: require('../../../assets/sound/BGM/BGM_R_0003.mp3') },
    { id: 'BGM_T_0001', source: require('../../../assets/sound/BGM/BGM_T_0001.mp3') },


    // ================音效===============================
    // SE=音效。命名缩略文字，KO战斗，CQ气氛 MS魔法释放 UE界面音效 AM动物声音 HV人声

    { id: 'SE_AM_0001', source: require('../../../assets/sound/SE/SE_AM_0001.wav') },
    { id: 'SE_AM_0002', source: require('../../../assets/sound/SE/SE_AM_0002.wav') },
    { id: 'SE_AM_0003', source: require('../../../assets/sound/SE/SE_AM_0003.wav') },
    { id: 'SE_AM_0004', source: require('../../../assets/sound/SE/SE_AM_0004.wav') },
    { id: 'SE_AM_0005', source: require('../../../assets/sound/SE/SE_AM_0005.wav') },
    { id: 'SE_AM_0006', source: require('../../../assets/sound/SE/SE_AM_0006.wav') },
    { id: 'SE_AM_0007', source: require('../../../assets/sound/SE/SE_AM_0007.wav') },
   


    { id: 'SE_CQ_0001', source: require('../../../assets/sound/SE/SE_CQ_0001.wav') },
    { id: 'SE_CQ_0002', source: require('../../../assets/sound/SE/SE_CQ_0002.wav') },
    { id: 'SE_CQ_0003', source: require('../../../assets/sound/SE/SE_CQ_0003.wav') },
    { id: 'SE_CQ_0004', source: require('../../../assets/sound/SE/SE_CQ_0004.wav') },
    { id: 'SE_CQ_0005', source: require('../../../assets/sound/SE/SE_CQ_0005.wav') },
    { id: 'SE_CQ_0006', source: require('../../../assets/sound/SE/SE_CQ_0006.wav') },
    { id: 'SE_CQ_0007', source: require('../../../assets/sound/SE/SE_CQ_0007.wav') },
    { id: 'SE_CQ_0008', source: require('../../../assets/sound/SE/SE_CQ_0008.wav') },
    { id: 'SE_CQ_0009', source: require('../../../assets/sound/SE/SE_CQ_0009.wav') },
    { id: 'SE_CQ_0010', source: require('../../../assets/sound/SE/SE_CQ_0010.wav') },
    { id: 'SE_CQ_0011', source: require('../../../assets/sound/SE/SE_CQ_0011.wav') },
    { id: 'SE_CQ_0012', source: require('../../../assets/sound/SE/SE_CQ_0012.wav') },
    { id: 'SE_CQ_0013', source: require('../../../assets/sound/SE/SE_CQ_0013.wav') },
    { id: 'SE_CQ_0014', source: require('../../../assets/sound/SE/SE_CQ_0014.wav') },
    { id: 'SE_CQ_0015', source: require('../../../assets/sound/SE/SE_CQ_0015.wav') },
    { id: 'SE_CQ_0016', source: require('../../../assets/sound/SE/SE_CQ_0016.wav') },

    { id: 'SE_HV_0001', source: require('../../../assets/sound/SE/SE_HV_0001.wav') },
    { id: 'SE_HV_0002', source: require('../../../assets/sound/SE/SE_HV_0002.wav') },
    { id: 'SE_HV_0003', source: require('../../../assets/sound/SE/SE_HV_0003.wav') },
    { id: 'SE_HV_0004', source: require('../../../assets/sound/SE/SE_HV_0004.wav') },
    { id: 'SE_HV_0005', source: require('../../../assets/sound/SE/SE_HV_0005.wav') },
    { id: 'SE_HV_0006', source: require('../../../assets/sound/SE/SE_HV_0006.wav') },
    { id: 'SE_HV_0007', source: require('../../../assets/sound/SE/SE_HV_0007.wav') },
    { id: 'SE_HV_0008', source: require('../../../assets/sound/SE/SE_HV_0008.wav') },
    { id: 'SE_HV_0009', source: require('../../../assets/sound/SE/SE_HV_0009.wav') },
    { id: 'SE_HV_0010', source: require('../../../assets/sound/SE/SE_HV_0010.wav') },
    { id: 'SE_HV_0011', source: require('../../../assets/sound/SE/SE_HV_0011.wav') },
    { id: 'SE_HV_0012', source: require('../../../assets/sound/SE/SE_HV_0012.wav') },
    { id: 'SE_HV_0013', source: require('../../../assets/sound/SE/SE_HV_0013.wav') },
    { id: 'SE_HV_0014', source: require('../../../assets/sound/SE/SE_HV_0014.wav') },
    { id: 'SE_HV_0015', source: require('../../../assets/sound/SE/SE_HV_0015.wav') },
    { id: 'SE_HV_0016', source: require('../../../assets/sound/SE/SE_HV_0016.wav') },
    { id: 'SE_HV_0017', source: require('../../../assets/sound/SE/SE_HV_0017.wav') },


    { id: 'SE_ED_0021', source: require('../../../assets/sound/SE/SE_ED_0021.wav') },

    { id: 'SE_KO_0001', source: require('../../../assets/sound/SE/SE_KO_0001.wav') },
    { id: 'SE_KO_0002', source: require('../../../assets/sound/SE/SE_KO_0002.wav') },
    { id: 'SE_KO_0003', source: require('../../../assets/sound/SE/SE_KO_0003.wav') },
    { id: 'SE_KO_0004', source: require('../../../assets/sound/SE/SE_KO_0004.wav') },
    { id: 'SE_KO_0006', source: require('../../../assets/sound/SE/SE_KO_0006.wav') },
    { id: 'SE_KO_0007', source: require('../../../assets/sound/SE/SE_KO_0007.wav') },
    { id: 'SE_KO_0008', source: require('../../../assets/sound/SE/SE_KO_0008.wav') },
    { id: 'SE_KO_0009', source: require('../../../assets/sound/SE/SE_KO_0009.wav') },
    { id: 'SE_KO_0010', source: require('../../../assets/sound/SE/SE_KO_0010.wav') },
    { id: 'SE_KO_0011', source: require('../../../assets/sound/SE/SE_KO_0011.wav') },
    { id: 'SE_KO_0012', source: require('../../../assets/sound/SE/SE_KO_0012.wav') },
    { id: 'SE_KO_0014', source: require('../../../assets/sound/SE/SE_KO_0014.wav') },
    { id: 'SE_KO_0015', source: require('../../../assets/sound/SE/SE_KO_0015.wav') },
    { id: 'SE_KO_0016', source: require('../../../assets/sound/SE/SE_KO_0016.wav') },
    { id: 'SE_KO_0017', source: require('../../../assets/sound/SE/SE_KO_0017.wav') },
    { id: 'SE_KO_0018', source: require('../../../assets/sound/SE/SE_KO_0017.wav') },
    { id: 'SE_KO_0019', source: require('../../../assets/sound/SE/SE_KO_0019.wav') },
    { id: 'SE_KO_0021', source: require('../../../assets/sound/SE/SE_KO_0021.wav') },
    { id: 'SE_KO_0022', source: require('../../../assets/sound/SE/SE_KO_0022.wav') },
    { id: 'SE_KO_0023', source: require('../../../assets/sound/SE/SE_KO_0023.wav') },
    { id: 'SE_KO_0024', source: require('../../../assets/sound/SE/SE_KO_0024.wav') },
    { id: 'SE_KO_0025', source: require('../../../assets/sound/SE/SE_KO_0025.wav') },
    { id: 'SE_KO_0030', source: require('../../../assets/sound/SE/SE_KO_0021.wav') },

    { id: 'SE_MS_0001', source: require('../../../assets/sound/SE/SE_MS_0001.wav') },
    { id: 'SE_MS_0002', source: require('../../../assets/sound/SE/SE_MS_0002.wav') },
    { id: 'SE_MS_0003', source: require('../../../assets/sound/SE/SE_MS_0003.wav') },
    { id: 'SE_MS_0004', source: require('../../../assets/sound/SE/SE_MS_0004.wav') },

    { id: 'SE_MS_0031', source: require('../../../assets/sound/SE/SE_MS_0031.wav') },
    { id: 'SE_MS_0032', source: require('../../../assets/sound/SE/SE_MS_0032.wav') },
    { id: 'SE_MS_0041', source: require('../../../assets/sound/SE/SE_MS_0041.wav') },

    { id: 'SE_UE_0001', source: require('../../../assets/sound/SE/SE_UE_0001.wav') },
    { id: 'SE_UE_0002', source: require('../../../assets/sound/SE/SE_UE_0002.wav') },
    { id: 'SE_UE_0003', source: require('../../../assets/sound/SE/SE_UE_0003.wav') },
    { id: 'SE_UE_0004', source: require('../../../assets/sound/SE/SE_UE_0004.wav') },
    { id: 'SE_UE_0005', source: require('../../../assets/sound/SE/SE_UE_0005.wav') },
    { id: 'SE_UE_0006', source: require('../../../assets/sound/SE/SE_UE_0006.wav') },
    { id: 'SE_UE_0007', source: require('../../../assets/sound/SE/SE_UE_0007.wav') },
    { id: 'SE_UE_0008', source: require('../../../assets/sound/SE/SE_UE_0008.wav') },
    { id: 'SE_UE_0009', source: require('../../../assets/sound/SE/SE_UE_0009.wav') },
    { id: 'SE_UE_0010', source: require('../../../assets/sound/SE/SE_UE_0010.wav') },
    { id: 'SE_UE_0011', source: require('../../../assets/sound/SE/SE_UE_0011.wav') },
    { id: 'SE_UE_0012', source: require('../../../assets/sound/SE/SE_UE_0012.wav') },
    { id: 'SE_UE_0013', source: require('../../../assets/sound/SE/SE_UE_0013.wav') },

    { id: 'SE_UE_0014', source: require('../../../assets/sound/SE/SE_UE_0014.wav') },
    { id: 'SE_UE_0015', source: require('../../../assets/sound/SE/SE_UE_0015.wav') },
    { id: 'SE_UE_0016', source: require('../../../assets/sound/SE/SE_UE_0016.wav') },


];