collects: [
  {
    id: '1',

    # 背景图片
    background: 'CaoDi_2',

    # 阶段列表
    periods: [
      { itemsNum: 3 },
      { itemsNum: 3 },
      { itemsNum: 4 },
    ], 
#野生白芍
    # 宝箱配置
    items: [
      { id: 1, time: 5, props: [{ propId: 1011, num: 2 }] },
      # { id: 1, props: [{ propId: 101, num: 3 }] },
      # { id: 1, time: 5, props: [{ propId: 43, num: 2 }] },
      # { id: 4, props: [{ propId: 23, num: 1 }] },
      # { id: 5, time: 8, props: [{ propId: 24, num: 1 }] },
      # { id: 6, props: [{ propId: 25, num: 1 }] },
      # { id: 7, time: 3,  props: [{ propId: 26, num: 1 }] },
    ],

    # 总量控制
    limits: [
    ],

    # 刷新周期(单位秒)
    refresh_period: 300,
  },
]
