collects: [
  {
    id: '2',

    # 背景图片
    background: 'collect_default',

    # 阶段列表
    periods: [
      { itemsNum: 2 },
      { itemsNum: 3 },
      { itemsNum: 3 },
    ], 
#何首乌
    # 宝箱配置
    items: [
      # { id: 1, time: 5, props: [{ propId: 41, num: 1 }] },
      # { id: 1, props: [{ propId: 27, num: 1 }] },
      { id: 2, time: 4, props: [{ propId: 1012, num: 2 }] },
      { id: 4, props: [{ propId: 23, num: 1 }] },
      # { id: 5, time: 7, props: [{ propId: 24, num: 1 }] },
      # { id: 6, props: [{ propId: 25, num: 3 }] },
      { id: 7, time: 5,  props: [{ propId: 26, num: 1 }] },
    ],

    # 总量控制
    limits: [
    ],

    # 刷新周期(单位秒)
    refresh_period: 300,
  },
]
