# ===========================================
# 战斗配置
# ===========================================
challenge: {
    # 战斗ID
    id: 'f_x2',
    #挂机战斗_中阶不入流_训练木人
    myself: 
      {
         uid: 1, 
         userName: '李森炎', 
         skillIds: [50, 51, 52, 54, 55, 56],
         attrs: [
          { key: 'hp', value: 400 },
          { key: 'mp', value: 140 },
          { key: 'speed', value: 100 },
          { key: 'shield', value: 100 },
          { key: 'physicalAttack', value: 40 },
          { key: 'physicalDefense', value: 20 },
          { key: 'magicDefense', value: 20 },
         ],
      },

    enemies: [
      { 
         uid: 100000, 
         userName: '普通的0号训练木人-中阶不入流', 
         skillIds: [10, 12],
         attrs: [
          { key: 'hp', value: 200 },
          { key: 'mp', value: 10 },
          { key: 'speed', value: 1 },
          { key: 'shield', value: 25 },
          { key: 'physicalAttack', value: 15 },
          { key: 'physicalDefense', value: 10 },
          { key: 'magicDefense', value: 0 },
          ],
         liftRate: [
          #{ attr: "all", multiplied: 1.2 },
          { attr: "all", multiplied: 1 },
          #{ attr: "all", multiplied: 0.8 },
          #{ attr: "speed", multiplied: 1.3 },
          #{ attr: "all", multiplied: 0.5 },
          #{ attr: "hp", multiplied: 2 },
         ]
      },
      { 
         uid: 100001, 
         userName: '强大的1号训练木人-中阶不入流', 
         skillIds: [10, 12],
         attrs: [
          { key: 'hp', value: 200 },
          { key: 'mp', value: 10 },
          { key: 'speed', value: 1 },
          { key: 'shield', value: 25 },
          { key: 'physicalAttack', value: 15 },
          { key: 'physicalDefense', value: 10 },
          { key: 'magicDefense', value: 0 },
          ],
         liftRate: [
          { attr: "all", multiplied: 1.2 },
          #{ attr: "all", multiplied: 1 },
          #{ attr: "all", multiplied: 0.8 },
          #{ attr: "speed", multiplied: 1.3 },
          #{ attr: "all", multiplied: 0.5 },
          #{ attr: "hp", multiplied: 2 },
         ]
      },
      { 
         uid: 100002, 
         userName: '弱小的2号训练木人-中阶不入流', 
         skillIds: [10, 12],
         attrs: [
          { key: 'hp', value: 200 },
          { key: 'mp', value: 10 },
          { key: 'speed', value: 1 },
          { key: 'shield', value: 25 },
          { key: 'physicalAttack', value: 15 },
          { key: 'physicalDefense', value: 10 },
          { key: 'magicDefense', value: 0 },
          ],
         liftRate: [
          #{ attr: "all", multiplied: 1.2 },
          #{ attr: "all", multiplied: 1 },
          { attr: "all", multiplied: 0.8 },
          #{ attr: "speed", multiplied: 1.3 },
          #{ attr: "all", multiplied: 0.5 },
          #{ attr: "hp", multiplied: 2 },
         ]
      },
      { 
         uid: 100003, 
         userName: '迅捷的3号训练木人-中阶不入流', 
         skillIds: [10, 12],
         attrs: [
          { key: 'hp', value: 200 },
          { key: 'mp', value: 10 },
          { key: 'speed', value: 1 },
          { key: 'shield', value: 25 },
          { key: 'physicalAttack', value: 15 },
          { key: 'physicalDefense', value: 10 },
          { key: 'magicDefense', value: 0 },
          ],
         liftRate: [
          #{ attr: "all", multiplied: 1.2 },
          #{ attr: "all", multiplied: 1 },
          #{ attr: "all", multiplied: 0.8 },
          { attr: "speed", multiplied: 1.3 },
          #{ attr: "all", multiplied: 0.5 },
          #{ attr: "hp", multiplied: 2 },
         ]
      },
      { 
         uid: 100004, 
         userName: '虚弱的4号训练木人-中阶不入流', 
         skillIds: [10, 12],
         attrs: [
          { key: 'hp', value: 200 },
          { key: 'mp', value: 10 },
          { key: 'speed', value: 1 },
          { key: 'shield', value: 25 },
          { key: 'physicalAttack', value: 15 },
          { key: 'physicalDefense', value: 10 },
          { key: 'magicDefense', value: 0 },
          ],
         liftRate: [
          #{ attr: "all", multiplied: 1.2 },
          #{ attr: "all", multiplied: 1 },
          #{ attr: "all", multiplied: 0.8 },
          #{ attr: "speed", multiplied: 1.3 },
          { attr: "all", multiplied: 0.5 },
          #{ attr: "hp", multiplied: 2 },
         ]
      },
      { 
         uid: 100005, 
         userName: '强壮的5号训练木人-中阶不入流', 
         skillIds: [10, 12],
         attrs: [
          { key: 'hp', value: 200 },
          { key: 'mp', value: 10 },
          { key: 'speed', value: 1 },
          { key: 'shield', value: 25 },
          { key: 'physicalAttack', value: 15 },
          { key: 'physicalDefense', value: 10 },
          { key: 'magicDefense', value: 0 },
          ],
         liftRate: [
          #{ attr: "all", multiplied: 1.2 },
          #{ attr: "all", multiplied: 1 },
          #{ attr: "all", multiplied: 0.8 },
          #{ attr: "speed", multiplied: 1.3 },
          #{ attr: "all", multiplied: 0.5 },
          { attr: "hp", multiplied: 2 },
         ]
      },
      { 
         uid: 100006, 
         userName: '普通的6号训练木人-中阶不入流', 
         skillIds: [10, 12],
         attrs: [
          { key: 'hp', value: 200 },
          { key: 'mp', value: 10 },
          { key: 'speed', value: 1 },
          { key: 'shield', value: 25 },
          { key: 'physicalAttack', value: 15 },
          { key: 'physicalDefense', value: 10 },
          { key: 'magicDefense', value: 0 },
          ],
         liftRate: [
          #{ attr: "all", multiplied: 1.2 },
          { attr: "all", multiplied: 1 },
          #{ attr: "all", multiplied: 0.8 },
          #{ attr: "speed", multiplied: 1.3 },
          #{ attr: "all", multiplied: 0.5 },
          #{ attr: "hp", multiplied: 2 },
         ]
      },
      { 
         uid: 100007, 
         userName: '强大的7号训练木人-中阶不入流', 
         skillIds: [10, 12],
         attrs: [
          { key: 'hp', value: 200 },
          { key: 'mp', value: 10 },
          { key: 'speed', value: 1 },
          { key: 'shield', value: 25 },
          { key: 'physicalAttack', value: 15 },
          { key: 'physicalDefense', value: 10 },
          { key: 'magicDefense', value: 0 },
          ],
         liftRate: [
          { attr: "all", multiplied: 1.2 },
          #{ attr: "all", multiplied: 1 },
          #{ attr: "all", multiplied: 0.8 },
          #{ attr: "speed", multiplied: 1.3 },
          #{ attr: "all", multiplied: 0.5 },
          #{ attr: "hp", multiplied: 2 },
         ]
      },
      { 
         uid: 100008, 
         userName: '弱小的8号训练木人-中阶不入流', 
         skillIds: [10, 12],
         attrs: [
          { key: 'hp', value: 200 },
          { key: 'mp', value: 10 },
          { key: 'speed', value: 1 },
          { key: 'shield', value: 25 },
          { key: 'physicalAttack', value: 15 },
          { key: 'physicalDefense', value: 10 },
          { key: 'magicDefense', value: 0 },
          ],
         liftRate: [
          #{ attr: "all", multiplied: 1.2 },
          #{ attr: "all", multiplied: 1 },
          { attr: "all", multiplied: 0.8 },
          #{ attr: "speed", multiplied: 1.3 },
          #{ attr: "all", multiplied: 0.5 },
          #{ attr: "hp", multiplied: 2 },
         ]
      },
      { 
         uid: 100009, 
         userName: '迅捷的9号训练木人-中阶不入流', 
         skillIds: [10, 12],
         attrs: [
          { key: 'hp', value: 200 },
          { key: 'mp', value: 10 },
          { key: 'speed', value: 1 },
          { key: 'shield', value: 25 },
          { key: 'physicalAttack', value: 15 },
          { key: 'physicalDefense', value: 10 },
          { key: 'magicDefense', value: 0 },
          ],
         liftRate: [
          #{ attr: "all", multiplied: 1.2 },
          #{ attr: "all", multiplied: 1 },
          #{ attr: "all", multiplied: 0.8 },
          { attr: "speed", multiplied: 1.3 },
          #{ attr: "all", multiplied: 0.5 },
          #{ attr: "hp", multiplied: 2 },
         ]
      },
      { 
         uid: 100010, 
         userName: '虚弱的10号训练木人-中阶不入流', 
         skillIds: [10, 12],
         attrs: [
          { key: 'hp', value: 200 },
          { key: 'mp', value: 10 },
          { key: 'speed', value: 1 },
          { key: 'shield', value: 25 },
          { key: 'physicalAttack', value: 15 },
          { key: 'physicalDefense', value: 10 },
          { key: 'magicDefense', value: 0 },
          ],
         liftRate: [
          #{ attr: "all", multiplied: 1.2 },
          #{ attr: "all", multiplied: 1 },
          #{ attr: "all", multiplied: 0.8 },
          #{ attr: "speed", multiplied: 1.3 },
          { attr: "all", multiplied: 0.5 },
          #{ attr: "hp", multiplied: 2 },
         ]
      },
      { 
         uid: 100011, 
         userName: '强壮的11号训练木人-中阶不入流', 
         skillIds: [10, 12],
         attrs: [
          { key: 'hp', value: 200 },
          { key: 'mp', value: 10 },
          { key: 'speed', value: 1 },
          { key: 'shield', value: 25 },
          { key: 'physicalAttack', value: 15 },
          { key: 'physicalDefense', value: 10 },
          { key: 'magicDefense', value: 0 },
          ],
         liftRate: [
          #{ attr: "all", multiplied: 1.2 },
          #{ attr: "all", multiplied: 1 },
          #{ attr: "all", multiplied: 0.8 },
          #{ attr: "speed", multiplied: 1.3 },
          #{ attr: "all", multiplied: 0.5 },
          { attr: "hp", multiplied: 2 },
         ]
      },
      { 
         uid: 100012, 
         userName: '普通的12号训练木人-中阶不入流', 
         skillIds: [10, 12],
         attrs: [
          { key: 'hp', value: 200 },
          { key: 'mp', value: 10 },
          { key: 'speed', value: 1 },
          { key: 'shield', value: 25 },
          { key: 'physicalAttack', value: 15 },
          { key: 'physicalDefense', value: 10 },
          { key: 'magicDefense', value: 0 },
          ],
         liftRate: [
          #{ attr: "all", multiplied: 1.2 },
          { attr: "all", multiplied: 1 },
          #{ attr: "all", multiplied: 0.8 },
          #{ attr: "speed", multiplied: 1.3 },
          #{ attr: "all", multiplied: 0.5 },
          #{ attr: "hp", multiplied: 2 },
         ]
      },
      { 
         uid: 100013, 
         userName: '强大的13号训练木人-中阶不入流', 
         skillIds: [10, 12],
         attrs: [
          { key: 'hp', value: 200 },
          { key: 'mp', value: 10 },
          { key: 'speed', value: 1 },
          { key: 'shield', value: 25 },
          { key: 'physicalAttack', value: 15 },
          { key: 'physicalDefense', value: 10 },
          { key: 'magicDefense', value: 0 },
          ],
         liftRate: [
          { attr: "all", multiplied: 1.2 },
          #{ attr: "all", multiplied: 1 },
          #{ attr: "all", multiplied: 0.8 },
          #{ attr: "speed", multiplied: 1.3 },
          #{ attr: "all", multiplied: 0.5 },
          #{ attr: "hp", multiplied: 2 },
         ]
      },
      { 
         uid: 100014, 
         userName: '弱小的14号训练木人-中阶不入流', 
         skillIds: [10, 12],
         attrs: [
          { key: 'hp', value: 200 },
          { key: 'mp', value: 10 },
          { key: 'speed', value: 1 },
          { key: 'shield', value: 25 },
          { key: 'physicalAttack', value: 15 },
          { key: 'physicalDefense', value: 10 },
          { key: 'magicDefense', value: 0 },
          ],
         liftRate: [
          #{ attr: "all", multiplied: 1.2 },
          #{ attr: "all", multiplied: 1 },
          { attr: "all", multiplied: 0.8 },
          #{ attr: "speed", multiplied: 1.3 },
          #{ attr: "all", multiplied: 0.5 },
          #{ attr: "hp", multiplied: 2 },
         ]
      },
      { 
         uid: 100015, 
         userName: '迅捷的15号训练木人-中阶不入流', 
         skillIds: [10, 12],
         attrs: [
          { key: 'hp', value: 200 },
          { key: 'mp', value: 10 },
          { key: 'speed', value: 1 },
          { key: 'shield', value: 25 },
          { key: 'physicalAttack', value: 15 },
          { key: 'physicalDefense', value: 10 },
          { key: 'magicDefense', value: 0 },
          ],
         liftRate: [
          #{ attr: "all", multiplied: 1.2 },
          #{ attr: "all", multiplied: 1 },
          #{ attr: "all", multiplied: 0.8 },
          { attr: "speed", multiplied: 1.3 },
          #{ attr: "all", multiplied: 0.5 },
          #{ attr: "hp", multiplied: 2 },
         ]
      },
      { 
         uid: 100016, 
         userName: '虚弱的16号训练木人-中阶不入流', 
         skillIds: [10, 12],
         attrs: [
          { key: 'hp', value: 200 },
          { key: 'mp', value: 10 },
          { key: 'speed', value: 1 },
          { key: 'shield', value: 25 },
          { key: 'physicalAttack', value: 15 },
          { key: 'physicalDefense', value: 10 },
          { key: 'magicDefense', value: 0 },
          ],
         liftRate: [
          #{ attr: "all", multiplied: 1.2 },
          #{ attr: "all", multiplied: 1 },
          #{ attr: "all", multiplied: 0.8 },
          #{ attr: "speed", multiplied: 1.3 },
          { attr: "all", multiplied: 0.5 },
          #{ attr: "hp", multiplied: 2 },
         ]
      },
      { 
         uid: 100017, 
         userName: '强壮的17号训练木人-中阶不入流', 
         skillIds: [10, 12],
         attrs: [
          { key: 'hp', value: 200 },
          { key: 'mp', value: 10 },
          { key: 'speed', value: 1 },
          { key: 'shield', value: 25 },
          { key: 'physicalAttack', value: 15 },
          { key: 'physicalDefense', value: 10 },
          { key: 'magicDefense', value: 0 },
          ],
         liftRate: [
          #{ attr: "all", multiplied: 1.2 },
          #{ attr: "all", multiplied: 1 },
          #{ attr: "all", multiplied: 0.8 },
          #{ attr: "speed", multiplied: 1.3 },
          #{ attr: "all", multiplied: 0.5 },
          { attr: "hp", multiplied: 2 },
         ]
      },
      { 
         uid: 100018, 
         userName: '普通的18号训练木人-中阶不入流', 
         skillIds: [10, 12],
         attrs: [
          { key: 'hp', value: 200 },
          { key: 'mp', value: 10 },
          { key: 'speed', value: 1 },
          { key: 'shield', value: 25 },
          { key: 'physicalAttack', value: 15 },
          { key: 'physicalDefense', value: 10 },
          { key: 'magicDefense', value: 0 },
          ],
         liftRate: [
          #{ attr: "all", multiplied: 1.2 },
          { attr: "all", multiplied: 1 },
          #{ attr: "all", multiplied: 0.8 },
          #{ attr: "speed", multiplied: 1.3 },
          #{ attr: "all", multiplied: 0.5 },
          #{ attr: "hp", multiplied: 2 },
         ]
      },
      { 
         uid: 100019, 
         userName: '强大的19号训练木人-中阶不入流', 
         skillIds: [10, 12],
         attrs: [
          { key: 'hp', value: 200 },
          { key: 'mp', value: 10 },
          { key: 'speed', value: 1 },
          { key: 'shield', value: 25 },
          { key: 'physicalAttack', value: 15 },
          { key: 'physicalDefense', value: 10 },
          { key: 'magicDefense', value: 0 },
          ],
         liftRate: [
          { attr: "all", multiplied: 1.2 },
          #{ attr: "all", multiplied: 1 },
          #{ attr: "all", multiplied: 0.8 },
          #{ attr: "speed", multiplied: 1.3 },
          #{ attr: "all", multiplied: 0.5 },
          #{ attr: "hp", multiplied: 2 },
         ]
      },
      { 
         uid: 100020, 
         userName: '弱小的20号训练木人-中阶不入流', 
         skillIds: [10, 12],
         attrs: [
          { key: 'hp', value: 200 },
          { key: 'mp', value: 10 },
          { key: 'speed', value: 1 },
          { key: 'shield', value: 25 },
          { key: 'physicalAttack', value: 15 },
          { key: 'physicalDefense', value: 10 },
          { key: 'magicDefense', value: 0 },
          ],
         liftRate: [
          #{ attr: "all", multiplied: 1.2 },
          #{ attr: "all", multiplied: 1 },
          { attr: "all", multiplied: 0.8 },
          #{ attr: "speed", multiplied: 1.3 },
          #{ attr: "all", multiplied: 0.5 },
          #{ attr: "hp", multiplied: 2 },
         ]
      },
      { 
         uid: 100021, 
         userName: '迅捷的21号训练木人-中阶不入流', 
         skillIds: [10, 12],
         attrs: [
          { key: 'hp', value: 200 },
          { key: 'mp', value: 10 },
          { key: 'speed', value: 1 },
          { key: 'shield', value: 25 },
          { key: 'physicalAttack', value: 15 },
          { key: 'physicalDefense', value: 10 },
          { key: 'magicDefense', value: 0 },
          ],
         liftRate: [
          #{ attr: "all", multiplied: 1.2 },
          #{ attr: "all", multiplied: 1 },
          #{ attr: "all", multiplied: 0.8 },
          { attr: "speed", multiplied: 1.3 },
          #{ attr: "all", multiplied: 0.5 },
          #{ attr: "hp", multiplied: 2 },
         ]
      },
      { 
         uid: 100022, 
         userName: '虚弱的22号训练木人-中阶不入流', 
         skillIds: [10, 12],
         attrs: [
          { key: 'hp', value: 200 },
          { key: 'mp', value: 10 },
          { key: 'speed', value: 1 },
          { key: 'shield', value: 25 },
          { key: 'physicalAttack', value: 15 },
          { key: 'physicalDefense', value: 10 },
          { key: 'magicDefense', value: 0 },
          ],
         liftRate: [
          #{ attr: "all", multiplied: 1.2 },
          #{ attr: "all", multiplied: 1 },
          #{ attr: "all", multiplied: 0.8 },
          #{ attr: "speed", multiplied: 1.3 },
          { attr: "all", multiplied: 0.5 },
          #{ attr: "hp", multiplied: 2 },
         ]
      },
      { 
         uid: 1000023, 
         userName: '强壮的23号训练木人-中阶不入流', 
         skillIds: [10, 12],
         attrs: [
          { key: 'hp', value: 200 },
          { key: 'mp', value: 10 },
          { key: 'speed', value: 1 },
          { key: 'shield', value: 25 },
          { key: 'physicalAttack', value: 15 },
          { key: 'physicalDefense', value: 10 },
          { key: 'magicDefense', value: 0 },
          ],
         liftRate: [
          #{ attr: "all", multiplied: 1.2 },
          #{ attr: "all", multiplied: 1 },
          #{ attr: "all", multiplied: 0.8 },
          #{ attr: "speed", multiplied: 1.3 },
          #{ attr: "all", multiplied: 0.5 },
          { attr: "hp", multiplied: 2 },
         ]
      },
    ]
  }