# ===========================================
# 战斗配置
# ===========================================
challenge: {
    # 战斗ID
    id: 'f_x5',
    #和黑发阴灵的第一次战斗
    myself: 
      {
         uid: 1, 
         userName: '李森炎', 
         skillIds: [50, 51, 52, 54, 55, 56],
         attrs: [
          { key: 'hp', value: 10000 },
          { key: 'mp', value: 300 },
          { key: 'speed', value: 200 },
          { key: 'shield', value: 300 },
          { key: 'physicalAttack', value: 300 },
          { key: 'physicalDefense', value: 30 },
          { key: 'magicDefense', value: 30 },
         ],
      },

    enemies: [
      { 
         uid: 100000, 
         userName: '黑发阴灵', 
         skillIds: [10, 11, 12, 13],
         attrs: [
          { key: 'hp', value: 10000 },
          { key: 'mp', value: 300 },
          { key: 'speed', value: 0 },
          { key: 'shield', value: 300 },
          { key: 'physicalAttack', value: 300 },
          { key: 'physicalDefense', value: 30 },
          { key: 'magicDefense', value: 30 },
          ],
      },
    ]
  }