# ===========================================
# 战斗配置
# ===========================================
challenge: {
    # 战斗ID
    id: 'x2',

    myself: 
    {
       uid: 1, 
       userName: '李森炎', 
       skillIds: [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       attrs: [
        { key: 'hp', value: 4000 },
        { key: 'mp', value: 400 },
        { key: 'speed', value: 400 },
        { key: 'shield', value: 240 },
        { key: 'physicalAttack', value: 400 },
        { key: 'physicalDefense', value: 30 },
        { key: 'magicDefense', value: 30 },
      ],
      },

    enemies: [
      { 
         uid: 100000, 
         userName: '黑发阴灵', 
         skillIds: [40033, 40033, 40033],
         attrs: [
          { key: 'hp', value: 3000 },
          { key: 'mp', value: 300 },
          { key: 'speed', value: 0 },
          { key: 'shield', value: 240 },
          { key: 'physicalAttack', value: 300 },
          { key: 'physicalDefense', value: 30 },
          { key: 'magicDefense', value: 30 },
          ],
      },
    ]
  }