# ===========================================
# 战斗配置
# ===========================================
challenge: {
    # 战斗ID
    id: 'x1',
    #和黑发阴灵的第一次战斗
    myself: 
      {
         uid: 1, 
         userName: '李森炎', 
         skillIds: [50, 51, 52],
         attrs: [
          { key: 'hp', value: 2000 },
          { key: 'mp', value: 200 },
          { key: 'speed', value: 200 },
          { key: 'shield', value: 120 },
          { key: 'physicalAttack', value: 100 },
          { key: 'physicalDefense', value: 25 },
          { key: 'magicDefense', value: 15 },
         ],
      },

    enemies: [
      { 
         uid: 100000, 
         userName: '强大的筑基人面蛛王', 
         skillIds: [40030, 40031, 40032],
         attrs: [
          { key: 'hp', value: 500 },
          { key: 'mp', value: 125 },
          { key: 'speed', value: 1 },
          { key: 'shield', value: 125 },
          { key: 'physicalAttack', value: 50 },
          { key: 'physicalDefense', value: 25 },
          { key: 'magicDefense', value: 0 },
          ],
          iftRate: [
          { attr: "all", multiplied: 1.2 },
         ]
      },
      { 
         uid: 100001, 
         userName: '强大的练气人面白蛛', 
         skillIds: [40030, 40031, 40032],
         attrs: [
          { key: 'hp', value: 400 },
          { key: 'mp', value: 100 },
          { key: 'speed', value: 1 },
          { key: 'shield', value: 100 },
          { key: 'physicalAttack', value: 40 },
          { key: 'physicalDefense', value: 20 },
          { key: 'magicDefense', value: 0 },
          ],
          iftRate: [
          { attr: "all", multiplied: 1.2 },
         ]
      },
      { 
         uid: 100002, 
         userName: '强大的先天人面白蛛', 
         skillIds: [40030, 40031, 40032],
         attrs: [
          { key: 'hp', value: 300 },
          { key: 'mp', value: 75 },
          { key: 'speed', value: 1 },
          { key: 'shield', value: 75 },
          { key: 'physicalAttack', value: 30 },
          { key: 'physicalDefense', value: 15 },
          { key: 'magicDefense', value: 0 },
          ],
          iftRate: [
          { attr: "all", multiplied: 1.2 },
         ]
      },
      { 
         uid: 100003, 
         userName: '弱小的后天人面白蛛', 
         skillIds: [40030, 40031, 40032],
         attrs: [
          { key: 'hp', value: 200 },
          { key: 'mp', value: 50 },
          { key: 'speed', value: 1 },
          { key: 'shield', value: 50 },
          { key: 'physicalAttack', value: 20 },
          { key: 'physicalDefense', value: 10 },
          { key: 'magicDefense', value: 0 },
          ],
          iftRate: [
          { attr: "all", multiplied: 0.8 },
         ]
      },
      { 
         uid: 100004, 
         userName: '虚弱的不入流人面白蛛', 
         skillIds: [40030, 40031, 40032],
         attrs: [
          { key: 'hp', value: 100 },
          { key: 'mp', value: 25 },
          { key: 'speed', value: 1 },
          { key: 'shield', value: 25 },
          { key: 'physicalAttack', value: 10 },
          { key: 'physicalDefense', value: 5 },
          { key: 'magicDefense', value: 0 },
          ],
          iftRate: [
          { attr: "all", multiplied: 0.5 },
         ]
      },
      { 
         uid: 100005, 
         userName: '杨真', 
         skillIds: [40030, 40031, 40032],
         attrs: [
          { key: 'hp', value: 200 },
          { key: 'mp', value: 125 },
          { key: 'speed', value: 1 },
          { key: 'shield', value: 125 },
          { key: 'physicalAttack', value: 50 },
          { key: 'physicalDefense', value: 25 },
          { key: 'magicDefense', value: 0 },
          ],
          iftRate: [
          { attr: "all", multiplied: 1 },
         ]
      },
    ]
  }