# ===========================================
# 文件索引表
# ===========================================
files: [
  'XX_[START].txt',
  'XX_M1_N1_[A1].txt',
  'XX_M1_N1_[A2].txt',
  'XX_M1_N1.txt',
  'XX_M1.txt',
  'XX_M2.txt',
  'XX_M3.txt',
]