// ===============================
// 事件KEYS
// ===============================
export class EventKeys {

    static APP_SET_STATE = 'APP_SET_STATE';

    static APP_DISPATCH = 'APP_DISPATCH';

    static CAROUSEL_SELECT_ITEM = 'CAROUSEL_SELECT_ITEM';

    static CAROUSEL_ENTER_SHOW = 'CAROUSEL_ENTER_SHOW';

    static AREA_BLOCK_SELECTED = 'AREA_BLOCK_SELECTED';

    static EXPLORETABPAGE_SHOW = 'EXPLORETABPAGE_SHOW';

    static LOTTERYPOPPAGE_SHOW = 'LOTTERYPOPPAGE_SHOW';

    static ARTICLE_PAGE_PRESS = 'ARTICLE_PAGE_PRESS';

    static ARTICLE_PAGE_LONG_PRESS = 'ARTICLE_PAGE_LONG_PRESS';

    static ARTICLE_PAGE_SCROLL = 'ARTICLE_PAGE_SCROLL';

    static ARTICLE_PAGE_HIDE_BANNER = 'ARTICLE_PAGE_HIDE_BANNER';

    // 动画结束
    static ANIMATION_END = 'ANIMATION_END';

}
