// ===============================
// 事件KEYS
// ===============================
export class EventKeys {

    static USER_ATTR_UPDATE = 'USER_ATTR_UPDATE';
    static OPTIONS_HIDE = 'OPTIONS_HIDE';
    static APP_SET_STATE = 'APP_SET_STATE';
    static APP_DISPATCH = 'APP_DISPATCH';
    static ENTER_SCENE = 'ENTER_SCENE';
    static CAROUSEL_SELECT_ITEM = 'CAROUSEL_SELECT_ITEM';
    static CAROUSEL_ENTER_SHOW = 'CAROUSEL_ENTER_SHOW';
    static AREA_BLOCK_SELECTED = 'AREA_BLOCK_SELECTED';
    static EXPLORETABPAGE_SHOW = 'EXPLORETABPAGE_SHOW';
    static LOTTERYPOPPAGE_SHOW = 'LOTTERYPOPPAGE_SHOW';
    static ARTICLE_PAGE_PRESS = 'ARTICLE_PAGE_PRESS';
    static ARTICLE_PAGE_LONG_PRESS = 'ARTICLE_PAGE_LONG_PRESS';
    static ARTICLE_PAGE_SCROLL = 'ARTICLE_PAGE_SCROLL';
    static ARTICLE_PAGE_HIDE_BANNER = 'ARTICLE_PAGE_HIDE_BANNER';

    // 动画结束
    static ANIMATION_END = 'ANIMATION_END';

    // 探索相关消息
    static EXPLORE_MSGLIST_ADD = 'EXPLORE_MSGLIST_ADD';
    static EXPLORE_MSGLIST_ADDALL = 'EXPLORE_MSGLIST_ADDALL';
    static EXPLORE_TIMEBANNER_HIDE = 'EXPLORE_TIMEBANNER_HIDE';
    static EXPLORE_TIMEBANNER_RESUME = 'EXPLORE_TIMEBANNER_RESUME';
    static EXPLORE_UPDATE_EVENT_NUM = 'EXPLORE_UPDATE_EVENT_NUM';
    static EXPLORE_PK_BEGIN = 'EXPLORE_PK_BEGIN';
    static EXPLORE_PK_END = 'EXPLORE_PK_END';
    static EXPLORE_BOX_HIDE = 'EXPLORE_BOX_HIDE';
    static EXPLORE_UPDATE_PROGRESS = 'EXPLORE_UPDATE_PROGRESS';

    // 音乐音量设置
    static SOUND_BG_VOLUME_UPDATE = 'SOUND_BG_VOLUME_UPDATE';
    // 音效音量设置
    static SOUND_EFFECT_VOLUME_UPDATE = 'SOUND_EFFECT_VOLUME_UPDATE';
    // 播放背景音乐
    static SOUND_BGM_PLAY = 'SOUND_BGM_PLAY';
    // 播放音效
    static SOUND_EFFECT_PLAY = 'SOUND_EFFECT_PLAY';
    // 移动场景地图坐标
    static SCENE_MAP_MOVE = 'SCENE_MAP_MOVE';

    // 导航路径发生变化
    static NAVIGATION_ROUTE_CHANGED = 'NAVIGATION_ROUTE_CHANGED';

    // 图片视图进入事件检测区域
    static IMAGE_VIEW_ENTER_EVENT_AREA = 'IMAGE_VIEW_ENTER_EVENT_AREA';

    // 更换阅读器内容背景图片
    static READER_BACKGROUND_IMG_UPDATE = 'READER_BACKGROUND_IMG_UPDATE';

    // 切换至目录地图
    static GOTO_DIRECTORY_MAP = 'GOTO_DIRECTORY_MAP';
    // 隐藏目录地图
    static HIDE_DIRECTORY_MAP = 'HIDE_DIRECTORY_MAP';
    // 返回至目录
    static BACK_DIRECTORY = 'BACK_DIRECTORY';

    // 文章内超链接点击
    static ARTICLE_CLICK_LINK = 'ARTICLE_CLICK_LINK';
}
