
import lo from 'lodash';

const topBgImages = [
    { name: 'BGT_1', img: require('../../assets/scene/BGT_1.webp') },
    { name: 'BGT_2', img: require('../../assets/scene/BGT_2.webp') },
    { name: 'BGT_3', img: require('../../assets/scene/BGT_3.webp') },
    { name: 'BGT_4', img: require('../../assets/scene/BGT_4.webp') },
    { name: 'BGT_5', img: require('../../assets/scene/BGT_5.webp') },
    { name: 'BGT_6', img: require('../../assets/scene/BGT_6.webp') },
    { name: 'BGT_7', img: require('../../assets/scene/BGT_7.webp') },
    { name: 'BGT_8', img: require('../../assets/scene/BGT_8.webp') },
    { name: 'BGT_9', img: require('../../assets/scene/BGT_9.webp') },
    { name: 'BGT_10', img: require('../../assets/scene/BGT_10.webp') },
    { name: 'BGT_11', img: require('../../assets/scene/BGT_11.webp') },
    { name: 'BGT_12', img: require('../../assets/scene/BGT_12.webp') },
    { name: 'BGT_13', img: require('../../assets/scene/BGT_13.webp') },
    { name: 'BGT_14', img: require('../../assets/scene/BGT_14.webp') },
    { name: 'BGT_15', img: require('../../assets/scene/BGT_15.webp') },
    { name: 'BGT_16', img: require('../../assets/scene/BGT_16.webp') },
    { name: 'BGT_17', img: require('../../assets/scene/BGT_17.webp') },
    { name: 'BGT_18', img: require('../../assets/scene/BGT_18.webp') },
    { name: 'BGT_19', img: require('../../assets/scene/BGT_19.webp') },
    { name: 'BGT_20', img: require('../../assets/scene/BGT_20.webp') },
    { name: 'BGT_21', img: require('../../assets/scene/BGT_21.webp') },
    { name: 'BGT_22', img: require('../../assets/scene/BGT_22.webp') },
    { name: 'BGT_23', img: require('../../assets/scene/BGT_23.webp') },
    { name: 'BGT_24', img: require('../../assets/scene/BGT_24.webp') },
    { name: 'BGT_25', img: require('../../assets/scene/BGT_25.webp') },
    { name: 'BGT_26', img: require('../../assets/scene/BGT_26.webp') },
    { name: 'BGT_27', img: require('../../assets/scene/BGT_27.webp') },
    { name: 'BGT_28', img: require('../../assets/scene/BGT_28.webp') },
    { name: 'BGT_29', img: require('../../assets/scene/BGT_29.webp') },
    { name: 'BGT_30', img: require('../../assets/scene/BGT_30.webp') },
    { name: 'BGT_31', img: require('../../assets/scene/BGT_31.webp') },
    { name: 'BGT_32', img: require('../../assets/scene/BGT_32.webp') },
    { name: 'BGT_33', img: require('../../assets/scene/BGT_33.webp') },
    { name: 'BGT_34', img: require('../../assets/scene/BGT_34.webp') },
    { name: 'BGT_35', img: require('../../assets/scene/BGT_35.webp') },
    { name: 'BGT_36', img: require('../../assets/scene/BGT_36.webp') },
    { name: 'BGT_37', img: require('../../assets/scene/BGT_37.webp') },
    { name: 'BGT_38', img: require('../../assets/scene/BGT_38.webp') },
    { name: 'BGT_39', img: require('../../assets/scene/BGT_39.webp') },
    { name: 'BGT_40', img: require('../../assets/scene/BGT_40.webp') },
    { name: 'BGT_41', img: require('../../assets/scene/BGT_41.webp') },
    { name: 'BGT_42', img: require('../../assets/scene/BGT_42.webp') },
    { name: 'BGT_43', img: require('../../assets/scene/BGT_43.webp') },
    { name: 'BGT_44', img: require('../../assets/scene/BGT_44.webp') },
    { name: 'BGT_45', img: require('../../assets/scene/BGT_45.webp') },
    { name: 'BGT_46', img: require('../../assets/scene/BGT_46.webp') },
    { name: 'BGT_47', img: require('../../assets/scene/BGT_47.webp') },
    { name: 'BGT_48', img: require('../../assets/scene/BGT_48.webp') },
    { name: 'BGT_49', img: require('../../assets/scene/BGT_49.webp') },
    { name: 'BGT_50', img: require('../../assets/scene/BGT_50.webp') },
    { name: 'BGT_51', img: require('../../assets/scene/BGT_51.webp') },
    { name: 'BGT_52', img: require('../../assets/scene/BGT_52.webp') },
    { name: 'BGT_53', img: require('../../assets/scene/BGT_53.webp') },
    { name: 'BGT_54', img: require('../../assets/scene/BGT_54.webp') },
    { name: 'BGT_55', img: require('../../assets/scene/BGT_55.webp') },
    { name: 'BGT_56', img: require('../../assets/scene/BGT_56.webp') },
    { name: 'BGT_57', img: require('../../assets/scene/BGT_57.webp') },
    { name: 'BGT_58', img: require('../../assets/scene/BGT_58.webp') },
    { name: 'BGT_59', img: require('../../assets/scene/BGT_59.webp') },
    { name: 'BGT_60', img: require('../../assets/scene/BGT_60.webp') },
    { name: 'BGT_61', img: require('../../assets/scene/BGT_61.webp') },
    { name: 'BGT_62', img: require('../../assets/scene/BGT_62.webp') },
    { name: 'BGT_63', img: require('../../assets/scene/BGT_63.webp') },
    { name: 'BGT_64', img: require('../../assets/scene/BGT_64.webp') },
    { name: 'BGT_65', img: require('../../assets/scene/BGT_65.webp') },
    { name: 'BGT_66', img: require('../../assets/scene/BGT_66.webp') },
    { name: 'BGT_67', img: require('../../assets/scene/BGT_67.webp') },
    { name: 'BGT_68', img: require('../../assets/scene/BGT_68.webp') },
    { name: 'BGT_69', img: require('../../assets/scene/BGT_69.webp') },
    { name: 'BGT_70', img: require('../../assets/scene/BGT_70.webp') },
    { name: 'BGT_71', img: require('../../assets/scene/BGT_71.webp') },
    { name: 'BGT_72', img: require('../../assets/scene/BGT_72.webp') },
    { name: 'BGT_73', img: require('../../assets/scene/BGT_73.webp') },
    { name: 'BGT_74', img: require('../../assets/scene/BGT_74.webp') },
    { name: 'BGT_75', img: require('../../assets/scene/BGT_75.webp') },
    { name: 'BGT_76', img: require('../../assets/scene/BGT_76.webp') },
    { name: 'BGT_77', img: require('../../assets/scene/BGT_77.webp') },
    { name: 'BGT_78', img: require('../../assets/scene/BGT_78.webp') },
    { name: 'BGT_79', img: require('../../assets/scene/BGT_79.webp') },
    { name: 'BGT_80', img: require('../../assets/scene/BGT_80.webp') },
    { name: 'BGT_81', img: require('../../assets/scene/BGT_81.webp') },
    { name: 'BGT_82', img: require('../../assets/scene/BGT_82.webp') },
    { name: 'BGT_83', img: require('../../assets/scene/BGT_83.webp') },
    { name: 'BGT_84', img: require('../../assets/scene/BGT_84.webp') },
    { name: 'BGT_85', img: require('../../assets/scene/BGT_85.webp') },
    { name: 'BGT_86', img: require('../../assets/scene/BGT_86.webp') },
    { name: 'BGT_87', img: require('../../assets/scene/BGT_87.webp') },
    { name: 'BGT_88', img: require('../../assets/scene/BGT_88.webp') },
    { name: 'BGT_89', img: require('../../assets/scene/BGT_89.webp') },
    { name: 'BGT_90', img: require('../../assets/scene/BGT_90.webp') },
    { name: 'BGT_91', img: require('../../assets/scene/BGT_91.webp') },
    { name: 'BGT_92', img: require('../../assets/scene/BGT_92.webp') },
    { name: 'BGT_93', img: require('../../assets/scene/BGT_93.webp') },
    { name: 'BGT_94', img: require('../../assets/scene/BGT_94.webp') },
    { name: 'BGT_95', img: require('../../assets/scene/BGT_95.webp') },
    { name: 'BGT_96', img: require('../../assets/scene/BGT_96.webp') },
    { name: 'BGT_97', img: require('../../assets/scene/BGT_97.webp') },
    { name: 'BGT_98', img: require('../../assets/scene/BGT_98.webp') },
    { name: 'BGT_99', img: require('../../assets/scene/BGT_99.webp') },
    { name: 'BGT_100', img: require('../../assets/scene/BGT_100.webp') },
    { name: 'BGT_101', img: require('../../assets/scene/BGT_101.webp') },
    { name: 'BGT_102', img: require('../../assets/scene/BGT_102.webp') },
    { name: 'BGT_103', img: require('../../assets/scene/BGT_103.webp') },
    { name: 'BGT_104', img: require('../../assets/scene/BGT_104.webp') },
    { name: 'BGT_105', img: require('../../assets/scene/BGT_105.webp') },
    { name: 'BGT_106', img: require('../../assets/scene/BGT_106.webp') },


    



   // { name: '上部背景图57656', img: require('../../assets/scene/BGT_70789789.jpg') },
];

// 场景背景图
export const getSceneTopBackgroundImage = (name) => {
    return topBgImages.find(e => lo.isEqual(e.name, name));
}