data:
  {
    id: "qiyu_4_XXX",
    name: "qiyu_4_XXX",
    data:
      {
        style: 6,
        title: "神秘阵盘",
        dialogType: "HalfScreen",
        textAnimationType: "TextFadeIn",
        sections:
          [
            {
              key: "p1",
              content:
                [
                  "你迅速跑过去，地面有些东西。",
                  "走开走开，马夫大喝， 正从远处拨开人群走来。",
                  "获得几颗石头珠子，看起来能卖不少钱。",
                ],
              btn:
                [
                  {
                    title: "去拿菜刀",
                    tokey: "p2",
                    props: [{ propId: 20, num: 10 }],
                  },
                  { title: "去拿画轴", tokey: "p3" },
                ],
            },
            {
              key: "p2",
              content:
                [
                  "来这里这么多天了，连个像样的防身东西都没有，你觉得菜刀出现的正是时候。",
                  "动不了",
                  "动不了",
                  "动不了",
                ],
              btn: [{ title: "退出", tokey: "next" }],
            },
            {
              key: "p3",
              content:
                [
                  "那是一个没有磕碰的精美画轴，你直觉的感到那些是个很值钱的东西。",
                  "动不了",
                  "动不了",
                  "动不了",
                ],
              btn: [{ title: "退出", tokey: "next" }],
            },
          ],
      },
  }
