## 配置线索

cluesConfigData: {

    # 默认 线索
    defaultClues: ['xiansuo2', 'xiansuo3'],

    # 线索类型 注册
    type: ['线索', '流言', '情报'],

    # groupId: ['李家村', '王家村', '杨家村'],

    # 对应线索 过滤条件
    filterData: [
        {
          type: '线索',
          filterCondition:
            [
              {filterType: 'location', filterTypeName: '地点'},
              {filterType: 'biaoqian', filterTypeName: '标签'},
              # {filterType: 'chapter', filterTypeName: '章节'},

            ],
        },
        {
          type: '流言',
          filterCondition:
            [
              {filterType: 'location', filterTypeName: '地址'},
            ],
        },
    ],

    # 线索配置注册
    config_List: [
      'CLUES/xiansuo1',
      'CLUES/xiansuo2',
      'CLUES/xiansuo3',
      'CLUES/xiansuo4',
      'Liuyan/liuyan1',
      'Liuyan/liuyan2',
      'Liuyan/liuyan3',
    ],

  }
