# ===========================================
# BUFF配置
# ===========================================
buffs: [
   {
      # Buff ID
      id: 1,

      # 图标ID
      iconId: 1,

      # 技能名称
      name: '锻体决 BUFF',

      # 描述
      desc: '',

      # 影响公式
      formula: 'A_物理防御 = A_物理防御 * 1.1 + 200',

      # 影响回合
      round: 3,
   },
   {
      # Buff ID
      id: 2,

      # 图标ID
      iconId: 1,

      # 技能名称
      name: '护身罡气 BUFF',

      # 描述
      desc: '',

      # 影响公式
      formula: 'A_物理防御 = A_物理防御 + 400',

      # 影响回合
      round: 3,
   },
   {
      # Buff ID
      id: 3,

      # 图标ID
      iconId: 1,

      # 技能名称
      name: '微光盾 BUFF',

      # 描述
      desc: '',

      # 影响公式
      formula: 'A_法术防御 = A_法术防御 * 2',

      # 影响回合
      round: 3,
   },
]