# 收藏品 (绿2->蓝3->紫4->橙5)
collections: [
  {
    # 收藏品唯一ID
    id: 1,

    # 收藏品名称
    name: '金项链',

    # 所属分类
    categories: ['金'],

    # 解锁道具
    propId: 700,

    # 星级
    stars: 3,

    # 激活消耗
    activation: {
      copper: 200,
    },

    # 收藏品属性加成
    attrs: [
      [{ key: '速度', value: 10 }, { key: '防御', value: 5 }], # 1星
      [{ key: '速度', value: 20 }, { key: '防御', value: 10 }], # 2星
      [{ key: '速度', value: 30 }, { key: '防御', value: 20 }], # 3星
    ],

    # 升级
    upgrade: [
      # 1星
      {
        # 阶段升级
        items: [
          # 第一个卡位
          [
            { propId: 100, num: 1 },
            { propId: 100, num: 1 },
            { propId: 100, num: 1 },
            { propId: 100, num: 1 },
            { propId: 100, num: 1 },
          ],
          # 第二个卡位
          [
            { propId: 100, num: 2 },
            { propId: 100, num: 2 },
            { propId: 100, num: 2 },
            { propId: 100, num: 2 },
            { propId: 100, num: 2 },
          ],
          # 第三个卡位
          [
            { propId: 100, num: 3 },
          ],
        ]
      },

      # 2星
      {
        # 阶段升级
        items: [
          # 第一个卡位
          [
            { propId: 100, num: 1 },
            { propId: 100, num: 1 },
            { propId: 100, num: 1 },
            { propId: 100, num: 1 },
            { propId: 100, num: 1 },
          ],
          # 第二个卡位
          [
            { propId: 100, num: 1 },
            { propId: 100, num: 1 },
            { propId: 100, num: 1 },
            { propId: 100, num: 1 },
            { propId: 100, num: 1 },
          ],
          # 第三个卡位
          [
            { propId: 100, num: 1 },
          ],
        ]
      },

      # 3星
      {
        # 阶段升级
        items: [
          # 第一个卡位
          [
            { propId: 100, num: 1 },
            { propId: 100, num: 1 },
            { propId: 100, num: 1 },
            { propId: 100, num: 1 },
            { propId: 100, num: 1 },
          ],
          # 第二个卡位
          [
            { propId: 100, num: 1 },
            { propId: 100, num: 1 },
            { propId: 100, num: 1 },
            { propId: 100, num: 1 },
            { propId: 100, num: 1 },
          ],
          # 第三个卡位
          [
            { propId: 100, num: 1 },
          ],
        ]
      },
    ]
  },

]