# 收藏品 (绿2->蓝3->紫4->橙5)
collections: {
  # 改良需要消耗对应品质的道具
  improvementProps: [ 3001, 3002, 3003, 3004 ], # 必须为4个, 用于在收藏品页面顶部显示道具数量

  # 定义所有收藏品
  items: [
    {
      # 收藏品唯一ID
      id: 1,

      # 收藏品名称
      name: '金项链',

      # 所属分类
      categories: ['金'],

      # 解锁道具
      propId: 700,

      # 星级
      stars: 3,

      # 激活消耗
      activation: {
        copper: 200,
      },

      # 收藏品属性加成
      attrs: [
        [{ key: '速度', value: 10 }, { key: '防御', value: 5 }], # 1星
        [{ key: '速度', value: 20 }, { key: '防御', value: 10 }], # 2星
        [{ key: '速度', value: 30 }, { key: '防御', value: 20 }], # 3星
      ],

      # 升级
      upgrade: [
        # 1星
        {
          # 阶段升级
          items: [
            # 第一个卡位
            [
              { props: [{ propId: 3001, num: 1 }] },
              { props: [{ propId: 3001, num: 1 }] },
              { props: [{ propId: 3001, num: 1 }] },
              { props: [{ propId: 3001, num: 1 }] },
              { props: [{ propId: 3001, num: 1 }] },
            ],
            # 第二个卡位
            [
              { props: [{ propId: 3001, num: 2 }] },
              { props: [{ propId: 3001, num: 2 }] },
              { props: [{ propId: 3001, num: 2 }] },
              { props: [{ propId: 3001, num: 2 }] },
              { props: [{ propId: 3001, num: 2 }] },
            ],
            # 第三个卡位
            [
              { props: [{ propId: 3001, num: 3 }, { propId: 3101, num: 1 }] },
            ],
          ]
        },

        # 2星
        {
          # 阶段升级
          items: [
            # 第一个卡位
            [
              { props: [{ propId: 3001, num: 1 }] },
              { props: [{ propId: 3001, num: 1 }] },
              { props: [{ propId: 3001, num: 1 }] },
              { props: [{ propId: 3001, num: 1 }] },
              { props: [{ propId: 3001, num: 1 }] },
            ],
            # 第二个卡位
            [
              { props: [{ propId: 3001, num: 2 }] },
              { props: [{ propId: 3001, num: 2 }] },
              { props: [{ propId: 3001, num: 2 }] },
              { props: [{ propId: 3001, num: 2 }] },
              { props: [{ propId: 3001, num: 2 }] },
            ],
            # 第三个卡位
            [
              { props: [{ propId: 3001, num: 3 }, { propId: 3101, num: 2 }] },
            ],
          ]
        },

        # 3星
        {
          # 阶段升级
          items: [
            # 第一个卡位
            [
              { props: [{ propId: 3001, num: 1 }] },
              { props: [{ propId: 3001, num: 1 }] },
              { props: [{ propId: 3001, num: 1 }] },
              { props: [{ propId: 3001, num: 1 }] },
              { props: [{ propId: 3001, num: 1 }] },
            ],
            # 第二个卡位
            [
              { props: [{ propId: 3001, num: 2 }] },
              { props: [{ propId: 3001, num: 2 }] },
              { props: [{ propId: 3001, num: 2 }] },
              { props: [{ propId: 3001, num: 2 }] },
              { props: [{ propId: 3001, num: 2 }] },
            ],
            # 第三个卡位
            [
              { props: [{ propId: 3001, num: 3 }, { propId: 3101, num: 3 }] },
            ],
          ]
        },
      ]
    },

    {
      # 收藏品唯一ID
      id: 2,

      # 收藏品名称
      name: '金手镯',

      # 所属分类
      categories: ['金'],

      # 解锁道具
      propId: 700,

      # 星级
      stars: 5,

      # 激活消耗
      activation: {
        copper: 200,
      },

      # 收藏品属性加成
      attrs: [
        [{ key: '速度', value: 10 }, { key: '防御', value: 5 }], # 1星
        [{ key: '速度', value: 20 }, { key: '防御', value: 10 }], # 2星
        [{ key: '速度', value: 30 }, { key: '防御', value: 20 }], # 3星
        [{ key: '速度', value: 40 }, { key: '防御', value: 30 }], # 4星
        [{ key: '速度', value: 50 }, { key: '防御', value: 40 }], # 5星
      ],

      # 升级
      upgrade: [
        # 1星
        {
          # 阶段升级
          items: [
            # 第一个卡位
            [
              { props: [{ propId: 3001, num: 1 }, { propId: 3002, num: 1 }] },
              { props: [{ propId: 3001, num: 1 }] },
              { props: [{ propId: 3001, num: 1 }] },
              { props: [{ propId: 3001, num: 1 }] },
              { props: [{ propId: 3001, num: 1 }] },
            ],
            # 第三个卡位
            [
              { props: [{ propId: 3001, num: 3 }, { propId: 3102, num: 1 }] },
            ],
          ]
        },

        # 2星
        {
          # 阶段升级
          items: [
            # 第一个卡位
            [
              { props: [{ propId: 3001, num: 1 }] },
              { props: [{ propId: 3001, num: 1 }] },
              { props: [{ propId: 3001, num: 1 }] },
              { props: [{ propId: 3001, num: 1 }] },
              { props: [{ propId: 3001, num: 1 }] },
            ],
            # 第二个卡位
            [
              { props: [{ propId: 3001, num: 2 }] },
              { props: [{ propId: 3001, num: 2 }] },
              { props: [{ propId: 3001, num: 2 }] },
              { props: [{ propId: 3001, num: 2 }] },
              { props: [{ propId: 3001, num: 2 }] },
            ],
            # 第三个卡位
            [
              { props: [{ propId: 3001, num: 3 }, { propId: 3102, num: 2 }] },
            ],
          ]
        },

        # 3星
        {
          # 阶段升级
          items: [
            # 第一个卡位
            [
              { props: [{ propId: 3001, num: 1 }] },
              { props: [{ propId: 3001, num: 1 }] },
              { props: [{ propId: 3001, num: 1 }] },
              { props: [{ propId: 3001, num: 1 }] },
              { props: [{ propId: 3001, num: 1 }] },
            ],
            # 第二个卡位
            [
              { props: [{ propId: 3001, num: 2 }] },
              { props: [{ propId: 3001, num: 2 }] },
              { props: [{ propId: 3001, num: 2 }] },
              { props: [{ propId: 3001, num: 2 }] },
              { props: [{ propId: 3001, num: 2 }] },
            ],
            # 第三个卡位
            [
              { props: [{ propId: 3001, num: 2 }] },
              { props: [{ propId: 3001, num: 2 }] },
              { props: [{ propId: 3001, num: 2 }] },
              { props: [{ propId: 3001, num: 2 }] },
              { props: [{ propId: 3001, num: 2 }] },
            ],
            # 第四个卡位
            [
              { props: [{ propId: 3002, num: 2 }] },
              { props: [{ propId: 3002, num: 2 }] },
              { props: [{ propId: 3002, num: 2 }] },
              { props: [{ propId: 3002, num: 2 }] },
              { props: [{ propId: 3002, num: 2 }] },
            ],
            # 第五个卡位
            [
              { props: [{ propId: 3003, num: 3 }, { propId: 3102, num: 3 }] },
            ],
          ]
        },

        # 4星
        {
          # 阶段升级
          items: [
            # 第一个卡位
            [
              { props: [{ propId: 3001, num: 1 }] },
              { props: [{ propId: 3001, num: 1 }] },
              { props: [{ propId: 3001, num: 1 }] },
              { props: [{ propId: 3001, num: 1 }] },
              { props: [{ propId: 3001, num: 1 }] },
            ],
            # 第二个卡位
            [
              { props: [{ propId: 3001, num: 2 }] },
              { props: [{ propId: 3001, num: 2 }] },
              { props: [{ propId: 3001, num: 2 }] },
              { props: [{ propId: 3001, num: 2 }] },
              { props: [{ propId: 3001, num: 2 }] },
            ],
            # 第三个卡位
            [
              { props: [{ propId: 3001, num: 2 }] },
              { props: [{ propId: 3001, num: 2 }] },
              { props: [{ propId: 3001, num: 2 }] },
              { props: [{ propId: 3001, num: 2 }] },
              { props: [{ propId: 3001, num: 2 }] },
            ],
            # 第四个卡位
            [
              { props: [{ propId: 3002, num: 2 }] },
              { props: [{ propId: 3002, num: 2 }] },
              { props: [{ propId: 3002, num: 2 }] },
              { props: [{ propId: 3002, num: 2 }] },
              { props: [{ propId: 3002, num: 2 }] },
            ],
            # 第五个卡位
            [
              { props: [{ propId: 3003, num: 3 }, { propId: 3102, num: 4 }] },
            ],
          ]
        },

        # 5星
        {
          # 阶段升级
          items: [
            # 第一个卡位
            [
              { props: [{ propId: 3001, num: 1 }] },
              { props: [{ propId: 3001, num: 1 }] },
              { props: [{ propId: 3001, num: 1 }] },
              { props: [{ propId: 3001, num: 1 }] },
              { props: [{ propId: 3001, num: 1 }] },
            ],
            # 第二个卡位
            [
              { props: [{ propId: 3001, num: 2 }] },
              { props: [{ propId: 3001, num: 2 }] },
              { props: [{ propId: 3001, num: 2 }] },
              { props: [{ propId: 3001, num: 2 }] },
              { props: [{ propId: 3001, num: 2 }] },
            ],
            # 第三个卡位
            [
              { props: [{ propId: 3001, num: 2 }] },
              { props: [{ propId: 3001, num: 2 }] },
              { props: [{ propId: 3001, num: 2 }] },
              { props: [{ propId: 3001, num: 2 }] },
              { props: [{ propId: 3001, num: 2 }] },
            ],
            # 第四个卡位
            [
              { props: [{ propId: 3002, num: 2 }] },
              { props: [{ propId: 3002, num: 2 }] },
              { props: [{ propId: 3002, num: 2 }] },
              { props: [{ propId: 3002, num: 2 }] },
              { props: [{ propId: 3002, num: 2 }] },
            ],
            # 第五个卡位
            [
              { props: [{ propId: 3003, num: 3 }, { propId: 3102, num: 5 }] },
            ],
          ]
        },
      ]
    },
  ]
}