# 收藏品 (绿2->蓝3->紫4->橙5)
collections: {
  # 改良需要消耗对应品质的道具
  improvementProps: [ 3001, 3002, 3003, 3004 ], # 必须为4个, 用于在收藏品页面顶部显示道具数量

  # 定义所有收藏品
  items: [
    {
      # 收藏品唯一ID
      id: 1,

      # 收藏品名称
      name: '金项链',

      # 所属分类
      categories: ['金'],

      # 解锁道具
      propId: 700,

      # 星级
      stars: 3,

      # 激活消耗
      activation: {
        copper: 200,
      },

      # 收藏品属性加成(激活后初始属性)
      attrs: [
        { key: 'speed', value: 10 },
        { key: 'defense', value: 10 },
      ],

      # 升级
      upgrade: [
        # 1星
        {
          # 阶段升级
          items: [
            # 第一个卡位
            [
              { props: [{ propId: 3001, num: 1 }], attrs: [{ key: 'speed', value: 1 }] },
              { props: [{ propId: 3001, num: 1 }], attrs: [{ key: 'speed', value: 1 }] },
              { props: [{ propId: 3001, num: 1 }], attrs: [{ key: 'speed', value: 1 }] },
              { props: [{ propId: 3001, num: 1 }], attrs: [{ key: 'speed', value: 1 }] },
              { props: [{ propId: 3001, num: 1 }], attrs: [{ key: 'speed', value: 1 }] },
            ],
            # 第二个卡位
            [
              { props: [{ propId: 3001, num: 2 }], attrs: [{ key: 'defense', value: 1 }] },
              { props: [{ propId: 3001, num: 2 }], attrs: [{ key: 'defense', value: 1 }] },
              { props: [{ propId: 3001, num: 2 }], attrs: [{ key: 'defense', value: 1 }] },
              { props: [{ propId: 3001, num: 2 }], attrs: [{ key: 'defense', value: 1 }] },
              { props: [{ propId: 3001, num: 2 }], attrs: [{ key: 'defense', value: 1 }] },
            ],
            # 第三个卡位
            [
              { props: [{ propId: 3001, num: 3 }, { propId: 3101, num: 1 }] },
            ],
          ]
        },

        # 2星
        {
          # 阶段升级
          items: [
            # 第一个卡位
            [
              { props: [{ propId: 3001, num: 1 }], attrs: [{ key: 'speed', value: 2 }] },
              { props: [{ propId: 3001, num: 1 }], attrs: [{ key: 'speed', value: 2 }] },
              { props: [{ propId: 3001, num: 1 }], attrs: [{ key: 'speed', value: 2 }] },
              { props: [{ propId: 3001, num: 1 }], attrs: [{ key: 'speed', value: 2 }] },
              { props: [{ propId: 3001, num: 1 }], attrs: [{ key: 'speed', value: 2 }] },
            ],
            # 第二个卡位
            [
              { props: [{ propId: 3001, num: 2 }], attrs: [{ key: 'defense', value: 2 }] },
              { props: [{ propId: 3001, num: 2 }], attrs: [{ key: 'defense', value: 2 }] },
              { props: [{ propId: 3001, num: 2 }], attrs: [{ key: 'defense', value: 2 }] },
              { props: [{ propId: 3001, num: 2 }], attrs: [{ key: 'defense', value: 2 }] },
              { props: [{ propId: 3001, num: 2 }], attrs: [{ key: 'defense', value: 2 }] },
            ],
            # 第三个卡位
            [
              { props: [{ propId: 3001, num: 3 }, { propId: 3101, num: 2 }] },
            ],
          ]
        },

        # 3星
        {
          # 阶段升级
          items: [
            # 第一个卡位
            [
              { props: [{ propId: 3001, num: 1 }], attrs: [{ key: 'speed', value: 1 }, { key: 'defense', value: 1 }] },
              { props: [{ propId: 3001, num: 1 }], attrs: [{ key: 'speed', value: 1 }, { key: 'defense', value: 1 }] },
              { props: [{ propId: 3001, num: 1 }], attrs: [{ key: 'speed', value: 1 }, { key: 'defense', value: 1 }] },
              { props: [{ propId: 3001, num: 1 }], attrs: [{ key: 'speed', value: 1 }, { key: 'defense', value: 1 }] },
              { props: [{ propId: 3001, num: 1 }], attrs: [{ key: 'speed', value: 1 }, { key: 'defense', value: 1 }] },
            ],
            # 第二个卡位
            [
              { props: [{ propId: 3001, num: 2 }], attrs: [{ key: 'speed', value: 2 }, { key: 'defense', value: 2 }] },
              { props: [{ propId: 3001, num: 2 }], attrs: [{ key: 'speed', value: 2 }, { key: 'defense', value: 2 }] },
              { props: [{ propId: 3001, num: 2 }], attrs: [{ key: 'speed', value: 2 }, { key: 'defense', value: 2 }] },
              { props: [{ propId: 3001, num: 2 }], attrs: [{ key: 'speed', value: 2 }, { key: 'defense', value: 2 }] },
              { props: [{ propId: 3001, num: 2 }], attrs: [{ key: 'speed', value: 2 }, { key: 'defense', value: 2 }] },
            ],
            # 第三个卡位
            [
              { props: [{ propId: 3001, num: 3 }, { propId: 3101, num: 3 }] },
            ],
          ]
        },
      ]
    },

    {
      # 收藏品唯一ID
      id: 2,

      # 收藏品名称
      name: '金手镯',

      # 所属分类
      categories: ['金'],

      # 解锁道具
      propId: 700,

      # 星级
      stars: 5,

      # 激活消耗
      activation: {
        copper: 200,
      },

      # 收藏品属性加成(激活后初始属性)
      attrs: [
        { key: 'speed', value: 20 },
        { key: 'defense', value: 20 },
      ],

      # 升级
      upgrade: [
        # 1星
        {
          # 阶段升级
          items: [
            # 第一个卡位
            [
              { props: [{ propId: 3001, num: 1 }, { propId: 3002, num: 1 }], attrs: [{ key: 'speed', value: 1 }] },
              { props: [{ propId: 3001, num: 1 }], attrs: [{ key: 'speed', value: 1 }] },
              { props: [{ propId: 3001, num: 1 }], attrs: [{ key: 'speed', value: 1 }] },
              { props: [{ propId: 3001, num: 1 }], attrs: [{ key: 'speed', value: 1 }] },
              { props: [{ propId: 3001, num: 1 }], attrs: [{ key: 'speed', value: 1 }] },
            ],
            # 第三个卡位
            [
              { props: [{ propId: 3001, num: 3 }, { propId: 3102, num: 1 }] },
            ],
          ]
        },

        # 2星
        {
          # 阶段升级
          items: [
            # 第一个卡位
            [
              { props: [{ propId: 3001, num: 1 }], attrs: [{ key: 'speed', value: 2 }] },
              { props: [{ propId: 3001, num: 1 }], attrs: [{ key: 'speed', value: 2 }] },
              { props: [{ propId: 3001, num: 1 }], attrs: [{ key: 'speed', value: 2 }] },
              { props: [{ propId: 3001, num: 1 }], attrs: [{ key: 'speed', value: 2 }] },
              { props: [{ propId: 3001, num: 1 }], attrs: [{ key: 'speed', value: 2 }] },
            ],
            # 第二个卡位
            [
              { props: [{ propId: 3001, num: 2 }], attrs: [{ key: 'defense', value: 1 }] },
              { props: [{ propId: 3001, num: 2 }], attrs: [{ key: 'defense', value: 1 }] },
              { props: [{ propId: 3001, num: 2 }], attrs: [{ key: 'defense', value: 1 }] },
              { props: [{ propId: 3001, num: 2 }], attrs: [{ key: 'defense', value: 1 }] },
              { props: [{ propId: 3001, num: 2 }], attrs: [{ key: 'defense', value: 1 }] },
            ],
            # 第三个卡位
            [
              { props: [{ propId: 3001, num: 3 }, { propId: 3102, num: 2 }] },
            ],
          ]
        },

        # 3星
        {
          # 阶段升级
          items: [
            # 第一个卡位
            [
              { props: [{ propId: 3001, num: 1 }], attrs: [{ key: 'speed', value: 3 }] },
              { props: [{ propId: 3001, num: 1 }], attrs: [{ key: 'speed', value: 3 }] },
              { props: [{ propId: 3001, num: 1 }], attrs: [{ key: 'speed', value: 3 }] },
              { props: [{ propId: 3001, num: 1 }], attrs: [{ key: 'speed', value: 3 }] },
              { props: [{ propId: 3001, num: 1 }], attrs: [{ key: 'speed', value: 3 }] },
            ],
            # 第二个卡位
            [
              { props: [{ propId: 3001, num: 2 }], attrs: [{ key: 'defense', value: 2 }] },
              { props: [{ propId: 3001, num: 2 }], attrs: [{ key: 'defense', value: 2 }] },
              { props: [{ propId: 3001, num: 2 }], attrs: [{ key: 'defense', value: 2 }] },
              { props: [{ propId: 3001, num: 2 }], attrs: [{ key: 'defense', value: 2 }] },
              { props: [{ propId: 3001, num: 2 }], attrs: [{ key: 'defense', value: 2 }] },
            ],
            # 第三个卡位
            [
              { props: [{ propId: 3001, num: 2 }], attrs: [{ key: 'speed', value: 4 }] },
              { props: [{ propId: 3001, num: 2 }], attrs: [{ key: 'speed', value: 4 }] },
              { props: [{ propId: 3001, num: 2 }], attrs: [{ key: 'speed', value: 4 }] },
              { props: [{ propId: 3001, num: 2 }], attrs: [{ key: 'speed', value: 4 }] },
              { props: [{ propId: 3001, num: 2 }], attrs: [{ key: 'speed', value: 4 }] },
            ],
            # 第四个卡位
            [
              { props: [{ propId: 3002, num: 2 }], attrs: [{ key: 'defense', value: 3 }] },
              { props: [{ propId: 3002, num: 2 }], attrs: [{ key: 'defense', value: 3 }] },
              { props: [{ propId: 3002, num: 2 }], attrs: [{ key: 'defense', value: 3 }] },
              { props: [{ propId: 3002, num: 2 }], attrs: [{ key: 'defense', value: 3 }] },
              { props: [{ propId: 3002, num: 2 }], attrs: [{ key: 'defense', value: 3 }] },
            ],
            # 第五个卡位
            [
              { props: [{ propId: 3003, num: 3 }, { propId: 3102, num: 3 }] },
            ],
          ]
        },

        # 4星
        {
          # 阶段升级
          items: [
            # 第一个卡位
            [
              { props: [{ propId: 3001, num: 1 }], attrs: [{ key: 'speed', value: 1 }, { key: 'defense', value: 1 }] },
              { props: [{ propId: 3001, num: 1 }], attrs: [{ key: 'speed', value: 1 }, { key: 'defense', value: 1 }] },
              { props: [{ propId: 3001, num: 1 }], attrs: [{ key: 'speed', value: 1 }, { key: 'defense', value: 1 }] },
              { props: [{ propId: 3001, num: 1 }], attrs: [{ key: 'speed', value: 1 }, { key: 'defense', value: 1 }] },
              { props: [{ propId: 3001, num: 1 }], attrs: [{ key: 'speed', value: 1 }, { key: 'defense', value: 1 }] },
            ],
            # 第二个卡位
            [
              { props: [{ propId: 3001, num: 2 }], attrs: [{ key: 'speed', value: 2 }, { key: 'defense', value: 2 }] },
              { props: [{ propId: 3001, num: 2 }], attrs: [{ key: 'speed', value: 2 }, { key: 'defense', value: 2 }] },
              { props: [{ propId: 3001, num: 2 }], attrs: [{ key: 'speed', value: 2 }, { key: 'defense', value: 2 }] },
              { props: [{ propId: 3001, num: 2 }], attrs: [{ key: 'speed', value: 2 }, { key: 'defense', value: 2 }] },
              { props: [{ propId: 3001, num: 2 }], attrs: [{ key: 'speed', value: 2 }, { key: 'defense', value: 2 }] },
            ],
            # 第三个卡位
            [
              { props: [{ propId: 3001, num: 2 }], attrs: [{ key: 'speed', value: 3 }, { key: 'defense', value: 3 }] },
              { props: [{ propId: 3001, num: 2 }], attrs: [{ key: 'speed', value: 3 }, { key: 'defense', value: 3 }] },
              { props: [{ propId: 3001, num: 2 }], attrs: [{ key: 'speed', value: 3 }, { key: 'defense', value: 3 }] },
              { props: [{ propId: 3001, num: 2 }], attrs: [{ key: 'speed', value: 3 }, { key: 'defense', value: 3 }] },
              { props: [{ propId: 3001, num: 2 }], attrs: [{ key: 'speed', value: 3 }, { key: 'defense', value: 3 }] },
            ],
            # 第四个卡位
            [
              { props: [{ propId: 3002, num: 2 }], attrs: [{ key: 'speed', value: 4 }, { key: 'defense', value: 4 }] },
              { props: [{ propId: 3002, num: 2 }], attrs: [{ key: 'speed', value: 4 }, { key: 'defense', value: 4 }] },
              { props: [{ propId: 3002, num: 2 }], attrs: [{ key: 'speed', value: 4 }, { key: 'defense', value: 4 }] },
              { props: [{ propId: 3002, num: 2 }], attrs: [{ key: 'speed', value: 4 }, { key: 'defense', value: 4 }] },
              { props: [{ propId: 3002, num: 2 }], attrs: [{ key: 'speed', value: 4 }, { key: 'defense', value: 4 }] },
            ],
            # 第五个卡位
            [
              { props: [{ propId: 3003, num: 3 }, { propId: 3102, num: 4 }] },
            ],
          ]
        },

        # 5星
        {
          # 阶段升级
          items: [
            # 第一个卡位
            [
              { props: [{ propId: 3001, num: 1 }], attrs: [{ key: 'speed', value: 5 }, { key: 'defense', value: 5 }] },
              { props: [{ propId: 3001, num: 1 }], attrs: [{ key: 'speed', value: 5 }, { key: 'defense', value: 5 }] },
              { props: [{ propId: 3001, num: 1 }], attrs: [{ key: 'speed', value: 5 }, { key: 'defense', value: 5 }] },
              { props: [{ propId: 3001, num: 1 }], attrs: [{ key: 'speed', value: 5 }, { key: 'defense', value: 5 }] },
              { props: [{ propId: 3001, num: 1 }], attrs: [{ key: 'speed', value: 5 }, { key: 'defense', value: 5 }] },
            ],
            # 第二个卡位
            [
              { props: [{ propId: 3001, num: 2 }], attrs: [{ key: 'speed', value: 6 }, { key: 'defense', value: 6 }] },
              { props: [{ propId: 3001, num: 2 }], attrs: [{ key: 'speed', value: 6 }, { key: 'defense', value: 6 }] },
              { props: [{ propId: 3001, num: 2 }], attrs: [{ key: 'speed', value: 6 }, { key: 'defense', value: 6 }]},
              { props: [{ propId: 3001, num: 2 }], attrs: [{ key: 'speed', value: 6 }, { key: 'defense', value: 6 }] },
              { props: [{ propId: 3001, num: 2 }], attrs: [{ key: 'speed', value: 6 }, { key: 'defense', value: 6 }] },
            ],
            # 第三个卡位
            [
              { props: [{ propId: 3001, num: 2 }], attrs: [{ key: 'speed', value: 7 }, { key: 'defense', value: 7 }] },
              { props: [{ propId: 3001, num: 2 }], attrs: [{ key: 'speed', value: 7 }, { key: 'defense', value: 7 }] },
              { props: [{ propId: 3001, num: 2 }], attrs: [{ key: 'speed', value: 7 }, { key: 'defense', value: 7 }] },
              { props: [{ propId: 3001, num: 2 }], attrs: [{ key: 'speed', value: 7 }, { key: 'defense', value: 7 }] },
              { props: [{ propId: 3001, num: 2 }], attrs: [{ key: 'speed', value: 7 }, { key: 'defense', value: 7 }] },
            ],
            # 第四个卡位
            [
              { props: [{ propId: 3002, num: 2 }], attrs: [{ key: 'speed', value: 8 }, { key: 'defense', value: 8 }] },
              { props: [{ propId: 3002, num: 2 }], attrs: [{ key: 'speed', value: 8 }, { key: 'defense', value: 8 }] },
              { props: [{ propId: 3002, num: 2 }], attrs: [{ key: 'speed', value: 8 }, { key: 'defense', value: 8 }] },
              { props: [{ propId: 3002, num: 2 }], attrs: [{ key: 'speed', value: 8 }, { key: 'defense', value: 8 }] },
              { props: [{ propId: 3002, num: 2 }], attrs: [{ key: 'speed', value: 8 }, { key: 'defense', value: 8 }] },
            ],
            # 第五个卡位
            [
              { props: [{ propId: 3003, num: 3 }, { propId: 3102, num: 5 }] },
            ],
          ]
        },
      ]
    },
  ]
}