# ===========================================
# 掉落配置表
#
# 支持下列掉落操作 (名称与用法跟场景、阅读器配置一致)
# 1. sendProps 发送道具 ‘道具ID,数量’ （如：'40,10'）
# 2. alterAttrs 修改属性 ['属性名称,变动值',...] （如：['成神,-1']）
#{ id: 'D1000000', sendProps: '40,10', alterAttrs: ['气运,1', '道行,2'] },
# ===========================================
drops: [
  #
  { id: 'WZXX_M1_N1_C001V_drop1', sendProps: '887,10,showBag', },
  { id: 'WZXX_M1_N1_C001V_drop2',  alterAttrs: ['悟性,1'] },
  { id: 'WZXX_M1_N1_C001V_drop3',  alterAttrs: ['悟性,1'] },
  { id: 'WZXX_M1_N1_C001V_drop4',  alterAttrs: ['智慧,1'] },
  { id: 'WZXX_M1_N1_C001V_drop5',  alterAttrs: ['学识,1'] },
  { id: 'WZXX_M1_N1_C001V_drop6',  alterAttrs: ['学识,1'] },
  { id: 'WZXX_M1_N1_C001V_drop7',  alterAttrs: ['智慧,1'] },
  { id: 'WZXX_M1_N1_C001V_drop8',  alterAttrs: ['智慧,-1'] },
  { id: 'WZXX_M1_N1_C001V_drop9',  alterAttrs: ['身法,1'] },
  #
  { id: 'WZXX_M1_N1_C001A_V_Vdrop1', sendProps: '887,10,showBag', },
  #
  { id: 'WZXX_M1_N1_C002A_V_Vdrop1', sendProps: '600,1,showBag', },
  { id: 'WZXX_M1_N1_C002A_V_Vdrop2', sendProps: '601,1,showBag', },
  { id: 'WZXX_M1_N1_C002A_V_Vdrop3', sendProps: '602,1,showBag',},
  { id: 'WZXX_M1_N1_C002A_V_Vdrop4', sendProps: '887,10,showBag',},
  { id: 'WZXX_M1_N1_C002A_V_Vdrop5',  alterAttrs: ['变化,1'] },
  { id: 'WZXX_M1_N1_C002A_V_Vdrop6',  alterAttrs: ['变化,1'] },
  { id: 'WZXX_M1_N1_C002A_V_Vdrop7',  alterAttrs: ['变化,1'] },
  { id: 'WZXX_M1_N1_C002A_V_Vdrop8',  alterAttrs: ['体魄,1'] },
  { id: 'WZXX_M1_N1_C002A_V_Vdrop9',  alterAttrs: ['身法,1'] },
  #
  { id: 'WZXX_M1_N1_C002B_V_Vdrop1',  alterAttrs: ['仙缘,1'] },
  { id: 'WZXX_M1_N1_C002B_V_Vdrop2', sendProps: '887,100,showBag', },
  { id: 'WZXX_M1_N1_C002B_V_Vdrop3',  alterAttrs: ['善良,1'] },
  { id: 'WZXX_M1_N1_C002B_V_Vdrop4',  alterAttrs: ['冷漠,1'] },
  { id: 'WZXX_M1_N1_C002B_V_Vdrop5',  alterAttrs: ['成神,1'] },
  { id: 'WZXX_M1_N1_C002B_V_Vdrop6',  alterAttrs: ['自由,1'] },
  #
  { id: 'WZXX_M1_N1_C005_V_Vdrop1',  alterAttrs: ['入魔,1'] },
  { id: 'WZXX_M1_N1_C005_V_Vdrop2',  alterAttrs: ['成神,1'] },
  { id: 'WZXX_M1_N1_C005_V_Vdrop3',  alterAttrs: ['入魔,1'] },
  { id: 'WZXX_M1_N1_C005_V_Vdrop4',  alterAttrs: ['成神,1'] },
  { id: 'WZXX_M1_N1_C005_V_Vdrop5',  alterAttrs: ['入魔,1'] },
  { id: 'WZXX_M1_N1_C005_V_Vdrop6',  alterAttrs: ['成神,1'] },
  { id: 'WZXX_M1_N1_C005_V_Vdrop7',  alterAttrs: ['入魔,1'] },
  { id: 'WZXX_M1_N1_C005_V_Vdrop8',  alterAttrs: ['成神,1'] },
  #
  { id: 'WZXX_M1_N1_C005_VA_Vdrop1',  alterAttrs: ['善良,1'] },
  { id: 'WZXX_M1_N1_C005_VA_Vdrop2',  alterAttrs: ['冷漠,1','自由,1'] },
  { id: 'WZXX_M1_N1_C005_VA_Vdrop3', sendProps: '887,100,showBag', },
  { id: 'WZXX_M1_N1_C005_VA_Vdrop4', sendProps: '887,100,showBag', },
  { id: 'WZXX_M1_N1_C005_VA_Vdrop5', sendProps: '887,100,showBag', },
  { id: 'WZXX_M1_N1_C005_VA_Vdrop6',  alterAttrs: ['善良,1'] },
  { id: 'WZXX_M1_N1_C005_VA_Vdrop7',  alterAttrs: ['冷漠,1','自由,1'] },
  { id: 'WZXX_M1_N1_C005_VA_Vdrop8', sendProps: '887,100,showBag', },
  { id: 'WZXX_M1_N1_C005_VA_Vdrop9', sendProps: '887,100, showBag',},
  { id: 'WZXX_M1_N1_C005_VA_Vdrop10', sendProps: '887,100, showBag',},
  #
  { id: 'WZXX_M1_N1_C006_V_Vdrop1', sendProps: '887,100, showBag',},
  { id: 'WZXX_M1_N1_C006_V_Vdrop2', sendProps: '887,100, showBag', },
  { id: 'WZXX_M1_N1_C006_V_Vdrop3', sendProps: '887,100, showBag',},
  { id: 'WZXX_M1_N1_C006_V_Vdrop4', sendProps: '887,-100, showBag',},
  #
  { id: 'WZXX_M1_N1_C006_drop1',  alterAttrs: ['悟性,1'] },
  { id: 'WZXX_M1_N1_C006_drop2', sendProps: '886,1, showBag',},
  #
  { id: 'WZXX_M1_N1_C0017_V_Vdrop1',  alterAttrs: ['入魔,1'] },
  #
  { id: 'WZXX_M1_N1_C0019_V_Vdrop1',  alterAttrs: ['体魄,1'] },
  { id: 'WZXX_M1_N1_C0019_V_Vdrop2',  alterAttrs: ['自由,1'] },
  #
  { id: 'WZXX_M1_N1_C0020_V_Vdrop1',  sendProps: '886,16,showBag', },
  { id: 'WZXX_M1_N1_C0020_V_Vdrop2',  sendProps: '886,16,showBag',},
  { id: 'WZXX_M1_N1_C0020_V_Vdrop3',  sendProps: '890,3,showBag',},
  #
  { id: 'WZXX_M1_N1_C0021_V_Vdrop1',  sendProps: '608,10,showBag',},
  #
  { id: 'WZXX_M1_N1_C0026_V_Vdrop1',  sendProps: '338,10,showBag',},
  { id: 'WZXX_M1_N1_C0026_V_Vdrop2',  sendProps: '339,2,showBag',},
  { id: 'WZXX_M1_N1_C0026_V_Vdrop3',  sendProps: '886,16,showBag',},

  { id: 'WZXX_M1_N1_C0026_V_Vdrop4',  sendProps: '349,1,showBag',},
  { id: 'WZXX_M1_N1_C0026_V_Vdrop5',  sendProps: '333,3,showBag',},
  { id: 'WZXX_M1_N1_C0026_V_Vdrop6',  sendProps: '332,1,showBag',},
  { id: 'WZXX_M1_N1_C0026_V_Vdrop7',  sendProps: '319,1,showBag',},

  { id: 'WZXX_M1_N1_C0026_V_Vdrop8',   alterAttrs: ['善良,1'] },
  { id: 'WZXX_M1_N1_C0026_V_Vdrop9',   alterAttrs: ['冷漠,1'] },

  { id: 'WZXX_M1_N1_C009_V_Vdrop7',  sendProps: '1015,1,showBag',},
  { id: 'WZXX_M1_N1_C009_V_Vdrop8',  sendProps: '1016,1,showBag',},
  { id: 'WZXX_M1_N1_C009_V_Vdrop9',  sendProps: '1017,1,showBag',},

  { id: 'WZXX_M1_N1_C009_V_Vdrop1',  sendProps: '1018,1,showBag',},
  


  


  
  
]