# ===========================================
# 掉落配置表
#
# 支持下列掉落操作 (名称与用法跟场景、阅读器配置一致)
# 1. sendProps 发送道具 ‘道具ID,数量’ （如：'40,10'）
# 2. alertAttrs 修改属性 ['属性名称,变动值',...] （如：['成神,-1']）
# ===========================================
drops: [
  { id: 'D1000000', sendProps: '40,10', alertAttrs: ['气运,1', '道行,2'] },
  { id: 'D1000001', sendProps: '20,10', alertAttrs: ['仙缘,1'] },
]