# ===========================================
# 掉落配置表
#
# 支持下列掉落操作 (名称与用法跟场景、阅读器配置一致)
# 1. sendProps 发送道具 ‘道具ID,数量’ （如：'40,10'）
# 2. alterAttrs 修改属性 ['属性名称,变动值',...] （如：['成神,-1']）
#{ id: 'D1000000', sendProps: '40,10', alterAttrs: ['气运,1', '道行,2'] },
# ===========================================
drops: [ 

# 
  { id: 'questionnaire_drop1', alterAttrs: ['颜值,1']  },
  { id: 'questionnaire_drop2', alterAttrs: ['悟性,1']  },
  { id: 'questionnaire_drop3', alterAttrs: ['智慧,1']  },
  { id: 'questionnaire_drop4', alterAttrs: ['变化,1']  },
  { id: 'questionnaire_drop5', alterAttrs: ['自由,1']  },

  { id: 'questionnaire_drop6', alterAttrs: ['变化,1']  },
  { id: 'questionnaire_drop7', alterAttrs: ['仙缘,1']  },
  { id: 'questionnaire_drop8', alterAttrs: ['颜值,1']  },
  { id: 'questionnaire_drop9', alterAttrs: ['神识,1']  },

  { id: 'questionnaire_drop10', alterAttrs: ['变化,1']  },
  { id: 'questionnaire_drop11', alterAttrs: ['仙缘,1']  },
  { id: 'questionnaire_drop12', alterAttrs: ['颜值,1']  },
  { id: 'questionnaire_drop13', alterAttrs: ['神识,1']  },

  { id: 'questionnaire_drop14', alterAttrs: ['神识,1']  },
  { id: 'questionnaire_drop15', alterAttrs: ['悟性,1']  },
  { id: 'questionnaire_drop16', alterAttrs: ['体魄,1']  },
  { id: 'questionnaire_drop17', alterAttrs: ['智慧,1']  },

  { id: 'questionnaire_drop18', alterAttrs: ['悟性,1']  },
  { id: 'questionnaire_drop19', alterAttrs: ['善良,1']  },
  { id: 'questionnaire_drop20', alterAttrs: ['体魄,1']  },

  { id: 'questionnaire_drop21', alterAttrs: ['自由,1']  },
  { id: 'questionnaire_drop22', alterAttrs: ['神通,1']  },
  { id: 'questionnaire_drop23', alterAttrs: ['变化,1']  },
  { id: 'questionnaire_drop24', alterAttrs: ['仙缘,1']  },

  { id: 'questionnaire_drop25', alterAttrs: ['悟性,1']  },
  { id: 'questionnaire_drop26', alterAttrs: ['学识,1']  },
  { id: 'questionnaire_drop27', alterAttrs: ['智慧,1']  },

  { id: 'questionnaire_drop28', alterAttrs: ['成神,1']  },
  { id: 'questionnaire_drop29', alterAttrs: ['气运,1']  },
  { id: 'questionnaire_drop30', alterAttrs: ['入魔,1']  },

  { id: 'questionnaire_drop31', alterAttrs: ['仙缘,1']  },
  { id: 'questionnaire_drop32', alterAttrs: ['神识,1']  },
  { id: 'questionnaire_drop33', alterAttrs: ['神通,1']  },

  { id: 'questionnaire_drop34', alterAttrs: ['神通,1']  },
  { id: 'questionnaire_drop35', alterAttrs: ['善良,1']  },
  { id: 'questionnaire_drop36', alterAttrs: ['悟性,1']  },
  { id: 'questionnaire_drop37', alterAttrs: ['体魄,1']  },

  { id: 'questionnaire_drop38', alterAttrs: ['入魔,1']  },
  { id: 'questionnaire_drop39', alterAttrs: ['冷漠,1']  },
  { id: 'questionnaire_drop40', alterAttrs: ['善良,1']  },
  { id: 'questionnaire_drop41', alterAttrs: ['成神,1']  },

  { id: 'questionnaire_drop42', alterAttrs: ['善良,1']  },
  { id: 'questionnaire_drop43', alterAttrs: ['神通,1']  },
  { id: 'questionnaire_drop44', alterAttrs: ['气运,1']  },
  
  { id: 'questionnaire_drop45', alterAttrs: ['智慧,1']  },
  { id: 'questionnaire_drop46', sendProps: '887,1,showBag',  },
  { id: 'questionnaire_drop47', alterAttrs: ['神通,1']  },
  { id: 'questionnaire_drop48', alterAttrs: ['自由,1']  },
  { id: 'questionnaire_drop49', alterAttrs: ['道行,1']  },

  { id: 'questionnaire_drop50', alterAttrs: ['道行,1']  },
  { id: 'questionnaire_drop51', alterAttrs: ['气运,1']  },
  { id: 'questionnaire_drop52', alterAttrs: ['神通,1']  },
  { id: 'questionnaire_drop53', alterAttrs: ['仙缘,1']  },


  { id: 'WZXX_M1_N1_C000A_V_drop1', sendProps: '363,1,showBag', },
  { id: 'WZXX_M1_N1_C000A_V_drop2', sendProps: '887,1,showBag', },

  { id: 'WZXX_M1_N1_C000A_V_drop3', sendProps: '887,1000,showBag', },
  { id: 'WZXX_M1_N1_C000A_V_drop4', sendProps: '363,1,showBag', },

  { id: 'WZXX_M1_N1_C000A_V_drop5', sendProps: '887,20,showBag', },
  { id: 'WZXX_M1_N1_C000A_V_drop6', sendProps: '363,1,showBag', },

  #小世界地图获取道具
  #归元草
  { id: 'WZXX_M1_N1_C000D_VA_V_drop1', sendProps: '1022,3,showBag', },
  #化生草
  { id: 'WZXX_M1_N1_C000D_VA_V_drop2', sendProps: '1023,3,showBag', },
  #固灵草
  { id: 'WZXX_M1_N1_C000D_VA_V_drop3', sendProps: '1024,3,showBag', },

  #灵感钥匙
  
  #动物园
  { id: 'WZXX_M1_N1_C000F_V_drop1', sendProps: '369,1,showBag', },
  #电脑桌
  { id: 'WZXX_M1_N1_C000F_V_drop2', sendProps: '369,1,showBag', },
  #阳台-思考人生
  { id: 'WZXX_M1_N1_C000F_V_drop3', sendProps: '370,1,showBag', },
  #冰箱-随便喝点
  { id: 'WZXX_M1_N1_C000F_V_drop4', sendProps: '371,1,showBag', },
  #植物园
  { id: 'WZXX_M1_N1_C000F_V_drop5', sendProps: '372,1,showBag', },
  #音乐走廊
  { id: 'WZXX_M1_N1_C000F_V_drop6', sendProps: '372,1,showBag', },
  #观景地和美术生聊天
  { id: 'WZXX_M1_N1_C000F_V_drop7', sendProps: '369,1,showBag', },
  #和便利店老板聊天
  { id: 'WZXX_M1_N1_C000F_V_drop8', sendProps: '371,1,showBag', },
  #帮助中心广场的小孩
  { id: 'WZXX_M1_N1_C000F_V_drop9', sendProps: '372,1,showBag', },
  #音乐学院的学生聊天
  { id: 'WZXX_M1_N1_C000F_V_drop10', sendProps: '370,1,showBag', },
  #第四天 电脑桌掉落道具
  { id: 'WZXX_M1_N1_C000F2_V_drop1', sendProps: '369,1,showBag', },
  #第五天 和老妈打电话掉落道具
  { id: 'WZXX_M1_N1_C000F2_V_drop2', sendProps: '370,1,showBag', },
  #第五天 电脑桌掉落道具
  { id: 'WZXX_M1_N1_C000F2_V_drop3', sendProps: '372,1,showBag', },
  #第五天 展览馆掉落道具
  { id: 'WZXX_M1_N1_C000F2_V_drop4', sendProps: '371,1,showBag', },
  #第五天 展览馆掉落道具
  { id: 'WZXX_M1_N1_C000F2_V_drop5', sendProps: '369,1,showBag', },


  #887铜币
  { id: 'WZXX_M1_N1_C001V_drop1', sendProps: '887,10,showBag', },
  { id: 'WZXX_M1_N1_C001V_drop2',  alterAttrs: ['悟性,1'] },
  { id: 'WZXX_M1_N1_C001V_drop3',  alterAttrs: ['悟性,1'] },
  { id: 'WZXX_M1_N1_C001V_drop4',  alterAttrs: ['灵性,1'] },
  { id: 'WZXX_M1_N1_C001V_drop5',  alterAttrs: ['学识,1'] },
  { id: 'WZXX_M1_N1_C001V_drop6',  alterAttrs: ['学识,1'] },
  { id: 'WZXX_M1_N1_C001V_drop7',  alterAttrs: ['灵性,1'] },
  { id: 'WZXX_M1_N1_C001V_drop8',  alterAttrs: ['灵性,-1'] },
  { id: 'WZXX_M1_N1_C001V_drop9',  alterAttrs: ['自由,1'] },
  # { id: 'WZXX_M1_N1_C001V_drop10',  sendProps: '44,100,showBag',},
  { id: 'WZXX_M1_N1_C001V_drop11',  sendProps: '887,100,showBag',},
  #887铜币WZXX_M1_N1_C001A_V
  { id: 'WZXX_M1_N1_C001A_V_Vdrop1', sendProps: '887,10,showBag', },
  { id: 'WZXX_M1_N1_C001A_V_Vdrop2', alterAttrs: ['灵性,1'] },
  #600白城冷笑话
  { id: 'WZXX_M1_N1_C002A_V_Vdrop1', sendProps: '600,1,showBag', },
  #601思无邪
  { id: 'WZXX_M1_N1_C002A_V_Vdrop2', sendProps: '601,1,showBag', },
  #602凌云决
  { id: 'WZXX_M1_N1_C002A_V_Vdrop3', sendProps: '602,1,showBag',},
  #887铜币
  { id: 'WZXX_M1_N1_C002A_V_Vdrop4', sendProps: '887,10,showBag',},
  { id: 'WZXX_M1_N1_C002A_V_Vdrop5',  alterAttrs: ['变化,1'] },
  { id: 'WZXX_M1_N1_C002A_V_Vdrop6',  alterAttrs: ['变化,1'] },
  { id: 'WZXX_M1_N1_C002A_V_Vdrop7',  alterAttrs: ['变化,1'] },
  { id: 'WZXX_M1_N1_C002A_V_Vdrop8',  alterAttrs: ['体魄,1'] },
  { id: 'WZXX_M1_N1_C002A_V_Vdrop9',  alterAttrs: ['身法,1'] },
  #
  { id: 'WZXX_M1_N1_C002B_V_Vdrop1',  alterAttrs: ['仙缘,1'] },
  #887铜币
  { id: 'WZXX_M1_N1_C002B_V_Vdrop2', sendProps: '887,100,showBag', },
  { id: 'WZXX_M1_N1_C002B_V_Vdrop3',  alterAttrs: ['善良,1'] },
  { id: 'WZXX_M1_N1_C002B_V_Vdrop4',  alterAttrs: ['冷漠,1'] },
  { id: 'WZXX_M1_N1_C002B_V_Vdrop5',  alterAttrs: ['成神,1'] },
  { id: 'WZXX_M1_N1_C002B_V_Vdrop6',  alterAttrs: ['自由,1'] },
  #WZXX_M1_N1_C003_V
  { id: 'WZXX_M1_N1_C003_V_Vdrop1',  alterAttrs: ['悟性,1'] },
  { id: 'WZXX_M1_N1_C003_V_Vdrop2',  alterAttrs: ['神识,1'] },
  #时空宝玉
   { id: 'WZXX_M1_N1_C003_V_Vdrop3',  sendProps: '44,1,showBag',},

  #
  { id: 'WZXX_M1_N1_C005_V_Vdrop1',  alterAttrs: ['入魔,1'] },
  { id: 'WZXX_M1_N1_C005_V_Vdrop2',  alterAttrs: ['成神,1'] },
  { id: 'WZXX_M1_N1_C005_V_Vdrop3',  alterAttrs: ['入魔,1'] },
  { id: 'WZXX_M1_N1_C005_V_Vdrop4',  alterAttrs: ['成神,1'] },
  { id: 'WZXX_M1_N1_C005_V_Vdrop5',  alterAttrs: ['入魔,1'] },
  { id: 'WZXX_M1_N1_C005_V_Vdrop6',  alterAttrs: ['成神,1'] },
  { id: 'WZXX_M1_N1_C005_V_Vdrop7',  alterAttrs: ['入魔,1'] },
  { id: 'WZXX_M1_N1_C005_V_Vdrop8',  alterAttrs: ['成神,1'] },
  # 
  { id: 'WZXX_M1_N1_C005_VA_Vdrop1',  alterAttrs: ['机智,1'] },
  { id: 'WZXX_M1_N1_C005_VA_Vdrop2',  alterAttrs: ['勇敢,1'] },

  #
  { id: 'WZXX_M1_N1_C005_VA_Vdrop1',  alterAttrs: ['善良,1'] },
  { id: 'WZXX_M1_N1_C005_VA_Vdrop2',  alterAttrs: ['冷漠,1','自由,1'] },
  #887铜币
  { id: 'WZXX_M1_N1_C005_VA_Vdrop3', sendProps: '887,100,showBag', },
  #887铜币
  { id: 'WZXX_M1_N1_C005_VA_Vdrop4', sendProps: '887,100,showBag', },
  #887铜币
  { id: 'WZXX_M1_N1_C005_VA_Vdrop5', sendProps: '887,100,showBag', },
  { id: 'WZXX_M1_N1_C005_VA_Vdrop6',  alterAttrs: ['善良,1'] },
  { id: 'WZXX_M1_N1_C005_VA_Vdrop7',  alterAttrs: ['冷漠,1','自由,1'] },
  #887铜币
  { id: 'WZXX_M1_N1_C005_VA_Vdrop8', sendProps: '887,100,showBag', },
  #887铜币
  { id: 'WZXX_M1_N1_C005_VA_Vdrop9', sendProps: '887,100, showBag',},
  #887铜币
  { id: 'WZXX_M1_N1_C005_VA_Vdrop10', sendProps: '887,100, showBag',},
  #887铜币
  { id: 'WZXX_M1_N1_C006_V_Vdrop1', sendProps: '887,100, showBag',},
  #887铜币
  { id: 'WZXX_M1_N1_C006_V_Vdrop2', sendProps: '887,100, showBag', },
  #887铜币
  { id: 'WZXX_M1_N1_C006_V_Vdrop3', sendProps: '887,100, showBag',},
  #887铜币
  { id: 'WZXX_M1_N1_C006_V_Vdrop4', sendProps: '887,-100, showBag',},
  #
  { id: 'WZXX_M1_N1_C006_drop1',  alterAttrs: ['悟性,1'] },
  #887铜币
  { id: 'WZXX_M1_N1_C006_drop2', sendProps: '886,1, showBag',},
  #
  # WZXX_M1_N1_C007_V
  { id: 'WZXX_M1_N1_C007_V_drop1', alterAttrs: ['耐心,1'],},
  { id: 'WZXX_M1_N1_C007_V_drop2', alterAttrs: ['智慧,1'],},
  { id: 'WZXX_M1_N1_C007_V_drop3', alterAttrs: ['仙缘,1'],},

  #
  { id: 'WZXX_M1_N1_C0017_V_Vdrop1',  alterAttrs: ['入魔,1'] },
  #
  { id: 'WZXX_M1_N1_C0019_V_Vdrop1',  alterAttrs: ['体魄,1'] },
  { id: 'WZXX_M1_N1_C0019_V_Vdrop2',  alterAttrs: ['自由,1'] },
  #886灵石
  { id: 'WZXX_M1_N1_C0020_V_Vdrop1',  sendProps: '886,16,showBag', },
  #886灵石
  { id: 'WZXX_M1_N1_C0020_V_Vdrop2',  sendProps: '886,16,showBag',},
  #890黄金饰品
  { id: 'WZXX_M1_N1_C0020_V_Vdrop3',  sendProps: '890,3,showBag',},
  #608符纸
  { id: 'WZXX_M1_N1_C0021_V_Vdrop1',  sendProps: '608,10,showBag',},
#   #338草药
#   { id: 'WZXX_M1_N1_C0026_V_Vdrop1',  sendProps: '338,10,showBag',},
#   #339不知名的蛋
#   { id: 'WZXX_M1_N1_C0026_V_Vdrop2',  sendProps: '339,2,showBag',},
#   #886灵石
#   { id: 'WZXX_M1_N1_C0026_V_Vdrop3',  sendProps: '886,16,showBag',},
# #349玄铁重剑
#   { id: 'WZXX_M1_N1_C0026_V_Vdrop4',  sendProps: '349,1,showBag',},
#   #333小还丹
#   { id: 'WZXX_M1_N1_C0026_V_Vdrop5',  sendProps: '333,3,showBag',},
#   #332大还丹
#   { id: 'WZXX_M1_N1_C0026_V_Vdrop6',  sendProps: '332,1,showBag',},
#   #319回气散
#   { id: 'WZXX_M1_N1_C0026_V_Vdrop7',  sendProps: '319,1,showBag',},

#   { id: 'WZXX_M1_N1_C0026_V_Vdrop8',   alterAttrs: ['善良,1'] },
#   { id: 'WZXX_M1_N1_C0026_V_Vdrop9',   alterAttrs: ['冷漠,1'] },
#1015黄心叶
  { id: 'WZXX_M1_N1_C009_V_Vdrop7',  sendProps: '1015,1,showBag',},
  #1016百络花
  { id: 'WZXX_M1_N1_C009_V_Vdrop8',  sendProps: '1016,1,showBag',},
  #1017子星草
  { id: 'WZXX_M1_N1_C009_V_Vdrop9',  sendProps: '1017,1,showBag',},
#1018不知名草药
  { id: 'WZXX_M1_N1_C009_V_Vdrop1',  sendProps: '1018,10,showBag',},
  { id: 'WZXX_M1_N1_C009_V_Vdrop2',  sendProps: '1018,10,showBag',},



  { id: 'S_00Test03_Vdrop1',  sendProps: '887,100,showBag',},
  { id: 'S_00Test03_Vdrop2',  alterAttrs: ['勇气,-1'],},
  { id: 'S_00Test03_gameover01',  sendProps: '383,1,showBag',},

 
 #死亡勋章
  { id: 'WZXX_M1_N1_C000D_V_gameover01',  sendProps: '383,1,showBag',},
  { id: 'WZXX_M1_N1_C000D_V_gameover02',  sendProps: '383,1,showBag',},
  { id: 'WZXX_M1_N1_C000G_V_gameover01',  sendProps: '383,1,showBag',},
  { id: 'WZXX_M1_N1_C000G_V_gameover02',  sendProps: '383,1,showBag',},
  { id: 'WZXX_M1_N1_C001A_V_gameover01',  sendProps: '383,1,showBag',},
  { id: 'WZXX_M1_N1_C001A_V_gameover02',  sendProps: '383,1,showBag',},

  { id: 'WZXX_M1_N1_C001B_V_gameover00',  sendProps: '383,1,showBag',},
  { id: 'WZXX_M1_N1_C001B_V_gameover01',  sendProps: '383,1,showBag',},
  
  { id: 'WZXX_M1_N1_C001B_V_gameoverD1',  sendProps: '383,1,showBag',},
  { id: 'WZXX_M1_N1_C001B_V_gameoverD2',  sendProps: '383,1,showBag',},
  { id: 'WZXX_M1_N1_C001B_V_gameoverD3',  sendProps: '383,1,showBag',},
  { id: 'WZXX_M1_N1_C001B_V_gameoverD4',  sendProps: '383,1,showBag',},
  { id: 'WZXX_M1_N1_C001B_V_gameoverD5',  sendProps: '383,1,showBag',},
  { id: 'WZXX_M1_N1_C001B_V_gameoverD6',  sendProps: '383,1,showBag',},


  { id: 'WZXX_M1_N1_C001C_V_gameover00',  sendProps: '383,1,showBag',},
  { id: 'WZXX_M1_N1_C001C_V_gameover01',  sendProps: '383,1,showBag',},
  { id: 'WZXX_M1_N1_C001C_V_gameover02',  sendProps: '383,1,showBag',},

  { id: 'WZXX_M1_N1_C001V_gameoverp1DGG',  sendProps: '383,1,showBag',},
  { id: 'WZXX_M1_N1_C001V_gameover00',  sendProps: '383,1,showBag',},
  { id: 'WZXX_M1_N1_C001V_gameover01A',  sendProps: '383,1,showBag',},
  { id: 'WZXX_M1_N1_C001V_gameover01',  sendProps: '383,1,showBag',},
  { id: 'WZXX_M1_N1_C001V_gameover02',  sendProps: '383,1,showBag',},
  { id: 'WZXX_M1_N1_C001V_gameover03',  sendProps: '383,1,showBag',},
  { id: 'WZXX_M1_N1_C001V_gameover04',  sendProps: '383,1,showBag',},
  { id: 'WZXX_M1_N1_C001V_gameover05',  sendProps: '383,1,showBag',},
  { id: 'WZXX_M1_N1_C001V_gameover06',  sendProps: '383,1,showBag',},

  { id: 'WZXX_M1_N1_C002A_V_gameover10',  sendProps: '383,1,showBag',},
  { id: 'WZXX_M1_N1_C002A_V_gameover10A',  sendProps: '383,1,showBag',},
  { id: 'WZXX_M1_N1_C002A_V_gameover12',  sendProps: '383,1,showBag',},
  { id: 'WZXX_M1_N1_C002A_V_gameover13',  sendProps: '383,1,showBag',},
  { id: 'WZXX_M1_N1_C002A_V_gameover14',  sendProps: '383,1,showBag',},
  { id: 'WZXX_M1_N1_C002A_V_gameover15',  sendProps: '383,1,showBag',},
  { id: 'WZXX_M1_N1_C002A_V_gameover16',  sendProps: '383,1,showBag',},
  { id: 'WZXX_M1_N1_C002A_V_gameover17',  sendProps: '383,1,showBag',},
  { id: 'WZXX_M1_N1_C002A_V_gameover18',  sendProps: '383,1,showBag',},
  { id: 'WZXX_M1_N1_C002A_V_gameover19',  sendProps: '383,1,showBag',},
  { id: 'WZXX_M1_N1_C002A_V_gameover03',  sendProps: '383,1,showBag',},
  { id: 'WZXX_M1_N1_C002A_V_gameover06',  sendProps: '383,1,showBag',},


  { id: 'WZXX_M1_N1_C002C_V_gameover01',  sendProps: '383,1,showBag',},
  { id: 'WZXX_M1_N1_C002C_V_gameover2',  sendProps: '383,1,showBag',},

  { id: 'WZXX_M1_N1_CC035_V_gameover00',  sendProps: '383,1,showBag',},

  { id: 'S_00Test02_gameover01',  sendProps: '383,1,showBag',},

  { id: 'WZXX_M1_N1_CC036_V_Vdrop1',  sendProps: '382,10,showBag',},


  { id: 'WZXX_M1_N1_C000A1_V_Vdrop1',  alterAttrs: ['勇气,1'],},
  { id: 'WZXX_M1_N1_C000A1_V_Vdrop2',  alterAttrs: ['灵性,1'],},
  { id: 'WZXX_M1_N1_C000A1_V_Vdrop3',  alterAttrs: ['悟性,1'],},
  { id: 'WZXX_M1_N1_C000A1_V_Vdrop4',  alterAttrs: ['变化,1'],},
  { id: 'WZXX_M1_N1_C000A1_V_Vdrop5',  alterAttrs: ['勇气,1'],},
  { id: 'WZXX_M1_N1_C000A1_V_Vdrop6',  alterAttrs: ['逼格,1'],},
  { id: 'WZXX_M1_N1_C000A1_V_Vdrop7',  alterAttrs: ['嫌弃,1'],},
  { id: 'WZXX_M1_N1_C000A1_V_Vdrop8',  alterAttrs: ['勇气,1'],},
  { id: 'WZXX_M1_N1_C000A1_V_Vdrop9',  alterAttrs: ['逼格,1'],},
  { id: 'WZXX_M1_N1_C000A1_V_Vdrop10',  alterAttrs: ['嫌弃,1'],},


  { id: 'WZXX_M1_N1_C001V_Vdrop100',  alterAttrs: ['勇气,1'],},
  { id: 'WZXX_M1_N1_C001V_Vdrop101',  alterAttrs: ['嫌弃,1'],},
  { id: 'WZXX_M1_N1_C001V_Vdrop102',  alterAttrs: ['逼格,1'],},

  { id: 'WZXX_M1_N1_C001V_Vdrop103',  alterAttrs: ['悟性,1'],},
  { id: 'WZXX_M1_N1_C001V_Vdrop104',  alterAttrs: ['节操,1'],},
  { id: 'WZXX_M1_N1_C001V_Vdrop105',  alterAttrs: ['威慑,1'],},

  { id: 'WZXX_M1_N1_C000A1_V_gameover01',  sendProps: '383,1,showBag',},
  { id: 'WZXX_M1_N1_C000A1_V_gameover02',  sendProps: '383,1,showBag',},
  { id: 'WZXX_M1_N1_C000A1_V_gameover03',  sendProps: '383,1,showBag',},
  { id: 'WZXX_M1_N1_C000A1_V_gameover04',  sendProps: '383,1,showBag',},
  { id: 'WZXX_M1_N1_C000A1_V_gameover05',  sendProps: '383,1,showBag',},
  { id: 'WZXX_M1_N1_C000A1_V_gameover06',  sendProps: '383,1,showBag',},
  { id: 'WZXX_M1_N1_C000A1_V_gameover07',  sendProps: '383,1,showBag',},
  { id: 'WZXX_M1_N1_C000A1_V_gameover08',  sendProps: '383,1,showBag',},
  { id: 'WZXX_M1_N1_C000A1_V_gameover09',  sendProps: '383,1,showBag',},
  { id: 'WZXX_M1_N1_C000A1_V_gameover10',  sendProps: '383,1,showBag',},
  { id: 'WZXX_M1_N1_C000A1_V_gameover11',  sendProps: '383,1,showBag',},
  { id: 'WZXX_M1_N1_C000A1_V_gameover12',  sendProps: '383,1,showBag',},
  { id: 'WZXX_M1_N1_C000A1_V_gameover13',  sendProps: '383,1,showBag',},
  { id: 'WZXX_M1_N1_C000A1_V_gameover14',  sendProps: '383,1,showBag',},
  { id: 'WZXX_M1_N1_C000A1_V_gameover15',  sendProps: '383,1,showBag',},
  { id: 'WZXX_M1_N1_C000A1_V_gameover16',  sendProps: '383,1,showBag',},
  { id: 'WZXX_M1_N1_C000A1_V_gameover17',  sendProps: '383,1,showBag',},
  { id: 'WZXX_M1_N1_C000A1_V_gameover18',  sendProps: '383,1,showBag',},
  { id: 'WZXX_M1_N1_C000A1_V_gameover19',  sendProps: '383,1,showBag',},
  { id: 'WZXX_M1_N1_C000A1_V_gameover20',  sendProps: '383,1,showBag',},


  { id: 'WZXX_M1_N1_C002_V_Vdrop1',  alterAttrs: ['正义,1'],},
  { id: 'WZXX_M1_N1_C002_V_Vdrop2',  alterAttrs: ['节操,1'],},
  { id: 'WZXX_M1_N1_C002_V_Vdrop3',  alterAttrs: ['入魔,1'],},
  { id: 'WZXX_M1_N1_C002_V_Vdrop4',  alterAttrs: ['正义,1'],},
  { id: 'WZXX_M1_N1_C002_V_Vdrop5',  alterAttrs: ['勇气,1'],},
  { id: 'WZXX_M1_N1_C002_V_Vdrop6',  alterAttrs: ['嫌弃,1'],},
  { id: 'WZXX_M1_N1_C002_V_Vdrop7',  alterAttrs: ['崇敬,2'],},
  
  { id: 'WZXX_M1_N1_C003_V_Vdrop1',  alterAttrs: ['正义,1'],},
  { id: 'WZXX_M1_N1_C003_V_Vdrop2',  alterAttrs: ['颜值,1'],},
  { id: 'WZXX_M1_N1_C003_V_Vdrop3',  alterAttrs: ['节操,-1'],},
  { id: 'WZXX_M1_N1_C003_V_Vdrop4',  alterAttrs: ['邪恶,1'],},

  
]