# ===========================================
# 探索配置
# ===========================================
explore: [
  {
    # ID
    id: 1,

    name: '新手村',

    desc: '新手村,新手村,新手村,新手村,新手村,新手村,新手村',

    areas: [
      {
        id: 1,
        name: '区域1',
        time: 30,
        interval: 1,
        points: [
          { idx: 5, event: 'xunbao' },
          { idx: 10, event: 'boss' },
          { idx: 15, event: 'xiansuo' },
          { idx: 20, event: 'qiyu' },
          { idx: 25, event: 'pk' },
        ]
      },
      {
        id: 2,
        name: '区域2',
        time: 10,
        interval: 1,
        points: [
          { idx: 10, action: 'challenge' },
          { idx: 15, action: 'challenge' },
        ]
      },
      {
        id: 3,
        name: '区域3',
        time: 10,
        interval: 1,
        points: [
          { idx: 10, action: 'challenge' },
          { idx: 15, action: 'challenge' },
        ]
      },
    ],
  },
  {
    # ID
    id: 2,

    name: '邻家树林',

    desc: '邻家树林,邻家树林,邻家树林,邻家树林,邻家树林,邻家树林',

    areas: [
      {
        id: 1,
        name: '区域1',
        time: 10,
        interval: 1,
        points: [
          { idx: 10, action: 'challenge' },
          { idx: 15, action: 'challenge' },
        ]
      },
      {
        id: 2,
        name: '区域2',
        time: 10,
        interval: 1,
        points: [
          { idx: 10, action: 'challenge' },
          { idx: 15, action: 'challenge' },
        ]
      },
      {
        id: 3,
        name: '区域3',
        time: 10,
        interval: 1,
        points: [
          { idx: 10, action: 'challenge' },
          { idx: 15, action: 'challenge' },
        ]
      },
    ],
  },
  {
    # ID
    id: 3,

    name: '隔壁山上',

    desc: '隔壁山上,隔壁山上,隔壁山上,隔壁山上,隔壁山上,隔壁山上',

    areas: [
      {
        id: 1,
        name: '区域1',
        time: 120,
        interval: 3,
        points: [
          { idx: 10, action: 'challenge' },
          { idx: 15, action: 'challenge' },
        ],
      },
      {
        id: 2,
        name: '区域2',
        time: 10,
        interval: 1,
        points: [
          { idx: 10, action: 'challenge' },
          { idx: 15, action: 'challenge' },
        ]
      },
      {
        id: 3,
        name: '区域3',
        time: 10,
        interval: 1,
        points: [
          { idx: 10, action: 'challenge' },
          { idx: 15, action: 'challenge' },
        ]
      },
    ],
  },
  {
    # ID
    id: 4,

    name: '隔壁后院',

    desc: '隔壁后院,隔壁后院,隔壁后院,隔壁后院,隔壁后院,隔壁后院',

    areas: [
      {
        id: 1,
        name: '区域1',
        time: 10,
        interval: 1,
        points: [
          { idx: 10, action: 'challenge' },
          { idx: 15, action: 'challenge' },
        ]
      },
      {
        id: 2,
        name: '区域2',
        time: 10,
        interval: 1,
        points: [
          { idx: 10, action: 'challenge' },
          { idx: 15, action: 'challenge' },
        ]
      },
      {
        id: 3,
        name: '区域3',
        time: 10,
        interval: 1,
        points: [
          { idx: 10, action: 'challenge' },
          { idx: 15, action: 'challenge' },
        ]
      },
    ],
  },
  {
    # ID
    id: 5,

    name: '隔壁屋顶',

    desc: '隔壁屋顶,隔壁屋顶,隔壁屋顶,隔壁屋顶,隔壁屋顶,隔壁屋顶',

    areas: [
      {
        id: 1,
        name: '区域1',
        time: 10,
        interval: 1,
        points: [
          { idx: 10, action: 'challenge' },
          { idx: 15, action: 'challenge' },
        ]
      },
      {
        id: 2,
        name: '区域2',
        time: 10,
        interval: 1,
        points: [
          { idx: 10, action: 'challenge' },
          { idx: 15, action: 'challenge' },
        ]
      },
      {
        id: 3,
        name: '区域3',
        time: 10,
        interval: 1,
        points: [
          { idx: 10, action: 'challenge' },
          { idx: 15, action: 'challenge' },
        ]
      },
    ],
  },
  {
    # ID
    id: 6,

    name: '隔壁创下',

    desc: '隔壁创下,隔壁创下,隔壁创下,隔壁创下,隔壁创下',

    areas: [
      {
        id: 1,
        name: '区域1',
        time: 10,
        interval: 1,
        points: [
          { idx: 10, action: 'challenge' },
          { idx: 15, action: 'challenge' },
        ]
      },
      {
        id: 2,
        name: '区域2',
        time: 10,
        interval: 1,
        points: [
          { idx: 10, action: 'challenge' },
          { idx: 15, action: 'challenge' },
        ]
      },
      {
        id: 3,
        name: '区域3',
        time: 10,
        interval: 1,
        points: [
          { idx: 10, action: 'challenge' },
          { idx: 15, action: 'challenge' },
        ]
      },
    ],
  },
]