# ===========================================
# 探索配置
# ===========================================
explore: [
  {
    # ID
    id: 1,

    name: '新手村',

    desc: '新手村,新手村,新手村,新手村,新手村,新手村,新手村',

    areas: [
      {
        id: 1,
        name: '区域1',
        time: 30,
        interval: 1,
        points: [
          { idx: 1, event: 'pk', seqId: 'explore', group: 'A' },
          { idx: 5, event: 'xunbao', action: 'xunbao_1' },
          { idx: 10, event: 'boss', seqId: 'explore', group: 'B' },
          { idx: 15, event: 'xiansuo' },
          { idx: 20, event: 'qiyu', action: 'qiyu_1_XXX' },
          { idx: 25, event: 'pk', seqId: 'explore', group: 'A' },
        ],
        slots: {
          # 随机道具
          props: {
            p100: [ { propId: 26, num: 1, rate: 20 }, { propId: 27, num: 2, rate: 20 } ],
            p1000: [ { propId: 28, num: 1, rate: 200 }, { propId: 29, num: 2, rate: 300 } ],
            p10000: [ { propId: 30, num: 1, rate: 800 } ],
          }
        },
      },
      {
        id: 2,
        name: '区域2',
        time: 30,
        interval: 1,
        points: [
          { idx: 5, event: 'xunbao', typeId: 2 },
          { idx: 10, event: 'boss', seqId: 'explore', group: 'C' },
          { idx: 15, event: 'xiansuo' },
          { idx: 20, event: 'qiyu' },
          { idx: 25, event: 'pk', seqId: 'explore', group: 'A' },
        ],
        slots: {
          # 随机道具
          props: {
            p100: [ { propId: 26, num: 1, rate: 20 }, { propId: 27, num: 2, rate: 20 } ],
            p1000: [ { propId: 28, num: 1, rate: 200 }, { propId: 29, num: 2, rate: 300 } ],
            p10000: [ { propId: 30, num: 1, rate: 800 } ],
          }
        },
      },
      {
        id: 3,
        name: '区域3',
        time: 30,
        interval: 1,
        points: [
          { idx: 5, event: 'xunbao', typeId: 3 },
          { idx: 10, event: 'boss', seqId: 'explore', group: 'D' },
          { idx: 15, event: 'xiansuo' },
          { idx: 20, event: 'qiyu' },
          { idx: 25, event: 'pk', seqId: 'explore', group: 'A' },
        ],
        slots: {
          # 随机道具
          props: {
            p100: [ { propId: 26, num: 1, rate: 20 }, { propId: 27, num: 2, rate: 20 } ],
            p1000: [ { propId: 28, num: 1, rate: 200 }, { propId: 29, num: 2, rate: 300 } ],
            p10000: [ { propId: 30, num: 1, rate: 800 } ],
          }
        },
      },
    ],
  },
  {
    # ID
    id: 2,

    name: '邻家树林',

    desc: '邻家树林,邻家树林,邻家树林,邻家树林,邻家树林,邻家树林',

    areas: [
      {
        id: 1,
        name: '区域1',
        time: 30,
        interval: 1,
        points: [
          { idx: 5, event: 'xunbao', typeId: 1 },
          { idx: 10, event: 'boss', seqId: 'explore', group: 'B' },
          { idx: 15, event: 'xiansuo' },
          { idx: 20, event: 'qiyu' },
          { idx: 25, event: 'pk', seqId: 'explore', group: 'A' },
        ],
        slots: {
          # 随机道具
          props: {
            p100: [ { propId: 26, num: 1, rate: 20 }, { propId: 27, num: 2, rate: 20 } ],
            p1000: [ { propId: 28, num: 1, rate: 200 }, { propId: 29, num: 2, rate: 300 } ],
            p10000: [ { propId: 30, num: 1, rate: 800 } ],
          }
        },
      },
      {
        id: 2,
        name: '区域2',
        time: 30,
        interval: 1,
        points: [
          { idx: 5, event: 'xunbao', typeId: 2 },
          { idx: 10, event: 'boss', seqId: 'explore', group: 'C' },
          { idx: 15, event: 'xiansuo' },
          { idx: 20, event: 'qiyu' },
          { idx: 25, event: 'pk', seqId: 'explore', group: 'A' },
        ],
        slots: {
          # 随机道具
          props: {
            p100: [ { propId: 26, num: 1, rate: 20 }, { propId: 27, num: 2, rate: 20 } ],
            p1000: [ { propId: 28, num: 1, rate: 200 }, { propId: 29, num: 2, rate: 300 } ],
            p10000: [ { propId: 30, num: 1, rate: 800 } ],
          }
        },
      },
      {
        id: 3,
        name: '区域3',
        time: 30,
        interval: 1,
        points: [
          { idx: 5, event: 'xunbao', typeId: 3 },
          { idx: 10, event: 'boss', seqId: 'explore', group: 'D' },
          { idx: 15, event: 'xiansuo' },
          { idx: 20, event: 'qiyu' },
          { idx: 25, event: 'pk', seqId: 'explore', group: 'A' },
        ],
        slots: {
          # 随机道具
          props: {
            p100: [ { propId: 26, num: 1, rate: 20 }, { propId: 27, num: 2, rate: 20 } ],
            p1000: [ { propId: 28, num: 1, rate: 200 }, { propId: 29, num: 2, rate: 300 } ],
            p10000: [ { propId: 30, num: 1, rate: 800 } ],
          }
        },
      },
    ],
  },
  {
    # ID
    id: 3,

    name: '隔壁山上',

    desc: '隔壁山上,隔壁山上,隔壁山上,隔壁山上,隔壁山上,隔壁山上',

    areas: [
      {
        id: 1,
        name: '区域1',
        time: 30,
        interval: 1,
        points: [
          { idx: 5, event: 'xunbao', typeId: 1 },
          { idx: 10, event: 'boss', seqId: 'explore', group: 'B' },
          { idx: 15, event: 'xiansuo' },
          { idx: 20, event: 'qiyu' },
          { idx: 25, event: 'pk', seqId: 'explore', group: 'A' },
        ],
        slots: {
          # 随机道具
          props: {
            p100: [ { propId: 26, num: 1, rate: 20 }, { propId: 27, num: 2, rate: 20 } ],
            p1000: [ { propId: 28, num: 1, rate: 200 }, { propId: 29, num: 2, rate: 300 } ],
            p10000: [ { propId: 30, num: 1, rate: 800 } ],
          }
        },
      },
      {
        id: 2,
        name: '区域2',
        time: 30,
        interval: 1,
        points: [
          { idx: 5, event: 'xunbao', typeId: 2 },
          { idx: 10, event: 'boss', seqId: 'explore', group: 'C' },
          { idx: 15, event: 'xiansuo' },
          { idx: 20, event: 'qiyu' },
          { idx: 25, event: 'pk', seqId: 'explore', group: 'A' },
        ],
        slots: {
          # 随机道具
          props: {
            p100: [ { propId: 26, num: 1, rate: 20 }, { propId: 27, num: 2, rate: 20 } ],
            p1000: [ { propId: 28, num: 1, rate: 200 }, { propId: 29, num: 2, rate: 300 } ],
            p10000: [ { propId: 30, num: 1, rate: 800 } ],
          }
        },
      },
      {
        id: 3,
        name: '区域3',
        time: 30,
        interval: 1,
        points: [
          { idx: 5, event: 'xunbao', typeId: 3 },
          { idx: 10, event: 'boss', seqId: 'explore', group: 'D' },
          { idx: 15, event: 'xiansuo' },
          { idx: 20, event: 'qiyu' },
          { idx: 25, event: 'pk', seqId: 'explore', group: 'A' },
        ],
        slots: {
          # 随机道具
          props: {
            p100: [ { propId: 26, num: 1, rate: 20 }, { propId: 27, num: 2, rate: 20 } ],
            p1000: [ { propId: 28, num: 1, rate: 200 }, { propId: 29, num: 2, rate: 300 } ],
            p10000: [ { propId: 30, num: 1, rate: 800 } ],
          }
        },
      },
    ],
  },
  {
    # ID
    id: 4,

    name: '隔壁后院',

    desc: '隔壁后院,隔壁后院,隔壁后院,隔壁后院,隔壁后院,隔壁后院',

    areas: [
      {
        id: 1,
        name: '区域1',
        time: 30,
        interval: 1,
        points: [
          { idx: 5, event: 'xunbao', typeId: 1 },
          { idx: 10, event: 'boss', seqId: 'explore', group: 'B' },
          { idx: 15, event: 'xiansuo' },
          { idx: 20, event: 'qiyu' },
          { idx: 25, event: 'pk', seqId: 'explore', group: 'A' },
        ],
        slots: {
          # 随机道具
          props: {
            p100: [ { propId: 26, num: 1, rate: 20 }, { propId: 27, num: 2, rate: 20 } ],
            p1000: [ { propId: 28, num: 1, rate: 200 }, { propId: 29, num: 2, rate: 300 } ],
            p10000: [ { propId: 30, num: 1, rate: 800 } ],
          }
        },
      },
      {
        id: 2,
        name: '区域2',
        time: 30,
        interval: 1,
        points: [
          { idx: 5, event: 'xunbao', typeId: 2 },
          { idx: 10, event: 'boss', seqId: 'explore', group: 'C' },
          { idx: 15, event: 'xiansuo' },
          { idx: 20, event: 'qiyu' },
          { idx: 25, event: 'pk', seqId: 'explore', group: 'A' },
        ],
        slots: {
          # 随机道具
          props: {
            p100: [ { propId: 26, num: 1, rate: 20 }, { propId: 27, num: 2, rate: 20 } ],
            p1000: [ { propId: 28, num: 1, rate: 200 }, { propId: 29, num: 2, rate: 300 } ],
            p10000: [ { propId: 30, num: 1, rate: 800 } ],
          }
        },
      },
      {
        id: 3,
        name: '区域3',
        time: 30,
        interval: 1,
        points: [
          { idx: 5, event: 'xunbao', typeId: 3 },
          { idx: 10, event: 'boss', seqId: 'explore', group: 'D' },
          { idx: 15, event: 'xiansuo' },
          { idx: 20, event: 'qiyu' },
          { idx: 25, event: 'pk', seqId: 'explore', group: 'A' },
        ],
        slots: {
          # 随机道具
          props: {
            p100: [ { propId: 26, num: 1, rate: 20 }, { propId: 27, num: 2, rate: 20 } ],
            p1000: [ { propId: 28, num: 1, rate: 200 }, { propId: 29, num: 2, rate: 300 } ],
            p10000: [ { propId: 30, num: 1, rate: 800 } ],
          }
        },
      },
    ],
  },
  {
    # ID
    id: 5,

    name: '隔壁屋顶',

    desc: '隔壁屋顶,隔壁屋顶,隔壁屋顶,隔壁屋顶,隔壁屋顶,隔壁屋顶',

    areas: [
      {
        id: 1,
        name: '区域1',
        time: 30,
        interval: 1,
        points: [
          { idx: 5, event: 'xunbao', typeId: 1 },
          { idx: 10, event: 'boss', seqId: 'explore', group: 'B' },
          { idx: 15, event: 'xiansuo' },
          { idx: 20, event: 'qiyu' },
          { idx: 25, event: 'pk', seqId: 'explore', group: 'A' },
        ],
        slots: {
          # 随机道具
          props: {
            p100: [ { propId: 26, num: 1, rate: 20 }, { propId: 27, num: 2, rate: 20 } ],
            p1000: [ { propId: 28, num: 1, rate: 200 }, { propId: 29, num: 2, rate: 300 } ],
            p10000: [ { propId: 30, num: 1, rate: 800 } ],
          }
        },
      },
      {
        id: 2,
        name: '区域2',
        time: 30,
        interval: 1,
        points: [
          { idx: 5, event: 'xunbao', typeId: 2 },
          { idx: 10, event: 'boss', seqId: 'explore', group: 'C' },
          { idx: 15, event: 'xiansuo' },
          { idx: 20, event: 'qiyu' },
          { idx: 25, event: 'pk', seqId: 'explore', group: 'A' },
        ],
        slots: {
          # 随机道具
          props: {
            p100: [ { propId: 26, num: 1, rate: 20 }, { propId: 27, num: 2, rate: 20 } ],
            p1000: [ { propId: 28, num: 1, rate: 200 }, { propId: 29, num: 2, rate: 300 } ],
            p10000: [ { propId: 30, num: 1, rate: 800 } ],
          }
        },
      },
      {
        id: 3,
        name: '区域3',
        time: 30,
        interval: 1,
        points: [
          { idx: 5, event: 'xunbao', typeId: 3 },
          { idx: 10, event: 'boss', seqId: 'explore', group: 'D' },
          { idx: 15, event: 'xiansuo' },
          { idx: 20, event: 'qiyu' },
          { idx: 25, event: 'pk', seqId: 'explore', group: 'A' },
        ],
        slots: {
          # 随机道具
          props: {
            p100: [ { propId: 26, num: 1, rate: 20 }, { propId: 27, num: 2, rate: 20 } ],
            p1000: [ { propId: 28, num: 1, rate: 200 }, { propId: 29, num: 2, rate: 300 } ],
            p10000: [ { propId: 30, num: 1, rate: 800 } ],
          }
        },
      },
    ],
  },
  {
    # ID
    id: 6,

    name: '隔壁创下',

    desc: '隔壁创下,隔壁创下,隔壁创下,隔壁创下,隔壁创下',

    areas: [
      {
        id: 1,
        name: '区域1',
        time: 30,
        interval: 1,
        points: [
          { idx: 5, event: 'xunbao', typeId: 1 },
          { idx: 10, event: 'boss', seqId: 'explore', group: 'B' },
          { idx: 15, event: 'xiansuo' },
          { idx: 20, event: 'qiyu' },
          { idx: 25, event: 'pk', seqId: 'explore', group: 'A' },
        ],
        slots: {
          # 随机道具
          props: {
            p100: [ { propId: 26, num: 1, rate: 20 }, { propId: 27, num: 2, rate: 20 } ],
            p1000: [ { propId: 28, num: 1, rate: 200 }, { propId: 29, num: 2, rate: 300 } ],
            p10000: [ { propId: 30, num: 1, rate: 800 } ],
          }
        },
      },
      {
        id: 2,
        name: '区域2',
        time: 30,
        interval: 1,
        points: [
          { idx: 5, event: 'xunbao', typeId: 2 },
          { idx: 10, event: 'boss', seqId: 'explore', group: 'B' },
          { idx: 15, event: 'xiansuo' },
          { idx: 20, event: 'qiyu' },
          { idx: 25, event: 'pk', seqId: 'explore', group: 'A' },
        ],
        slots: {
          # 随机道具
          props: {
            p100: [ { propId: 26, num: 1, rate: 20 }, { propId: 27, num: 2, rate: 20 } ],
            p1000: [ { propId: 28, num: 1, rate: 200 }, { propId: 29, num: 2, rate: 300 } ],
            p10000: [ { propId: 30, num: 1, rate: 800 } ],
          }
        },
      },
      {
        id: 3,
        name: '区域3',
        time: 30,
        interval: 1,
        points: [
          { idx: 5, event: 'xunbao', typeId: 3 },
          { idx: 10, event: 'boss', seqId: 'explore', group: 'B' },
          { idx: 15, event: 'xiansuo' },
          { idx: 20, event: 'qiyu' },
          { idx: 25, event: 'pk', seqId: 'explore', group: 'A' },
        ],
        slots: {
          # 随机道具
          props: {
            p100: [ { propId: 26, num: 1, rate: 20 }, { propId: 27, num: 2, rate: 20 } ],
            p1000: [ { propId: 28, num: 1, rate: 200 }, { propId: 29, num: 2, rate: 300 } ],
            p10000: [ { propId: 30, num: 1, rate: 800 } ],
          }
        },
      },
    ],
  },
]