# ===========================================
# 默认灵田配置
# 状态 status: 0-未开启, 1-开启但未种植, 2-种植中, 3-成熟了
# ===========================================

data:
  [
    {
      name: '顾春园',
      isOpen: true,
      lingTian:
        [
          {id: 1, status: 1, grade: 1, lingQiZhi: 100},
          {id: 2, status: 1, grade: 1, lingQiZhi: 100},
          {id: 3, status: 0, grade: 1, lingQiZhi: 100},
        ],
    },
    {
      name: '盛夏园',
      isOpen: false,
      lingTian: [{id: 1, grade: 1, status: 0, lingQiZhi: 100}],
    },
    {
      name: '秋雨园',
      isOpen: false,
      lingTian: [{id: 1, grade: 1, status: 0, lingQiZhi: 100}],
    },
    {
      name: '寒冬园',
      isOpen: false,
      lingTian: [{id: 1, grade: 1, status: 0, lingQiZhi: 100}],
    },
  ]
