scenes: [
  # 破庙门口场景
  {
    id: 'M01_S05_luoyuezhen_nanjieshi', name: '落月镇南-南街集市',

    # 变量定义
    vars: [
      { id: 'v1', min: 0, max: 1 },
      { id: 'v2', min: 0, max: 1 },
      { id: 'v3', min: 0, max: 1 },
    ],

    # 动作定义
    actions: [
    ],

    # 事件定义
    events: [
      { type: 'enter', andVarsOn: ['M01_S01_luoyuezhen_Time/Event01Day1'], nextChat: 'nanjieshi_Event01Day1' },
      { type: 'enter', andVarsOn: ['M01_S01_luoyuezhen_Time/Event01Day2'], nextChat: 'nanjieshi_Event01Day2' },
      { type: 'enter', andVarsOn: ['M01_S01_luoyuezhen_Time/Event01Day3'], nextChat: 'nanjieshi_Event01Day3' },
    ],

    # 对话选项
    chats: [
      #
      { 
        id: 'nanjieshi_Event01Day1', desc: '繁华的商业街道。', 
        options: [ 
          { title: '>>>【集市一角】', andVarsOn: ['v1'], toScene: 'M01_S06_luoyuezhen_jishiyijiao'}, 
          { title: '【和乞丐李大哥对话】', andVarsOff: ['v1'], dialogs: ['p1'] }, 
          { title: '【观察街市内】', andVarsOff: ['v2'], nextChat: 'nanjieshi_Event01Day1B' }, 
        ],
      },
      #
      { 
        id: 'nanjieshi_Event01Day1B', desc: '集市内有不少的商铺和地摊，十分热闹。', 
        options: [ 
        { title: '<<<返回', nextChat: 'nanjieshi_Event01Day1' }, 
        ],
      },


      #
      { 
        id: 'nanjieshi_Event01Day2', desc: '繁华的商业街道，和往常一样人来人往', 
        options: [ 
          { title: '【集市一角】', toScene: 'M01_S06_luoyuezhen_jishiyijiao'}, 
        ],
      },
       #
      { 
        id: 'nanjieshi_Event01Day3', desc: '繁华的商业街道。', 
        options: [ 
          { title: '【集市一角】', toScene: 'M01_S06_luoyuezhen_jishiyijiao'}, 
        ],
      },
    ],

    # 对话框
    dialogs: [
      { id: 'p1', style: 2, title: '乞丐李大哥：', sections: ['这里是外来的一般商家来的市场，一般为了图个彩头，不会有多寒酸 我们就在这附近讨乞。不出这条路就行。', '记住不能去隔壁的北街市，那是富人才能去的地方，乞丐是去不了的。'], varsOn: ['v1'], nextChat: 'nanjieshi_Event01Day1' },
    ],
  },
]