scenes: [
  # 一个专门控制落月镇时间的NPC场景
  {
    id: 'M01_S01_luoyuezhen_Time', name: '落月镇-时间的夹缝',
    # NPC
    # 指定场景为NPC场景
    isNpc: true,
    # 变量定义
    vars: [
      { id: 'Event01Day0', min: 0, max: 1 ,defaultValue: 1,},
      { id: 'Event01Day1', min: 0, max: 1 ,defaultValue: 0,},
      { id: 'Event01Day2', min: 0, max: 1 ,defaultValue: 0,},
      { id: 'Event01Day3', min: 0, max: 1 ,defaultValue: 0,},

      { id: 'Event02Day0', min: 0, max: 1 ,defaultValue: 0,},
      { id: 'Event02Day1', min: 0, max: 1 ,defaultValue: 0,},
      { id: 'Event02Day2', min: 0, max: 1 ,defaultValue: 0,},
      { id: 'Event02Day3', min: 0, max: 1 ,defaultValue: 0,},
      { id: 'Event02Day4', min: 0, max: 1 ,defaultValue: 0,},
      { id: 'Event02Day5', min: 0, max: 1 ,defaultValue: 0,},
    ],

    # 动作定义
    actions: [
    ],

    # 事件定义
    events: [
      { type: 'enter', nextChat: 'c1' },
 
    ],

    # 对话选项
    chats: [
      #
      { 
        id: 'c1', desc: '繁华的商业街道。', 
        options: [ 
          { title: '【观察街市内】', andVarsOff: ['v1'], dialogs: ['p1'] }, 
          { title: '【集市一角】', andVarsOn: ['v1'], toScene: 'jishiyijiao'}, 
        ],
      },
    ],

    # 对话框
    dialogs: [
      { id: 'p1', style: 2, title: '乞丐李大哥：', sections: ['这里是外来的一般商家来的市场，一般为了图个彩头，不会有多寒酸 我们就在这附近讨乞。不出这条路就行。', '讨乞后每天晚上要给帮派利钱，不然被记住会被帮派打走。', '记住不要去北街，那是富人才能去的地方，乞丐是去不了的。会被打。'], varsOn: ['v1'], nextChat: 'c1' },
    ],
  },
]