scenes: [
  # 破庙门口场景
  {
    id: 'xizhenminjujie', name: '西镇居民街',

    # 变量定义
    vars: [
      { id: 'v1', min: 0, max: 1 },
    ],

    # 动作定义
    actions: [
    ],

    # 事件定义
    events: [
      { type: 'enter', dialogs: ['p1'], nextChat: 'c1' },
    ],

    # 对话选项
    chats: [
      #
      { 
        id: 'c1', desc: '', 
        options: [ 
          # 第一天
          { title: '【和善的老人】', andVarsOn: ['v1'], andVarsOff: ['v5', 'v7', 'v8'], nextChat: 'c2' }, 
        ],
      },
      { 
        id: 'c2', desc: '路人露出鄙视的眼神', 
        options: [ 
          { title: '返回', varsOn: ['v2'], nextChat: 'c1' }, 
        ],
      },
    ],

    # 对话框
    dialogs: [
      { id: 'p1', style: 2, title: '乞丐李大哥：', sections: ['各位老爷行行好，给点赏赐，大吉大利……'], varsOn: ['v1'], andVarsOff: ['v1'], nextChat: 'c1' },
    ],
  },
]