scenes: [
  # 破庙门口场景
  {
    id: 'hutongkou', name: '落月镇西-胡同口',

    # 进入场景事件处理动作ID列表
    enterActions: ['b0', 'b1'],

    # 变量定义
    vars: [
      { id: 'v1', min: 0, max: 1, defaulValue: 0 },
      { id: 'v2', min: 0, max: 1, defaulValue: 0 },
    ],

    # 动作定义
    actions: [
      { id: 'b0', cmd: 'aside', params: 'p1' },
      { id: 'b1', cmd: 'chat', params: 'c1' },
      { id: 'b2', cmd: 'chat', params: 'c2' },
      { id: 'b3', cmd: 'aside', params: 'p2' },
      { id: 'b4', cmd: 'scene', params: 'xizhenminjujie' },
    ],

    # 事件定义
    events: [
    ],

    # 对话选项
    chats: [
      #
      { 
        id: 'c1', desc: '这里是荒凉的地方，没人经过', 
        options: [ 
          { title: '【观察四周】', clickActions: ['b2', 'b3'], andVarsOn: ['v1'], andVarsOff: ['v2'] }, 
          { title: '【西镇民居街】', clickActions: ['b4'], andVarsOn: ['v2'] }, 
        ],
      },
      { 
        id: 'c2', desc: '一些老人在路边闲坐，打发时间', 
        options: [ 
        ],
      },
    ],

    # 旁白
    asides: [
      { id: 'p1', style: 2, sections: ['落月镇是个几千人口的镇子，比村子大，但人数也不多。'], finishActions: ['b1'], varsOn: ['v1'], andVarsOff: ['v1'] },
      { id: 'p2', style: 2, title: '乞丐李大哥：', sections: ['这些人也是寻常人家，不会搭理乞丐的。'], finishActions: ['b1'], varsOn: ['v2'] },
    ],

    # 对话框
    dialogs: [
    ]
  },
]