scenes: [
  # 破庙门口场景
  {
    id: 'xizhenminjujie', name: '西镇民居街',

    # 变量定义
    vars: [
      { id: 'v1', min: 0, max: 1 },
    ],

    # 动作定义
    actions: [
    ],

    # 事件定义
    events: [
      { type: 'enter', nextChat: 'c1' },
    ],

    # 对话选项
    chats: [
      #
      { 
        id: 'c1', desc: '民居院落依着斜坡而建，路边有一条小河沟，桥头有一些小吃摊位', 
        options: [ 
          { title: '【观察路边的小吃摊】', andVarsOff: ['v1'], nextChat: 'c2', dialogs: ['p1'] }, 
          { title: '【大路口】', andVarsOn: ['v1'], toScene: 'dalukou' }, 
        ],
      },
      { 
        id: 'c2', desc: '一些老人在路边闲坐，打发时间', 
        options: [ 
        ],
      },
    ],

    # 对话框
    dialogs: [
      { id: 'p1', style: 2, title: '乞丐李大哥：', sections: ['价钱还行，运气好了讨到钱，我们也可以买东西吃，但不要在人多的时候打扰生意。'], varsOn: ['v1'], nextChat: 'c1' },
    ],
  },
]