scenes: [
  # 新手村场景
  {
    id: 'pomiao', name: '破庙',

    # 进入场景事件处理动作ID列表
    enterActions: ['a0'],

    # 变量定义
    vars: [
      { id: 'v1', min: 0, max: 1, defaulValue: 0 },
      { id: 'v2', min: 0, max: 1, defaulValue: 0 },
      { id: 'v3', min: 0, max: 1, defaulValue: 0 },
      { id: 'v4', min: 0, max: 1, defaulValue: 0 },
      { id: 'v5', min: 0, max: 1, defaulValue: 0 },
      { id: 'v6', min: 0, max: 1, defaulValue: 0 },
      { id: 'v7', min: 0, max: 1, defaulValue: 0 },
      { id: 'v8', min: 0, max: 1, defaulValue: 0 },
      { id: 'v9', min: 0, max: 1, defaulValue: 0 },
      { id: 'v10', min: 0, max: 1, defaulValue: 0 },
      { id: 'v11', min: 0, max: 1, defaulValue: 0 },
    ],

    # 动作定义
    actions: [
      { id: 'a0', cmd: 'chat', params: 'c1' },
      { id: 'b0', cmd: 'chat',  params: 'c2' },
      { id: 'b1', cmd: 'aside',  params: 'p1' },
      { id: 'b2', cmd: 'aside',  params: 'p2' },
      { id: 'b3', cmd: 'aside',  params: 'p3' },
      { id: 'b4', cmd: 'aside',  params: 'p4' },
      { id: 'b5', cmd: 'aside',  params: 'p5' },
      { id: 'b6', cmd: 'aside',  params: 'p6' },
      { id: 'b7', cmd: 'aside',  params: 'p7' },
      { id: 'b8', cmd: 'dialog',  params: 'd1' },
      { id: 'b9', cmd: 'aside',  params: 'p10' },
      { id: 'b10', cmd: 'aside',  params: 'p11' },
      { id: 'b11', cmd: 'dialog',  params: 'd2' },
      { id: 'b12', cmd: 'aside',  params: 'p12' },
      { id: 'b13', cmd: 'aside',  params: 'p13' },
      { id: 'b14', cmd: 'aside',  params: 'p14' },
      { id: 'b15', cmd: 'aside',  params: 'p15' },
      { id: 'b16', cmd: 'aside',  params: 'p16' },
      { id: 'b17', cmd: 'dialog',  params: 'd3' },
      { id: 'b18', cmd: 'scene',  params: 'pomiaomk' },
      { id: 'b19', cmd: 'wtime',  params: '@day/1/6' },
    ],

    # 事件定义
    events: [
    ],

    # 对话选项
    chats: [
      # 新手对话主列表
      { 
        id: 'c1', desc: '你在一座破庙里面', 
        options: [ 
          { title: '【查看四周】', clickActions: ['b1'], andVarsOff: ['v10'] }, 
          { title: '【查看头顶】', clickActions: ['b2'], andVarsOff: ['v10'] }, 
          { title: '【动动身子】', clickActions: ['b3'], andVarsOn: ['v1', 'v2'], andVarsOff: ['v10'] }, 
          { title: '【看看自己的手】', clickActions: ['b4'], andVarsOn: ['v1', 'v2', 'v3'], andVarsOff: ['v10'] }, 
          { title: '【询问周围的乞丐】', clickActions: ['b5'], andVarsOn: ['v1', 'v2', 'v3', 'v4'], andVarsOff: ['v6', 'v10'] }, 
          { title: '【尝试起身】', clickActions: ['b6'], andVarsOn: ['v1', 'v2', 'v3', 'v4'], andVarsOff: ['v5', 'v10'] }, 
          # 以下选项在【询问周围的乞丐】&【尝试起身】点击后替换
          { title: '【询问周围的乞丐】', clickActions: ['b7'], andVarsOn: ['v1', 'v2', 'v3', 'v4', 'v6'], andVarsOff: ['v10'] }, 
          { title: '【尝试起身】', clickActions: ['b7'], andVarsOn: ['v1', 'v2', 'v3', 'v4', 'v5'], andVarsOff: ['v10'] }, 
          { title: '【睡觉】', clickActions: ['b19', 'a0'], andVarsOn: ['v10'], andVarsOff: ['v11'], varsOn: ['v11'] }, 
          { title: '【走出破庙】', clickActions: ['b18'], andVarsOn: ['v11'] }, 
        ],
      },
      {
        id: 'c2', desc: '你在一座破庙里面', 
        options: [ 
          { title: '【大声怪叫】', clickActions: ['b8'], andVarsOff: ['v7'] }, 
          { title: '【询问  这是在哪】', clickActions: ['b11'], andVarsOn: ['v7'], andVarsOff: ['v8'] }, 
          { title: '【承认】', clickActions: ['b13'], andVarsOn: ['v8'], andVarsOff: ['v9'] }, 
          { title: '【拒绝】', clickActions: ['b14'], andVarsOn: ['v8'], andVarsOff: ['v9'] }, 
          { title: '【离开破庙】', clickActions: ['b18'], andVarsOn: ['v9'], varsOn: ['v10'] }, 
        ],
      },
    ],

    # 旁白
    asides: [
      { id: 'p1', style: 2, sections: ['这是一个小破庙，大概不到二十平米，由土垒成，而不是砖建造的这种建筑即使是农村也几乎见不到了。'], finishActions: ['a0'], varsOn: ['v1'] },
      { id: 'p2', style: 2, sections: ['破庙的房顶是木头和茅草，有些漏风'], finishActions: ['a0'], varsOn: ['v2'] },
      { id: 'p3', style: 2, sections: ['一身酸痛袭来，怎么回事？'], finishActions: ['a0'], varsOn: ['v3'] },
      { id: 'p4', style: 2, sections: ['这是一只稚嫩的手，不过脏兮兮的，指甲还有点血丝。'], finishActions: ['a0'], varsOn: ['v4'] },
      { id: 'p5', style: 2, sections: ['乞丐在睡觉，没有理你'], finishActions: ['a0'], varsOn: ['v5'] },
      { id: 'p6', style: 2, sections: ['动不了'], finishActions: ['a0'], varsOn: ['v6'] },
      { id: 'p7', style: 2, sections: ['总得想个办法'], finishActions: ['b0'], varsOn: ['v5', 'v6'] },
      { id: 'p10', style: 1, sections: ['周围本来睡着的乞丐出声'], finishActions: ['b10'] },
      { id: 'p11', style: 2, sections: ['你发现乞丐说的是一种没听过的语音，但是你竟然可以听懂。', '一股关于语言的记忆涌上脑海', '看来交流没问题', '那么'], finishActions: ['b0'], varsOn: ['v7'] },
      { id: 'p12', style: 2, sections: ['……完全没听过的名字。', '你是不是被打后伤到脑袋了，乞丐问。'], finishActions: ['b0'], varsOn: ['v8'] },
      { id: 'p13', style: 2, sections: ['那这几天好好休息，乞丐说'], finishActions: ['b15'] },
      { id: 'p14', style: 2, sections: ['还行，那你知道我是谁吗？', '……', '看来病的不轻……好好休息。'], finishActions: ['b0'] },
      { id: 'p15', style: 2, sections: ['在闲聊中，你知道旁边的乞丐是你以前认的乞丐李大哥，两人都是从更远的地方流浪而来。', '你知道了全身的伤是因为讨乞的时候被村里的王员外打的。', '起因只是因为挡了人家的道，被嫌弃晦气。', '看来，到了一个不得了的世界啊。'], finishActions: ['b16'] },
      { id: 'p16', style: 2, sections: ['一晃几天过去了', '经过几天修养，现在可以走路了', '乞丐的生活是很清苦的，能吃饱饭已经谢天谢地。', '在小村镇当中，也没有那么多富裕人家。', '奇怪的是，全身的伤，在半饥饿的状态好了个七七八八。', '询问乞丐李大哥，对方说大概是因为这片土地的天地灵气比较充沛的缘故。', '大多数人都受到恩惠。', '既然能够行动，李大哥决定带你一起讨乞。'], finishActions: ['b17'] },
    ],

    # 对话框
    dialogs: [
      { id: 'd1', title: '附近的声音：', content: '吵死了', confirmActions: ['b9'] },
      { id: 'd2', title: '乞丐：', content: '这是落月镇的土地庙啊', confirmActions: ['b12'] },
      { id: 'd3', title: '乞丐李大哥：', content: '平时讨乞的位置是在附近的东街市，我们一起走', confirmActions: ['b0'], varsOn: ['v9'] },
    ]
  },
]