scenes: [
  # 破庙门口场景
  {
    id: 'dalukou', name: '大路口',

    # 变量定义
    vars: [
      { id: 'v1', min: 0, max: 1 },
    ],

    # 动作定义
    actions: [
    ],

    # 事件定义
    events: [
      { type: 'enter', nextChat: 'c1' },
    ],

    # 对话选项
    chats: [
      #
      { 
        id: 'c1', desc: '有些少许行人在路边，匆匆而过', 
        options: [ 
          { title: '【观察路边状况】', andVarsOff: ['v1'], asides: ['p1'] }, 
          { title: '【南街市】', andVarsOn: ['v1'], toScene: 'nanjieshi' }, 
        ],
      },
    ],

    # 旁白
    asides: [
      { id: 'p1', style: 2, title: '乞丐李大哥：', sections: ['这里是马车路，记得要走两边，被马撞到的话只能认栽，一起也有被马撞死的乞丐，或者应该是被踩死的吧。'], varsOn: ['v1'], nextChat: 'c1' },
    ],

    # 对话框
    dialogs: [
    ]
  },
]