scenes: [
  # 破庙门口场景
  {
    id: 'dalukou', name: '大路口',

    # 进入场景事件处理动作ID列表
    enterActions: ['b0'],

    # 变量定义
    vars: [
      { id: 'v1', min: 0, max: 1, defaulValue: 0 },
    ],

    # 动作定义
    actions: [
      { id: 'b0', cmd: 'chat', params: 'c1' },
      { id: 'b1', cmd: 'aside', params: 'p1' },
      { id: 'b2', cmd: 'scene', params: 'nanjieshi' },
    ],

    # 事件定义
    events: [
    ],

    # 对话选项
    chats: [
      #
      { 
        id: 'c1', desc: '有些少许行人在路边，匆匆而过', 
        options: [ 
          { title: '【观察路边状况】', clickActions: ['b1'], andVarsOff: ['v1']}, 
          { title: '【南街市】', clickActions: ['b2'], andVarsOn: ['v1']}, 
        ],
      },
    ],

    # 旁白
    asides: [
      { id: 'p1', style: 2, title: '乞丐李大哥：', sections: ['这里是马车路，记得要走两边，被马撞到的话只能认栽，一起也有被马撞死的乞丐，或者应该是被踩死的吧。'], finishActions: ['b0'], varsOn: ['v1'] },
    ],

    # 对话框
    dialogs: [
    ]
  },
]