scenes: [
  # 破庙门口场景
  {
    id: 'hutongkou', name: '落月镇西-胡同口',

    # 变量定义
    vars: [
      { id: 'v1', min: 0, max: 1 },
      { id: 'v2', min: 0, max: 1 },
      { id: 'v3', min: 0, max: 1 },
    ],

    # 动作定义
    actions: [
    ],

    # 事件定义
    events: [
      { type: 'enter', andVarsOff: ['v1'], dialogs: ['p1'] },
      { type: 'enter', andVarsOn: ['v1'], nextChat: 'c1' },
    ],

    # 对话选项
    chats: [
      #
      { 
        id: 'c1', desc: '这里是荒凉的地方，没人经过', 
        options: [ 
          { title: '【破庙门口】', andVarsOn: ['xizhenminjujie/v3'], varsOn: ['v3'], toScene: 'pomiaomk' }, 
          { title: '【观察四周】', andVarsOn: ['v1'], andVarsOff: ['v2'], dialogs: ['p2'], nextChat: 'c2' }, 
          { title: '【西镇民居街】', andVarsOn: ['v2'], toScene: 'xizhenminjujie' }, 
          { title: '➦【破庙门口】', andVarsOn: ['xizhenminjujie/v3'], varsOn: ['v3'], toScene: 'pomiaomk' }, 
        ],
      },
      { 
        id: 'c2', desc: '一些老人在路边闲坐，打发时间', 
        options: [ 
        ],
      },
    ],

    # 对话框
    dialogs: [
      { id: 'p1', style: 2, sections: ['落月镇是个几千人口的镇子，比村子大，但人数也不多。'], varsOn: ['v1'], nextChat: 'c1' },
      { id: 'p2', style: 2, title: '乞丐李大哥：', sections: ['这些人也是寻常人家，不会搭理乞丐的。'], varsOn: ['v2'], nextChat: 'c1' },
    ],
  },
]