scenes: [
  # 破庙门口场景
  {
    id: 'jishiyijiao', name: '集市一角',

    # 进入场景事件处理动作ID列表
    enter_actions: ['b0', 'b1'],

    # 变量定义
    vars: [
      { id: 'v1', min: 0, max: 1, defaulValue: 0 },
      { id: 'v2', min: 0, max: 1, defaulValue: 0 },
      { id: 'v3', min: 0, max: 1, defaulValue: 0 },
      { id: 'v4', min: 0, max: 1, defaulValue: 0 },
      { id: 'v5', min: 0, max: 1, defaulValue: 0 },
      { id: 'v6', min: 0, max: 1, defaulValue: 0 },
      { id: 'v7', min: 0, max: 1, defaulValue: 0 },
      { id: 'v8', min: 0, max: 1, defaulValue: 0 },
    ],

    # 动作定义
    actions: [
      { id: 'b0', cmd: 'aside', params: 'p1' },
      { id: 'b1', cmd: 'chat', params: 'c1' },
      { id: 'b2', cmd: 'chat', params: 'c2' },
      { id: 'b3', cmd: 'aside', params: 'p2' },
      { id: 'b4', cmd: 'aside', params: 'p3' },
      { id: 'b5', cmd: 'aside', params: 'p4' },
      { id: 'b6', cmd: 'copper', params: '1' },
      { id: 'b7', cmd: 'aside', params: 'p5' },
      { id: 'b8', cmd: 'wtime', params: '0,10800000' },
      { id: 'b9', cmd: 'aside', params: 'p6' },
      { id: 'b10', cmd: 'copper', params: '-20%' },
      { id: 'b11', cmd: 'aside', params: 'p7' },
      { id: 'b12', cmd: 'scene', params: 'pomiao' },
    ],

    # 对话选项
    chats: [
      #
      { 
        id: 'c1', desc: '这里是经常讨乞的地方', 
        options: [ 
          { title: '【学着大哥乞讨】', click_actions: ['b2'], andVarsOn: ['v1'], andVarsOff: ['v5', 'v7', 'v8'] }, 
          { title: '【观察周围】', click_actions: ['b3'], andVarsOn: ['v2'], andVarsOff: ['v5', 'v7', 'v8'] }, 
          { title: '【再次观察周围】', click_actions: ['b4'], andVarsOn: ['v3'], andVarsOff: ['v5', 'v7', 'v8'] }, 
          { title: '【提问】', click_actions: ['b5'], andVarsOn: ['v4'], andVarsOff: ['v5', 'v7', 'v8'] }, 
          { title: '【继续乞讨】 ', click_actions: ['b6', 'b7', 'b8', 'b1'], andVarsOn: ['v5'], andVarsOff: ['v7', 'v8'], andVarsValue: ['@world_time_hours < 17'] }, 
          { title: '【继续乞讨】 ', click_actions: ['b9'], andVarsOn: ['v5'], andVarsOff: ['v7', 'v8'], andVarsValue: ['@world_time_hours >= 17'] }, 
          { title: '【支付】', click_actions: ['b10', 'b11'], andVarsOn: ['v7'], andVarsOff: ['v8'] }, 
          { title: '今天已经累了，先回去吧', click_actions: ['b12'], andVarsOn: ['v8'] }, 
        ],
      },
      { 
        id: 'c2', desc: '路人露出鄙视的眼神', 
        options: [ 
          { title: '返回', click_actions: ['b1'], varsOn: ['v2'] }, 
        ],
      },
    ],

    # 旁白
    asides: [
      { id: 'p1', style: 2, title: '乞丐李大哥：', sections: ['各位老爷行行好，给点赏赐，大吉大利……'], finish_actions: ['b1'], varsOn: ['v1'], andVarsOff: ['v1'] },
      { id: 'p2', style: 2, sections: ['周围形形色色的人川流而过，各种面孔，大多数人的衣着都还不错，能看出不少人带着行李商品，各种驴车马车偶尔带着商品经过。'], finish_actions: ['b1'], varsOn: ['v3'] },
      { id: 'p3', style: 2, sections: ['能看到不少人带着武器，像是武者的打扮。'], finish_actions: ['b1'], varsOn: ['v4'] },
      { id: 'p4', style: 2, title: '乞丐李大哥：', sections: ['你有没有发现，这里拿兵器的人不少，这是正常的吗。', '因为城镇外野兽精怪出没，这些跑商路的通常会雇佣一些佣兵防身，你看到的这些人估计都是些做这种活计的武者。'], finish_actions: ['b1'], varsOn: ['v5'] },
      { id: 'p5', style: 2, title: '乞丐李大哥', sections: ['如果有两个铜币就够一个包子钱，加油'], finish_actions: ['b1'], varsOn: ['v6'], andVarsOff: ['v6'] },
      { id: 'p6', style: 1, title: '帮派小弟：', sections: ['今日的份子交了吧'], finish_actions: ['b1'], varsOn: ['v7'] },
      { id: 'p7', style: 1, title: '', sections: ['已扣除身上两成的铜币'], finish_actions: ['b1'], varsOn: ['v8'] },
    ],

    # 对话框
    dialogs: [
    ]
  },
]