# ===========================================
# 配置说明：
#   单独一个场景使用{}包围，有效的配置项为：
#     id: 场景ID（整个项目必须唯一）
#
#     name: 场景名称
#
#     vars: 变量定义
#       id: 变量名称
#       min: 变量最小值
#       max: 变量最大值
#       defaultValue: 变量缺省值
#
#     actions: 动作列表
#       id: 动作ID
#       cmd: 命令
#       params: 参数
#
#     chats: 对话选项
#       id:       对话ID
#       desc:     对话框顶部描述
#       options:  选项列表
#         title:  选项名称
#         click_actions: 选项点击事件后触发的动作ID列表
#         andVarsOn:    该选项显示所需判断为ON的变量列表(全匹配) 
#         andVarsOff:   该选项显示所需判断为OFF的变量列表(全匹配)
#         andVarsValue: 该选项显示所需判断值大小的条件列表(全匹配)，
#                       如：varsValue: ['var1 >= 1', 'var1 <= 10']，可支持 ==, >, <, >=, <=, != 运算符。
#         orVarsOn:     该选项显示所需判断为ON的变量列表(匹配任意一个)
#         orVarsOff:    该选项显示所需判断为OFF的变量列表(匹配任意一个)
#         orVarsValue:  该选项显示所需判断值大小的条件列表(匹配任意一个)
#
#     asides: 旁白列表
#       id: 旁白ID
#       style: 风格ID
#       sections: 旁白段落
#       confirm_actions: 旁白结束事件触发的动作ID列表
#
#     dialogs: 对话框列表
#       id: 对话框ID
#       title: 标题
#       content: 内容
#       confirm_actions: 对话框确认按钮点击事件触发的动作ID列表
#
# ===========================================
scenes: [
  # 新手村场景
  {
    id: 'scene2', name: '破庙',

    # 进入场景事件处理动作ID列表
    enter_actions: ['a0'],

    # 变量定义
    vars: [
      { id: 'v1', min: 0, max: 1, defaulValue: 0 },
      { id: 'v2', min: 0, max: 1, defaulValue: 0 },
      { id: 'v3', min: 0, max: 1, defaulValue: 0 },
      { id: 'v4', min: 0, max: 1, defaulValue: 0 },
      { id: 'v5', min: 0, max: 1, defaulValue: 0 },
      { id: 'v6', min: 0, max: 1, defaulValue: 0 },
    ],

    # 动作定义
    actions: [
      { id: 'a0', cmd: 'chat', params: 'c1' },
      { id: 'a1', cmd: 'var',  params: 'v1 = ON' },
      { id: 'a2', cmd: 'var',  params: 'v2 = ON' },
      { id: 'a3', cmd: 'var',  params: 'v3 = ON' },
      { id: 'a4', cmd: 'var',  params: 'v4 = ON' },
      { id: 'a5', cmd: 'var',  params: 'v5 = ON' },
      { id: 'a6', cmd: 'var',  params: 'v6 = ON' },

      { id: 'b1', cmd: 'aside',  params: 'p1' },
      { id: 'b2', cmd: 'aside',  params: 'p2' },
      { id: 'b3', cmd: 'aside',  params: 'p3' },
      { id: 'b4', cmd: 'aside',  params: 'p4' },
      { id: 'b5', cmd: 'aside',  params: 'p5' },
      { id: 'b6', cmd: 'aside',  params: 'p6' },
      { id: 'b7', cmd: 'aside',  params: 'p7' },
      { id: 'b7_test', cmd: 'dialog',  params: 'd1' },
    ],

    # 对话选项
    chats: [
      # 新手对话主列表
      { 
        id: 'c1', desc: '你在一座破庙里面', 
        options: [ 
          { title: '【查看四周】', click_actions: ['b1'] }, 
          { title: '【查看头顶】', click_actions: ['b2'] }, 
          { title: '【动动身子】', click_actions: ['b3'], andVarsOn: ['v1', 'v2'] }, 
          { title: '【看看自己的手】', click_actions: ['b4'], andVarsOn: ['v1', 'v2', 'v3'] }, 
          { title: '【询问周围的乞丐】', click_actions: ['b5'], andVarsOn: ['v1', 'v2', 'v3', 'v4'], andVarsOff: ['v6'] }, 
          { title: '【尝试起身】', click_actions: ['b6'], andVarsOn: ['v1', 'v2', 'v3', 'v4'], andVarsOff: ['v5'] }, 
          # 以下选项在【询问周围的乞丐】&【尝试起身】点击后替换
          { title: '【询问周围的乞丐】', click_actions: ['b7_test'], andVarsOn: ['v1', 'v2', 'v3', 'v4', 'v6'] }, 
          { title: '【尝试起身】', click_actions: ['b7_test'], andVarsOn: ['v1', 'v2', 'v3', 'v4', 'v5'] }, 
        ],
      },
    ],

    # 旁白
    asides: [
      { id: 'p1', style: 2, sections: ['这是一个小破庙，大概不到二十平米，由土垒成，而不是砖建造的这种建筑即使是农村也几乎见不到了。'], confirm_actions: ['a1', 'a0'] },
      { id: 'p2', style: 2, sections: ['破庙的房顶是木头和茅草，有些漏风'], confirm_actions: ['a2', 'a0'] },
      { id: 'p3', style: 2, sections: ['一身酸痛袭来，怎么回事？'], confirm_actions: ['a3', 'a0'] },
      { id: 'p4', style: 2, sections: ['这是一只稚嫩的手，不过脏兮兮的，指甲还有点血丝。'], confirm_actions: ['a4', 'a0'] },
      { id: 'p5', style: 2, sections: ['乞丐在睡觉，没有理你'], confirm_actions: ['a5', 'a0'] },
      { id: 'p6', style: 2, sections: ['动不了'], confirm_actions: ['a6', 'a0'] },
      { id: 'p7', style: 2, sections: ['总得想个办法'], confirm_actions: ['a5', 'a6', 'a0'] },
    ],

    # 对话框
    dialogs: [
      { id: 'd1', title: '对话框标题', content: '对话框内容', confirm_actions: ['a5', 'a6', 'a0'] },
    ]
  }
]