scenes: [
  # 破庙门口场景
  {
    id: 'jishiyijiao', name: '集市一角',

    # 进入场景事件处理动作ID列表
    enterActions: ['b0', 'b1'],

    # 变量定义
    vars: [
      { id: 'v1', min: 0, max: 1, defaulValue: 0 },
      { id: 'v2', min: 0, max: 1, defaulValue: 0 },
      { id: 'v3', min: 0, max: 1, defaulValue: 0 },
      { id: 'v4', min: 0, max: 1, defaulValue: 0 },
      { id: 'v5', min: 0, max: 1, defaulValue: 0 },
      { id: 'v6', min: 0, max: 1, defaulValue: 0 },
      { id: 'v7', min: 0, max: 1, defaulValue: 0 },
      { id: 'v8', min: 0, max: 1, defaulValue: 0 },
      { id: 'v9', min: 0, max: 1, defaulValue: 0 },
      { id: 'v10', min: 0, max: 1, defaulValue: 0 },
      { id: 'v11', min: 0, max: 1, defaulValue: 0 },
      { id: 'v12', min: 0, max: 1, defaulValue: 0 },
      { id: 'v13', min: 0, max: 1, defaulValue: 0 },
    ],

    # 动作定义
    actions: [
      { id: 'b0', cmd: 'aside', params: 'p1' },
      { id: 'b1', cmd: 'chat', params: 'c1' },
      { id: 'b2', cmd: 'chat', params: 'c2' },
      { id: 'b3', cmd: 'aside', params: 'p2' },
      { id: 'b4', cmd: 'aside', params: 'p3' },
      { id: 'b5', cmd: 'aside', params: 'p4' },
      { id: 'b6', cmd: 'copper', params: '1' },
      { id: 'b7', cmd: 'aside', params: 'p5' },
      { id: 'b8', cmd: 'wtime', params: '10800000' },
      { id: 'b9', cmd: 'aside', params: 'p6' },
      { id: 'b10', cmd: 'copper', params: '-20%' },
      { id: 'b11', cmd: 'aside', params: 'p7' },
      { id: 'b12', cmd: 'scene', params: 'pomiao' },
      # 第二天
      { id: 'b13', cmd: 'copper', params: '2' },
      { id: 'b14', cmd: 'wtime', params: '10800000' },
      { id: 'b15', cmd: 'aside', params: 'p8' },
      { id: 'b16', cmd: 'aside', params: 'p9' },
      { id: 'b17', cmd: 'aside', params: 'p10' },
      { id: 'b18', cmd: 'aside', params: 'p11' },
      { id: 'b19', cmd: 'aside', params: 'p12' },
      { id: 'b20', cmd: 'aside', params: 'p13' },
      { id: 'b21', cmd: 'aside', params: 'p14' },
      { id: 'b22', cmd: 'scene', params: 'xizhenminjujie' },
    ],

    # 事件定义
    events: [
      { andVarsOn: ['v9'], andVarsOff: ['v10'], andVarsValue: ['@world_time_hours >= 17'], eventActions: ['b16'],  varsOn: ['v10'] },
    ],

    # 对话选项
    chats: [
      #
      { 
        id: 'c1', desc: '这里是经常讨乞的地方', 
        options: [ 
          # 第一天
          { title: '【学着大哥乞讨】', clickActions: ['b2'], andVarsOn: ['v1'], andVarsOff: ['v5', 'v7', 'v8'] }, 
          { title: '【观察周围】', clickActions: ['b3'], andVarsOn: ['v2'], andVarsOff: ['v5', 'v7', 'v8'] }, 
          { title: '【再次观察周围】', clickActions: ['b4'], andVarsOn: ['v3'], andVarsOff: ['v5', 'v7', 'v8'] }, 
          { title: '【提问】', clickActions: ['b5'], andVarsOn: ['v4'], andVarsOff: ['v5', 'v7', 'v8'] }, 
          { title: '【继续乞讨】 ', clickActions: ['b6', 'b7', 'b8', 'b1'], andVarsOn: ['v5'], andVarsOff: ['v7', 'v8'], andVarsValue: ['@world_time_hours < 17'] }, 
          { title: '【继续乞讨】 ', clickActions: ['b9'], andVarsOn: ['v5'], andVarsOff: ['v7', 'v8'], andVarsValue: ['@world_time_hours >= 17'] }, 
          { title: '【支付】', clickActions: ['b10', 'b11'], andVarsOn: ['v7'], andVarsOff: ['v8'] }, 
          { title: '今天已经累了，先回去吧', clickActions: ['b12'], andVarsOn: ['v8'], andVarsOff: ['v9'], varsOn: ['v9'] }, 
          # 第二天
          { title: '【学着大哥乞讨】', clickActions: ['b13', 'b14', 'b15'], andVarsOn: ['v9'], andVarsOff: ['v10'] }, 
          { title: '【支付】', clickActions: ['b10', 'b18', 'b19'], andVarsOn: ['v11'], andVarsOff: ['v12'], varsOn: ['v12'] }, 
          { title: '【问乞丐哥】', clickActions: ['b20'], andVarsOn: ['v12'], andVarsOff: ['v13'] }, 
          { title: '<<<【西镇居民街】', clickActions: ['b22'], andVarsOn: ['v13'] }, 
        ],
      },
      { 
        id: 'c2', desc: '路人露出鄙视的眼神', 
        options: [ 
          { title: '返回', clickActions: ['b1'], varsOn: ['v2'] }, 
        ],
      },
    ],

    # 旁白
    asides: [
      { id: 'p1', style: 2, title: '乞丐李大哥：', sections: ['各位老爷行行好，给点赏赐，大吉大利……'], finishActions: ['b1'], varsOn: ['v1'], andVarsOff: ['v1'] },
      { id: 'p2', style: 2, sections: ['周围形形色色的人川流而过，各种面孔，大多数人的衣着都还不错，能看出不少人带着行李商品，各种驴车马车偶尔带着商品经过。'], finishActions: ['b1'], varsOn: ['v3'] },
      { id: 'p3', style: 2, sections: ['能看到不少人带着武器，像是武者的打扮。'], finishActions: ['b1'], varsOn: ['v4'] },
      { id: 'p4', style: 2, title: '乞丐李大哥：', sections: ['你有没有发现，这里拿兵器的人不少，这是正常的吗。', '因为城镇外野兽精怪出没，这些跑商路的通常会雇佣一些佣兵防身，你看到的这些人估计都是些做这种活计的武者。'], finishActions: ['b1'], varsOn: ['v5'] },
      { id: 'p5', style: 2, title: '乞丐李大哥', sections: ['如果有两个铜币就够一个包子钱，加油'], finishActions: ['b1'], varsOn: ['v6'], andVarsOff: ['v6'] },
      { id: 'p6', style: 1, title: '帮派小弟：', sections: ['今日的份子交了吧'], finishActions: ['b1'], varsOn: ['v7'] },
      { id: 'p7', style: 1, title: '', sections: ['已扣除身上两成的铜币'], finishActions: ['b1'], varsOn: ['v8'] },
      { id: 'p8', style: 2, title: '', sections: ['获得2个铜币'], finishActions: ['b1'] },
      { id: 'p9', style: 1, title: '', sections: ['帮派小弟来收保护费。'], finishActions: ['b17'] },
      { id: 'p10', style: 2, title: '', sections: ['今日的份子交了吧'], finishActions: ['b1'], varsOn: ['v11'] },
      { id: 'p11', style: 2, title: '', sections: ['已扣除身上两成的铜币', '还是你们识相，我们老大可是真本事，有修为的，你们要是有心，以后可以加入我们帮派。', '帮派小弟离开了。'], finishActions: [], varsOn: [] },
      { id: 'p12', style: 1, title: '', sections: ['有修为是什么意思，难道是武侠，或者是修仙？'], finishActions: ['b1'], varsOn: ['v12'] },
      { id: 'p13', style: 2, title: '乞丐哥：', sections: ['我一个乞丐，哪里知道那么多，估计你要自己去问了，我们吃了上顿没下顿，别想那么多。'], finishActions: ['b21'] },
      { id: 'p14', style: 2, title: '', sections: ['来到这个世界，莫非真做乞丐一辈子？既然到了一个可能有修仙的世界，就一定要打听清楚。'], finishActions: ['b1'], varsOn: ['v13'] },
    ],

    # 对话框
    dialogs: [
    ]
  },
]