# ===========================================
# 战斗挂机配置
# ===========================================
sequences: [
  {
    # 挂机序列ID
    id: 'x1',

    # 所有分组打完后是否循环
    loop: false,

    # 敌方
    enemies: [
      {
        group: 'A',
        items: [
          { 
            uid: 100000, 
            userName: '杂鱼1', 
            skillIds: [1],
            attrs: [
              { key: 'hp', value: 800 },
              { key: 'mp', value: 500 },
              { key: 'speed', value: 80 },
              { key: 'physicalAttack', value: 100 },
              { key: 'physicalDefense', value: 100 },
              { key: 'magicDefense', value: 50 },
            ],
          },
          { 
            uid: 100001, 
            userName: '杂鱼2', 
            skillIds: [1],
            attrs: [
              { key: 'hp', value: 800 },
              { key: 'mp', value: 500 },
              { key: 'speed', value: 80 },
              { key: 'physicalAttack', value: 100 },
              { key: 'physicalDefense', value: 100 },
              { key: 'magicDefense', value: 50 },
            ],
          },
        ]
      },
      {
        group: 'B',
        items: [
          { 
            uid: 100002, 
            userName: '杂鱼3', 
            skillIds: [1],
            attrs: [
              { key: 'hp', value: 800 },
              { key: 'mp', value: 500 },
              { key: 'speed', value: 80 },
              { key: 'physicalAttack', value: 100 },
              { key: 'physicalDefense', value: 100 },
              { key: 'magicDefense', value: 50 },
            ],
          },
          { 
            uid: 100003, 
            userName: '杂鱼4', 
            skillIds: [1],
            attrs: [
              { key: 'hp', value: 800 },
              { key: 'mp', value: 500 },
              { key: 'speed', value: 80 },
              { key: 'physicalAttack', value: 100 },
              { key: 'physicalDefense', value: 100 },
              { key: 'magicDefense', value: 50 },
            ],
          },
        ]
      },
    ],

    # 奖励列表
    awards: {
      # 总共有效时间(单位秒)
      expire: 60,

      # 物品列表
      items: [
        { uid: [100000, 100001], propId: 20, num: 1 },
        { uid: [100001], propId: 51, num: 1 },
        { uid: [100001], propId: 24, num: 2 },
        { uid: [100001], propId: 2, num: 2  },
        { uid: [100000, 100001], propId: 36, num: 1 },
      ]
    },
  },
]