# ===========================================
# 战斗挂机配置
# ===========================================
sequences: [
  {
    # 挂机序列ID
    id: 'explore',

    # 所有分组打完后是否循环
    loop: false,

    # 敌方
    enemies: [
      {
        group: 'A',
        items: [
          { 
            uid: 100000, 
            userName: '娜扎', 
            skillIds: [1],
            attrs: [
              { key: 'hp', value: 500 },
              { key: 'mp', value: 500 },
              { key: 'speed', value: 80 },
              { key: 'shield', value: 200 },
              { key: 'physicalAttack', value: 5 },
              { key: 'physicalDefense', value: 5 },
              { key: 'magicDefense', value: 5 },
            ],
          },
        ]
      },
      {
        group: 'B',
        items: [
          { 
            uid: 100001, 
            userName: '灰太狼', 
            skillIds: [1],
            attrs: [
              { key: 'hp', value: 500 },
              { key: 'mp', value: 500 },
              { key: 'speed', value: 80 },
              { key: 'shield', value: 200 },
              { key: 'physicalAttack', value: 5 },
              { key: 'physicalDefense', value: 5 },
              { key: 'magicDefense', value: 5 },
            ],
          },
        ]
      },
    ],

    # 奖励列表
    awards: {
      # 总共有效时间(单位秒)
      expire: 60,

      # 物品列表
      items: [
        { uid: [100001, 100002], propId: 20, num: 1 },
      ]
    }
  },
]