# ===========================================
# 商店配置
# ===========================================
shops: [
   {
      id: 'default',

      name: '白城商铺',

      # CD刷新周期，单位秒
      cdValue: 0,

      # 商城道具购买列表
      buy_list: [
         { 
            # 道具ID
            propId: 350,
            # 刷新概率设定
            rates : {
               p100: [ { num: 1, rate: 100 }, { num: 1, rate: 100 } ],
               # p1000: [ { num: 30, rate: 200 }, { num: 40, rate: 300 } ],
               # p10000: [ { num: 50, rate: 800 } ],
            },
            # 消耗设定
            consume: [
               { propId: 887, num: 1 },
            ]
         },
      ]
   },
    {
      id: 'shop_sell_test_1',

      name: '白城首饰商铺',

      # 商城道具出售列表
      sell_list: [
         { 
            # 道具ID
            propId: 1011,
         },
      ]
   },

   {
      id: 'shop2',

      name: '白城首饰商铺',

      # CD刷新周期，单位秒
      cdValue: 300,

      # 商城道具购买列表
      buy_list: [
         { 
            # 道具ID
            propId: 1,
            # 刷新概率设定
            rates : {
               p100: [ { num: 10, rate: 20 }, { num: 20, rate: 80 } ],
               # p1000: [ { num: 30, rate: 200 }, { num: 40, rate: 300 } ],
               # p10000: [ { num: 50, rate: 800 } ],
            },
            # 消耗设定
            consume: [
               { propId: 887, num: 1 },
            ]
         },
         { 
            # 道具ID
            propId: 2,
            # 刷新概率设定
            rates : {
               p100: [ { num: 10, rate: 20 }, { num: 20, rate: 80 } ],
               # p1000: [ { num: 30, rate: 200 }, { num: 40, rate: 300 } ],
               # p10000: [ { num: 50, rate: 800 } ],
            },
            # 消耗设定
            consume: [
               { propId: 887, num: 10 },
            ]
         },
      ]
   },

   {
      id: 'shop_sell_test',

      name: '白城首饰商铺',

      # 商城道具出售列表
      sell_list: [
         { 
            # 道具ID
            propId: 1,
         },
         { 
            # 道具ID
            propId: 2,
         },
      ]
   }
]