# ===========================================
# 商店配置
# ===========================================
shop: {
   # CD刷新周期，单位秒
   cdValue: 300,

   # 商城道具列表
   list: [
      { 
         # 道具ID
         propId: 1,
         # 刷新概率设定
         rates : {
            p100: [ { num: 10, rate: 20 }, { num: 20, rate: 80 } ],
            p1000: [ { num: 30, rate: 200 }, { num: 40, rate: 300 } ],
            p10000: [ { num: 50, rate: 800 } ],
         },
         # 消耗设定
         consume: [
            { propId: 200, num: 1 },
         ]
      },

      { 
         # 道具ID
         propId: 2,
         # 刷新概率设定
         rates : {
            p100: [ { num: 10, rate: 20 }, { num: 20, rate: 80 } ],
            p1000: [ { num: 30, rate: 200 }, { num: 40, rate: 300 } ],
            p10000: [ { num: 50, rate: 800 } ],
         },
         # 消耗设定
         consume: [
            { propId: 200, num: 2 },
         ]
      },
   ]
}