# ===========================================
# 技能配置
# ===========================================
skills: [
   {
      # 技能唯一ID 
      id: 1,

      # 图标ID
      iconId: 1,

      # 技能名称
      name: '冷月剑',

      # 描述
      desc: '(物理攻击X120) + 120伤害',

      # 计算公式
      formula: '(A_物理攻击 - D_物理防御) * 1.2 + 120',

      # 效果列表
      effects: [],

   },
   {
      # 技能唯一ID 
      id: 2,

      # 图标ID
      iconId: 1,

      # 技能名称
      name: '锻体决',

      # 计算公式
      formula: 'A_物理防御 * 1.1 + 200',

      # 效果列表
      effects: [],

   },
   {
      # 技能唯一ID 
      id: 3,

      # 图标ID
      iconId: 1,

      # 技能名称
      name: '护身罡气',

      # 伤害计算公式
      formula: '物理防御(+400)',

      # 效果列表
      effects: [],

   },
   {
      # 技能唯一ID 
      id: 4,

      # 图标ID
      iconId: 1,

      # 技能名称
      name: '风意剑',

      # 伤害计算公式
      formula: 'a.atk * 4 - b.def * 2',

      # 效果列表
      effects: [],

   },
   {
      # 技能唯一ID 
      id: 5,

      # 图标ID
      iconId: 1,

      # 技能名称
      name: '微光盾',

      # 伤害计算公式
      formula: 'a.atk * 4 - b.def * 2',

      # 效果列表
      effects: [],

   },
]