# ===========================================
# 技能配置
# ===========================================
skills: [
   {
      # 技能唯一ID 
      id: 1,

      # 图标ID
      iconId: 1,

      # 技能名称
      name: '冷月剑',

      # 描述
      desc: '',

      # 影响公式
      formula: '伤害 = (A_物理攻击 - D_物理防御) * 1.2 + 120',

      # 效果列表
      effects: [],
   },
   {
      # 技能唯一ID 
      id: 2,

      # 图标ID
      iconId: 1,

      # 技能名称
      name: '锻体决',

      # 描述
      desc: '',

      # 被动
      passive: true,
   
      # 影响公式
      formula: '',

      # 效果列表
      effects: [
         { buffId: 1, groupId: 1 },
      ],
   },
   {
      # 技能唯一ID 
      id: 3,

      # 图标ID
      iconId: 1,

      # 技能名称
      name: '护身罡气',

      # 描述
      desc: '',

      # 被动
      passive: true,

      # 影响公式
      formula: '',

      # 效果列表
      effects: [
         { buffId: 2, groupId: 1 },
      ],
   },
   {
      # 技能唯一ID 
      id: 4,

      # 图标ID
      iconId: 1,

      # 技能名称
      name: '风意剑',

      # 描述
      desc: '',

      # 影响公式
      formula: '伤害 = (A_法术攻击 - D_法术防御) * 1.2 + 300',

      # 消耗法力
      useMP: 30,

      # 效果列表
      effects: [],
   },
   {
      # 技能唯一ID 
      id: 5,

      # 图标ID
      iconId: 1,

      # 技能名称
      name: '微光盾',

      # 描述
      desc: '',

      # 被动
      passive: true,

      # 影响公式
      formula: '',

      # 消耗法力
      useMP: 50,

      # 效果列表
      effects: [
         { buffId: 3, groupId: 2 },
      ],
   },
]