# ============================
# 小宇宙项目 配置
# ============================
# mainAttrs: 主属性
# levelConfig: 主属性等级配置
# grade: 等级
# needProps: 升级需求道具
# subAttrs: 副属性

data: {

  # 总等级
  overallGrade: 14,

  # 副属性
  allSubAttrs: [
    { key: "实力", name: "实力" },
    { key: "主炮", name: "主炮" },
    { key: "装甲", name: "装甲" },
  ],

  # 主属性
  mainAttrs: [
    # ===== 1 ======
    {
      iconId: 1,
      quality: 1,
      name: '画面',
      desc: "主力输出",
      props: [
        { key: "灵感钥匙", propId: 369,},
       
      ],
      levelConfig: [
        { grade: 1, subAttrs: ['实力,100','主炮,100'], needProps: ['灵感钥匙,1'] },
        { grade: 2, subAttrs: ['实力,200','主炮,200'], needProps: ['灵感钥匙,1'] },
        { grade: 3, subAttrs: ['实力,300','主炮,300'], needProps: ['灵感钥匙,1'] },
        { grade: 4, subAttrs: ['实力,400','主炮,400'], needProps: ['灵感钥匙,1'] },
        { grade: 5, subAttrs: ['实力,500','主炮,500'], needProps: ['灵感钥匙,1'] },
   
      ],
    },

    # ===== 2 ======
    {
      iconId: 1,
      quality: 1,
      name: '剧情',
      desc: "主要防御",
      props: [
        { key: "灵感钥匙", propId: 369,},
      ],
      levelConfig: [
        { grade: 1, subAttrs: ['实力,100','装甲,100'], needProps: ['灵感钥匙,1']},
        { grade: 2, subAttrs: ['实力,200','装甲,200'], needProps: ['灵感钥匙,1'] },
        { grade: 3, subAttrs: ['实力,300','装甲,300'], },
      ],
    },

    # ===== 3 ======
    {
      iconId: 1,
      quality: 1,
      name: '细节',
      desc: "主要防御",
      props: [
       { key: "灵感钥匙", propId: 369,},
      ],
      levelConfig: [
        { grade: 1, subAttrs: ['实力,100','主炮,100'], needProps: ['灵感钥匙,1']},
        { grade: 2, subAttrs: ['实力,200','主炮,200'], needProps: ['灵感钥匙,1'] },
        { grade: 3, subAttrs: ['实力,300','主炮,300'], },
      ],
    },

    # ===== 4 ======
    {
      iconId: 1,
      quality: 1,
      name: '操作',
      desc: "主要防御",
      props: [
        { key: "灵感钥匙", propId: 369,},
      ],
      levelConfig: [
        { grade: 1, subAttrs: ['实力,100','主炮,100'], needProps: ['灵感钥匙,1'] },
        { grade: 2, subAttrs: ['实力,200','主炮,200'], needProps: ['灵感钥匙,1'] },
        { grade: 3, subAttrs: ['实力,300','主炮,300'], },
      ],
    },
    
  ],
}
