#
#  routeName: 导航栏切换的路径名称
#  soundId: 音乐音效ID
#  bgm: 是否为背景音乐，不指定为音效
#  seek: 跳开多少秒
#

sound: [
    # 首页
    { routeName: 'First', soundId: 'BGM00001', seek: 20 },
    # 设置页
    { routeName: 'Profile', soundId: 'BGM00002' },
    # 道具页
    { routeName: 'Props', soundId: 'BGM00003' },
    # 制作页
    { routeName: 'Compose', soundId: 'BGM00004' },
    # 城镇页
    { routeName: 'Town', soundId: 'BGM00005' },
    # 世界页
    { routeName: 'World', soundId: 'BGM00006' },
    # 阅读器默认
    { routeName: 'Article', soundId: 'BGM00003' },
]