# ================== 
# 翻格子配置
# ==================
#
# x,y: 坐标
# status: 0-不可翻开 || 1-可翻开 || 2-已翻开 , status 不配置时默认为 0
# type: "入口" || "出口" || "道具" || "空" || "墙" || "事件", type 不配置时默认为 "空"

# ===== 道具格子 配置
# { type: "道具", prop: { id: 30, num: 1, iconId: 1, quality: 1, } }

# ===== 事件 配置
# toScene, 只需要在 action 中直接配置 toScene: "XXX"
#  type: "事件", action: { toScene: 'C000A_V2_MAP_3_1' }
#
# toChapter, 只需要在 action 中直接配置 toChapter: "XXX"
#  type: "事件", action: { toChapter: "WZXX_M1_N1_C001B" } 
#
# dialogs, 需要配置对应的 sceneId 和 dialog 的ID, 如果要离开  翻格子游戏,则要在对应的 按钮 中配置 closeTurnLattice: true
# type: "事件", action: { sceneId: 'WZXX_M1_N1_C001V' ,dialogs: ['Screen1'] }

# 事件类型: ( 宝箱 | 出口 | 入口 | 战斗 | 剧情 | 位子提示 | 道具)


latticeMaze: [
  ##== 航海探索 副本
  {
    latticeMazeId: "航海探索",
    desc: "海上探索",
    # 解锁道具 前面的‘1’代表道具ID 后面的‘1’代表数量
    unlockProps: ['1,1'],
    # 消耗道具
    consumableProps: ['2,1'],
    data: [
      # --- 第一层
      {
        id: 1,
        # 行
        row: 10,
        # 列
        column: 0,
        # 背景图片ID
        img: 0,
        # 事件数据
        eventData : [
          # 事件1怪物
          # 事件2怪物
          # 事件3宝箱
          # 事件4怪物
          # 事件5宝箱
          
          {
            id: "1",
            type: "战斗",
            challenge: 'x4',
            # BOSS 图标ID
            bossIconId: 1,
            afterEventId: "2",
          },

          {
            id: "2",
            type: "战斗",
            challenge: 'x5',
            # BOSS 图标ID
            bossIconId: 1,
            afterEventId: "2",
          },

          {
            id: "3",
            type: "宝箱",
            treasureChestId: 2,
          },
          # 明天优先配置几个战斗系统，把战斗配置完之后，大概结束第一层的配置 继续画图 宝箱的礼品配置，根据剧情来定。

          {
            id: "4",
            type: "战斗",
            challenge: 'x6',
            # BOSS 图标ID
            bossIconId: 1,
            afterEventId: "2",
          },
        ],
        config: [
          { x: 0, y: 0, type: "墙", }, { x: 1, y: 0, }, { x: 2, y: 0, }, { x: 3, y: 0, }, { x: 4, y: 0, }, { x: 5, y: 0, },{ x: 6, y: 0, },{ x: 7, y: 0, },{ x: 8, y: 0, },{ x: 9, y: 0, },
          { x: 0, y: 1, type: "墙", }, { x: 1, y: 1, }, { x: 2, y: 1, }, { x: 3, y: 1, }, { x: 4, y: 1, }, { x: 5, y: 1, },{ x: 6, y: 1, },{ x: 7, y: 1, },{ x: 8, y: 1, },{ x: 9, y: 1, },
          { x: 0, y: 2, type: "墙", }, { x: 1, y: 2, }, { x: 2, y: 2, }, { x: 3, y: 2, }, { x: 4, y: 2, }, { x: 5, y: 2, },{ x: 6, y: 2, },{ x: 7, y: 2, },{ x: 8, y: 2, },{ x: 9, y: 2, },
          { x: 0, y: 3, type: "墙", }, { x: 1, y: 3, }, { x: 2, y: 3, type: "事件", eventId: "4"}, { x: 3, y: 3, }, { x: 4, y: 3, }, { x: 5, y: 3, },{ x: 6, y: 3, },{ x: 7, y: 3, },{ x: 8, y: 3, },{ x: 9, y: 3, },
          { x: 0, y: 4, type: "墙", }, { x: 1, y: 4, }, { x: 2, y: 4, }, { x: 3, y: 4, }, { x: 4, y: 4, }, { x: 5, y: 4, },{ x: 6, y: 4, },{ x: 7, y: 4, },{ x: 8, y: 4, },{ x: 9, y: 4, },
          { x: 0, y: 5, type: "墙", }, { x: 1, y: 5, }, { x: 2, y: 5, }, { x: 3, y: 5, }, { x: 4, y: 5, }, { x: 5, y: 5, },{ x: 6, y: 5, },{ x: 7, y: 5, },{ x: 8, y: 5, },{ x: 9, y: 5, },
          { x: 0, y: 6, type: "墙", }, { x: 1, y: 6, type: "事件", eventId: "3"}, { x: 2, y: 6, }, { x: 3, y: 6, }, { x: 4, y: 6, }, { x: 5, y: 6, },{ x: 6, y: 6, },{ x: 7, y: 6, },{ x: 8, y: 6, },{ x: 9, y: 6, },
          { x: 0, y: 7, type: "墙", }, { x: 1, y: 7, }, { x: 2, y: 7, }, { x: 3, y: 7, }, { x: 4, y: 7, }, { x: 5, y: 7, },{ x: 6, y: 7, },{ x: 7, y: 7, },{ x: 8, y: 7, },{ x: 9, y: 7, },
          { x: 0, y: 8, type: "墙", }, { x: 1, y: 8, }, { x: 2, y: 8, type: "事件", eventId: "1" }, { x: 3, y: 8, }, { x: 4, y: 8, }, { x: 5, y: 8, },{ x: 6, y: 8, },{ x: 7, y: 8, },{ x: 8, y: 8, },{ x: 9, y: 8, },
          { x: 0, y: 9, type: "墙", }, { x: 1, y: 9, type: "入口", }, { x: 2, y: 9, }, { x: 3, y: 9, type: "出口", keyPropId: 30, }, { x: 4, y: 9, }, { x: 5, y: 9, },{ x: 6, y: 9, },{ x: 7, y: 9, },{ x: 8, y: 9, },{ x: 9, y: 9, },

          # { x: 0, y: 0, type: "墙", }, { x: 1, y: 0, }, { x: 2, y: 0, }, { x: 3, y: 0, }, { x: 4, y: 0, }, { x: 5, y: 0, },{ x: 6, y: 0, },{ x: 7, y: 0, },{ x: 8, y: 0, },{ x: 9, y: 0, },
          # { x: 0, y: 1, type: "墙", }, { x: 1, y: 1, }, { x: 2, y: 1, }, { x: 3, y: 1, }, { x: 4, y: 1, }, { x: 5, y: 1, },{ x: 6, y: 1, },{ x: 7, y: 1, },{ x: 8, y: 1, },{ x: 9, y: 1, },
          # { x: 0, y: 2, type: "墙", }, { x: 1, y: 2, }, { x: 2, y: 2, }, { x: 3, y: 2, }, { x: 4, y: 2, }, { x: 5, y: 2, },{ x: 6, y: 2, },{ x: 7, y: 2, },{ x: 8, y: 2, },{ x: 9, y: 2, },
          # { x: 0, y: 3, type: "墙", }, { x: 1, y: 3, }, { x: 2, y: 3, }, { x: 3, y: 3, }, { x: 4, y: 3, }, { x: 5, y: 3, },{ x: 6, y: 3, },{ x: 7, y: 3, },{ x: 8, y: 3, },{ x: 9, y: 3, },
          # { x: 0, y: 4, type: "墙", }, { x: 1, y: 4, }, { x: 2, y: 4, }, { x: 3, y: 4, }, { x: 4, y: 4, }, { x: 5, y: 4, },{ x: 6, y: 4, },{ x: 7, y: 4, },{ x: 8, y: 4, },{ x: 9, y: 4, },
          # { x: 0, y: 5, type: "墙", }, { x: 1, y: 5, }, { x: 2, y: 5, }, { x: 3, y: 5, }, { x: 4, y: 5, }, { x: 5, y: 5, },{ x: 6, y: 5, },{ x: 7, y: 5, },{ x: 8, y: 5, },{ x: 9, y: 5, },
          # { x: 0, y: 6, type: "墙", }, { x: 1, y: 6, }, { x: 2, y: 6, type: "事件", action: { toScene: 'C000A_V2_MAP_3_1' }}, { x: 3, y: 6, }, { x: 4, y: 6, }, { x: 5, y: 6, },{ x: 6, y: 6, },{ x: 7, y: 6, },{ x: 8, y: 6, },{ x: 9, y: 6, },
          # { x: 0, y: 7, type: "墙", }, { x: 1, y: 7, type: "道具", prop: { id: 30, num: 1, iconId: 1, quality: 1, } }, { x: 2, y: 7, }, { x: 3, y: 7, }, { x: 4, y: 7, }, { x: 5, y: 7, },{ x: 6, y: 7, },{ x: 7, y: 7, },{ x: 8, y: 7, },{ x: 9, y: 7, },
          # { x: 0, y: 8, type: "墙", }, { x: 1, y: 8, }, { x: 2, y: 8, type: "事件", action: { toChapter: "WZXX_M1_N1_C001B" } }, { x: 3, y: 8, }, { x: 4, y: 8, }, { x: 5, y: 8, },{ x: 6, y: 8, },{ x: 7, y: 8, },{ x: 8, y: 8, },{ x: 9, y: 8, },
          # { x: 0, y: 9, type: "墙", }, { x: 1, y: 9, type: "入口", }, { x: 2, y: 9, type: "事件", action: { sceneId: 'WZXX_M1_N1_C001V' ,dialogs: ['Screen1'] } }, { x: 3, y: 9, type: "出口", }, { x: 4, y: 9, }, { x: 5, y: 9, },{ x: 6, y: 9, },{ x: 7, y: 9, },{ x: 8, y: 9, },{ x: 9, y: 9, },
        ]
      },
      # --- 第二层
      {
        id: 2,
        row: 10,
        column: 10,
        img: 0,
        eventData : [
          {
            id: "1",
            type: "道具",
            prop: { id: 30, num: 1,},
            beforeEventId: "2",
            afterEventId: "2",
          },
          {
            id: "2",
            type: "剧情",
            style: 10, 
            textAnimationType: 'TextSingle',
            sections: [
              { figureId: "01", location: "right", content: ['“大爷你好。”', ], },
              { figureId: "02", location: "left", content: ['“你好。”',], },
              { figureId: "01", location: "right", content: ['“大爷你知道黄心叶、百络花、子星草这些东西在哪吗？”',], },
            ],
          },
          {
            id: "3",
            type: "宝箱",
            treasureChestId: 2,
          },
          {
            id: "4",
            type: "战斗",
            challenge: 'x1',
            # boss图标ID
            bossIconId: 1,
            afterEventId: "2",
          },
        ],
        config: [
          { x: 0, y: 0, type: "墙", }, { x: 1, y: 0, }, { x: 2, y: 0, }, { x: 3, y: 0, }, { x: 4, y: 0, }, { x: 5, y: 0, },{ x: 6, y: 0, },{ x: 7, y: 0, },{ x: 8, y: 0, },{ x: 9, y: 0, },
          { x: 0, y: 1, type: "墙", }, { x: 1, y: 1, }, { x: 2, y: 1, }, { x: 3, y: 1, }, { x: 4, y: 1, }, { x: 5, y: 1, },{ x: 6, y: 1, },{ x: 7, y: 1, },{ x: 8, y: 1, },{ x: 9, y: 1, },
          { x: 0, y: 2, type: "墙", }, { x: 1, y: 2, }, { x: 2, y: 2, }, { x: 3, y: 2, }, { x: 4, y: 2, }, { x: 5, y: 2, },{ x: 6, y: 2, },{ x: 7, y: 2, },{ x: 8, y: 2, },{ x: 9, y: 2, },
          { x: 0, y: 3, type: "墙", }, { x: 1, y: 3, }, { x: 2, y: 3, type: "事件", eventId: "4"}, { x: 3, y: 3, }, { x: 4, y: 3, }, { x: 5, y: 3, },{ x: 6, y: 3, },{ x: 7, y: 3, },{ x: 8, y: 3, },{ x: 9, y: 3, },
          { x: 0, y: 4, type: "墙", }, { x: 1, y: 4, }, { x: 2, y: 4, }, { x: 3, y: 4, }, { x: 4, y: 4, }, { x: 5, y: 4, },{ x: 6, y: 4, },{ x: 7, y: 4, },{ x: 8, y: 4, },{ x: 9, y: 4, },
          { x: 0, y: 5, type: "墙", }, { x: 1, y: 5, }, { x: 2, y: 5, }, { x: 3, y: 5, }, { x: 4, y: 5, }, { x: 5, y: 5, },{ x: 6, y: 5, },{ x: 7, y: 5, },{ x: 8, y: 5, },{ x: 9, y: 5, },
          { x: 0, y: 6, type: "墙", }, { x: 1, y: 6, type: "事件", eventId: "3"}, { x: 2, y: 6, }, { x: 3, y: 6, }, { x: 4, y: 6, }, { x: 5, y: 6, },{ x: 6, y: 6, },{ x: 7, y: 6, },{ x: 8, y: 6, },{ x: 9, y: 6, },
          { x: 0, y: 7, type: "墙", }, { x: 1, y: 7, }, { x: 2, y: 7, }, { x: 3, y: 7, }, { x: 4, y: 7, }, { x: 5, y: 7, },{ x: 6, y: 7, },{ x: 7, y: 7, },{ x: 8, y: 7, },{ x: 9, y: 7, },
          { x: 0, y: 8, type: "墙", }, { x: 1, y: 8, }, { x: 2, y: 8, type: "事件", eventId: "1" }, { x: 3, y: 8, }, { x: 4, y: 8, }, { x: 5, y: 8, },{ x: 6, y: 8, },{ x: 7, y: 8, },{ x: 8, y: 8, },{ x: 9, y: 8, },
          { x: 0, y: 9, type: "墙", }, { x: 1, y: 9, type: "入口", }, { x: 2, y: 9, }, { x: 3, y: 9, }, { x: 4, y: 9, }, { x: 5, y: 9, },{ x: 6, y: 9, },{ x: 7, y: 9, },{ x: 8, y: 9, },{ x: 9, y: 9, },
        ]
      },
    ]
  },

  ##== XXX 副本
]


### ======== 模版 10 x 10

#  { x: 0, y: 0, }, { x: 1, y: 0, }, { x: 2, y: 0, }, { x: 3, y: 0, }, { x: 4, y: 0, }, { x: 5, y: 0, },{ x: 6, y: 0, },{ x: 7, y: 0, },{ x: 8, y: 0, },{ x: 9, y: 0, },
#  { x: 0, y: 1, }, { x: 1, y: 1, }, { x: 2, y: 1, }, { x: 3, y: 1, }, { x: 4, y: 1, }, { x: 5, y: 1, },{ x: 6, y: 1, },{ x: 7, y: 1, },{ x: 8, y: 1, },{ x: 9, y: 1, },
#  { x: 0, y: 2, }, { x: 1, y: 2, }, { x: 2, y: 2, }, { x: 3, y: 2, }, { x: 4, y: 2, }, { x: 5, y: 2, },{ x: 6, y: 2, },{ x: 7, y: 2, },{ x: 8, y: 2, },{ x: 9, y: 2, },
#  { x: 0, y: 3, }, { x: 1, y: 3, }, { x: 2, y: 3, }, { x: 3, y: 3, }, { x: 4, y: 3, }, { x: 5, y: 3, },{ x: 6, y: 3, },{ x: 7, y: 3, },{ x: 8, y: 3, },{ x: 9, y: 3, },
#  { x: 0, y: 4, }, { x: 1, y: 4, }, { x: 2, y: 4, }, { x: 3, y: 4, }, { x: 4, y: 4, }, { x: 5, y: 4, },{ x: 6, y: 4, },{ x: 7, y: 4, },{ x: 8, y: 4, },{ x: 9, y: 4, },
#  { x: 0, y: 5, }, { x: 1, y: 5, }, { x: 2, y: 5, }, { x: 3, y: 5, }, { x: 4, y: 5, }, { x: 5, y: 5, },{ x: 6, y: 5, },{ x: 7, y: 5, },{ x: 8, y: 5, },{ x: 9, y: 5, },
#  { x: 0, y: 6, }, { x: 1, y: 6, }, { x: 2, y: 6, }, { x: 3, y: 6, }, { x: 4, y: 6, }, { x: 5, y: 6, },{ x: 6, y: 6, },{ x: 7, y: 6, },{ x: 8, y: 6, },{ x: 9, y: 6, },
#  { x: 0, y: 7, }, { x: 1, y: 7, }, { x: 2, y: 7, }, { x: 3, y: 7, }, { x: 4, y: 7, }, { x: 5, y: 7, },{ x: 6, y: 7, },{ x: 7, y: 7, },{ x: 8, y: 7, },{ x: 9, y: 7, },
#  { x: 0, y: 8, }, { x: 1, y: 8, }, { x: 2, y: 8, }, { x: 3, y: 8, }, { x: 4, y: 8, }, { x: 5, y: 8, },{ x: 6, y: 8, },{ x: 7, y: 8, },{ x: 8, y: 8, },{ x: 9, y: 8, },
#  { x: 0, y: 9, }, { x: 1, y: 9, }, { x: 2, y: 9, }, { x: 3, y: 9, }, { x: 4, y: 9, }, { x: 5, y: 9, },{ x: 6, y: 9, },{ x: 7, y: 9, },{ x: 8, y: 9, },{ x: 9, y: 9, },
