# ==================
# 翻格子配置
# ==================
#
# x,y: 坐标
# status: 0-不可翻开 || 1-可翻开 || 2-已翻开 , status 不配置时默认为 0
# type: "入口" || "出口" || "道具" || "空" || "墙" || "事件", type 不配置时默认为 "空"

# ===== 道具格子 配置
# { type: "道具", prop: { id: 30, num: 1, iconId: 1, quality: 1, } }

# ===== 事件 配置
# toScene, 只需要在 action 中直接配置 toScene: "XXX"
#  type: "事件", action: { toScene: 'C000A_V2_MAP_3_1' }
#
# toChapter, 只需要在 action 中直接配置 toChapter: "XXX"
#  type: "事件", action: { toChapter: "WZXX_M1_N1_C001B" }
#
# dialogs, 需要配置对应的 sceneId 和 dialog 的ID, 如果要离开  翻格子游戏,则要在对应的 按钮 中配置 closeTurnLattice: true
# type: "事件", action: { sceneId: 'WZXX_M1_N1_C001V' ,dialogs: ['Screen1'] }

# 事件类型: ( 宝箱 | 出口 | 入口 | 战斗 | 剧情 | 位子提示 | 道具)

latticeMaze: [
    ##== 航海探索 副本
    {
      latticeMazeId: "航海探索",
      desc: "海上探索",
      # 解锁道具 前面的‘1’代表道具ID 后面的‘1’代表数量
      unlockProps: ["1,1"],
      # 消耗道具
      consumableProps: ["2,1"],
      data: [
          # --- 第一层
          {
            id: 1,
            # 行
            row: 9,
            # 列
            column: 9,
            # 背景图片ID
            img: 0,
            # 事件数据
            eventData: [
                # afterEventId: "2",
                #铁剑
                { id: "1", type: "宝箱",
                 treasureChestId: 3
                },

                # afterEventId: "2",
                #出洞窟的钥匙
                { id: "2", type: "宝箱",
                beforeEventId: "3",
                treasureChestId: 4 ,
                afterEventId: "4", },

                {
                 id: '3', style: 13, title: '山洞石窟', imgName: "BGT_165",
                 sections: {
                 content: '左边的洞口看起来比较狭窄，应该能够同时容纳两个人，李森炎犹豫了一下后，选择了左边看起来较大的洞口。一具死去多时的骸骨，几乎只剩下白花花的骨头，不过骸骨的破衣上似乎藏了些东西。',
                  btn: [
                   { title: '观察结束', nextChat: 'C1' },
                  ]
                },
                },

                {
                  id: "4",
                  iconId: 100,
                  type: "剧情",
                  style: 5,
                  textAnimationType: "TextSingle",
                  sections:
                    [
                      {
                        type: "TopToBottom",
                        bgImageId: 11,
                        loop: true,
                        play: true,
                        content:
                          [
                            "李森炎穿过林子，顺着小径往里穿行，他的凌云步越来越精炼了，就算在这种密林之中也能如履平地，穿梭自由。",
                            "就当他踏着凌云步赶路的时候，他忽然发现一处山林中隐藏着一个洞窟。",
                            "看着这个隐蔽的洞窟，李森炎不由迟疑了一下。",
                            "“有人进入的痕迹...”",
                            "“看来里面应该有好东西。”",
                            "李森炎看了看这洞窟入口，很快就发现有人进入过这个洞窟，而且看起来进去的人可不少。",
                            "既然有人进去这个洞窟，那这个地方显然有好东西了，不然根本没有人会做这种多余的事情。",
                            "想到这里，他也是搓了搓手小心翼翼地走进了这个洞窟。",
                            "洞窟内看起来有点阴暗，不过李森炎点亮耀光符后，这洞窟很快就明亮了起来。",
                            "他沿着洞窟缓缓地前行，很快就来到了一个分叉洞口。",
                            "这分叉洞口通往了三个不同的方向。",
                          ],
                      },
                    ],
                },

                 { 
                id: '5',style: 6, title: '人脸蜘蛛', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
                sections: [
                {
                key: 'P2', 
                content: ['他也没有在这里停留太久，继续沿着这通道缓缓前行。',
                '“滋滋滋...”', '听到这诡异的声响后，李森炎也是立刻警惕了起来。',
                '很快一只诡异的生物便出现在他眼前。','他皱了下眉头，这是个什么玩意？为什么还张着一张人脸？',
                '这生物有半个人大小，浑身布满白色绒毛，身上八根蛛矛尖锐异常，凶悍并且行动迅猛，头上顶着一张人脸，那张人脸泛着疯狂而怪异的神采，裂开嘴发出怪异的笑声，直让人觉得汗毛倒竖，脊背发凉。',
                ],
                btn: [
                  {
                  title: '准备战斗',
                  toScene: 'S_00Test03',
                  },
                 ]
                },
                 ]  
                }, 
              ],
            config:
              [
              { "x": 0, "y": 0 },{ "x": 1, "y": 0, "keyPropId": 373, "type": "出口" , },{ "x": 2, "y": 0 },{ "x": 3, "y": 0 },{ "x": 4, "y": 0 },{ "x": 5, "y": 0 },{ "x": 6, "y": 0, "type": "墙" },{ "x": 7, "y": 0, "eventId": "5", "type": "事件" },{ "x": 8, "y": 0 },
              { "x": 0, "y": 1 },{ "x": 1, "y": 1 },{ "x": 2, "y": 1 },{ "x": 3, "y": 1 },{ "x": 4, "y": 1 },{ "x": 5, "y": 1 },{ "x": 6, "y": 1, "type": "墙" },{ "x": 7, "y": 1 },{ "x": 8, "y": 1 },
              { "x": 0, "y": 2 },{ "x": 1, "y": 2 },{ "x": 2, "y": 2 },{ "x": 3, "y": 2, "eventId": "3", "type": "事件" },{ "x": 4, "y": 2 },{ "x": 5, "y": 2 },{ "x": 6, "y": 2, "type": "墙" },{ "x": 7, "y": 2 },{ "x": 8, "y": 2 },
              { "x": 0, "y": 3 },{ "x": 1, "y": 3 },{ "x": 2, "y": 3 },{ "x": 3, "y": 3 },{ "x": 4, "y": 3 },{ "x": 5, "y": 3 },{ "x": 6, "y": 3, "type": "墙" },{ "x": 7, "y": 3 },{ "x": 8, "y": 3 },
              { "x": 0, "y": 4 },{ "x": 1, "y": 4, "eventId": "2", "type": "事件" },{ "x": 2, "y": 4 },{ "x": 3, "y": 4 },{ "x": 4, "y": 4 },{ "x": 5, "y": 4, "type": "墙" },{ "x": 6, "y": 4, "type": "墙" },{ "x": 7, "y": 4 },{ "x": 8, "y": 4 },
              { "x": 0, "y": 5 },{ "x": 1, "y": 5 },{ "x": 2, "y": 5 },{ "x": 3, "y": 5 },{ "x": 4, "y": 5 },{ "x": 5, "y": 5, "type": "墙" },{ "x": 6, "y": 5 },{ "x": 7, "y": 5 },{ "x": 8, "y": 5 },
              { "x": 0, "y": 6 },{ "x": 1, "y": 6 },{ "x": 2, "y": 6 },{ "x": 3, "y": 6 },{ "x": 4, "y": 6 },{ "x": 5, "y": 6 },{ "x": 6, "y": 6 },{ "x": 7, "y": 6 },{ "x": 8, "y": 6 },
              { "x": 0, "y": 7 },{ "x": 1, "y": 7 },{ "x": 2, "y": 7 },{ "x": 3, "y": 7 },{ "x": 4, "y": 7 },{ "x": 5, "y": 7 },{ "x": 6, "y": 7 },{ "x": 7, "y": 7 },{ "x": 8, "y": 7, "type": "墙" },
              { "x": 0, "y": 8, "type": "墙" },{ "x": 1, "y": 8, "type": "墙" },{ "x": 2, "y": 8 },{ "x": 3, "y": 8 },{ "x": 4, "y": 8, "type": "入口", },{ "x": 5, "y": 8 ,"eventId": "6", "type": "事件"},{ "x": 6, "y": 8 },{ "x": 7, "y": 8 },{ "x": 8, "y": 8, "type": "墙" },
              ],
          },
          # --- 第二层
          { id: 2, 
          row: 9,
          column: 9, 
          img: 1, 
          eventData: [
            { 
            id: '1',style: 6, title: '突发事件', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
            sections: [
              {
                key: 'P1', 
                content: ['“啊！！！”',
                '随着李森炎刚踏入第二层的洞窟，一声女人的尖叫，引起了他的注意。', '一阵无比恶臭的气息传来，他脸色微变。',
                '神识忽然开启，李森炎一下洞察到，有一只体型庞大的人面白蛛，正追着一个女子跑。','而且这人面白蛛跟他之前遇到的人面白蛛并不一样，这体积至少是他刚才遇到的两倍。',
                '此时，那发出惨叫的女子，右手滋滋冒血，想必是在刚才的打斗过程中受了伤，最关键的是身体被粘性极强的蛛网缚住，失去了反抗和逃走的可能了。',],
                btn: [
                {
                title: '英雄救美，这波冲了',
                tokey: "P2",
                },
                {
                title: '观望一下，不要冲动',
                tokey: "P3",
                },
               
                ]
              },

              {
                key: 'P2', 
                content: ['身为一个血气方刚，英姿勃勃，顶天立地的九尺男儿，咳咳……虽然有点夸张的成分，但都不重要。',
                '我辈中人，当扶危解困！', '“拜托你救救我！我必有重谢！！！”',
                '重谢？','听到她的喊话后，李森炎更是加快了自己的脚步。',],
                btn: [
                {
                title: '上！',
                toChapter: "WZXX_M1_N1_Z3C30",
                },
                ]
              },
    
              {
                key: 'P3', 
                content: ['先不要轻举妄动，不能被情绪冲昏了头脑。','就他现在的境界，没有云云在，冒然行动说不定还会得不偿失。',
                '人不为己天诛地灭，李森炎决定明哲保身。', '谁曾想，那女子这时候看见了他，立马朝他呼喊，“拜托你救救我！我必有重谢！！！”',
                '重谢？','他李森炎岂是这种贪财之辈，他丝毫没有犹豫便朝着这个女子冲了过去。','而就在这时候，那人面白蛛已张开朝着女子扑了过去。',
                ],
                btn: [
                {
                title: '上！',
                toChapter: "WZXX_M1_N1_Z3C30",
                },
                ]
              },
            ]  
          }, 

          { 
            id: '2',style: 6, title: '选择小队', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
            sections: [
              {
                key: 'P2', 
                content: ['李森炎眉头微皱，本来不想去的，但架不住江依依的盛情相邀，还是跟着她前往他们小队聚集点。',
                '两人身形飞速在林间穿行，不多时，便是来到林中一处空地上，那里已聚集了四个人影，正等待着江依依的到来。', '见到江依依身影，四人旋即都凑了上来，为首之人，当先开口：“师妹，你没事吧？”',
                '江依依点头：“我没事，多亏了李大哥，我才得以脱险。”','李森炎一眼扫过四人，发现都是之前在百草镇认识的人。','“多谢李兄弟仗义相助。”',
                '杨真对着李森炎抱拳说道。','不过让他没有想到的是这个李森炎明明只有炼体境的力量，竟然能够救下筑基期的江依依。','“李兄弟能帮依依脱离险境，修为定然是相当出色的，不知能否透露一些？”',
                ],
                btn: [
                {
                title: '该怎么说？',
                toChapter: "WZXX_M1_N1_Z3C31",
                },
                ]
              },
            ]  
          }, 
              ],
              
          config: 
              [
              {"x": 0,"y": 0,"type": "墙"},{"x": 1,"y": 0,"type": "墙"},{"x": 2,"y": 0,"type": "墙"},{"x": 3,"y": 0},{"x": 4,"y": 0,"keyPropId": 375,"type": "出口"},{"x": 5,"y": 0},{"x": 6,"y": 0,"type": "墙"},{"x": 7,"y": 0},{"x": 8,"y": 0,"keyPropId": 376,"type": "出口"},
              {"x": 0,"y": 1},{"x": 1,"y": 1},{"x": 2,"y": 1,"type": "墙"},{"x": 3,"y": 1,"type": "墙"},{"x": 4,"y": 1},{"x": 5,"y": 1},{"x": 6,"y": 1},{"x": 7,"y": 1},{"x": 8,"y": 1},
              {"x": 0,"y": 2},{"x": 1,"y": 2},{"x": 2,"y": 2},{"x": 3,"y": 2},{"x": 4,"y": 2},{"x": 5,"y": 2,"eventId": "2"},{"x": 6,"y": 2},{"x": 7,"y": 2},{"x": 8,"y": 2,"type": "墙"},{"x": 0,"y": 3},{"x": 1,"y": 3},
              {"x": 2,"y": 3},{"x": 3,"y": 3},{"x": 4,"y": 3},{"x": 5,"y": 3},{"x": 6,"y": 3},{"x": 7,"y": 3,"type": "墙"},{"x": 8,"y": 3,"type": "墙"},
              {"x": 0,"y": 4},{"x": 1,"y": 4},{"x": 2,"y": 4},{"x": 3,"y": 4},{"x": 4,"y": 4},{"x": 5,"y": 4},{"x": 6,"y": 4},{"x": 7,"y": 4,"type": "墙"},{"x": 8,"y": 4,"type": "墙"},
              {"x": 0,"y": 5},{"x": 1,"y": 5},{"x": 2,"y": 5},{"x": 3,"y": 5,"type": "墙"},{"x": 4,"y": 5,"type": "墙"},{"x": 5,"y": 5},{"x": 6,"y": 5},{"x": 7,"y": 5,"type": "墙"},{"x": 8,"y": 5,"type": "墙"},
              {"x": 0,"y": 6,"type": "墙"},{"x": 1,"y": 6},{"x": 2,"y": 6,"eventId": "1"},{"x": 3,"y": 6},{"x": 4,"y": 6},{"x": 5,"y": 6},{"x": 6,"y": 6},{"x": 7,"y": 6,"type": "墙"},{"x": 8,"y": 6,"type": "墙"},
              {"x": 0,"y": 7,"type": "墙"},{"x": 1,"y": 7},{"x": 2,"y": 7},{"x": 3,"y": 7},{"x": 4,"y": 7},{"x": 5,"y": 7},{"x": 6,"y": 7,"type": "墙"},{"x": 7,"y": 7,"type": "墙"},{"x": 8,"y": 7,"type": "墙"},
              {"x": 0,"y": 8,"type": "墙"},{"x": 1,"y": 8},{"x": 2,"y": 8,"type": "入口"},{"x": 3,"y": 8},{"x": 4,"y": 8,"type": "墙"},{"x": 5,"y": 8,"type": "墙"},{"x": 6,"y": 8,"type": "墙"},{"x": 7,"y": 8,"type": "墙"},{"x": 8,"y": 8,"type": "墙"}
              ]
         },
        ],
     },
  ]
