# ===========================================
# 修行
# ===========================================
xiuxing: [
  {
    # 名称
    title: '返虚期.一重',

    # 修为上限
    limit: 10000,

    # 属性加成
    attrs: [
      { key: '体力', value: 100 },
      { key: '防御', value: 100 },
      { key: '法力', value: 100 },
      { key: '攻击', value: 100 },
    ],

    # 在线修行(每分钟增加多少点修为)
    increaseXiuXingPerMinute: 100,
  },

  {
    # 名称
    title: '返虚期.二重',

    # 修为上限
    limit: 20000,

    # 属性加成
    attrs: [
      { key: '体力', value: 200 },
      { key: '防御', value: 200 },
      { key: '法力', value: 200 },
      { key: '攻击', value: 200 },
    ],

    # 在线修行(每分钟增加多少点修为)
    increaseXiuXingPerMinute: 200,
  },
]
