# ===========================================
# 修行配置
# 说明： 
#   tupo: {...}, pingjing: {...} 突破和瓶颈配置项只能二选一。
# ===========================================
xiuxing: [
  {
    # 名称
    title: '锻体.一重',

    # 阶段名称
    period: '锻体',

    # 阶段等级
    level: 1,

    # 修为上限
    limit: 1000,

    # 属性加成
    attrs: [
      { key: 'hp', value: 10 },
      { key: 'defense', value: 10 },
      { key: 'mp', value: 10 },
      { key: 'attack', value: 10 },
    ],

    # 是否提示美术字
    toastText: true,

    # 在线修行(每分钟增加多少点修为)
    increaseXiuXingPerMinute: 60,
  },

  {
    # 名称
    title: '锻体.二重',

    # 阶段名称
    period: '锻体',

    # 阶段等级
    level: 2,

    # 修为上限
    limit: 2000,

    # 属性加成
    attrs: [
      { key: 'hp', value: 10 },
      { key: 'defense', value: 10 },
      { key: 'mp', value: 10 },
      { key: 'attack', value: 10 },
    ],

    # 是否提示美术字
    toastText: true,

    # 在线修行(每分钟增加多少点修为)
    increaseXiuXingPerMinute: 60,
  },

  {
    # 名称
    title: '锻体.三重',

    # 阶段名称
    period: '锻体',

    # 阶段等级
    level: 3,

    # 修为上限
    limit: 3000,

    # 属性加成
    attrs: [
      { key: 'hp', value: 10 },
      { key: 'defense', value: 10 },
      { key: 'mp', value: 10 },
      { key: 'attack', value: 10 },
    ],

 

    # 是否提示美术字
    toastText: true,

    # 在线修行(每分钟增加多少点修为)
    increaseXiuXingPerMinute: 60,
  },

  {
    # 名称
    title: '锻体.四重',

    # 阶段名称
    period: '锻体',

    # 阶段等级
    level: 4,

    # 修为上限
    limit: 4000,

    # 属性加成
    attrs: [
      { key: 'hp', value: 10 },
      { key: 'defense', value: 10 },
      { key: 'mp', value: 10 },
      { key: 'attack', value: 10 },
    ],

    # 是否提示美术字
    toastText: true,

    # 在线修行(每分钟增加多少点修为)
    increaseXiuXingPerMinute: 60,
  },

    {
    # 名称
    title: '锻体.五重',

    # 阶段名称
    period: '锻体',

    # 阶段等级
    level: 5,

    # 修为上限
    limit: 5000,

    # 属性加成
    attrs: [
      { key: 'hp', value: 10 },
      { key: 'defense', value: 10 },
      { key: 'mp', value: 10 },
      { key: 'attack', value: 10 },
    ],

 
    # 是否提示美术字
    toastText: true,

    # 在线修行(每分钟增加多少点修为)
    increaseXiuXingPerMinute: 60,
  },

  {
    # 名称
    title: '锻体.六重',

    # 阶段名称
    period: '锻体',

    # 阶段等级
    level: 6,

    # 修为上限
    limit: 6000,

    # 属性加成
    attrs: [
      { key: 'hp', value: 10 },
      { key: 'defense', value: 10 },
      { key: 'mp', value: 10 },
      { key: 'attack', value: 10 },
    ],

  
    # 是否提示美术字
    toastText: true,

    # 在线修行(每分钟增加多少点修为)
    increaseXiuXingPerMinute: 60,
  },

   {
    # 名称
    title: '锻体.七重',

    # 阶段名称
    period: '锻体',

    # 阶段等级
    level: 7,

    # 修为上限
    limit: 7000,

    # 属性加成
    attrs: [
      { key: 'hp', value: 10 },
      { key: 'defense', value: 10 },
      { key: 'mp', value: 10 },
      { key: 'attack', value: 10 },
    ],



    # 是否提示美术字
    toastText: true,

    # 在线修行(每分钟增加多少点修为)
    increaseXiuXingPerMinute: 60,
  },

  {
    # 名称
    title: '锻体.八重',

    # 阶段名称
    period: '锻体',

    # 阶段等级
    level: 8,

    # 修为上限
    limit: 8000,

    # 属性加成
    attrs: [
      { key: 'hp', value: 10 },
      { key: 'defense', value: 10 },
      { key: 'mp', value: 10 },
      { key: 'attack', value: 10 },
    ],


    # 是否提示美术字
    toastText: true,

    # 在线修行(每分钟增加多少点修为)
    increaseXiuXingPerMinute: 60,
  },

   {
    # 名称
    title: '锻体.九重',

    # 阶段名称
    period: '锻体',

    # 阶段等级
    level: 9,

    # 修为上限
    limit: 9000,

    # 属性加成
    attrs: [
      { key: 'hp', value: 10 },
      { key: 'defense', value: 10 },
      { key: 'mp', value: 10 },
      { key: 'attack', value: 10 },
    ],

    # 突破配置
    tupo: {
      # 突破基础成功率
      successRate: 60,

      # 突破失败后的CD时间(单位秒)
      failCDTime: 1200,
    },

    # 是否提示美术字
    toastText: true,

    # 在线修行(每分钟增加多少点修为)
    increaseXiuXingPerMinute: 60,
  },


  {
    # 名称
    title: '先天.一重',

    # 阶段名称
    period: '先天',

    # 阶段等级
    level: 1,

    # 修为上限
    limit: 10000,

    # 属性加成
    attrs: [
      { key: 'hp', value: 20 },
      { key: 'defense', value: 20 },
      { key: 'mp', value: 20 },
      { key: 'attack', value: 20 },
    ],

     # 瓶颈配置
    pingjing: {
      # 瓶颈成功率(目前统一为100%)
      successRate: 100,
    },

    # 是否提示美术字
    toastText: true,

    # 在线修行(每分钟增加多少点修为)
    increaseXiuXingPerMinute: 60,
  },

  

  {
    # 名称
    title: '先天.二重',

    # 阶段名称
    period: '先天',

    # 阶段等级
    level: 2,

    # 修为上限
    limit: 20000,

    # 属性加成
    attrs: [
      { key: 'hp', value: 20 },
      { key: 'defense', value: 20 },
      { key: 'mp', value: 20 },
      { key: 'attack', value: 20 },
    ],

    # 突破配置
    tupo: {
      # 突破基础成功率
      successRate: 60,

      # 突破失败后的CD时间(单位秒)
      failCDTime: 1200,
    },

    # 是否提示美术字
    toastText: true,

    # 在线修行(每分钟增加多少点修为)
    increaseXiuXingPerMinute: 69,
  },

  {
    # 名称
    title: '先天.三重',

    # 阶段名称
    period: '先天',

    # 阶段等级
    level: 3,

    # 修为上限
    limit: 30000,

    # 属性加成
    attrs: [
      { key: 'hp', value: 20 },
      { key: 'defense', value: 20 },
      { key: 'mp', value: 20 },
      { key: 'attack', value: 20 },
    ],

   # 突破配置
    tupo: {
      # 突破基础成功率
      successRate: 60,

      # 突破失败后的CD时间(单位秒)
      failCDTime: 1200,
    },

    # 是否提示美术字
    toastText: true,

    # 在线修行(每分钟增加多少点修为)
    increaseXiuXingPerMinute: 104,
  },

   {
    # 名称
    title: '先天.四重',

    # 阶段名称
    period: '先天',

    # 阶段等级
    level: 4,

    # 修为上限
    limit: 40000,

    # 属性加成
    attrs: [
      { key: 'hp', value: 20 },
      { key: 'defense', value: 20 },
      { key: 'mp', value: 20 },
      { key: 'attack', value: 20 },
    ],

   # 突破配置
    tupo: {
      # 突破基础成功率
      successRate: 60,

      # 突破失败后的CD时间(单位秒)
      failCDTime: 1200,
    },

    # 是否提示美术字
    toastText: true,

    # 在线修行(每分钟增加多少点修为)
    increaseXiuXingPerMinute: 139,
  },

  {
    # 名称
    title: '先天.五重',

    # 阶段名称
    period: '先天',

    # 阶段等级
    level: 5,

    # 修为上限
    limit: 50000,

    # 属性加成
    attrs: [
      { key: 'hp', value: 20 },
      { key: 'defense', value: 20 },
      { key: 'mp', value: 20 },
      { key: 'attack', value: 20 },
    ],

   # 突破配置
    tupo: {
      # 突破基础成功率
      successRate: 60,

      # 突破失败后的CD时间(单位秒)
      failCDTime: 1200,
    },

    # 是否提示美术字
    toastText: true,

    # 在线修行(每分钟增加多少点修为)
    increaseXiuXingPerMinute: 174,
  },

  {
    # 名称
    title: '先天.六重',

    # 阶段名称
    period: '先天',

    # 阶段等级
    level: 6,

    # 修为上限
    limit: 60000,

    # 属性加成
    attrs: [
      { key: 'hp', value: 20 },
      { key: 'defense', value: 20 },
      { key: 'mp', value: 20 },
      { key: 'attack', value: 20 },
    ],

   # 突破配置
    tupo: {
      # 突破基础成功率
      successRate: 60,

      # 突破失败后的CD时间(单位秒)
      failCDTime: 1200,
    },

    # 是否提示美术字
    toastText: true,

    # 在线修行(每分钟增加多少点修为)
    increaseXiuXingPerMinute: 208,
  },

   {
    # 名称
    title: '先天.七重',

    # 阶段名称
    period: '先天',

    # 阶段等级
    level: 7,

    # 修为上限
    limit: 70000,

    # 属性加成
    attrs: [
      { key: 'hp', value: 20 },
      { key: 'defense', value: 20 },
      { key: 'mp', value: 20 },
      { key: 'attack', value: 20 },
    ],

   # 突破配置
    tupo: {
      # 突破基础成功率
      successRate: 60,

      # 突破失败后的CD时间(单位秒)
      failCDTime: 1200,
    },

    # 是否提示美术字
    toastText: true,

    # 在线修行(每分钟增加多少点修为)
    increaseXiuXingPerMinute: 243,
  },

     {
    # 名称
    title: '先天.八重',

    # 阶段名称
    period: '先天',

    # 阶段等级
    level: 8,

    # 修为上限
    limit: 80000,

    # 属性加成
    attrs: [
      { key: 'hp', value: 20 },
      { key: 'defense', value: 20 },
      { key: 'mp', value: 20 },
      { key: 'attack', value: 20 },
    ],

    # 突破配置
    tupo: {
      # 突破基础成功率
      successRate: 100,

      # 突破失败后的CD时间(单位秒)
      failCDTime: 1200,
    },

    # 是否提示美术字
    toastText: true,

    # 在线修行(每分钟增加多少点修为)
    increaseXiuXingPerMinute: 278,
  },

   {
    # 名称
    title: '先天.九重',

    # 阶段名称
    period: '先天',

    # 阶段等级
    level: 9,

    # 修为上限
    limit: 90000,

    # 属性加成
    attrs: [
      { key: 'hp', value: 20 },
      { key: 'defense', value: 20 },
      { key: 'mp', value: 20 },
      { key: 'attack', value: 20 },
    ],

   # 突破配置
    tupo: {
      # 突破基础成功率
      successRate: 2,

      # 突破失败后的CD时间(单位秒)
      failCDTime: 120000,
    },

    # 是否提示美术字
    toastText: true,

    # 在线修行(每分钟增加多少点修为)
    increaseXiuXingPerMinute: 313,
  },
]
