# ===========================================
# 修行配置
# ===========================================
xiuxing: [
  {
    # 名称
    title: '炼体期.一重',

    # 修为上限
    limit: 10000,

    # 属性加成
    attrs: [
      { key: '体力', value: 100 },
      { key: '防御', value: 100 },
      { key: '法力', value: 100 },
      { key: '攻击', value: 100 },
    ],

    # 突破配置
    tupo: {
      # 突破基础成功率
      successRate: 80,

      # 突破失败后的CD时间(单位秒)
      failCDTime: 300,
    },

    # 在线修行(每分钟增加多少点修为)
    increaseXiuXingPerMinute: 100,
  },

  {
    # 名称
    title: '炼体期.二重',

    # 修为上限
    limit: 20000,

    # 属性加成
    attrs: [
      { key: '体力', value: 200 },
      { key: '防御', value: 200 },
      { key: '法力', value: 200 },
      { key: '攻击', value: 200 },
    ],

    # 突破配置
    tupo: {
      # 突破基础成功率
      successRate: 70,

      # 突破失败后的CD时间(单位秒)
      failCDTime: 600,
    },

    # 在线修行(每分钟增加多少点修为)
    increaseXiuXingPerMinute: 200,
  },

  {
    # 名称
    title: '返虚期.三重',

    # 修为上限
    limit: 50000,

    # 属性加成
    attrs: [
      { key: '体力', value: 300 },
      { key: '防御', value: 300 },
      { key: '法力', value: 300 },
      { key: '攻击', value: 300 },
    ],

    # 突破配置
    tupo: {
      # 突破基础成功率
      successRate: 60,

      # 突破失败后的CD时间(单位秒)
      failCDTime: 1200,
    },

    # 在线修行(每分钟增加多少点修为)
    increaseXiuXingPerMinute: 300,
  },

  {
    # 名称
    title: '返虚期.四重',

    # 修为上限
    limit: 100000,

    # 属性加成
    attrs: [
      { key: '体力', value: 500 },
      { key: '防御', value: 500 },
      { key: '法力', value: 500 },
      { key: '攻击', value: 500 },
    ],

    # 突破配置
    tupo: {
      # 突破基础成功率
      successRate: 50,

      # 突破失败后的CD时间(单位秒)
      failCDTime: 2400,
    },

    # 在线修行(每分钟增加多少点修为)
    increaseXiuXingPerMinute: 500,
  },

  {
    # 名称
    title: '返虚期.五重',

    # 修为上限
    limit: 200000,

    # 属性加成
    attrs: [
      { key: '体力', value: 1000 },
      { key: '防御', value: 1000 },
      { key: '法力', value: 1000 },
      { key: '攻击', value: 1000 },
    ],

    # 突破配置
    tupo: {
      # 突破基础成功率
      successRate: 5,

      # 突破失败后的CD时间(单位秒)
      failCDTime: 4800,
    },

    # 在线修行(每分钟增加多少点修为)
    increaseXiuXingPerMinute: 1000,
  },

  {
    # 名称
    title: '返虚期.六重',

    # 修为上限
    limit: 500000,

    # 属性加成
    attrs: [
      { key: '体力', value: 2000 },
      { key: '防御', value: 2000 },
      { key: '法力', value: 2000 },
      { key: '攻击', value: 2000 },
    ],

    # 突破配置
    tupo: {
      # 突破基础成功率
      successRate: 5,

      # 突破失败后的CD时间(单位秒)
      failCDTime: 9600,
    },

    # 在线修行(每分钟增加多少点修为)
    increaseXiuXingPerMinute: 2000,
  },
]
