# ===========================================
# 修行配置
# 说明： 
#   tupo: {...}, pingjing: {...} 突破和瓶颈配置项只能二选一。
# ===========================================
xiuxing: [
  {
    # 名称
    title: '锻体.一重',

    # 阶段名称
    period: '锻体',

    # 阶段等级
    level: 1,

    # 修为上限
    limit: 1000,

    # 属性加成
    attrs: [
      { key: '体力', value: 10 },
      { key: '防御', value: 10 },
      { key: '法力', value: 10 },
      { key: '攻击', value: 10 },
    ],

    # 是否提示美术字
    toastText: true,

    # 在线修行(每分钟增加多少点修为)
    increaseXiuXingPerMinute: 60,
  },

  {
    # 名称
    title: '锻体.二重',

    # 阶段名称
    period: '锻体',

    # 阶段等级
    level: 2,

    # 修为上限
    limit: 2000,

    # 属性加成
    attrs: [
      { key: '体力', value: 10 },
      { key: '防御', value: 10 },
      { key: '法力', value: 10 },
      { key: '攻击', value: 10 },
    ],

    # 是否提示美术字
    toastText: true,

    # 在线修行(每分钟增加多少点修为)
    increaseXiuXingPerMinute: 60,
  },

  {
    # 名称
    title: '锻体.三重',

    # 阶段名称
    period: '锻体',

    # 阶段等级
    level: 3,

    # 修为上限
    limit: 3000,

    # 属性加成
    attrs: [
      { key: '体力', value: 10 },
      { key: '防御', value: 10 },
      { key: '法力', value: 10 },
      { key: '攻击', value: 10 },
    ],

    # 瓶颈配置
    pingjing: {
      # 瓶颈成功率(目前统一为100%)
      successRate: 100,
    },

    # 是否提示美术字
    toastText: true,

    # 在线修行(每分钟增加多少点修为)
    increaseXiuXingPerMinute: 60,
  },

  {
    # 名称
    title: '锻体.四重',

    # 阶段名称
    period: '锻体',

    # 阶段等级
    level: 4,

    # 修为上限
    limit: 4000,

    # 属性加成
    attrs: [
      { key: '体力', value: 10 },
      { key: '防御', value: 10 },
      { key: '法力', value: 10 },
      { key: '攻击', value: 10 },
    ],

    # 突破配置
    tupo: {
      # 突破基础成功率
      successRate: 60,

      # 突破失败后的CD时间(单位秒)
      failCDTime: 1200,
    },

    # 是否提示美术字
    toastText: true,

    # 在线修行(每分钟增加多少点修为)
    increaseXiuXingPerMinute: 60,
  },

    {
    # 名称
    title: '锻体.五重',

    # 阶段名称
    period: '锻体',

    # 阶段等级
    level: 5,

    # 修为上限
    limit: 5000,

    # 属性加成
    attrs: [
      { key: '体力', value: 10 },
      { key: '防御', value: 10 },
      { key: '法力', value: 10 },
      { key: '攻击', value: 10 },
    ],

    # 瓶颈配置
    pingjing: {
      # 瓶颈成功率(目前统一为100%)
      successRate: 100,
    },

    # 是否提示美术字
    toastText: true,

    # 在线修行(每分钟增加多少点修为)
    increaseXiuXingPerMinute: 60,
  },

  {
    # 名称
    title: '锻体.六重',

    # 阶段名称
    period: '锻体',

    # 阶段等级
    level: 6,

    # 修为上限
    limit: 6000,

    # 属性加成
    attrs: [
      { key: '体力', value: 10 },
      { key: '防御', value: 10 },
      { key: '法力', value: 10 },
      { key: '攻击', value: 10 },
    ],

      # 瓶颈配置
    pingjing: {
      # 瓶颈成功率(目前统一为100%)
      successRate: 100,
    },

    # 是否提示美术字
    toastText: true,

    # 在线修行(每分钟增加多少点修为)
    increaseXiuXingPerMinute: 60,
  },

   {
    # 名称
    title: '锻体.七重',

    # 阶段名称
    period: '锻体',

    # 阶段等级
    level: 7,

    # 修为上限
    limit: 7000,

    # 属性加成
    attrs: [
      { key: '体力', value: 10 },
      { key: '防御', value: 10 },
      { key: '法力', value: 10 },
      { key: '攻击', value: 10 },
    ],

      # 瓶颈配置
    pingjing: {
      # 瓶颈成功率(目前统一为100%)
      successRate: 100,
    },

    # 是否提示美术字
    toastText: true,

    # 在线修行(每分钟增加多少点修为)
    increaseXiuXingPerMinute: 60,
  },

  {
    # 名称
    title: '锻体.八重',

    # 阶段名称
    period: '锻体',

    # 阶段等级
    level: 8,

    # 修为上限
    limit: 8000,

    # 属性加成
    attrs: [
      { key: '体力', value: 10 },
      { key: '防御', value: 10 },
      { key: '法力', value: 10 },
      { key: '攻击', value: 10 },
    ],

     # 瓶颈配置
    pingjing: {
      # 瓶颈成功率(目前统一为100%)
      successRate: 100,
    },

    # 是否提示美术字
    toastText: true,

    # 在线修行(每分钟增加多少点修为)
    increaseXiuXingPerMinute: 60,
  },

   {
    # 名称
    title: '锻体.九重',

    # 阶段名称
    period: '锻体',

    # 阶段等级
    level: 9,

    # 修为上限
    limit: 9000,

    # 属性加成
    attrs: [
      { key: '体力', value: 10 },
      { key: '防御', value: 10 },
      { key: '法力', value: 10 },
      { key: '攻击', value: 10 },
    ],

    # 突破配置
    tupo: {
      # 突破基础成功率
      successRate: 60,

      # 突破失败后的CD时间(单位秒)
      failCDTime: 1200,
    },

    # 是否提示美术字
    toastText: true,

    # 在线修行(每分钟增加多少点修为)
    increaseXiuXingPerMinute: 60,
  },


  {
    # 名称
    title: '先天.一重',

    # 阶段名称
    period: '先天',

    # 阶段等级
    level: 1,

    # 修为上限
    limit: 100000,

    # 属性加成
    attrs: [
      { key: '体力', value: 500 },
      { key: '防御', value: 500 },
      { key: '法力', value: 500 },
      { key: '攻击', value: 500 },
    ],

     # 瓶颈配置
    pingjing: {
      # 瓶颈成功率(目前统一为100%)
      successRate: 100,
    },

    # 是否提示美术字
    toastText: true,

    # 在线修行(每分钟增加多少点修为)
    increaseXiuXingPerMinute: 500,
  },

  

  {
    # 名称
    title: '先天.二重',

    # 阶段名称
    period: '先天',

    # 阶段等级
    level: 2,

    # 修为上限
    limit: 200000,

    # 属性加成
    attrs: [
      { key: '体力', value: 1000 },
      { key: '防御', value: 1000 },
      { key: '法力', value: 1000 },
      { key: '攻击', value: 1000 },
    ],

    # 突破配置
    tupo: {
      # 突破基础成功率
      successRate: 5,

      # 突破失败后的CD时间(单位秒)
      failCDTime: 4800,
    },

    # 是否提示美术字
    toastText: true,

    # 在线修行(每分钟增加多少点修为)
    increaseXiuXingPerMinute: 1000,
  },

  {
    # 名称
    title: '先天.三重',

    # 阶段名称
    period: '先天',

    # 阶段等级
    level: 3,

    # 修为上限
    limit: 500000,

    # 属性加成
    attrs: [
      { key: '体力', value: 2000 },
      { key: '防御', value: 2000 },
      { key: '法力', value: 2000 },
      { key: '攻击', value: 2000 },
    ],

    # 突破配置
    tupo: {
      # 突破基础成功率
      successRate: 5,

      # 突破失败后的CD时间(单位秒)
      failCDTime: 9600,
    },

    # 是否提示美术字
    toastText: true,

    # 在线修行(每分钟增加多少点修为)
    increaseXiuXingPerMinute: 2000,
  },
]
