xunbao:
  {
    style: 6,
    title: "寻宝",
    dialogType: "HalfScreen",
    textAnimationType: "TextSingle",
    sections:
      [
        {
          key: "p1",
          content:
            [
              "你迅速跑过去，地面有些东西。",
              ["过关1"],
              "走开走开，马夫大喝， 正从远处拨开人群走来。",
              ["边缘闪烁绿"],
              "获得几颗石头珠子，看起来能卖不少钱。",
            ],
          btn:
            [
              {
                title: "领取奖励",
                tokey: "",
                props: [{ propId: 20, num: 10 }],
              },
            ],
        },
      ],
  }
