# 线索1
clues:
  {
    id: 'xiansuo2',
    type: '线索',
    groupId: '坊市',
    filterCondition: {location: '坊市', chapter: '第三卷'},
    title: '诀溟草的线索',
    content: ['【诀溟草，众生山脉，最北方】',],
    condition: {npcId: 1, scenes: 'pomiao', prop: 20, andVarsOff: ['v7']},
  }
