# 线索1
clues:
  {
    id: 'xiansuo2',
    type: '线索',
    groupId: '李家村',
    filterCondition: {location: '全部',},
    title: "简述",
    content: ['通过和人物对话',"可以获得一些线索"],
    condition: {npcId: 1, scenes: 'pomiao', prop: 20, andVarsOff: ['v7']},
  }
