# ===========================================
# 文件索引表
# 文件名说明 举例："WZXX_M1_N1_C001_[A1].txt",
# 内容分别代表 书本_主线_支线_章节_[章节内选择出的小章节]
# ===========================================
files:
  [
  #第一章
    "QGXX_[START].txt",


  #选择身份


#
#
#
#

#
  ]
