## 配置线索

clueConfig:
  [
    {
      cluesType: "CLUES",
      cluesTypeName: "线索",
      data:
        [
          "xiansuo1",
          "xiansuo2",
          "xiansuo3",
          "xiansuo4",
          "xiansuo5",
          "xiansuo6",
        ],
    },
    {
      cluesType: "INTELLIGENCE",
      cluesTypeName: "情报",
      data: ["xiansuo1", "xiansuo2"],
    },
    { cluesType: "GOSSIP", cluesTypeName: "流言", data: ["xiansuo1"] },
  ]
