# ===========================================
# BUFF配置
# ===========================================
buffs: [
   {
      # Buff ID
      id: 1,

      # 图标ID
      iconId: 1,

      # 技能名称
      name: '锻体决_BUFF',

      # 描述
      desc: '',

      # 影响效果
      effects: [
         { formula: 'A_物理防御 = A_物理防御 * 1.1 + 200' },
         { formula: 'A_法术防御 = A_法术防御 * 1.1 + 200' },
      ],

      # 影响回合
      round: 2,
   },
   {
      # Buff ID
      id: 2,

      # 图标ID
      iconId: 1,

      # 技能名称
      name: '护身罡气_BUFF',

      # 描述
      desc: '',

      # 影响效果
      effects: [
         { formula: 'A_物理防御 = A_物理防御 * 1.1 + 200' },
         { formula: 'A_法术防御 = A_法术防御 * 1.1 + 200' },
      ],

      # 影响回合
      round: 3,
   },
   {
      # Buff ID
      id: 3,

      # 图标ID
      iconId: 1,

      # 技能名称
      name: '微光盾_BUFF',

      # 描述
      desc: '',

      # 影响效果
      effects: [
         { formula: 'A_物理防御 = A_物理防御 * 1.1 + 200' },
         { formula: 'A_法术防御 = A_法术防御 * 1.1 + 200' },
      ],

      # 影响回合
      round: 3,
   },
]