# ===========================================
# 技能配置
# ===========================================
skills: [
   {
      # 技能唯一ID 
      id: 1,

      # 技能等级
      level: 1,

      # 图标ID
      iconId: 1,

      # 技能名称
      name: '冷月剑',

      # 描述
      desc: '',

      # 蓄力时间
      xuLiMillis: 500,

      # 冷却时间
      cdMillis: 1000,

      # 技能消耗
      consume: [
         { mp: 20 },
         { hp: 20 },
      ],

      # 影响公式
      actions: [
         { target: 'ALL', hit_rate: 100, crit_rate: 40, crit_add: 1.5, formula: '伤害 = (A_物理攻击 - D_物理防御) * 1.2 + 120' },
         { target: 'ME', hit_rate: 100, formula: '回血 = 5' },
         { target: 'ME', hit_rate: 100, formula: '回蓝 = 5' },
      ],

      # 效果列表
      effects: [],
   },
   {
      # 技能唯一ID 
      id: 2,

      # 技能等级
      level: 1,

      # 图标ID
      iconId: 1,

      # 技能名称
      name: '锻体决',

      # 描述
      desc: '',

      # 蓄力时间
      xuLiMillis: 600,

      # 冷却时间
      cdMillis: 3000,

      # 技能消耗
      consume: [
         { mp: 20 },
      ],

      # 被动
      passive: true,
   
      # 影响公式
      actions: [
      ],

      # 效果列表
      effects: [
         { target: 'ME', buffId: 1, rate: 100, groupId: 'A' },
      ],
   },
   {
      # 技能唯一ID 
      id: 3,

      # 技能等级
      level: 1,

      # 图标ID
      iconId: 1,

      # 技能名称
      name: '护身罡气',

      # 描述
      desc: '',

      # 蓄力时间
      xuLiMillis: 600,

      # 冷却时间
      cdMillis: 3000,

      # 技能消耗
      consume: [
         { mp: 20 },
      ],

      # 被动
      passive: true,

      # 影响公式
      actions: [
      ],

      # 效果列表
      effects: [
         { target: 'ME', buffId: 2, groupId: 'A' },
      ],
   },
   {
      # 技能唯一ID 
      id: 4,

      # 技能等级
      level: 1,

      # 图标ID
      iconId: 1,

      # 技能名称
      name: '风意剑',

      # 描述
      desc: '',

      # 蓄力时间
      xuLiMillis: 600,

      # 冷却时间
      cdMillis: 3000,

      # 技能消耗
      consume: [
         { mp: 20 },
      ],

      # 影响公式
      actions: [
         { target: 'ALL', hit_rate: 80, crit_rate: 10, crit_add: 1.5, formula: '伤害 = (A_法术攻击 - D_法术防御) * 1.2 + 300' },
      ],

      # 效果列表
      effects: [],
   },
   {
      # 技能唯一ID 
      id: 5,

      # 技能等级
      level: 1,

      # 图标ID
      iconId: 1,

      # 技能名称
      name: '微光盾',

      # 描述
      desc: '',

      # 蓄力时间
      xuLiMillis: 600,

      # 冷却时间
      cdMillis: 3000,

      # 技能消耗
      consume: [
         { mp: 20 },
      ],

      # 被动
      passive: true,

      # 影响公式
      actions: [
      ],

      # 效果列表
      effects: [
         { target: 'ME', buffId: 3, groupId: 'B' },
      ],
   },
   {
      # 技能唯一ID 
      id: 6,

      # 技能等级
      level: 1,

      # 图标ID
      iconId: 1,

      # 技能名称
      name: '吃药',

      # 描述
      desc: '',

      # 蓄力时间
      xuLiMillis: 500,

      # 冷却时间
      cdMillis: 1000,

      # 技能消耗
      consume: [
         { mp: 20 },
         {
            props: [
               { propId: 1, hp: 20, mp: 20 },
               { propId: 2, hp: 20, mp: 20 }
            ]
         }
      ],

      # 影响公式
      actions: [
      ],

      # 效果列表
      effects: [],
   },
   {
      # 技能唯一ID 
      id: 7,

      # 技能等级
      level: 1,

      # 图标ID
      iconId: 1,

      # 技能名称
      name: '斩杀',

      # 描述
      desc: '',

      # 蓄力时间
      xuLiMillis: 500,

      # 冷却时间
      cdMillis: 1000,

      # 技能消耗
      consume: [
         { mp: 20 },
         { hp: 20 },
      ],

      # 影响公式
      actions: [
         { target: 'ME', hit_rate: 100, formula: '伤害 = D_hp * 0.5' }
      ],

      # 效果列表
      effects: [],
   },
]