# ===========================================
# 文件索引表
# 文件名说明 举例："WZXX_M1_N1_C001_[A1].txt",
# 内容分别代表 书本_主线_支线_章节_[章节内选择出的小章节]
# ===========================================
files:
  [
  #第一章
    "WZXX_[START].txt",
    "WZXX_M1_N1_C001.txt",
    "WZXX_M1_N1_C001A.txt",
    "WZXX_M1_N1_C001B_[A1].txt",
    "WZXX_M1_N1_C001B_[B1].txt",
    "WZXX_M1_N1_C001B_[B2].txt",
    "WZXX_M1_N1_C001B_[C1].txt",
    "WZXX_M1_N1_C001B_[C2].txt",
    "WZXX_M1_N1_C001B_[C3].txt",
    "WZXX_M1_N1_C001B_[N1].txt",
    "WZXX_M1_N1_C001B.txt",
    "WZXX_M1_N1_C001C_[N1].txt",
    "WZXX_M1_N1_C001C_[N2].txt",
    "WZXX_M1_N1_C001C_[N3].txt",
    "WZXX_M1_N1_C001C.txt",
    #
    "WZXX_M1_N1_C002_[N1].txt",
    "WZXX_M1_N1_C002_[N3].txt",
    "WZXX_M1_N1_C002_[N4].txt",
    "WZXX_M1_N1_C002_[N5].txt",
    "WZXX_M1_N1_C002_[N6].txt",
    "WZXX_M1_N1_C002_[N7].txt",
    "WZXX_M1_N1_C002_[N8].txt",
    "WZXX_M1_N1_C002_[N9].txt",
    "WZXX_M1_N1_C002_[N10].txt",
    "WZXX_M1_N1_C003_[N1].txt",
    "WZXX_M1_N1_C003_[N2].txt",
    "WZXX_M1_N1_C003_[N3].txt",
    "WZXX_M1_N1_C004_[N1].txt",
    "WZXX_M1_N1_C004_[N2].txt",
    "WZXX_M1_N1_C005.txt",
    "WZXX_M1_N1_C005A.txt",
    "WZXX_M1_N1_C005B.txt",
    "WZXX_M1_N1_C005C.txt",
    "WZXX_M1_N1_C005D.txt",

    "WZXX_M1_N1_C006.txt",
    "WZXX_M1_N1_C007.txt",
    "WZXX_M1_N1_C007A.txt",

    "WZXX_M1_N1_C008.txt",
    "WZXX_M1_N1_C009_[N1].txt",
    "WZXX_M1_N1_C009_[N2].txt",
    "WZXX_M1_N1_C010_[N1].txt",
    "WZXX_M1_N1_C010_[N2].txt",
    "WZXX_M1_N1_C010_[N3].txt",
    "WZXX_M1_N1_C010_[N4].txt",
    "WZXX_M1_N1_C010_[N5].txt",
    "WZXX_M1_N1_C010_[N6].txt",
    "WZXX_M1_N1_C010_[N7].txt",
    "WZXX_M1_N1_C010_[N8].txt",
    "WZXX_M1_N1_C010_[N9].txt",
    "WZXX_M1_N1_C010_[N10].txt",
    "WZXX_M1_N1_C010_[N11].txt",
    "WZXX_M1_N1_C010_[N12].txt",
    "WZXX_M1_N1_C010_[N13].txt",



    "WZXX_M1_N1_C011_[N1].txt",
    "WZXX_M1_N1_C011_[N2].txt",
    
    "WZXX_M1_N1_C012_[N1].txt",
    "WZXX_M1_N1_C012_[N2].txt",
    "WZXX_M1_N1_C013_[N1].txt",

    "WZXX_M1_N1_C013_[N2].txt",
    "WZXX_M1_N1_C013_[N3].txt",
    "WZXX_M1_N1_C013_[N4].txt",


    "WZXX_M1_N1_C014_[N1].txt",
    "WZXX_M1_N1_C014A.txt",
    "WZXX_M1_N1_C015_[N1].txt",
    "WZXX_M1_N1_C015_[N2].txt",
    "WZXX_M1_N1_C015_[N3].txt",
    "WZXX_M1_N1_C015_[N4].txt",
    "WZXX_M1_N1_C015_[N5].txt",
    "WZXX_M1_N1_C015_[V1].txt",
    "WZXX_M1_N1_C016_[N1].txt",
    "WZXX_M1_N1_C016_[N2].txt",
    "WZXX_M1_N1_C016_[N3].txt",
    "WZXX_M1_N1_C017_[N1].txt",
    "WZXX_M1_N1_C017_[N2].txt",
    "WZXX_M1_N1_C018_[N1].txt",
    "WZXX_M1_N1_C018_[N2].txt",
    "WZXX_M1_N1_C019_[N1].txt",
    "WZXX_M1_N1_C019_[N2].txt",
    "WZXX_M1_N1_C020.txt",
    "WZXX_M1_N1_C021.txt",
    "WZXX_M1_N1_C022_[N1].txt",
    "WZXX_M1_N1_C022_[N2].txt",

    "WZXX_M1_N1_C023_[N1].txt",
    "WZXX_M1_N1_C023_[N2].txt",
    "WZXX_M1_N1_C024_[N1].txt",
    "WZXX_M1_N1_C025.txt",

    ##副本现代剧情
    "WZXX_M1_N1_C988.txt",
    "WZXX_M1_N1_C989.txt",
    "WZXX_M1_N1_C990.txt",
    "WZXX_M1_N1_C991.txt",
    "WZXX_M1_N1_C992.txt",
    "WZXX_M1_N1_C993.txt",
    "WZXX_M1_N1_C994.txt",
    "WZXX_M1_N1_C995.txt",
    "WZXX_M1_N1_C996.txt",
    "WZXX_M1_N1_C997.txt",
    "WZXX_M1_N1_C998.txt",

    #选择身份
    "WZXX_M1_N1_C999.txt",
    #地图测试
    "WZXX_M1_N1_C1000.txt",
    
    #第二卷剧情
    "WZXX_M1_N1_Z2C01.txt",
    "WZXX_M1_N1_Z2C02.txt",
    "WZXX_M1_N1_Z2C03.txt",
    "WZXX_M1_N1_Z2C04.txt",
    "WZXX_M1_N1_Z2C05.txt",
    "WZXX_M1_N1_Z2C04_[N1].txt",
    "WZXX_M1_N1_Z2C04_[N2].txt",
    "WZXX_M1_N1_Z2C05.txt",
    "WZXX_M1_N1_Z2C06.txt",
    "WZXX_M1_N1_Z2C07.txt",
    "WZXX_M1_N1_Z2C08.txt",
    "WZXX_M1_N1_Z2C09.txt",
    "WZXX_M1_N1_Z2C10.txt",
    "WZXX_M1_N1_Z2C11.txt",
    "WZXX_M1_N1_Z2C12.txt",
    "WZXX_M1_N1_Z2C13.txt",
    "WZXX_M1_N1_Z2C14.txt",
    "WZXX_M1_N1_Z2C15.txt",
    "WZXX_M1_N1_Z2C16.txt",
    "WZXX_M1_N1_Z2C17.txt",

    #
    "WZXX_M1_N1_Z3C01.txt",
    "WZXX_M1_N1_Z3C02.txt",
    "WZXX_M1_N1_Z3C03.txt",
    "WZXX_M1_N1_Z3C04.txt",
    "WZXX_M1_N1_Z3C05.txt",

    "WZXX_M1_N1_Z3C10_[N1].txt",
    "WZXX_M1_N1_Z3C10_[N2].txt",
    "WZXX_M1_N1_Z3C11.txt",
    "WZXX_M1_N1_Z3C12.txt",
    "WZXX_M1_N1_Z3C13.txt",
    "WZXX_M1_N1_Z3C14.txt",
    "WZXX_M1_N1_Z3C15.txt",
    "WZXX_M1_N1_Z3C16.txt",
    "WZXX_M1_N1_Z3C17.txt",
    "WZXX_M1_N1_Z3C18.txt",

    
    "WZXX_M1_N1_Z3C20.txt",
    "WZXX_M1_N1_Z3C21.txt",
    "WZXX_M1_N1_Z3C22.txt",
    "WZXX_M1_N1_Z3C23.txt",
    "WZXX_M1_N1_Z3C24.txt",
    "WZXX_M1_N1_Z3C25.txt",
    "WZXX_M1_N1_Z3C26.txt",
    "WZXX_M1_N1_Z3C27.txt",
    "WZXX_M1_N1_Z3C28.txt",
    "WZXX_M1_N1_Z3C09.txt",
    "WZXX_M1_N1_Z3C98.txt",
    "WZXX_M1_N1_Z3C99.txt",
    
  
 

  ]
