# ===========================================
# 文件索引表
# 文件名说明 举例："WZXX_M1_N1_C001_[A1].txt",
# 内容分别代表 书本_主线_支线_章节_[章节内选择出的小章节]
# ===========================================
files:
  [
  #第一章
    "WZXX_[START].txt",
    "WZXX_M1_N1_C001.txt",
    "WZXX_M1_N1_C001A.txt",
    "WZXX_M1_N1_C001B_[A1].txt",
    "WZXX_M1_N1_C001B_[B1].txt",
    "WZXX_M1_N1_C001B_[B2].txt",
    "WZXX_M1_N1_C001B_[C1].txt",
    "WZXX_M1_N1_C001B_[C2].txt",
    "WZXX_M1_N1_C001B_[C3].txt",
    "WZXX_M1_N1_C001B.txt",
    "WZXX_M1_N1_C001C_[N1].txt",
    "WZXX_M1_N1_C001C_[N2].txt",
    "WZXX_M1_N1_C001C_[N3].txt",
    "WZXX_M1_N1_C001C.txt",
    #
    "WZXX_M1_N1_C002_[N1].txt",
    "WZXX_M1_N1_C002_[N3].txt",
    "WZXX_M1_N1_C002_[N4].txt",
    "WZXX_M1_N1_C002_[N5].txt",
    "WZXX_M1_N1_C002_[N6].txt",
    "WZXX_M1_N1_C002_[N7].txt",
    "WZXX_M1_N1_C002_[N8].txt",
    "WZXX_M1_N1_C002_[N9].txt",
    "WZXX_M1_N1_C002_[N10].txt",
    "WZXX_M1_N1_C003_[N1].txt",
    "WZXX_M1_N1_C003_[N2].txt",
    "WZXX_M1_N1_C003_[N3].txt",
    "WZXX_M1_N1_C004_[N1].txt",
    "WZXX_M1_N1_C004_[N2].txt",
    "WZXX_M1_N1_C005_[N1].txt",
    "WZXX_M1_N1_C006_[N1].txt",
    "WZXX_M1_N1_C007_[N1].txt",

    "WZXX_M1_N1_C008_[N1].txt",
    "WZXX_M1_N1_C009_[N1].txt",
    "WZXX_M1_N1_C010_[N1].txt",
    "WZXX_M1_N1_C011_[N1].txt",
    "WZXX_M1_N1_C011_[N2].txt",
    "WZXX_M1_N1_C012_[N1].txt",
    "WZXX_M1_N1_C012_[N2].txt",
    "WZXX_M1_N1_C013_[N1].txt",

    "WZXX_M1_N1_C013_[N2].txt",
    "WZXX_M1_N1_C014_[N1].txt",
    "WZXX_M1_N1_C015_[N1].txt",
    "WZXX_M1_N1_C015_[V1].txt",
    "WZXX_M1_N1_C016_[N1].txt",
    "WZXX_M1_N1_C017_[N1].txt",
    "WZXX_M1_N1_C017_[N2].txt",
    "WZXX_M1_N1_C018_[N1].txt",
    "WZXX_M1_N1_C018_[N2].txt",
    "WZXX_M1_N1_C019_[N1].txt",
    "WZXX_M1_N1_C019_[N2].txt",
    "WZXX_M1_N1_C020.txt",
    "WZXX_M1_N1_C021.txt",
    "WZXX_M1_N1_C022_[N1].txt",

    "WZXX_M1_N1_C023_[N1].txt",
    "WZXX_M1_N1_C024_[N1].txt",
    "WZXX_M1_N1_C025_[N1].txt",
    "WZXX_M1_N1_C026_[N1].txt",
    "WZXX_M1_N1_C027_[N1].txt",
    "WZXX_M1_N1_C028_[N1].txt", 
    "WZXX_M1_N1_C029_[N1].txt",
    "WZXX_M1_N1_C030_[N1].txt",
    "WZXX_M1_N1_C030.txt",
    "WZXX_M1_N1_C031_[N1].txt",
    "WZXX_M1_N1_C032_[N1].txt",
    "WZXX_M1_N1_C033_[N1].txt",

  
    "WZXX_M1_N1_C033.txt",
    "WZXX_M1_N1_C034.txt",
    "WZXX_M1_N1_C035.txt",
    "WZXX_M1_N1_C036.txt",
    "WZXX_M1_N1_C037.txt",
    "WZXX_M1_N1_C038.txt",
#
#
#
  #选择身份
    "WZXX_M1_N1_C999.txt",
#
  ]
