# ===========================================
# 文件索引表
# 文件名说明 举例："WZXX_M1_N1_C001_[A1].txt",
# 内容分别代表 书本_主线_支线_章节_[章节内选择出的小章节]
# ===========================================
files:
  [
  #第一章
    "WZXX_[START].txt",
    "WZXX_M1_N1_C001.txt",
    "WZXX_M1_N1_C001A.txt",
    "WZXX_M1_N1_C001B_[A1].txt",
    "WZXX_M1_N1_C001B_[B1].txt",
    "WZXX_M1_N1_C001B_[B2].txt",
    "WZXX_M1_N1_C001B_[C1].txt",
    "WZXX_M1_N1_C001B_[C2].txt",
    "WZXX_M1_N1_C001B.txt",
    "WZXX_M1_N1_C001C_[N1].txt",
    "WZXX_M1_N1_C001C_[N2].txt",
    "WZXX_M1_N1_C001C_[N3].txt",
    "WZXX_M1_N1_C001C.txt",
    #
    "WZXX_M1_N1_C002_[N1].txt",
    "WZXX_M1_N1_C002_[N2].txt",
    "WZXX_M1_N1_C002_[N3].txt",
    #
    "WZXX_M1_N1_C003_[N1].txt",
    "WZXX_M1_N1_C003_[N2].txt",
    #
    "WZXX_M1_N1_C004_[N1].txt",
    "WZXX_M1_N1_C004_[N2].txt",
    "WZXX_M1_N1_C004C.txt",
    #
    "WZXX_M1_N1_C005_[N1].txt",
    "WZXX_M1_N1_C005_[N2].txt",
    #
    "WZXX_M1_N1_C006_[N0].txt",
    #
    "WZXX_M1_N1_C007_[N0].txt",
    #
    "WZXX_M1_N1_C008_[N0].txt",
    #
    "WZXX_M1_N1_C009_[V2].txt",
    #
    "WZXX_M1_N1_C010_[V1][N1].txt",
    "WZXX_M1_N1_C010_[V1][N2].txt",
    "WZXX_M1_N1_C010_[V2][N1].txt",
    "WZXX_M1_N1_C010_[V2][N2].txt",
    #
    "WZXX_M1_N1_C011_[V0].txt",
    "WZXX_M1_N1_C012_[V0].txt",
    "WZXX_M1_N1_C013_[V0].txt",
    "WZXX_M1_N1_C015_[V0].txt",
    "WZXX_M1_N1_C016_[V0].txt",
   #
    "WZXX_M1_N1_C017_[N1].txt",
    "WZXX_M1_N1_C017_[N2].txt",
    "WZXX_M1_N1_C019.txt",
    "WZXX_M1_N1_C020.txt",
     #
    "WZXX_M1_N1_C021.txt",
    "WZXX_M1_N1_C022.txt",
    "WZXX_M1_N1_C023.txt",
    "WZXX_M1_N1_C024.txt",
    "WZXX_M1_N1_C025.txt",
    "WZXX_M1_N1_C026.txt",
    "WZXX_M1_N1_C027.txt",
    "WZXX_M1_N1_C028.txt",
    "WZXX_M1_N1_C029.txt",
    "WZXX_M1_N1_C030.txt",
    "WZXX_M1_N1_C031.txt",
    "WZXX_M1_N1_C032.txt",
    "WZXX_M1_N1_C033.txt",
    "WZXX_M1_N1_C034.txt",
    "WZXX_M1_N1_C035.txt",
    
#
#
#
  #选择身份
    "WZXX_M1_N1_C999.txt",
#
  ]
