# ===========================================
# 文件索引表
# 文件名说明 举例："WZXX_M1_N1_C001_[A1].txt",
# 内容分别代表 书本_主线_支线_章节_[章节内选择出的小章节]
# ===========================================
files:
  [
  #第一章
    "WZXX_[START].txt",
    "WZXX_M1_N1_C001.txt",
    "WZXX_M1_N1_C001A.txt",
    "WZXX_M1_N1_C001B_[A1].txt",
    "WZXX_M1_N1_C001B_[B1].txt",
    "WZXX_M1_N1_C001B_[B2].txt",
    "WZXX_M1_N1_C001B_[C1].txt",
    "WZXX_M1_N1_C001B_[C2].txt",
    "WZXX_M1_N1_C001B_[C3].txt",
    "WZXX_M1_N1_C001B_[N1].txt",
    "WZXX_M1_N1_C001B.txt",
    "WZXX_M1_N1_C001C_[N1].txt",
    "WZXX_M1_N1_C001C_[N2].txt",
    "WZXX_M1_N1_C001C_[N3].txt",
    "WZXX_M1_N1_C001C.txt",
    #
    "WZXX_M1_N1_C002_[N1].txt",
    "WZXX_M1_N1_C002_[N3].txt",
    "WZXX_M1_N1_C002_[N4].txt",
    "WZXX_M1_N1_C002_[N5].txt",
    "WZXX_M1_N1_C002_[N6].txt",
    "WZXX_M1_N1_C002_[N7].txt",
    "WZXX_M1_N1_C002_[N8].txt",
    "WZXX_M1_N1_C002_[N9].txt",
    "WZXX_M1_N1_C002_[N10].txt",
    "WZXX_M1_N1_C003_[N1].txt",
    "WZXX_M1_N1_C003_[N2].txt",
    "WZXX_M1_N1_C003_[N3].txt",
    "WZXX_M1_N1_C004_[N1].txt",
    "WZXX_M1_N1_C004_[N2].txt",
    "WZXX_M1_N1_C005.txt",
    "WZXX_M1_N1_C006.txt",
    "WZXX_M1_N1_C007.txt",

    "WZXX_M1_N1_C008.txt",
    "WZXX_M1_N1_C009_[N1].txt",
    "WZXX_M1_N1_C009_[N2].txt",
    # "WZXX_M1_N1_C009_[N3].txt",
    "WZXX_M1_N1_C010.txt",
    "WZXX_M1_N1_C011_[N1].txt",
    "WZXX_M1_N1_C011_[N2].txt",
    
    "WZXX_M1_N1_C012_[N1].txt",
    "WZXX_M1_N1_C012_[N2].txt",
    "WZXX_M1_N1_C013_[N1].txt",

    "WZXX_M1_N1_C013_[N2].txt",
    "WZXX_M1_N1_C014_[N1].txt",
    "WZXX_M1_N1_C014A.txt",
    "WZXX_M1_N1_C015_[N1].txt",
    "WZXX_M1_N1_C015_[V1].txt",
    "WZXX_M1_N1_C016_[N1].txt",
    "WZXX_M1_N1_C016_[N2].txt",
    "WZXX_M1_N1_C016_[N3].txt",
    "WZXX_M1_N1_C017_[N1].txt",
    "WZXX_M1_N1_C017_[N2].txt",
    "WZXX_M1_N1_C018_[N1].txt",
    "WZXX_M1_N1_C018_[N2].txt",
    "WZXX_M1_N1_C019_[N1].txt",
    "WZXX_M1_N1_C019_[N2].txt",
    "WZXX_M1_N1_C020.txt",
    "WZXX_M1_N1_C021.txt",
    "WZXX_M1_N1_C022.txt",

    "WZXX_M1_N1_C023_[N1].txt",
    "WZXX_M1_N1_C023.txt",
    "WZXX_M1_N1_C024_[N1].txt",
    "WZXX_M1_N1_C025.txt",
    "WZXX_M1_N1_C026.txt",
    "WZXX_M1_N1_C027.txt",
    "WZXX_M1_N1_C028.txt", 
    "WZXX_M1_N1_C029.txt",
    "WZXX_M1_N1_C030.txt",
    "WZXX_M1_N1_C031_[N1].txt",
    "WZXX_M1_N1_C032.txt",
    "WZXX_M1_N1_C033.txt",

    "WZXX_M1_N1_C034.txt",
    "WZXX_M1_N1_C035.txt",
    "WZXX_M1_N1_C036.txt",
    "WZXX_M1_N1_C037.txt",
    "WZXX_M1_N1_C038.txt",
    "WZXX_M1_N1_C039.txt",
    "WZXX_M1_N1_C040.txt",

    ##
    "WZXX_M1_N1_C988.txt",
    "WZXX_M1_N1_C989.txt",
    "WZXX_M1_N1_C990.txt",
    "WZXX_M1_N1_C991.txt",
    "WZXX_M1_N1_C992.txt",
    "WZXX_M1_N1_C993.txt",
    "WZXX_M1_N1_C994.txt",
    "WZXX_M1_N1_C995.txt",
    "WZXX_M1_N1_C996.txt",
    "WZXX_M1_N1_C997.txt",
    "WZXX_M1_N1_C998.txt",
#
#
#
  #选择身份
    "WZXX_M1_N1_C999.txt",
    #地图测试
    "WZXX_M1_N1_C1000.txt",
    #第二个分支内容
    "WZXX_M1_N2_C014.txt",
    "WZXX_M1_N2_C015.txt",
    "WZXX_M1_N2_C016.txt",
    "WZXX_M1_N2_C017.txt",
    "WZXX_M1_N2_C018.txt",
    "WZXX_M1_N2_C019.txt",
    "WZXX_M1_N2_C020.txt",
    "WZXX_M1_N2_C021.txt",
    "WZXX_M1_N2_C022.txt",
#
  ]
