scenes: [
  # NPC1
  {
    id: 'npc_1', name: '老者NPC——2', 
    # npc 头像
    avatarId: 2,

    # 指定场景为NPC场景
    isNpc: true,

    # 变量定义
    vars: [
      { id: 'hao_gan_du',
       min: -1000,
       max: 10000000, 
      #  默认好感度为0
       defaultValue: 0 },
    ],

    # 动作定义
    actions: [
      { id: 'a1', cmd: 'var', params: 'hao_gan_du += 10' },
      { id: 'a2', cmd: 'var', params: 'hao_gan_du -= 10' },
      { id: 'a3', cmd: 'var', params: 'hao_gan_du ++ 1' },
      { id: 'a4', cmd: 'var', params: 'hao_gan_du -- 1' },
    ],

    # 事件定义
    events: [
      { type: 'enter', nextChat: 'c1' },
    ],

    # 对话选项
    chats: [
      #
      { 
        id: 'c1', desc: '老者', 
        options: [ 
          { title: "查看好感度", dialogs: ['p1'] },
          { title: '好感度 >= 200 显示', andVarsValue: ['hao_gan_du >= 200'] },
          { title: '好感度 < 200 显示', andVarsValue: ['hao_gan_du < 200'] },
          { title: '增加10点好感度', clickActions: ['a1'] },
          { title: '减少10点好感度', clickActions: ['a2'] },
          { title: '好感度等级加一', clickActions: ['a3'] },
          { title: '好感度等级减一', clickActions: ['a4'] },
          { title: '返回原场景', toScene: '@previous' },
        ],
      }
    ],

    # 对话框
    dialogs: [
      {
        id: 'p1', style: 200, textAnimationType: 'TextSingle', duanWei: "宗师",
        sections: {
          content: '来这里这么多天了，连个像样的防身东西都没有，你觉得菜刀出现的正是时候。',
          btn: [
            { title: '对话', dialogs: ["p3"],},
            { title:  '去破庙', toScene: 'pomiaomk'},
          ]
        }, 
      },
      { id: 'p3',
        style: 7, 
        artId: 1,
        title: '你挂了',
        dialogType: 'FullScreen', 
        textAnimationType: 'TextFadeIn', 
        sections: [
        { key: 'p1', content: ['你挂了，请选择'], btn: [{title: '不放弃，再来', },]},
        ],
      },
    ],
  },
]