### =============
### 调查问卷
### =============

scenes: [
    {
      id: 'questionnaire',
      name: '调查问卷',
      # 指定场景为NPC或MAP场景
      isNpc: true,
      #横图显示
      # sceneImage: 'BGT_8',
      #不显示时间
      # worldTimeHidden: true,
      # 当前场景地图
      # mapId: 'C000C_V_MAP_0_0',
      # 地图中心点，也是进入地图后的点
      # mapCenterPoint: [-1, 3],

      # 变量定义
      vars: [],

      # 动作定义
      actions: [],

      # 事件定义
      events: [{type: 'enter'}],

      # 对话选项
      chats: [],

      # 对话框
      dialogs: [
        {
          id: 'Screen1',
          style: 100,
          title: '调查问卷',
          desc: '进入调查问卷文本',
          # dialogType: 'FullScreen',
          # textAnimationType: 'TextFadeIn',
          sections: [
            {
              key: 1,
              content: "1、您平时喜欢看什么类型的小说",
              btn: [
                { title: 'A、男频小说', toKey: 2, dropIds: ['WZXX_M1_N1_C001A_V_Vdrop1',], },
                { title: 'B、女频小说', toKey: 3, dropIds: ['WZXX_M1_N1_C001A_V_Vdrop1',], },
              ],
            },
            {
              key: 2,
              content: "2、您的性别是",
              btn: [
                { title: 'A、男', toKey: 3, },
                { title: 'B、女', toKey: 3, },
              ],
            },
            {
              key: 3,
              content: "3、请问您在接下来的互动当中是否愿意，用女性视角开启阅读",
              btn: [
                { title: 'A、是', },
                { title: 'B、否', },
              ],
            },
          ],
        },
      ],
    },
]
