scenes: [
    #
    {
      id: 'WZXX_M1_N1_ZC33_V',
      name: "定义对应标题名当前章节内的选项和变量",

      # 变量定义
      vars: [
      { id: "v1", min: 0, max: 1 },
      { id: "v2", min: 0, max: 1 },
      { id: "v3", min: 0, max: 1 },
      { id: "biaoqianv1", min: 0, max: 1 } ,
      { id: "biaoqianv2", min: 0, max: 1 } ,
      { id: "biaoqianv3", min: 0, max: 1 } ,
      { id: "biaoqianv4", min: 0, max: 1 } ,
      { id: "biaoqianv5", min: 0, max: 1 } ,
      { id: "biaoqianv6", min: 0, max: 1 } ,
      { id: "biaoqianv7", min: 0, max: 1 } ,
      { id: "biaoqianv8", min: 0, max: 1 } ,
      ],

      # 动作定义
      actions: [],

      # 事件定义
      # 故事中的场景事件暂时没什么意义
      events: [
      ],
    
      chats: [
      
      {
        id: 'WZXX_M1_N1_ZC33_V1', desc: '诗', 
        options: [
          {
          title: "【能不能说人话】",dialogs: ['ZC33_1.1A'],varsOn: ['biaoqianv1',],
          icon: { id: 1, bindVar: 'biaoqianv1' }, 
          },

          {
          title: "【我读书少，能不能爽快点】",  varsOn: ['biaoqianv2',], dialogs: ['ZC33_1.1B'],
          icon: { id: 1, bindVar: 'biaoqianv2' }, 
          },

          {
          title: "【闹呢？搁着玩故弄玄虚那一套】",dialogs: ['ZC33_1.1C'], 
          icon: { id: 1, bindVar: 'biaoqianv3' }, varsOn: ['biaoqianv3']
          },

          {
          title: "【老头，不对啊，这有问题……】",dialogs: ['ZC33_1.1D'],
          icon: { id: 1, bindVar: 'biaoqianv4' }, varsOn: ['biaoqianv4']
          },
        ],
      },
      ],

      # 对话框
      dialogs:
        [
         #选项对话
          { 
            id: 'ZC33_1.1A',style: 6, title: '能不能说人话', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
            sections: [
              {
                key: 'P1', 
                content: ['“你老头子就不能说让人听懂的话吗？”',
                '“为什么非要用这诗词来表述，最终还不是迷惑人。”', '“这是我们行业的规矩啊。”',
                '“有时候你说太清楚了，万一有什么细节不对。”','“别人把这些小事细节咬住不放，那我们可不就亏了吗？”',
                '这老道士说的这么实在，这还真没法接话了。',],
                btn: [
                {
                title: '别卖关子了！',
                toChapter: "WZXX_M1_N1_Z2C34",
                },
                ]
              },
            ]  
          }, 

          { 
            id: 'ZC33_1.1B',style: 6, title: '我读书少，能不能爽快点', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
            sections: [
              {
                key: 'P1', 
                content: ['“说得好！”李森炎当即鼓掌。',
                '老头满意的点点头，露出欣慰得意的笑容。',
                '“就是说了一大堆……我没怎么听懂。”','老头：“……”',
                '李森炎看着他，“我读书少，你能不能爽快点！中译中一下？”',],
                btn: [
                {
                title: '别卖关子了！',toChapter: "WZXX_M1_N1_Z2C34",
                },
                ]
              },
            ]  
          }, 

          { 
            id: 'ZC33_1.1C',style: 6, title: '闹呢？', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
            sections: [
              {
                key: 'P1', 
                content: ['“嗯，这个打油诗不错，”李森炎先是赞许的点点头，然后抬头，“所以呢，线索在哪里？”',
                '老头措不及防，“这，这个就是线索啊。”', '“玩我呢？这能看得出什么线索？”',
                '“你仔细看看，其中自有乾坤。”','李森炎摆手，“你可别和我说这些有的没得，我可是花钱来你这找线索，可不是来你这里解密。”',
                '别给他整那一套，他在现代可是防诈先锋！',],
                btn: [
                {
                title: '别卖关子了！', toChapter: "WZXX_M1_N1_Z2C34",
                },
                ]
              },
            ]  
          }, 

          { 
            id: 'ZC33_1.1D',style: 6, title: '这有问题……', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
            sections: [
              {
                key: 'P1', 
                content: ['“你这个诗……”李森炎看着纸，露出愁容深思的模样。',
                '老头见他这样，也有点奇怪，不觉凑近，“怎么了？小道友有什么问题吗？”', '李森炎拿着纸也不说话，就是皱着眉，一会儿看看纸，一会儿看看老头。',
                '这模样别说，还把老头整的怪紧张的。','“小兄弟，你别不说话，你是发现了其中的什么玄妙之处吗？”',
                '李森炎摇摇头，把手上的纸转交个老头，缓缓才吐出一句。','“你这个最后一句，不押韵啊……”',
                '老头：“……”',],
                btn: [
                {
                title: '别卖关子了！', toChapter: "WZXX_M1_N1_Z2C34",
                },
                ]
              },
            ]  
          }, 

        ],
    }
]
