scenes: [
    #
    {
      id: 'WZXX_[START]',
      name: "小说专属场景",

      # 变量定义
      vars: [
      { id: 'v1', min: 0, max: 1 },
      # 变量定义
      { id: 'DEBUG', min: 0, max: 1 },
      # 变量定义已读标签
      { id: 'WZXX_001_Option_Already_Read_V1', min: 0, max: 1 },

      
    ],

      # 动作定义
      actions: [],

      # 事件定义
      # 故事中的场景事件暂时没什么意义
      events: [],

      # 对话选项
      chats: [
          #
      #
      { 
        id: 'WZXX_[START]', desc: '选项', 
        options: [ 
          { title: "【开始阅读】", toChapter: "WZXX_M1_N1_C001" },
        ],
      },
      #
      { 
        id: 'WZXX_[START]_DEBUG', desc: '选项', 
        options: [ 

          { title: "【世界选择功能】", varsOn: "WZXX_M1_N1_C001_[A1]" },
          { title: "【DEBUG阶段2】", toChapter: "WZXX_M1_N1_C001A" },
          { title: "【DEBUG阶段3】", toChapter: "WZXX_M1_N1_C001B" },
        ],
      },
      #
      { 
        id: 'TEST_PARAGRAPH', desc: '测试段落', plain: true,
        options: [ 

          { title: "罡风怒号，剑影挥动，血洒苍天！", dialogs: ["p1"] },
          { title: "<一阵疼痛袭来。>", shock: 'slightShock' },
          { title: "啊啊啊啊……这个感觉绝不想再来了，绝对！" },
        ],
      },
      { 
        id: 'WZXX_[START]_DEBUG2', desc: '选项', 
        options: [ 
      { 
            title: "【选择章节】", 
            selector: {
              data: [
                {
                  title: "第一章",
                  body: "现实场景，这里添加更多描述，这是一段很长的描述， 这是一段很长的描述，这是一段很长的描述。",
                  toChapter: "WZXX_M1_N1_C001",
                },
                {
                  title: "第二章",
                  body: "灵修场景，这里添加更多描述，这是一段很长的描述， 这是一段很长的描述，这是一段很长的描述，这是一段很长的描述，这是一段很长的描述，这是一段很长的描述。",
                  toChapter: "WZXX_M1_N1_C002",
                },
                {
                  title: "第三章",
                  body: "尘界场景，这里添加更多描述",
                  desc: "尘界场景，这里添加更多描述，尘界场景，这里添加更多描述，尘界场景，这里添加更多描述，尘界场景，这里添加更多描述",
                  toChapter: "WZXX_M1_N1_C003",
                },
              ]
            }
          },
          #
          { 
            title: "【选择世界】", 
            selector: {
              data: [
                {
                  worldId: 0,
                  title: "现实",
                  body: "现实场景，这里添加更多描述",
                  desc: "现实场景，这里添加更多描述, 现实场景，这里添加更多描述, 现实场景，这里添加更多描述, 现实场景，这里添加更多描述",
                  imgUrl: "https://picsum.photos/id/11/200/300",
                  toChapter: "WZXX_M1_N1_C001",
                },
                {
                  worldId: 1,
                  title: "尘界",
                  body: "尘界场景，这里添加更多描述",
                  desc: "尘界场景，这里添加更多描述，尘界场景，这里添加更多描述，尘界场景，这里添加更多描述，尘界场景，这里添加更多描述",
                  imgUrl: "https://picsum.photos/id/12/200/300",
                  toChapter: "WZXX_M1_N1_C003",
                },
                {
                  worldId: 2,
                  title: "灵修界",
                  body: "灵修场景，这里添加更多描述",
                  desc: "灵修场景，这里添加更多描述, 灵修场景，这里添加更多描述, 灵修场景，这里添加更多描述, 灵修场景，这里添加更多描述",
                  imgUrl: "https://picsum.photos/id/10/200/300",
                  toChapter: "WZXX_M1_N1_C002",
                },
              ]
            }
          },
        ],
      },

      { 
        id: 'WZXX_M1_N1_C999V', desc: '选项', 
        options: [ 
        #  { title: "【开始阅读333】", varsOn: ['WZXX_M1_N1_C001_[A1]'], },
          { title: "【回到开头】", toChapter: "WZXX_M1_N1_C001",},
 
        ],
      },

      #
          {
            id: "c4",
            desc: "",
            options: [{ title: "弹出对话框", dialogs: ["p1"] }],
          },
        ],

      # 对话框
      dialogs:
        [
 #
          { id: 'p1', title: '乞丐：', content: '这是落月镇的土地庙啊' },
        ],
    },
  ]
