scenes: [
    #策划手动配的
    {
      id: "WZXX_[Chapters]",
      name: "一些章节的变量放在这里集中管理",

      # 变量定义 ，每个章节默认对应一个变量，主要用于分支,章节解锁的检测,
      vars: [
           #
          { id: "WZXX_M1_N1_C001", min: 0, max: 1 },
          { id: "WZXX_M1_N1_C001FZ", min: 0, max: 1 },
          { id: "WZXX_M1_N1_C001A", min: 0, max: 1 },
          { id: "WZXX_M1_N1_C001AFZ", min: 0, max: 1 },

          { id: "WZXX_M1_N1_C001B_[A1]", min: 0, max: 1 },
          { id: "WZXX_M1_N1_C001B_[A1]FZ", min: 0, max: 1 },

          { id: "WZXX_M1_N1_C001B_[B1]", min: 0, max: 1 },
          { id: "WZXX_M1_N1_C001B_[B1]FZ", min: 0, max: 1 },
          { id: "WZXX_M1_N1_C001B_[B2]", min: 0, max: 1 },
          { id: "WZXX_M1_N1_C001B_[B2]FZ", min: 0, max: 1 },
          { id: "WZXX_M1_N1_C001B_[C1]", min: 0, max: 1 },
          { id: "WZXX_M1_N1_C001B_[C1]FZ", min: 0, max: 1 },

          { id: "WZXX_M1_N1_C001B_[C2]", min: 0, max: 1 },
          { id: "WZXX_M1_N1_C001B_[C2]FZ", min: 0, max: 1 },

          { id: "WZXX_M1_N1_C001B_[C3]", min: 0, max: 1 },
          { id: "WZXX_M1_N1_C001B_[C3]FZ", min: 0, max: 1 },
     

          { id: "WZXX_M1_N1_C001B_[N1]", min: 0, max: 1 },
          { id: "WZXX_M1_N1_C001B_[N1]FZ", min: 0, max: 1 },

          { id: "WZXX_M1_N1_C001B", min: 0, max: 1 },
          { id: "WZXX_M1_N1_C001BFZ", min: 0, max: 1 },
          { id: "WZXX_M1_N1_C001C_[N1]", min: 0, max: 1 },
          { id: "WZXX_M1_N1_C001C_[N1]FZ", min: 0, max: 1 },
          { id: "WZXX_M1_N1_C001C_[N2]", min: 0, max: 1 },
          { id: "WZXX_M1_N1_C001C_[N2]FZ", min: 0, max: 1 },
          { id: "WZXX_M1_N1_C001C_[N3]", min: 0, max: 1 },
          { id: "WZXX_M1_N1_C001C_[N3]FZ", min: 0, max: 1 },

          { id: "WZXX_M1_N1_C001C", min: 0, max: 1 },
          { id: "WZXX_M1_N1_C001CFZ", min: 0, max: 1 },
           #
          { id: "WZXX_M1_N1_C002_[N1]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C002_[N1]FZ",min: 0, max: 1 },

          # { id: "WZXX_M1_N1_C002_[N2]",min: 0, max: 1 },
          # { id: "WZXX_M1_N1_C002_[N2]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C002_[N3]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C002_[N3]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C002_[N4]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C002_[N4]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C002_[N5]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C002_[N5]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C002_[N6]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C002_[N6]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C002_[N7]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C002_[N7]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C002_[N8]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C002_[N8]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C002_[N9]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C002_[N9]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C002_[N10]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C002_[N10]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C003_[N1]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C003_[N1]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C003_[N2]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C003_[N2]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C003_[N3]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C003_[N3]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C004_[N1]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C004_[N1]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C004_[N2]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C004_[N2]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C005",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C005FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C006",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C006FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C007",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C007FZ",min: 0, max: 1 },
            #

        
            #
          { id: "WZXX_M1_N1_C008_[N0]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C008_[N0]FZ",min: 0, max: 1 },
            #
          { id: "WZXX_M1_N1_C009_[N1]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C009_[N1]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C009_[N2]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C009_[N2]FZ",min: 0, max: 1 },

          # { id: "WZXX_M1_N1_C009_[N3]",min: 0, max: 1 },
          # { id: "WZXX_M1_N1_C009_[N3]FZ",min: 0, max: 1 },

            #
          { id: "WZXX_M1_N1_C010",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C010FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C011_[N1]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C011_[N1]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C011_[N2]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C011_[N2]FZ",min: 0, max: 1 },
        
          { id: "WZXX_M1_N1_C012_[N1]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C012_[N1]FZ",min: 0, max: 1 },
          
          { id: "WZXX_M1_N1_C012_[N2]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C012_[N2]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C013_[N1]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C013_[N1]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C013_[N2]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C013_[N2]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C014_[N1]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C014_[N1]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C014A",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C014AFZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C015_[N1]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C015_[N1]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C015_[N2]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C015_[N2]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C015_[N3]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C015_[N3]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C015_[N4]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C015_[N4]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C015_[N5]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C015_[N5]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C015_[V1]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C015_[V1]FZ",min: 0, max: 1 },


          { id: "WZXX_M1_N1_C016_[N1]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C016_[N1]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C016_[N2]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C016_[N2]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C016_[N3]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C016_[N3]FZ",min: 0, max: 1 },
          #
          { id: "WZXX_M1_N1_C017_[N1]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C017_[N1]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C017_[N2]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C017_[N2]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C018_[N1]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C018_[N1]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C018_[N2]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C018_[N2]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C019_[N1]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C019_[N1]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C019_[N2]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C019_[N2]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C020",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C020FZ",min: 0, max: 1 },
            #
          { id: "WZXX_M1_N1_C021",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C021FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C022",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C022FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C023_[N1]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C023_[N1]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C023_[N2]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C023_[N2]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C024_[N1]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C024_[N1]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C025",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C025FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C026",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C026FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C027",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C027FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C028",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C028FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C029",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C029FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C030",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C030FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C031_[N1]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C031_[N1]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C032",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C032FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C033",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C033FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C034",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C034FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C035",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C035FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C036",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C036FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C037",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C037FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C038",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C038FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C039",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C039FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C040",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C040FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C988",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C988FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C989",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C989FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C990",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C990FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C991",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C991FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C992",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C992FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C993",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C993FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C994",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C994FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C995",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C995FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C996",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C996FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C997",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C997FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C998",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C998FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C999",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C1000",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C1000FZ",min: 0, max: 1 },
           
          { id: "WZXX_M1_N2_C014",min: 0, max: 1 },
          { id: "WZXX_M1_N2_C014FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N2_C015",min: 0, max: 1 },
          { id: "WZXX_M1_N2_C015FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N2_C016",min: 0, max: 1 },
          { id: "WZXX_M1_N2_C016FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N2_C017",min: 0, max: 1 },
          { id: "WZXX_M1_N2_C017FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N2_C018",min: 0, max: 1 },
          { id: "WZXX_M1_N2_C018FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N2_C019",min: 0, max: 1 },
          { id: "WZXX_M1_N2_C019FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N2_C020",min: 0, max: 1 },
          { id: "WZXX_M1_N2_C020FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N2_C021",min: 0, max: 1 },
          { id: "WZXX_M1_N2_C021FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N2_C022",min: 0, max: 1 },
          { id: "WZXX_M1_N2_C022FZ",min: 0, max: 1 },
        ],

      #
      # 动作定义
      actions: [],

      # 事件定义
      # 故事中的场景事件暂时没什么意义
      events: [],

      # 对话选项
      chats: [
          #
          { id: "WZXX_ChaptersVar ", desc: "选项", options: [] },
        ],

      # 对话框
      dialogs: [],
    },
  ]
