scenes: [
    #
    {
      id: 'WZXX_M1_N1_C000B_V',
      name: "定义对应标题名当前章节内的选项和变量",

      # 变量定义
      vars: [
      { id: "v1", min: 0, max: 1 },

      ],

      # 动作定义
      actions: [],

      # 事件定义# 故事中的场景事件暂时没什么意义
      events: [],

      chats: [
   { 
        id: 'WZXX_M1_N1_C000B_V1', desc: '打工还是守夜', 
        options: [ 
          { title: "【去打工】",toScene: 'C000B_V_MAP_-1_2',},
          { title: "【去守夜】",toChapter: "WZXX_M1_N1_C011_[N2]",},
        ],
      },

        ],

  
    },

 #===========事件场景==============
       {
  # NPC2
    id: 'C000B_V_MAP_0_0', name: '坊市出入口',

    # 指定场景为NPC或MAP场景
    isNpc: true,
    #不显示时间
      worldTimeHidden: true,
    # 当前场景地图
    mapId: 'C000B_V_MAP_0_0',
    # 地图中心点，也是进入地图后的点
    mapCenterPoint: [0, 0],

     # 变量定义
    vars: [
    { id: "ONE_OPEN_0", min: 0, max: 1 },
    { id: "ONE_OPEN_1", min: 0, max: 1 },

    ],

    # 动作定义
    actions: [
    ],
    # 事件定义
    events: [
       { type: 'enter',  nextChat: 'B1' },
     #   { type: 'enter', andVarsOff: ['ONE_OPEN_0',"N1B2_V",], andVarsOn: ['N1C1_V'], dialogs: ['Screen1'] },

    ],

    # 对话选项
    chats: [
      #
      { 
        id: 'B1', desc: '坊市出入口', 
        options: [ 
         { title: '【继续往前走】', nextChat: 'B2'}, 
         { title: '【打量一下风景】', nextChat: 'B3'}, 


        ],
      },
      #
      { 
        id: 'B3', desc: '外边没什么好看的，还是去坊市里边看看吧', 
        options: [ 
         { title: '<<<出发', nextChat: 'B2' }, 
        ]
      },
      #

      { 
        id: 'B2', desc: '选择移动位置', 
        options: [ 
        { title: '【空白摊位】', nextChat: 'B2A'},  #这里需要做个判定，第一次点进去，触发“这摊位空空如也，东西应该是卖完了”，链接坊市主道。
        { title: '【坊市主道】',  toChapter: 'WZXX_M1_N1_C008_[N0]'}, #接剧情
      { 
        id: 'B2A', desc: '这摊位空空如也，东西应该是卖完了', 
        options: [ 
         { title: '<<<走吧', toChapter: 'WZXX_M1_N1_C008_[N0]' }, 
        ]
      },
        
        ],
      },

#剧情到准备去医馆的时候接回这里
  #  { 
      #  id: 'B4', desc: '选择移动位置', 
     #   options: [ 
      #  { title: '【医馆】', toScene: 'C000B_V_MAP_-1_2'},  #这里继续接医馆剧情
    #    { title: '【东街】',  toScene: 'C000B_V_MAP_1_2'}, #这里需要一个判定，判定是第一次来，触发“小命要紧，事不宜迟，还是不要闲逛了”，同样接回医馆剧情

        #医馆剧情之后，到打工部分剧情
        

   #     ],
  #    },

       #
    ],
   
  },
 #===========事件场景==============
       {
  # NPC2
    id: 'C000B_V_MAP_-1_2', name: '医馆',

    # 指定场景为NPC或MAP场景
    isNpc: true,
    #不显示时间
      worldTimeHidden: true,
    # 当前场景地图
    mapId: 'C000B_V_MAP_0_0',
    # 地图中心点，也是进入地图后的点
    mapCenterPoint: [-1, 2],

     # 变量定义
    vars: [
    { id: "ONE_OPEN_0", min: 0, max: 1 },
    { id: "ONE_OPEN_1", min: 0, max: 1 },

    ],

    # 动作定义
    actions: [
    ],
    # 事件定义
    events: [
       { type: 'enter',  nextChat: 'C1' },
     #   { type: 'enter', andVarsOff: ['ONE_OPEN_0',"N1B2_V",], andVarsOn: ['N1C1_V'], dialogs: ['Screen1'] },

    ],

    # 对话选项
    chats: [
      #
      { 
        id: 'C1', desc: '医馆', 
        options: [ 
         { title: '【对话】', nextChat: 'C2'}, 
         { title: '【去哪里赚钱？】', nextChat: 'X1'}, 

         #{ title: '【对话】',nextChat: 'C2' toChapter: "WZXX_M1_N1_C001B_[C2]" }, 

        ],
      },
      #
      { 
        id: 'C2', desc: '赶快去赚钱，别在这待了', 
        options: [ 
         { title: '<<<行吧', nextChat: 'X1' }, 
        ]
      },
      #

      { 
        id: 'X1', desc: '选择移动位置', 
        options: [ 
        { title: '【饭馆】', toScene: 'C000B_V_MAP_-2_3'}, 
         { title: '【当铺】', toScene: 'C000B_V_MAP_-1_3'}, 
         { title: '【珍宝阁】', toScene: 'C000B_V_MAP_0_3'}, 
         { title: '【兵器铺】', toScene: 'C000B_V_MAP_-1_4'},
         #{ title: '【医馆】', toScene: 'C000B_V_MAP_-1_2'}, 
        ],
      },
       #
    ],
   
  },


#===========事件场景==============
       {
  # NPC2
    id: 'C000B_V_MAP_-2_3', name: '饭馆',
    # 指定场景为NPC或MAP场景
    isNpc: true,
    #不显示时间
      worldTimeHidden: true,
    # 当前场景地图
    mapId: 'C000B_V_MAP_0_0',
    # 地图中心点，也是进入地图后的点
    mapCenterPoint: [-2, 3],
     # 变量定义
    vars: [
    { id: "ONE_OPEN_0", min: 0, max: 1 },
    { id: "ONE_OPEN_1", min: 0, max: 1 },
    ],
    # 动作定义
    actions: [ ],
    # 事件定义
    events: [
       { type: 'enter',  nextChat: 'C1' },
    ],
    # 对话选项
    chats: [
      { 
        id: 'C1', desc: '饭馆', 
        options: [ 
         { title: '【饭馆掌柜】', nextChat: 'C2'}, 
         { title: '【离开】', nextChat: 'X1'}, 
         #{ title: '【对话】',nextChat: 'C2' toChapter: "WZXX_M1_N1_C001B_[C2]" }, 
        ],
      },
      #
      { 
        id: 'C2', desc: '有什么事？', 
        options: [ 
         { title: '聊聊做工的事', nextChat: 'C3',}, 
         { title: '<<<离开', nextChat: 'C1' }, 
        ],
      },
      #
      { 
        id: 'C3', desc: '我这倒是有些工作可以做，你看看能做什么？', 
        options: [ 
         { title: '算账的工作',dialogs: ['Screen1'] }, 
         { title: '跑堂的工作',dialogs: ['Screen2'] }, 
         { title: '<<<离开', nextChat: 'C1' }, 
        ],
      },



      #
      { 
        id: 'X1', desc: '选择移动位置', 
        options: [ 
        # { title: '【饭馆】', toScene: 'C000B_V_MAP_-2_3'}, 
         { title: '【当铺】', toScene: 'C000B_V_MAP_-1_3'}, 
         { title: '【珍宝阁】', toScene: 'C000B_V_MAP_0_3'}, 
         { title: '【兵器铺】', toScene: 'C000B_V_MAP_-1_4'},
         { title: '【医馆】', toScene: 'C000B_V_MAP_-1_2'}, 
        ],
      },
       #
    ],
      # 对话框===========
      dialogs:
        [
           #选项对话1
          { id: 'Screen1',style: 6, title: '算账的工作', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
          sections: [
          { key: 'P1', content: ['“算账？你会吗？”','“当然，我数学一流。”递给掌柜一个靠谱的眼神','“好！”掌柜拍拍手，让人拿来了三大堆账本','“你今天的工作，就是把这些算出来。”','……好多啊','一上午过去……','脑昏头晕，肚子饿','掌柜的给了点小食','吃过继续算……','天昏地暗，三大堆终于算完了！！！',
          ],
          btn: [{title: '下班，结工资',tokey: "P2"},]},

          { key: 'P2', content: ['掌柜的看了你一眼，那副市侩的脸露出奸奸的笑，扣这扣那的，最后从钱柜里丢出几个灵石',[{ sounds: [{ soundId: 'SE_CQ_0016',}] }] ,'才五个灵石？！',
          '这不是欺负老实人嘛！你可是足足累了一天','“就这么点，你店里大大小小的活可都是我干的，不是说好二十起步吗，才五个？”','你愤愤不平','掌柜摇扇，冷笑，“二十个？做梦吧你，你这种生手，五个我都已经算是给多啦。”','请选择行动——',
          ],
          btn: [{title: '忍一时越想越气，干他',tokey: "P3",dropId: 'WZXX_M1_N1_C005_V_Vdrop1'},
          {title: '忍一时风平浪静，算了',tokey: "P4",dropId: 'WZXX_M1_N1_C005_V_Vdrop2'}]},

          { key: 'P3', content: ['士可忍孰不可忍！这黑心吸血鬼，你攥起拳头准备上前','但老板一摇扇，周围几个健硕的保镖，瞬间站到了你面前','“……”','算了，大人不记小人过……','不和他们计较，还是回去给医灵守夜吧',
          ],
          btn: [{title: '回医馆',toChapter: "WZXX_M1_N1_C011_[N2]" },]},

          { key: 'P4', content: ['你愤怒至极，这一天五个灵石，你要一百天才能凑齐五百个','一百天，自己怕是早就毒发身亡，坟头草都得有两米高了！','给这群人干活，还不如给美女大夫做事，至少还能救命，这些人都是吃肉不吐骨头的恶臭资本家！！！',
          ],
          btn: [{title: '回医馆',toChapter: "WZXX_M1_N1_C011_[N2]"},]},



           ], },

           #选项对话1
          { id: 'Screen2',style: 6, title: '跑堂的工作', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
          sections: [
          { key: 'P1', content: ['“跑堂吧，我手脚很麻利的！”','掌柜上下扫视你一眼，勉强点了点头。',
          '你换上个跑堂的衣服，小毛巾肩上一搭，有跑堂内味了','上午客人不多，零零散散还算轻松','中午客人爆满，快忙不过来了','忙的满头大汗，饥肠辘辘','继续干活——','客人不多了，你刚吃几口饭，又被叫去干活了','又忙了两个时辰','该下班了',],
          btn: [{title: '下班，结工资',tokey: "P2"},]},

          { key: 'P2', content: ['掌柜的看了你一眼，那副市侩的脸露出奸奸的笑，扣这扣那的，最后从钱柜里丢出几个灵石',[{ sounds: [{ soundId: 'SE_CQ_0016',}] }] ,'才五个灵石？！',
          '这不是欺负老实人嘛！你可是足足累了一天','“就这么点，你店里大大小小的活可都是我干的，不是说好二十起步吗，才五个？”','你愤愤不平','掌柜摇扇，冷笑，“二十个？做梦吧你，你这种生手，五个我都已经算是给多啦。”','请选择行动——',
          ],
          btn: [{title: '忍一时越想越气，干他',tokey: "P3",dropId: 'WZXX_M1_N1_C005_V_Vdrop3'},
          {title: '忍一时风平浪静，算了',tokey: "P4",dropId: 'WZXX_M1_N1_C005_V_Vdrop4'}]},

          { key: 'P3', content: ['士可忍孰不可忍！这黑心吸血鬼，你攥起拳头准备上前','但老板一摇扇，周围几个健硕的保镖，瞬间站到了你面前','“……”','算了，大人不记小人过……','不和他们计较，还是回去给医灵守夜吧',
          ],
          btn: [{title: '回医馆',toChapter: "WZXX_M1_N1_C011_[N2]"},]},

          { key: 'P4', content: ['你愤怒至极，这一天五个灵石，你要一百天才能凑齐五百个','一百天，自己怕是早就毒发身亡，坟头草都得有两米高了！','给这群人干活，还不如给美女大夫做事，至少还能救命，这些人都是吃肉不吐骨头的恶臭资本家！！！',
          ],
          btn: [{title: '回医馆',toChapter: "WZXX_M1_N1_C011_[N2]"},]},


           ], },

  ],
  },


#===========事件场景==============
       {
  # NPC2
    id: 'C000B_V_MAP_-1_3', name: '当铺',
    # 指定场景为NPC或MAP场景
    isNpc: true,
    #不显示时间
      worldTimeHidden: true,
    # 当前场景地图
    mapId: 'C000B_V_MAP_0_0',
    # 地图中心点，也是进入地图后的点
    mapCenterPoint: [-1, 3],
     # 变量定义
    vars: [
    { id: "ONE_OPEN_0", min: 0, max: 1 },
    { id: "ONE_OPEN_1", min: 0, max: 1 },
    ],
    # 动作定义
    actions: [ ],
    # 事件定义
    events: [
       { type: 'enter',  nextChat: 'C1' },
    ],
    # 对话选项
    chats: [
      { 
        id: 'C1', desc: '当铺', 
        options: [ 
         { title: '【对话】', nextChat: 'C2'}, 
         { title: '【离开】', nextChat: 'X1'}, 
         #{ title: '【对话】',nextChat: 'C2' toChapter: "WZXX_M1_N1_C001B_[C2]" }, 
        ],
      },
     { 
        id: 'C2', desc: '有什么事？', 
        options: [ 
         { title: '聊聊做工的事', nextChat: 'C3',}, 
         { title: '<<<离开', nextChat: 'C1' }, 
        ],
      },
      #
      { 
        id: 'C3', desc: '我这倒是有些工作可以做，你看看能做什么？', 
        options: [ 
         { title: '打杂的工作',dialogs: ['Screen1'] }, 
         { title: '验货的工作',dialogs: ['Screen2'] }, 
         { title: '<<<离开', nextChat: 'C1' }, 
        ],
      },
      #
      { 
        id: 'X1', desc: '选择移动位置', 
        options: [ 
         { title: '【饭馆】', toScene: 'C000B_V_MAP_-2_3'}, 
        # { title: '【当铺】', toScene: 'C000B_V_MAP_-1_3'}, 
         { title: '【珍宝阁】', toScene: 'C000B_V_MAP_0_3'}, 
         { title: '【兵器铺】', toScene: 'C000B_V_MAP_-1_4'},
         { title: '【医馆】', toScene: 'C000B_V_MAP_-1_2'}, 
        ],
      },
       #

       
    ],
# 对话框===========
      dialogs:
        [
           #选项对话1
          { id: 'Screen1',style: 6, title: '打杂的工作', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
          sections: [
          { key: 'P1', content: ['“随便干点什么都行”','“那就打杂吧。”当铺老板看了你一眼','随后让人把你安排到后面的仓库','开启一天的工作','你先把仓库全都打扫了一遍','然后被叫去搬货','货很多，你在烈日底下搬货','老板给了些吃食','吃完，继续搬货……','累的天昏地暗，终于算完了！！！',
          ],
          btn: [{title: '下班，结工资',tokey: "P2"},]},

          { key: 'P2', content: ['掌柜的看了你一眼，那副市侩的脸露出奸奸的笑，扣这扣那的，最后从钱柜里丢出几个灵石',[{ sounds: [{ soundId: 'SE_CQ_0016',}] }] ,'才五个灵石？！',
          '这不是欺负老实人嘛！你可是足足累了一天','“就这么点，你店里大大小小的活可都是我干的，不是说好二十起步吗，才五个？”','你愤愤不平','掌柜摇扇，冷笑，“二十个？做梦吧你，你这种生手，五个我都已经算是给多啦。”','请选择行动——',
          ],
          btn: [{title: '忍一时越想越气，干他',tokey: "P3",dropId: 'WZXX_M1_N1_C005_V_Vdrop5'},
          {title: '忍一时风平浪静，算了',tokey: "P4",dropId: 'WZXX_M1_N1_C005_V_Vdrop6'}]},

          { key: 'P3', content: ['士可忍孰不可忍！这黑心吸血鬼，你攥起拳头准备上前','但老板一摇扇，周围几个健硕的保镖，瞬间站到了你面前','“……”','算了，大人不记小人过……','不和他们计较，还是回去给医灵守夜吧',
          ],
          btn: [{title: '回医馆',toChapter: "WZXX_M1_N1_C011_[N2]"},]},

          { key: 'P4', content: ['你愤怒至极，这一天五个灵石，你要一百天才能凑齐五百个','一百天，自己怕是早就毒发身亡，坟头草都得有两米高了！','给这群人干活，还不如给美女大夫做事，至少还能救命，这些人都是吃肉不吐骨头的恶臭资本家！！！',
          ],
          btn: [{title: '回医馆',toChapter: "WZXX_M1_N1_C011_[N2]"},]},



           ], },

           #选项对话1
          { id: 'Screen2',style: 6, title: '验货的工作', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
          sections: [
          { key: 'P1', content: ['“我这个人很细心的，能胜任验货”','掌柜上下扫视你一眼，勉强点了点头。',
          '老板让人把你带进仓库','你的任务是把仓库中的货全都验出来','开始工作……','仓库又闷又热，你硬着头皮继续干活','干了一上午，闷了一身汗，吃点东西喝口水继续——','老板派人来检查，上午的货你验错了，不得不重头再来','又忙了两个时辰','终于忙完了，下班！',],
          btn: [{title: '下班，结工资',tokey: "P2"},]},

          { key: 'P2', content: ['掌柜的看了你一眼，那副市侩的脸露出奸奸的笑，扣这扣那的，最后从钱柜里丢出几个灵石',[{ sounds: [{ soundId: 'SE_CQ_0016',}] }] ,'才五个灵石？！',
          '这不是欺负老实人嘛！你可是足足累了一天','“就这么点，你店里大大小小的活可都是我干的，不是说好二十起步吗，才五个？”','你愤愤不平','掌柜摇扇，冷笑，“二十个？做梦吧你，你这种生手，五个我都已经算是给多啦。”','请选择行动——',
          ],
          btn: [{title: '忍一时越想越气，干他',tokey: "P3",dropId: 'WZXX_M1_N1_C005_V_Vdrop7'},
          {title: '忍一时风平浪静，算了',tokey: "P4",dropId: 'WZXX_M1_N1_C005_V_Vdrop8'}]},

          { key: 'P3', content: ['士可忍孰不可忍！这黑心吸血鬼，你攥起拳头准备上前','但老板一摇扇，周围几个健硕的保镖，瞬间站到了你面前','“……”','算了，大人不记小人过……','不和他们计较，还是回去给医灵守夜吧',
          ],
          btn: [{title: '回医馆',toChapter: "WZXX_M1_N1_C011_[N2]"},]},

          { key: 'P4', content: ['你愤怒至极，这一天五个灵石，你要一百天才能凑齐五百个','一百天，自己怕是早就毒发身亡，坟头草都得有两米高了！','给这群人干活，还不如给美女大夫做事，至少还能救命，这些人都是吃肉不吐骨头的恶臭资本家！！！',
          ],
          btn: [{title: '回医馆',toChapter: "WZXX_M1_N1_C011_[N2]"},]},


           ], },

  ],
  },



#===========事件场景==============
       {
  # NPC2
    id: 'C000B_V_MAP_0_3', name: '珍宝阁',
    # 指定场景为NPC或MAP场景
    isNpc: true,
    #不显示时间
      worldTimeHidden: true,
    # 当前场景地图
    mapId: 'C000B_V_MAP_0_0',
    # 地图中心点，也是进入地图后的点
    mapCenterPoint: [0, 3],
     # 变量定义
    vars: [
    { id: "ONE_OPEN_0", min: 0, max: 1 },
    { id: "ONE_OPEN_1", min: 0, max: 1 },
    ],
    # 动作定义
    actions: [ ],
    # 事件定义
    events: [
       { type: 'enter',  nextChat: 'C1' },
    ],
    # 对话选项
    chats: [
      { 
        id: 'C1', desc: '珍宝阁', 
        options: [ 
         { title: '【珍宝阁告示】', nextChat: 'C2'}, 
         { title: '【移动】', nextChat: 'X1'}, 
         #{ title: '【对话】',nextChat: 'C2' toChapter: "WZXX_M1_N1_C001B_[C2]" }, 
        ],
      },
      #
      { 
        id: 'C2', desc: '招募有经验的鉴定者，最低需要筑基期修为', 
        options: [ 
         { title: '<<<离开', nextChat: 'C1' }, 
        ],
      },
      #
      { 
        id: 'X1', desc: '选择移动位置', 
        options: [ 
         { title: '【饭馆】', toScene: 'C000B_V_MAP_-2_3'}, 
         { title: '【当铺】', toScene: 'C000B_V_MAP_-1_3'}, 
        # { title: '【珍宝阁】', toScene: 'C000B_V_MAP_0_3'}, 
         { title: '【兵器铺】', toScene: 'C000B_V_MAP_-1_4'},
         { title: '【医馆】', toScene: 'C000B_V_MAP_-1_2'}, 
        ],
      },
       #
    ],

  },


#===========事件场景==============
       {
  # NPC2
    id: 'C000B_V_MAP_-1_4', name: '兵器铺',
    # 指定场景为NPC或MAP场景
    isNpc: true,
    #不显示时间
      worldTimeHidden: true,
    # 当前场景地图
    mapId: 'C005_V_MAP_0_0',
    # 地图中心点，也是进入地图后的点
    mapCenterPoint: [-1, 4],
     # 变量定义
    vars: [
    { id: "ONE_OPEN_0", min: 0, max: 1 },
    { id: "ONE_OPEN_1", min: 0, max: 1 },
    ],
    # 动作定义
    actions: [ ],
    # 事件定义
    events: [
       { type: 'enter',  nextChat: 'C1' },
    ],
    # 对话选项
    chats: [
      { 
        id: 'C1', desc: '兵器铺', 
        options: [ 
         { title: '【兵器铺告示】', nextChat: 'C2'}, 
         { title: '【移动】', nextChat: 'X1'}, 
         #{ title: '【对话】',nextChat: 'C2' toChapter: "WZXX_M1_N1_C001B_[C2]" }, 
        ],
      },
      #
      { 
        id: 'C2', desc: '招募练器师傅，需要练器师一阶，筑基期修为', 
        options: [ 
         { title: '<<<离开', nextChat: 'C1' }, 
        ],
      },
      #
      { 
        id: 'X1', desc: '选择移动位置', 
        options: [ 
         { title: '【饭馆】', toScene: 'C000B_V_MAP_-2_3'}, 
         { title: '【当铺】', toScene: 'C000B_V_MAP_-1_3'}, 
         { title: '【珍宝阁】', toScene: 'C000B_V_MAP_0_3'}, 
         #{ title: '【兵器铺】', toScene: 'C000B_V_MAP_-1_4'},
         { title: '【医馆】', toScene: 'C000B_V_MAP_-1_2'}, 
        ],
      },
       #
    ],

  },


    #=================================场景地图的设置==================================
    maps: [
      {
        id: 'C000B_V_MAP_0_0',
        data: [
          { point: [0, 0], title: '坊市出入口', toScene: 'C000B_V_MAP_0_0', links: [ 0, 1] },
          { point: [0, 1], title: '天机阁摊位', toScene: 'C000B_V_MAP_0_1', links: [0, 2 ] },
          { point: [0, 2], title: '坊市主道', toScene: 'C000B_V_MAP_0_2', links: [-1, 2], [1, 2] },
          { point: [1, 2], title: '东街', toScene: 'C000B_V_MAP_1_2', links: [ 2, 2] },
          { point: [2, 2], title: '酒肆', toScene: 'C000B_V_MAP_2_2', links: [ ] },
          { point: [-1, 2], title: '医馆', toScene: 'C000B_V_MAP_-1_2', links: [0, 2], [-2, 2], [-1, 3]},
          { point: [-2, 2], title: '西街', toScene: 'C000B_V_MAP_-2_2', links: [-3, 2] },
          { point: [-3, 2], title: '赌摊', toScene: 'C000B_V_MAP_-3_2', links: [ ] },
          { point: [-1, 3], title: '当铺', toScene: 'C000B_V_MAP_-1_3', links: [-1, 4], [-2, 3], [0, 3] },
          { point: [-2, 3], title: '饭馆', toScene: 'C000B_V_MAP_-2_3', links: [ ] },
          { point: [-1, 4], title: '兵器铺', toScene: 'C000B_V_MAP_-1_4', links: [-1, 5] },
          { point: [-1, 5], title: '小集市', toScene: 'C000B_V_MAP_-1_5', links: [ ] },
          { point: [0, 3], title: '珍宝阁', toScene: 'C000B_V_MAP_0_3', links: [1, 3] },
          { point: [1, 3], title: '客栈', toScene: 'C000B_V_MAP_1_3', links: [ ] },
        ]
      },
    ]
    ]
   #  { 
       #  id: 'X1', desc: '选择移动位置', 
    #     options: [ 
        # { title: '【饭馆】', toScene: 'C000B_V_MAP_-2_3'}, 
        #  { title: '【当铺】', toScene: 'C000B_V_MAP_-1_3'}, 
        #  { title: '【珍宝阁】', toScene: 'C000B_V_MAP_0_3'}, 
        #  { title: '【兵器铺】', toScene: 'C000B_V_MAP_-1_4'},
        #  { title: '【医馆】', toScene: 'C000B_V_MAP_-1_2'}, 
       #  ],
       #},