scenes: [
    #
    {
      id: 'WZXX_M1_N1_C0023_V',
      name: "定义对应标题名当前章节内的选项和变量",

      # 变量定义
      vars: [{ id: "v1", min: 0, max: 1 }],

      # 动作定义
      actions: [],

      # 事件定义
      # 故事中的场景事件暂时没什么意义
      events: [],


    
      chats: [
      #

      { 
        id: 'WZXX_M1_N1_C0023_V1', desc: '小队的邀请', 
        options: [ 
          { title: "【加入小队】",dialogs: ['C0023A_jiaruA']},
          { title: "【不加入小队】",dialogs: ['C0023A_bujiaruA']},
        ],
      },

      


        ],








      # 对话框
      dialogs:
        [
           #选项对话
          { id: 'C0023A_jiaruA',style: 6, title: '小队的邀请', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
          sections: [
          { key: 'P1', content: ['在邀请李森炎的同时，杨真也让赖崇信向李森炎致歉。','赖崇信虽然内心不愿，不过碍于队长的面子，再加上出于现实的考量——有李森炎加入的话，他们寻宝的胜算也会更大一些。',
          '基于这两点，他纵使内心怨气再深，也得先拉下这个脸来，跟李森炎赔不是，称自己是看走了眼，让李森炎原谅。','“谈不上原谅。”','李森炎淡淡说道，这话倒是不假，他根本就没把这人看在眼里，对一个他完全不会在意的人，根本没有什么值得原谅或者不原谅的。',
          '至于他们团队的邀请，李森炎想了想，既然大家都是散修，抱个团探宝也未尝不可。','互相之间也有个照应，总比一个人行动要来得好些。',
          ],
          btn: [{title: '既然如此，那就出发吧',tokey: "P2",},]},

          { key: 'P2', content: ['李森炎跟随小队来到所谓的宝窟，洞窟入口有天然遮掩，被蔓藤覆盖，相当隐秘，若无人指引，还真不容易找到。','入口还算宽敞，可容数人通行，在入口处听不到里面的动静，想来这洞窟有些深度。','“我们已经把里面的人面白蛛都引出来了并且杀掉了，但里面还有一只人面蛛王，很棘手，大家要小心。”',
          '杨真神情严肃开口，这话虽然是对所有人说的，但最主要的还是针对李森炎说的，因为他不清楚这里面的情况。','“人面猪王？猪刚鬣吗？”','众人都不知道猪刚鬣是什么意思，一时间都有些莫名其妙地看着他。','好吧，气氛似乎更紧张了。',
          ],
          btn: [{title: '算了，当我没说',tokey: "P3",}]},

          { key: 'P3', content: ['一行人陆续深入，洞窟内部阴寒之气颇重，萦绕在鼻息间的气味不是很好闻，有股潮湿而糜烂的味道。',
          '越往深处走，这股阴寒气越是让人四肢发僵，这阴寒程度，丝毫不逊色于李森炎在医灵房间门口感受到的那股。',
          '四壁湿润滑腻，不断有冰水低落下来，感觉好像走入了黑暗雨林之中。','继续深入，顶上石壁已不再落水，而是已经结霜。',
           [{ sounds: [{ soundId: 'SE_CQ_0002',}] }] ,
          '前方忽现一些亮色，众人不约而同放慢了脚步，影影绰绰地可看见不似人形的东西一闪而过。',
          
          ],
          btn: [{title: '小心！',toChapter: "WZXX_M1_N1_C024_[V1]",}]},
           ]  
        },
#选项对话
          { id: 'C0023A_bujiaruA',style: 6, title: '不加入', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
          sections: [
          { key: 'B1', content: ['话说得好听，李森炎却听不入耳，对这个小队并无好感，耻与为伍，他本来就是看在江依依的面子上过来，可却有人狗眼看人低，现在再想补救，为时已晚。',
          '“不必了，我没兴趣。”',
          '李森炎转身就走，无论杨真在背后如何挽留。','走了一阵，身后传来脚步声。','“我不是说了我没兴趣加入你们吗？”','李森炎回头，来的人却不是杨真，而是江依依。','见到是她，李森炎脸色稍微缓和了些。',
          ],
          btn: [{title: '“你来应该不是打算劝我的吧？”',tokey: "B2",},]},

          { key: 'B2', content: ['江依依摇了摇头：“我知道你心意已决，我过来只是想跟你说一声抱歉，我好心办了坏事，实在是没有脸见你，又怎么可能再纠缠你了。”','李森炎摇头：“这件事与你无关。”',
          '江依依低着头，而后拿出一枚晶莹剔透的碧色环形玉珏，不由分说地塞到李森炎手里。','“李大哥对我有救命之恩，却只是收了我那么一点灵石，我心里过意不去，这玉珏，请李大哥收下。”',
          ],
          btn: [{title: '不收下', tokey: "B3",}]},

          { key: 'B3', content: ['“不必了，那灵石我拿得心安理得，这个，我就不能再收了。”','拿人手短吃人嘴软，既然已经下定决心离开，就不必再拿人东西，以免纠缠不清。',
          '江依依似乎看出了李森炎的顾虑，连忙解释道。',
          '“这个不是很值钱的，李大哥你不必有任何负担，我就是……做个纪念。”','说着她目光向下看去。',
          ],
          btn: [{title: '顺着她的目光看下去',tokey: "B4",}]},

          { key: 'B4', content: ['李森炎顺着她的目光低头看向她腰间，嗯，确实好腰……呸，我是来看腰的吗？','这时李森炎才注意到，这玉珏是成对的，她腰间也有一枚一模一样的，李森炎也不是未经世事的傻愣子，一下就明白她的心意。',
          '最难消受美人恩呐，现在拒绝会不会太残忍了？反正以后大概率也不会碰到，拿了就拿了吧，既然价值不大的话那也没什么不好意思的。',
          ],
          btn: [{title: '算了不然还是收下吧',toChapter: "WZXX_M1_N1_C029A_[V2]",}]},
           ]  
        }

  ]
    }
]