scenes: [
    #
    {
      id: 'WZXX_M1_N1_C006_V',
      name: "定义对应标题名当前章节内的选项和变量",

      # 变量定义
      vars: [{ id: "v1", min: 0, max: 1 }],

      # 动作定义
      actions: [],

      # 事件定义
      # 故事中的场景事件暂时没什么意义
      events: [],


    
      chats: [
      #

      { 
        id: 'WZXX_M1_N1_C006_V1', desc: '吃还是不吃，这是一个问题', 
        options: [ 
          { title: "【吃下醒神丹】",dialogs: ['C006A_chiyaoA']},
          { title: "【再忍一忍，晚点吃】",dialogs: ['C006A_buchiyaoB']},
        ],
      },
      { 
        id: 'WZXX_M1_N1_C006_V2', desc: '谁来了', 
        options: [ 
          { title: "【是谁？？？】",dialogs: ['C006A_shisheiA']},
      
        ],
      },

      { 
        id: 'WZXX_M1_N1_C006_V3', desc: '想个办法', 
        options: [ 
          { title: "【得想个办法，旁敲侧击！】",dialogs: ['C006A_fangshiA']},
  
        ],
      },

      { 
        id: 'WZXX_M1_N1_C006_V4', desc: '两个陶老', 
        options: [ 
          { title: "【什么情况？】",dialogs: ['C006A_taolaoA']},
     
        ],
      },

       { 
        id: 'WZXX_M1_N1_C006_V5', desc: '挑战成功', 
        options: [ 
          { title: "【向东走】",dialogs: ['C006A_xiangdonA']},
          { title: "【向西走】",dialogs: ['C006A_xiangxiA']},
     
        ],
      },


        ],


      # 对话框
      dialogs:
        [




           #选项对话
          { id: 'C006A_buchiyaoB',style: 6, title: '不吃药', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
          sections: [
          { key: 'P1', content: ['李森炎犹豫了下，又觉得现在似乎还没到穷途末路的时候','醒神丹是有时限的，只有万不得已的时候才能服下','现在还为时过早',
          '他当即决定先对抗，最好能把对方藏的脸找出来',['边缘闪烁红'],'一番艰难打斗之后，他被无脸阴灵头发缠住，重重摔在身后','然后李森炎就看见了对方的脸，在屁股上','“哈哈哈，你居然把脸藏在屁股上，笑死偶嘞”','然后……','李森炎就真死了',[{ sounds: [{ soundId: 'SE_UE_0003',}] }] ,'被愤怒的阴灵用头发缠绕，窒息而死……',
          ],
          btn: [{title: '算了，重新再来',tokey: "P2"},]},

          { key: 'P2', content: ['李森炎迅速摸出醒神丹服下，瞬间感觉到一股清凉之意汇入脑海，精神力量瞬间暴涨！','当下自信心也爆棚，主动出击，反手抓住对方那乌泱泱的头发，用力一扯，直接将对方的头发从头皮上扯下来。','那阴灵发出一阵哀嚎，无脸再加上光头，就像脖子上顶着一个灯泡一样颇为滑稽','此时的阴灵跟见了鬼似的向后退缩，内心滋生恐惧',
          '这家伙，明明刚才没有那么厉害的，难道是在扮猪吃虎？','阴灵心生退却之意，但李森炎哪里会放过他？',],
          btn: [{title: '追上去，干他！',toChapter: "WZXX_M1_N1_C011_[V0]"}]},
         
           ]  
        },



          #选项对话2
          { id: 'C006A_chiyaoA',style: 6, title: '吃药', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
          sections: [
          { key: 'P3', content: ['李森炎迅速摸出醒神丹服下，瞬间感觉到一股清凉之意汇入脑海，精神力量瞬间暴涨！','当下自信心也爆棚，主动出击，反手抓住对方那乌泱泱的头发，用力一扯，直接将对方的头发从头皮上扯下来。','那阴灵发出一阵哀嚎，无脸再加上光头，就像脖子上顶着一个灯泡一样颇为滑稽','此时的阴灵跟见了鬼似的向后退缩，内心滋生恐惧',
          '这家伙，明明刚才没有那么厉害的，难道是在扮猪吃虎？','阴灵心生退却之意，但李森炎哪里会放过他？',],
          btn: [{title: '追上去，干他！',toChapter: "WZXX_M1_N1_C011_[V0]"}]},
        ],
    },


          #选项对话3
          { id: 'C006A_shisheiA',style: 6, title: '是谁？？？', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
          sections: [
          { key: 'P4', content: ['房门洞开，一道清丽的人影站在门口，正是医灵',[{ sounds: [{ soundId: 'SE_CQ_0012',},],}, {animations: {id: 3} }],'她周身泛着冰冷的寒气，眼神也是冰冷如霜','那阴灵看见她，就像是饿极的野兽看见食物一般，目光中充斥贪婪',[{ sounds: [{ soundId: 'SE_CQ_0011',}] }] ,'房门一打开，阴灵根的气息彻底外泄，便犹如掀开锅盖，飘香十里，刹那间，更多的阴灵出现在房门外',],
          btn: [{title: '这……', tokey: "P4_1"},]},

          { key: 'P4_1', content: ['如同群狼般的眼神，在暗夜中闪烁着幽绿的光，死死地盯着医灵不放。','一般人见到这种场面早就吓傻了。','可医灵的神色却没有任何波动。',[{ sounds: [{ soundId: 'SE_CQ_0011',},], }] ,'下一刻，随着距离最近的阴灵率先暴起发难，所有的阴灵都疯了一般朝房门涌去。',],
          btn: [{title: '危险……', tokey: "P4_2"},]},

          { key: 'P4_2', content: ['而就在这时，云云忽然出现在门前，面露凶相，身形瞬间膨胀变大，几乎撑到天花板。','巨大身影往前一个翻滚，朝着蜂拥而至的阴灵直接碾压过去。','无数凄厉无比的惨叫声响起，在走廊中回荡。'],
          btn: [{title: '……', tokey: "P4_3"},]},

          { key: 'P4_3', content: ['片刻之后，场间便是一片安静，落针可闻了。','门口的医灵没有说话，似乎对这一幕并不意外。','云云缩小回原来的模样：“你为了李森炎打开门，我便替你收拾了这些阴灵，咱们扯平。”','医灵依旧没开口，只是点了点头，目光看向李森炎，清冷的眸子第一次出现些许复杂的神采。',],
          btn: [{title: '一夜过去', tokey: "P5"},]},

          { key: 'P5', content: ['李森炎的意识渐渐回归。','“我这是……死了吗？”','记得当时自己是使用醒神丹精神消耗过度昏睡过去了。','这让李森炎不得不怀疑，自己是不是已经被那些阴灵搞死了？',
          '但很快，他就感觉到一只冰凉的手在他额头和太阳穴之间轻轻揉捏，很舒服的感觉，他彻底清醒过来：“原来我还活着，太好了。”','“醒了吗？”','医灵如同黄鹂般清脆的声音在耳边响起',],
          btn: [{title: '苏醒',tokey: "P6"},{title: '装睡',tokey: "P7"}]},

          { key: 'P6', content: ['李森炎睁眼醒来，医灵当即把手拿开。','他起身揉了揉脑袋说道：“抱歉，那些阴灵我没能全部解决……”','“那些东西我已经帮你解决了”，云云撇了撇嘴，“关键时刻，还是得靠我。”','李森炎竖起大拇指，这时候医灵开口：“你身上的毒，我已经一并帮你解决了。”',
          '李森炎下了地活动筋骨，感觉神清气爽，最关键的是身体的疲软乏力和剧烈疼痛感都一并消失了。','不仅如此，他感觉自己的肉身力量，比中毒之前还要更好了，四肢发力，力量感从肌肉筋骨间不断涌现！','甚至，他还感觉自己已经摸到了炼气四层的门槛，随时可能突破！',],
          btn: [{title: '因祸得福？竟有这好事！',toChapter: "WZXX_M1_N1_C012_[V0]"}]},

          { key: 'P7', content: ['李森炎想多体验一下被按摩的感觉','于是继续装睡','但很快，他感觉到额头上的手拿开了','接着，他就听到了“刷刷”的金属摩擦声音',[{ sounds: [{ soundId: 'SE_KO_0018',}] }] ,'声音很刺耳，李森炎觉得有点熟悉','好像在哪里听过……是厨房！','卧槽，她该不会在磨刀吧？',
          '李森炎突然浑身一个激灵','她想干嘛？','李森炎感觉下半身一阵凉意','不行，不能再装了！',],
          btn: [{title: '睁开眼',tokey: "P8"}]},
          
          { key: 'P8', content: ['李森炎猛地睁眼醒来，医灵一脸平静地看着他，并没有在磨刀','被骗了……','李森炎若无其事地笑笑，起身揉了揉脑袋说道……','“抱歉，那些阴灵我没能全部解决……”','“那些东西我已经帮你解决了”，云云撇了撇嘴，“关键时刻，还是得靠我。”','李森炎竖起大拇指，这时候医灵开口：“你身上的毒，我已经一并帮你解决了。”','李森炎下了地活动筋骨，感觉神清气爽，最关键的是身体的疲软乏力和剧烈疼痛感都一并消失了','甚至，他还感觉自己已经摸到了炼气四层的门槛，随时可能突破！',],
          btn: [{title: '因祸得福？竟有这好事！', toChapter: "WZXX_M1_N1_C012_[V0]"}]},


        ],
    },


        #选项对话4
          { id: 'C006A_fangshiA',style: 6, title: '坊市', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
          sections: [
          { key: 'P9', content: ['“李森炎，我说话你到底有没有在听啊！”','见李森炎始终没有理她，云云都有些不耐烦了。','李森炎回过神，起身问道：“刚刚我的脑子里突然出现了医馆的画面，还听到了医灵和一株牡丹花的对话，你知不知道这是怎么一回事？”',
          '“我觉得你可能需要检查一下脑子……。”','“我跟你说认真的。”','“我也是认真的，据我所知哈，有一些个疯子，脑子里也经常出现别人的画面……”','李森炎语塞，云云转过头来又问道：“那你都听到了些什么？”','“这重要吗？一个疯子的臆想而已，你想听一个疯子胡言乱语？”',
          '云云没心没肺道：“说出来乐呵乐呵也好啊。”','“呵呵。”','李森炎没理她，直接走向坊市。',],
          btn: [{title: '向东走',tokey: "P9_A"},{title: '向北走',tokey: "P9_B"},{title: '向西走',tokey: "P9_C"}]},

          { key: 'P9_A', content: ['李森炎来到坊市东街，一名热情洋溢的中年男子当即叫住了他','“这位小兄弟，来一瓶天仙酿吗？”','“这可是滋阴补肾，强身健体的好东西，居家旅行必备之良品，喝了保证你夜夜快活似神仙哦！”','“快活似神仙？那我要一瓶！”',
          '云云如饿虎扑食般凑了过去。','“你要个屁”，李森炎一把将她扯了回来，对那摊主笑了笑，“她还小，童言无忌，别介意。','云云不爽道：“谁说我小了，我可比你大多了。”','中年男子面色略微有些古怪，不过他在这坊市里待了多年，什么场面没见过，也就见怪不怪了。','他依旧保持着礼貌的笑容：“那小兄弟你要不要来一瓶？”','李森炎表示自己还要再考虑考虑：“我有一个朋友想问问你，这个效果……是不是真有你说的这么好？”',
          '听到这话，中年男子的脸色立马就严肃起来了。','“我老王在这里卖了十年了，你可以四处去打听打听我的名声，绝对是童叟无欺，这效果绝对杠杠滴！”','“怎么样小兄弟？来一瓶吧，不贵，一块灵石一瓶，我再送你九瓶，相当于买一得十，只限今天！',],
          btn: [{title: '这么划算，买了！',tokey: "P10"},{title: '你当我傻啊，不买！',tokey: "P11"},]},

          { key: 'P10', content: ['李森炎觉得这还真挺划算的，不过似乎还有讲价的余地','这时候一个醉汉醉醺醺走过来','李森炎闻到对方难闻的酒骚味，让开了一些','醉汉冲着摊主痴痴说道：“老王，你这可真是好东西！”',
          '“我整宿睡不着的毛病，喝了你这酒立马就好了！”','“一觉睡到大天亮，还做了个美梦，嘿嘿。”','李森炎闻言，嘴角抽动，幸好还没买，差点就被骗了','这酒原来是助眠的！','所谓的夜夜快活似神仙，原来是在梦里快活似神仙啊！','李森炎脚底抹油，跑了。',],
          btn: [{title: '向北走',tokey: "P9_B"},{title: '向西走',tokey: "P9_C"},]},

          { key: 'P11', content: ['面对所谓买一得十的诱惑，李森炎不为所动','这种销售套路他早就见多，产生免疫了','摊主不搞这些套路还好','这么一搞，李森炎对其印象分大减',
          '“你刚刚叫我什么？”','老王笑脸依旧：“小兄弟啊。”','“没叫我靓仔，差评！不买了！”','李森炎转身就走','老王笑容瞬间消失，独自在风中凌乱','李森炎表示自己还要再考虑考虑：“我有一个朋友想问问你，这个效果……是不是真有你说的这么好？”',],
          btn: [{title: '向北走',tokey: "P9_B"},{title: '向西走',tokey: "P9_C"},]},

          { key: 'P9_B', content: ['向北走','这条街大多都是些娱乐性的铺子，有投壶，有斗鸡，还有些下棋的，各种好玩的游戏层出不穷，挑战成功还能赚钱。','一时间吸引了不少人的注意。','李森炎也不意外，他挑了个没什么人，但是看上去很特别的铺子，上前询问。',
          '“小兄弟，想不想挑战一下，半块灵石一次，只要全记住了，退还你一个灵石，怎么样，玩不玩？”','摊主简单给李森炎介绍了下游戏规则，是考验记忆力的游戏。','出题人给出一句话，只要在三秒钟之内找出所有的字，即算是挑战成功。',],
          btn: [{title: '挑战一次（-半个灵石)',tokey: "P12"},{title: '离开',tokey: "P13"},]},

          { key: 'P12', content: ['李森炎对于自己的记忆力还是很有信心的。','等下，分分钟教老板做人。','点击游戏，游戏开始。',],
          btn: [{title: '挑战开始', games: { id: 3, words: ['不', '知', '道', ] }, toChapter: "WZXX_M1_N1_C013_[V0]"},]},

          #{ key: 'P12_A', content: ['恭喜游戏成功，获得灵石+1','悟性+1','云云凑近，意外的抬了下眼，“没想到你还有点东西。”','早已习惯了她阴阳怪气的李森炎，自信的梳了把头发，“那当然。”',],
          #btn: [{title: '向东走',tokey: "P9_A"},{title: '向西走',tokey: "P9_C"},]},

          #{ key: 'P12_B', content: ['游戏失败，请不要灰心。','灵石-1  悟性-1','“认清现实吧，你的智商不适合玩这种游戏。”云云无情补刀。','李森炎：“……”','赶紧离开这个伤心的地方吧……',],
          #btn: [{title: '向东走',tokey: "P9_A"},{title: '向西走',tokey: "P9_C"},]},

          { key: 'P13', content: ['这种游戏，立刻让李森炎回想起现代的套环游戏，这种游戏多半是坑钱，要么乱收费，要么游戏难上加难','他觉得没什么意思，就转身转身离开了。',],
          btn: [{title: '向东走',tokey: "P9_A"},{title: '向西走',tokey: "P9_C"},]},


          { key: 'P9_C', content: ['向西走','那边似乎很热闹，人群熙熙攘攘。','走到人最多的一个摊位上，摊位上摆放着数枚丹药，李森炎刚开始还以为是卖丹药的，看了一会儿才明白过来。','敢情这是个赌局。',
          '花钱购买品质不明的丹药，这些丹药都做了表面处理，外表统一，如果验明是真丹，则摊主会花最低两倍的价钱回购，如果是废丹，那你就只能自认倒霉了。','摊主见有李森炎一副饶有兴致的样子，立刻过来热情招呼，“小兄弟赌一把吗？”','摊主倒是直接，也不遮掩，这本质上就是一场赌局。','李森炎看别人赌还行，轮到自己的时候，就有些犹豫了，赌博靠运气，他本来就穷了，这要是赌输了，岂不是要当街要饭去？','这些丹药都是做了隔绝神识勘察的处理，神识无法辨得真假，因为多了一层涂料，肉眼更是看不出来。','毕竟这里来往的都是修士，要是不做处理的话，摊主就是妥妥的送财童子了',
          '望着摊主那张不断凑近的大饼脸，李森炎沉吟犹豫，云云在一旁开口道：“喂，你不会真的要赌吧？你清醒一点呐，你可是个穷鬼！”',],
          btn: [{title: '搏一搏，赌！',tokey: "P14"},{title: '我与赌毒不共戴天！离开',tokey: "P15"},]},

          { key: 'P14', content: ['“你懂什么，只有搏一搏，单车才能变摩托。”','李森炎手指往其中一枚丹药点去。',],
          btn: [{title: '丹药照片',tokey: "P14_A"},{title: '丹药照片',tokey: "P14_B"},{title: '丹药照片',tokey: "P14_C"},]},

          { key: 'P14_A', content: ['李森炎搓搓手，把自己挑好的丹药，交给摊主。','摊主将丹药置于一盆淡黄色液体中。','丹药表面涂料散去，显露真容……','“恭喜你，这是一枚真丹！”','“丹药品质，普通。”','摊主直接以最低两倍的价格回购','灵石+2','李森炎见好就收，转身离开',],
          btn: [{title: '离开坊市',tokey: "P16"},]},

          { key: 'P14_B', content: ['李森炎搓搓手，把自己挑好的丹药，交给摊主。','摊主将丹药置于一盆淡黄色液体中。','丹药表面涂料散去，显露真容……','“恭喜你，这是一枚真丹！”','“丹药品质，高级。”','摊主直接以三倍的价格回购','灵石+3','李森炎见好就收，转身离开',],
          btn: [{title: '离开坊市',tokey: "P16"},]},
          
          { key: 'P14_C', content: ['李森炎搓搓手，把自己挑好的丹药，交给摊主。','摊主将丹药置于一盆淡黄色液体中。','丹药表面涂料散去，显露真容……','“恭……很遗憾，这是一枚废丹！”','灵石-1','李森炎及时止损，转身离开'],
          btn: [{title: '离开坊市',tokey: "P16"}]},

          { key: 'P15', content: ['李森炎和云云站在摊位旁边看了一会儿。','来来往往的人很多，短短几分钟，他就看到了好几个人抱着一堆破丹药痛苦，也有几个沾沾自喜赚了点甜头的。','其实啊，最终落在一个赌字上面。','十赌九输，还是不要碰为好','李森炎直接离开',],
          btn: [{title: '离开坊市',tokey: "P16"},]},

          { key: 'P16', content: ['临近坊市出口，有一个摊位引起了李森炎的注意，因为那摊位空无一物。','他刚来的时候就看到过，以为是东西卖完了，也没多在意。','可现在他都在坊市待了两天要走了，对方还在那。','按理来说，东西卖光了应该收摊才对，可那摊主依然双手抱胸，静静坐在那里。',
          '有一种高人的风范，却也有骗子的嫌疑。','李森炎不禁好奇仔细打量，只见摊主旁边立了一面白幡，上面书写着十六个字。','“天机阁报，天上天下，无有不知，无有不晓。”','天机阁……好像是个买卖情报的组织。','所以，这是个情报摊位？','无有不知，无有不晓，这牛皮吹得有点大啊……',],
          btn: [{title: '上前试探',tokey: "P17"},]},

          { key: 'P17', content: ['李森炎沉吟了一下，问道：“你们真的什么都知道吗？”','“当然是有些夸张的成分，不过我们绝不会乱说的，知道便是知道，不知道也绝不会乱收你的钱，情报组织最讲究的就是一个‘信’字，无信则不立。”','摊主摸了摸下巴一小撮胡须，依然保持着那一副桀骜不驯的样子。','“好，那我问问你，在没有修为的情况下，有没有什么办法，能解决阴灵根体质带来的副作用？”',
          '摊主沉思片刻，言简意赅回道：“有。”','“怎么解决？”','当李森炎再问时他就不回答了，将手伸到李森炎面前：“这消息值一枚灵石。”'],
          btn: [{title: '支付（灵石-1）', toChapter: "WZXX_M1_N1_C015_[V0]"},]},



  ],
    },


    #选项对话4
          { id: 'C006A_xiangdonA',style: 6, title: '向东走', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
          sections: [
          { key: 'P9_A', content: ['李森炎来到坊市东街，一名热情洋溢的中年男子当即叫住了他','“这位小兄弟，来一瓶天仙酿吗？”','“这可是滋阴补肾，强身健体的好东西，居家旅行必备之良品，喝了保证你夜夜快活似神仙哦！”','“快活似神仙？那我要一瓶！”',
          '云云如饿虎扑食般凑了过去。','“你要个屁”，李森炎一把将她扯了回来，对那摊主笑了笑，“她还小，童言无忌，别介意。','云云不爽道：“谁说我小了，我可比你大多了。”','中年男子面色略微有些古怪，不过他在这坊市里待了多年，什么场面没见过，也就见怪不怪了。','他依旧保持着礼貌的笑容：“那小兄弟你要不要来一瓶？”','李森炎表示自己还要再考虑考虑：“我有一个朋友想问问你，这个效果……是不是真有你说的这么好？”',
          '听到这话，中年男子的脸色立马就严肃起来了。','“我老王在这里卖了十年了，你可以四处去打听打听我的名声，绝对是童叟无欺，这效果绝对杠杠滴！”','“怎么样小兄弟？来一瓶吧，不贵，一块灵石一瓶，我再送你九瓶，相当于买一得十，只限今天！',],
          btn: [{title: '这么划算，买了！',tokey: "P10"},{title: '你当我傻啊，不买！',tokey: "P11"},]},

          { key: 'P10', content: ['李森炎觉得这还真挺划算的，不过似乎还有讲价的余地','这时候一个醉汉醉醺醺走过来','李森炎闻到对方难闻的酒骚味，让开了一些','醉汉冲着摊主痴痴说道：“老王，你这可真是好东西！”',
          '“我整宿睡不着的毛病，喝了你这酒立马就好了！”','“一觉睡到大天亮，还做了个美梦，嘿嘿。”','李森炎闻言，嘴角抽动，幸好还没买，差点就被骗了','这酒原来是助眠的！','所谓的夜夜快活似神仙，原来是在梦里快活似神仙啊！','李森炎脚底抹油，跑了。',],
          btn: [{title: '向北走',tokey: "P9_B"},{title: '向西走',tokey: "P9_C"},]},

          { key: 'P11', content: ['面对所谓买一得十的诱惑，李森炎不为所动','这种销售套路他早就见多，产生免疫了','摊主不搞这些套路还好','这么一搞，李森炎对其印象分大减',
          '“你刚刚叫我什么？”','老王笑脸依旧：“小兄弟啊。”','“没叫我靓仔，差评！不买了！”','李森炎转身就走','老王笑容瞬间消失，独自在风中凌乱','李森炎表示自己还要再考虑考虑：“我有一个朋友想问问你，这个效果……是不是真有你说的这么好？”',],
          btn: [{title: '向西走',tokey: "P9_C"},]},

          { key: 'P9_C', content: ['向西走','那边似乎很热闹，人群熙熙攘攘。','走到人最多的一个摊位上，摊位上摆放着数枚丹药，李森炎刚开始还以为是卖丹药的，看了一会儿才明白过来。','敢情这是个赌局。',
          '花钱购买品质不明的丹药，这些丹药都做了表面处理，外表统一，如果验明是真丹，则摊主会花最低两倍的价钱回购，如果是废丹，那你就只能自认倒霉了。','摊主见有李森炎一副饶有兴致的样子，立刻过来热情招呼，“小兄弟赌一把吗？”','摊主倒是直接，也不遮掩，这本质上就是一场赌局。','李森炎看别人赌还行，轮到自己的时候，就有些犹豫了，赌博靠运气，他本来就穷了，这要是赌输了，岂不是要当街要饭去？','这些丹药都是做了隔绝神识勘察的处理，神识无法辨得真假，因为多了一层涂料，肉眼更是看不出来。','毕竟这里来往的都是修士，要是不做处理的话，摊主就是妥妥的送财童子了',
          '望着摊主那张不断凑近的大饼脸，李森炎沉吟犹豫，云云在一旁开口道：“喂，你不会真的要赌吧？你清醒一点呐，你可是个穷鬼！”',],
          btn: [{title: '搏一搏，赌！',tokey: "P14"},{title: '我与赌毒不共戴天！离开',tokey: "P15"},]},

          { key: 'P14', content: ['“你懂什么，只有搏一搏，单车才能变摩托。”','李森炎手指往其中一枚丹药点去。',],
          btn: [{title: '丹药照片',tokey: "P14_A"},{title: '丹药照片',tokey: "P14_B"},{title: '丹药照片',tokey: "P14_C"},]},

          { key: 'P14_A', content: ['李森炎搓搓手，把自己挑好的丹药，交给摊主。','摊主将丹药置于一盆淡黄色液体中。','丹药表面涂料散去，显露真容……','“恭喜你，这是一枚真丹！”','“丹药品质，普通。”','摊主直接以最低两倍的价格回购','灵石+2','李森炎见好就收，转身离开',],
          btn: [{title: '离开坊市',tokey: "P16"},]},

          { key: 'P14_B', content: ['李森炎搓搓手，把自己挑好的丹药，交给摊主。','摊主将丹药置于一盆淡黄色液体中。','丹药表面涂料散去，显露真容……','“恭喜你，这是一枚真丹！”','“丹药品质，高级。”','摊主直接以三倍的价格回购','灵石+3','李森炎见好就收，转身离开',],
          btn: [{title: '离开坊市',tokey: "P16"},]},
          
          { key: 'P14_C', content: ['李森炎搓搓手，把自己挑好的丹药，交给摊主。','摊主将丹药置于一盆淡黄色液体中。','丹药表面涂料散去，显露真容……','“恭……很遗憾，这是一枚废丹！”','灵石-1','李森炎及时止损，转身离开'],
          btn: [{title: '离开坊市',tokey: "P16"}]},

          { key: 'P15', content: ['李森炎和云云站在摊位旁边看了一会儿。','来来往往的人很多，短短几分钟，他就看到了好几个人抱着一堆破丹药痛苦，也有几个沾沾自喜赚了点甜头的。','其实啊，最终落在一个赌字上面。','十赌九输，还是不要碰为好','李森炎直接离开',],
          btn: [{title: '离开坊市',tokey: "P16"},]},

          { key: 'P16', content: ['临近坊市出口，有一个摊位引起了李森炎的注意，因为那摊位空无一物。','他刚来的时候就看到过，以为是东西卖完了，也没多在意。','可现在他都在坊市待了两天要走了，对方还在那。','按理来说，东西卖光了应该收摊才对，可那摊主依然双手抱胸，静静坐在那里。',
          '有一种高人的风范，却也有骗子的嫌疑。','李森炎不禁好奇仔细打量，只见摊主旁边立了一面白幡，上面书写着十六个字。','“天机阁报，天上天下，无有不知，无有不晓。”','天机阁……好像是个买卖情报的组织。','所以，这是个情报摊位？','无有不知，无有不晓，这牛皮吹得有点大啊……',],
          btn: [{title: '上前试探',tokey: "P17"},]},

          { key: 'P17', content: ['李森炎沉吟了一下，问道：“你们真的什么都知道吗？”','“当然是有些夸张的成分，不过我们绝不会乱说的，知道便是知道，不知道也绝不会乱收你的钱，情报组织最讲究的就是一个‘信’字，无信则不立。”','摊主摸了摸下巴一小撮胡须，依然保持着那一副桀骜不驯的样子。','“好，那我问问你，在没有修为的情况下，有没有什么办法，能解决阴灵根体质带来的副作用？”',
          '摊主沉思片刻，言简意赅回道：“有。”','“怎么解决？”','当李森炎再问时他就不回答了，将手伸到李森炎面前：“这消息值一枚灵石。”'],
          btn: [{title: '支付（灵石-1）', toChapter: "WZXX_M1_N1_C015_[V0]"},]},



        ],
    },


     #选项对话5
          { id: 'C006A_xiangxiA',style: 6, title: '向西走', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
          sections: [
           { key: 'P9_C', content: ['向西走','那边似乎很热闹，人群熙熙攘攘。','走到人最多的一个摊位上，摊位上摆放着数枚丹药，李森炎刚开始还以为是卖丹药的，看了一会儿才明白过来。','敢情这是个赌局。',
          '花钱购买品质不明的丹药，这些丹药都做了表面处理，外表统一，如果验明是真丹，则摊主会花最低两倍的价钱回购，如果是废丹，那你就只能自认倒霉了。','摊主见有李森炎一副饶有兴致的样子，立刻过来热情招呼，“小兄弟赌一把吗？”','摊主倒是直接，也不遮掩，这本质上就是一场赌局。','李森炎看别人赌还行，轮到自己的时候，就有些犹豫了，赌博靠运气，他本来就穷了，这要是赌输了，岂不是要当街要饭去？','这些丹药都是做了隔绝神识勘察的处理，神识无法辨得真假，因为多了一层涂料，肉眼更是看不出来。','毕竟这里来往的都是修士，要是不做处理的话，摊主就是妥妥的送财童子了',
          '望着摊主那张不断凑近的大饼脸，李森炎沉吟犹豫，云云在一旁开口道：“喂，你不会真的要赌吧？你清醒一点呐，你可是个穷鬼！”',],
          btn: [{title: '搏一搏，赌！',tokey: "P14"},{title: '我与赌毒不共戴天！离开',tokey: "P15"},]},

          { key: 'P14', content: ['“你懂什么，只有搏一搏，单车才能变摩托。”','李森炎手指往其中一枚丹药点去。',],
          btn: [{title: '丹药照片',tokey: "P14_A"},{title: '丹药照片',tokey: "P14_B"},{title: '丹药照片',tokey: "P14_C"},]},

          { key: 'P14_A', content: ['李森炎搓搓手，把自己挑好的丹药，交给摊主。','摊主将丹药置于一盆淡黄色液体中。','丹药表面涂料散去，显露真容……','“恭喜你，这是一枚真丹！”','“丹药品质，普通。”','摊主直接以最低两倍的价格回购','灵石+2','李森炎见好就收，转身离开',],
          btn: [{title: '离开坊市',tokey: "P16"},]},

          { key: 'P14_B', content: ['李森炎搓搓手，把自己挑好的丹药，交给摊主。','摊主将丹药置于一盆淡黄色液体中。','丹药表面涂料散去，显露真容……','“恭喜你，这是一枚真丹！”','“丹药品质，高级。”','摊主直接以三倍的价格回购','灵石+3','李森炎见好就收，转身离开',],
          btn: [{title: '离开坊市',tokey: "P16"},]},
          
          { key: 'P14_C', content: ['李森炎搓搓手，把自己挑好的丹药，交给摊主。','摊主将丹药置于一盆淡黄色液体中。','丹药表面涂料散去，显露真容……','“恭……很遗憾，这是一枚废丹！”','灵石-1','李森炎及时止损，转身离开'],
          btn: [{title: '离开坊市',tokey: "P16"}]},

          { key: 'P15', content: ['李森炎和云云站在摊位旁边看了一会儿。','来来往往的人很多，短短几分钟，他就看到了好几个人抱着一堆破丹药痛苦，也有几个沾沾自喜赚了点甜头的。','其实啊，最终落在一个赌字上面。','十赌九输，还是不要碰为好','李森炎直接离开',],
          btn: [{title: '离开坊市',tokey: "P16"},]},

          { key: 'P16', content: ['临近坊市出口，有一个摊位引起了李森炎的注意，因为那摊位空无一物。','他刚来的时候就看到过，以为是东西卖完了，也没多在意。','可现在他都在坊市待了两天要走了，对方还在那。','按理来说，东西卖光了应该收摊才对，可那摊主依然双手抱胸，静静坐在那里。',
          '有一种高人的风范，却也有骗子的嫌疑。','李森炎不禁好奇仔细打量，只见摊主旁边立了一面白幡，上面书写着十六个字。','“天机阁报，天上天下，无有不知，无有不晓。”','天机阁……好像是个买卖情报的组织。','所以，这是个情报摊位？','无有不知，无有不晓，这牛皮吹得有点大啊……',],
          btn: [{title: '上前试探',tokey: "P17"},]},

          { key: 'P17', content: ['李森炎沉吟了一下，问道：“你们真的什么都知道吗？”','“当然是有些夸张的成分，不过我们绝不会乱说的，知道便是知道，不知道也绝不会乱收你的钱，情报组织最讲究的就是一个‘信’字，无信则不立。”','摊主摸了摸下巴一小撮胡须，依然保持着那一副桀骜不驯的样子。','“好，那我问问你，在没有修为的情况下，有没有什么办法，能解决阴灵根体质带来的副作用？”',
          '摊主沉思片刻，言简意赅回道：“有。”','“怎么解决？”','当李森炎再问时他就不回答了，将手伸到李森炎面前：“这消息值一枚灵石。”'],
          btn: [{title: '支付（灵石-1）', toChapter: "WZXX_M1_N1_C015_[V0]"},]},




        ],
    },


   #选项对话3
          { id: 'C006A_taolaoA',style: 6, title: '再见陶老', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
          sections: [
          { key: 'T1', content: ['“凭感觉。”','云云一脸认真严肃，这时候她没有在开玩笑。','但李森炎此时却希望她在开玩笑，凭感觉这种办法，本事就是个玩笑。','“放心，有我在，我会提醒你。”','“这才是个正经的办法，那你可要时刻抱紧我大腿哦。”',
          '“你说反了吧，我才是你大腿。”','嘴上不饶人的云云又回来了','“那我们现在去哪儿？”'],
          btn: [{title: '离开林子',toChapter: "WZXX_M1_N1_C016_[V0]"}]},




        ],
    },


  ]
    }
]