scenes: [
    #
    {
      id: 'WZXX_M1_N1_C0025_V',
      name: "定义对应标题名当前章节内的选项和变量",

      # 变量定义
      vars: [{ id: "v1", min: 0, max: 1 }],

      # 动作定义
      actions: [],

      # 事件定义
      # 故事中的场景事件暂时没什么意义
      events: [],


    
      chats: [
      #

      { 
        id: 'WZXX_M1_N1_C0025_V1', desc: '与蛛王的搏斗', 
        options: [ 
          { title: "【凶险！】",dialogs: ['C0025A_bodouA']},
        ],
      },

      


        ],













      # 对话框
      dialogs:
        [
           #选项对话
          { id: 'C0025A_bodouA',style: 6, title: '与蛛王的搏斗', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
          sections: [
          { key: 'P1', content: ['长鞭捆住蛛王的瞬间，高雁兰反手一拉，鞭子瞬间绷直，奋力向后拉扯。','被高雁兰这一拉扯，人面蛛王的落点发生了偏移，轰然砸落在赖崇信身前，从它身上扬起白茫茫的雪屑，四处飞舞。',
          '那张充满诡异气息的脸距离赖崇信仅仅只有三尺左右的距离，张开大嘴嘶声吼叫的同时喷吐飞沫，赖崇信不仅心里发寒，脸上更是被喷了一脸飞沫寒霜，整个人都冻麻了。',
          '“踏马的，为什么倒霉的总是我……”','趁着蛛王被缚住的这个时机，杨真连忙招呼一声：“上！”',
          '旋即动身奔杀而去，手中长剑划出一道弧光。',['飞卷刀光1'],
          [{ sounds: [{ soundId: 'SE_KO_0016',}] }] ,
          ],
          btn: [{title: '厉害啊',tokey: "P2",},]},

 
          { key: 'P2', content: ['避开蛛王身上防御最强的部位，斩击在蛛王足于身连接部位的软肋之上，一道剑光直接精准切掉了蛛王的两足。',
          '几乎同一时间，江依依也出手了，她抛出手中半月环法器，锋锐的光芒在蛛王身下一闪而过，同样斩落它一足。',['飞卷刀光2'], [{ sounds: [{ soundId: 'SE_KO_0015',}] }] ,
          '李森炎也不甘示弱，不过他没有法器傍身，只得近身作战，以肉拳的冲击，将蛛王一足折断。',
          '蛛王吃痛，张开惊人大口，发出不明怪声，听来十分惊悚，让人直欲捂上耳朵，这是它暴怒发狂的征兆。',
          ],
          btn: [{title: '！！！',tokey: "P3",}]},


          { key: 'P3', content: ['它不断挣扎，在它那寒刺般的利足之下，地面便如嫩白豆腐一般被轻易洞穿，留下令人触目惊心的深洞。',
          '令人惊异的是，受伤之后，它的气息非但没有减弱，反而急速飙升，瞬间崩断高雁兰的法器。',
          '本命法器被毁，高雁兰神情羞恼，又从储物袋中取出一把平日里不大使用的弧形弯刀，愤而冲上前，朝蛛王的足身狠狠砍落。',
           [{ sounds: [{ soundId: 'SE_CQ_0002',}] }] ,
          ],
          btn: [{title: '别去！！！',tokey: "P4",}]},

           { key: 'P4', content: ['李森炎突然有股不详的预感，立马出声阻止，然而高雁兰这时候却根本听不进去他的话。',
          '下一刻，有利箭刺破长空的呼啸声响起。',
          '本命法器被毁，高雁兰神情羞恼，又从储物袋中取出一把平日里不大使用的弧形弯刀，愤而冲上前，朝蛛王的足身狠狠砍落。',
           [{ sounds: [{ soundId: 'SE_KO_0003',}] }] ,
          ],
          btn: [{title: '别去！！！',toChapter: "WZXX_[Chapters]/WZXX_M1_N1_C025_[N2][V1]",}]},
           ]  
        },


  ]
    }
]