scenes: [
    #worldTimeHidden: true or false // 设定对话场景中是否显示世界时间。
    #sceneImage: xxx // 设定对话场景中的背景图片名称
    {
      id: 'WZXX_M1_N1_C001B_V',
      name: "城外密林",
      worldTimeHidden: true,
      sceneImage: 'default',
      
      # 变量定义
      vars: [
      { id: "v1A", min: 0, max: 1 },
      { id: "v2A", min: 0, max: 1 },
      ],

      # 动作定义
      actions: [
      ],

      # 事件定义 阅读器中的场景事件暂时没什么意义
      events: [
      { type: 'enter', nextChat: 'C001B_EventSTART1',dialogs: ['C001B_START_shulin'],varsOff: ["v1A","v2A",],},
      ],

      # 对话选项
      chats: [
      #选择道路事件=================================================
      { 
      id: 'WZXX_M1_N1_C001B_VD', desc: '选项', 
      options: [ 
      { 
      title: "选择道路",
      toScene: 'WZXX_M1_N1_C001B_V', 
      },
      ],
      }, 
      #
      { 
      id: 'C001B_EventSTART1', desc: '初始位置，一个分叉路在你眼前', 
      options: [ 
      #第一次进入 
      { title: '【向左走】',nextChat: 'A3', varsOff: ["v1A","v2A",] },
      { title: '【向右走】',nextChat: 'B1', varsOff: ["v1A","v2A",] }, 
      #   { title: '【DEBUG 到场景外】',toChapter: "WZXX_M1_N1_C001B" },
      #    { title: '【DEBUG 去结局】',dialogs: ['C001B_EventEND1']},
      ],
      },
      #
      { 
      id: 'C001B_EventSTART2', desc: '一个分叉路在你眼前，你感觉和之前有所不同', 
      options: [ 
      #第一次进入 
      { title: '【向左走】',nextChat: 'B3'  }, 
      { title: '【向右走】',nextChat: 'A3'  }, 
      ],
      },
      { 
      id: 'A3', desc: '崩塌的乱石挡住了去路，前面无法通行', 
      options: [ 
      { title: '【绕路】',nextChat: 'C001B_EventSTART2' }, 
      { title: '【原路返回】',nextChat: 'C001B_EventSTART1' }, 
      ],
      },
      { 
      id: 'B1', desc: '前面是一条比较平坦的路', 
      options: [ 
      { title: '【向前走】',nextChat: 'C0' }, 
      ],
      },

      { 
      id: 'B2', desc: '有条小的三岔口，你感觉空气十分的清新', 
      options: [ 
      { title: '【向前走比较平坦的路】',nextChat: 'C1'  }, 
      { title: '【向左走是崖壁】',nextChat: 'B2A'  }, 
      { title: '【向右走是大道】',nextChat: 'B6'  }, 
      ],
      },
      { 
      id: 'B2', desc: '你在悬崖陡坡的下侧，虽然陡坡不高，但依旧攀爬不上去', 
      options: [ 
      { title: '【原路返回】',nextChat: 'B2'  }, 
      { title: '【沿着陡坡向右走】',nextChat: 'B2A'  }, 
      { title: '【沿着陡坡向左走】',nextChat: 'B6'  }, 
      ],
      },
      { 
      id: 'B3', desc: '这条小道四周怪石林立，你直觉觉得这条路并未走过', 
      options: [ 
      { title: '【向前走】',nextChat: 'C3'  }, 
      { title: '【向左走】',nextChat: 'B4'  }, 
      { title: '【向右走】',nextChat: 'B2'  }, 
      ],
      },
      { 
      id: 'B4', desc: '你来到了密林旁的一处小山坡之上', 
      options: [ 
      { title: '【向前走】',nextChat: 'D2'  }, 
      { title: '【向左走，下山坡】',nextChat: 'C4'  }, 
      { title: '【向右走，下山坡】',nextChat: 'C2'  }, 
      ],
      },
      { 
      id: 'B5', desc: '在陡坡上，你一个没注意，从坡上摔了下来！', 
      options: [ 
      { title: '【还好没事，看看四周】',nextChat: 'B1'  }, 
      ],
      },
      { 
      id: 'B6', desc: '你发现这条道路是城市附近的官道', 
      options: [ 
      { title: '【沿路向前走】',nextChat: 'D1'  }, 
      { title: '【向左走离开大道】',nextChat: 'B2'  }, 
      { title: '【向右走离开大道】',nextChat: 'C2'  },  
      { title: '【沿路向后走】',nextChat: 'B6A'  }, 
      ],
      },
      { 
      id: 'B6A', desc: '你感觉似乎距离城市更远了', 
      options: [ 
      { title: '【沿路向前走】',nextChat: 'D1'  }, 
      { title: '【沿路向后走】',nextChat: 'B6'  }, 
      ],
      },
      { 
      id: 'B6B', desc: '你发现一位旅人大叔正在道路上走着，可算遇到了人了', 
      options: [ 
      { title: '【沿路向前走】',nextChat: 'D1'  }, 
      { title: '【沿路向后走】',nextChat: 'B6'  }, 
      ],
      },
      { 
      id: 'B6B1', desc: '你发现一位旅人大叔正在道路上走着，可算遇到了人了', 
      options: [ 
      { title: '【沿路向前走】',nextChat: 'D1'  }, 
      { title: '【沿路向后走】',nextChat: 'B6'  }, 
      ],
      },
      { 
      id: 'B6B2', desc: '你发现一位旅人正在道路上走着，可算遇到了人了', 
      options: [ 
      { title: '【问路】',nextChat: 'B6B2A'  }, 
      { title: '【聊些别的】',nextChat: 'B6B2A'  }, 
      { title: '【其他】',nextChat: 'B6B2C'  }, 
      { title: '【谢过离开】',nextChat: 'B6'  }, 
      ],
      },
      { 
      id: 'B6B2A', desc: '你现在走的方向是去城外的路，要进城的话就是走反了', 
      options: [ 
      { title: '【返回】',nextChat: 'B6B2'  }, 
      ],
      },
      { 
      id: 'B6B2B', desc: '这条路最近没几个人敢走，因为传言附近有老虎出没', 
      options: [ 
      { title: '【若有所思】',nextChat: 'B6B2'  }, 
      ],
      },
      { 
      id: 'B6B2C', desc: '这官道东侧的森林很容易迷路，所以才有修这条道路，你可千万别进东侧森林，就是右手这边。', 
      options: [ 
      { title: '【返回】',nextChat: 'B6B2'  }, 
      ],
      },









      
       { 
        id: 'C0', desc: '普通的分岔道路', 
        options: [ 
          { title: '【向前走】',nextChat: 'C1'  }, 
          { title: '【向左走】',nextChat: 'B5'  }, 
          { title: '【向右走】',nextChat: 'B6'  }, 
        ],
      },

      { 
        id: 'C1', desc: '普通的分岔道路2', 
        options: [ 
          { title: '【向前走】',nextChat: 'D4'  }, 
          { title: '【向左走】',nextChat: 'D1'  }, 
          { title: '【向右走】',nextChat: 'C2'  }, 
        ],
      },


      { 
        id: 'C2', desc: '一根棍子在横在路边挡住去路，你觉得这根棍子很碍眼', 
        options: [ 
          { title: '【一脚踢飞】',andVarsOff: ['v1A'],varsOn: ['v1A'],dialogs: ['C2N1']  }, 
          { title: '【绕过去】',andVarsOff: ['v1A'],varsOn: ['v1A'],dialogs: ['C2N2'] }, 
          { title: '【捡起来用力扔旁边树上】',andVarsOff: ['v1A'],varsOn: ['v1A','v2A',],dialogs: ['C2N3']   }, 
          { title: '【离开】',andVarsOn: ['v1A','v2A',],nextChat: 'C3'}, 
          { title: '【走中间】',andVarsOn: ['v1A',],nextChat: 'D3'  }, 
          { title: '【向右走】',andVarsOn: ['v1A',],nextChat: 'C1'  }, 
        ],
      },
      { 
        id: 'C3', desc: '一个分岔路出现，一边是山丘，一边是密林，前方还有一个山洞', 
        options: [ 
          { title: '【去山洞口】',nextChat: 'D2'  }, 
          { title: '【去山丘】',nextChat: 'C4'  }, 
          { title: '【去密林】',nextChat: 'C2'  }, 
        ],
      },
      { 
        id: 'C4', desc: '你发现从树林里走了出来，眼前是不知名的大片平原草场', 
        options: [ 
          { title: '【向前走】',nextChat: 'E12'  }, 
          { title: '【向左走】',nextChat: 'C5'  }, 
          { title: '【返回密林】',nextChat: 'C3'  }, 
        ],
      },
      { 
        id: 'C5', desc: '远处有什么动静？', 
        options: [ 
          { title: '【一眼望去】',dialogs: ['gameoverD5']  }, 
 
        ],
      },
      { 
        id: 'D1', desc: '一条林间大道，你看出这是直通城镇的官道', 
        options: [ 
 
          { title: '【向前走，顺着官道】',nextChat: 'D5'  }, 
          { title: '【向左走，去路的左边森林】',nextChat: 'D1'  }, 
          { title: '【向右走，去路右边的森林】',dialogs: ['gameover01']  }, 
        ],
      },
      { 
        id: 'D2', desc: '距离前面的山洞越来越近了', 
        options: [ 
 
          { title: '【去山洞口】',nextChat: 'E8'  }, 
          { title: '【向左走】',nextChat: 'C4'  }, 
          { title: '【向右走】',nextChat: 'D3'  }, 
        ],
      },
      { 
        id: 'D3', desc: '一个分岔路出现，你发现旁边有个山洞口', 
        options: [ 
          { title: '【朝着树的方向走】',nextChat: 'E7'  }, 
          { title: '【向山洞的位置走】',nextChat: 'E8'  }, 
          { title: '【向右走】',nextChat: 'B2'  }, 
        ],
      },


      { 
        id: 'D4', desc: '这是一个猎人小道，因为你看到了猎人狩猎用的绳索', 
        options: [ 
 
          { title: '【向前走】',nextChat: 'E4'  }, 
          { title: '【向左走】',nextChat: 'D3'  }, 
          { title: '【向右走】',nextChat: 'D5'  }, 
        ],
      },
      { 
        id: 'D5', desc: '走着走着，你直觉感觉到有些危险', 
        options: [ 
          { title: '【向前走】',nextChat: 'E1'  }, 
          { title: '【向右走】',nextChat: 'D6'  }, 
          { title: '【返回】',nextChat: 'D4'  }, 
        ],
      },
    { 
        id: 'D5_2', desc: '你觉得危险正在逼近，四周仿佛有什么一直注视你', 
        options: [ 
          { title: '【向前走】',dialogs: ['E3'] }, 
          { title: '【向右走】',dialogs: ['D6']  }, 
          { title: '【返回】',nextChat: 'D4'  }, 
        ],
      },
      { 
        id: 'D6', desc: '走着走着，你发现?，你正和杀手对视!!', 
        options: [ 
          { title: '【逃跑！】', dialogs: ['gameoverD1']  }, 
          { title: '【正面刚！】', dialogs: ['gameoverD2']  }, 
        ],
      },


      { 
        id: 'E1', desc: '你觉得有种被注视的感觉', 
        options: [ 
         { title: '【向前走】',nextChat: 'E3'  }, 
         { title: '【向左走】',nextChat: 'E1B'  }, 
         { title: '【向右走】',nextChat: 'E2'  }, 
         { title: '【返回】',nextChat: 'D5'  }, 
        ],
      },
      { 
        id: 'E1B', desc: '眼前是陡峭的山坡，无法攀爬，你只能原路返回', 
        options: [ 
         { title: '返回',nextChat: 'E1'  }, 
        ],
      },
       { 
        id: 'E2', desc: '你发现，杀手就在距离很近的位置，朝着你微笑着!!', 
        options: [ 
          { title: '【逃跑！】', dialogs: ['gameoverD1']  }, 
          { title: '【正面刚！】', dialogs: ['gameoverD2']  }, 
        ],
      },
      { 
        id: 'E3', desc: '你的眼前是一只凶恶的老虎！！，怎么办', 
        options: [ 
         { title: '【向前走】',nextChat: 'E3_2'  }, 
         { title: '【向左走】',nextChat: 'E3_2'  }, 
         { title: '【向右走】',nextChat: 'E3_2'  }, 
         { title: '【转身跑路】',dialogs: ['gameoverD3']  }, 
        ],
      },
      { 
        id: 'E3_2', desc: '走了几步，却发现高大的石墙挡住去路，前面是死路！怎么办', 
        options: [ 
         { title: '【转身】',dialogs: ['gameoverD3']  }, 
        ],
      },
      { 
        id: 'E4', desc: '四周安静，你觉得内心也平静了', 
        options: [ 
         { title: '【向前走】',nextChat: 'E5'  }, 
        ],
      },
      { 
        id: 'E5', desc: '现在感觉没有那么危险，你干脆', 
        options: [ 
         { title: '【哼点小曲】',nextChat: 'E1'  }, 
         { title: '【小心翼翼的走】',nextChat: 'E6'  }, 
         { title: '【顺着官道往回走】',nextChat: 'B6'  }, 
        ],
      },

      { 
        id: 'E6', desc: '这是距离大树很近的山坡', 
        options: [ 
         { title: '【爬到山丘上面】',dialogs: ['E6N1']  }, 
         { title: '【去大树下看看】',dialogs: ['C001B_EventEND1']   }, 
         { title: '【山丘下好像有个山洞】',nextChat: 'D2'  }, 
        ],
      },
      { 
        id: 'E7', desc: '这条小道，你清晰的看到了远方的大树', 
        options: [ 
         { title: '【向前走，山坡方向】',nextChat: 'E6'  }, 
         { title: '【向左走，山洞方向】',nextChat: 'E8'  }, 
         { title: '【向右走，树林方向】',nextChat: 'D4'  }, 
        ],
      },
      { 
        id: 'E8', desc: '你到了山洞口，石壁的开凿痕迹，能看出这是有人居住过的，但现在已经早已荒废', 
        options: [ 
         { title: '【进入山洞】',nextChat: 'E9'  }, 
         { title: '【离开】',nextChat: 'E7'  }, 
        ],
      },
   { 
        id: 'E9', desc: '山洞很昏暗', 
        options: [ 
         { title: '【沿石阶而上】',nextChat: 'E11'  }, 
         { title: '【石阶附近搜寻】',nextChat: 'E9N2'  }, 
         { title: '【墙壁附近搜寻】',nextChat: 'E9N3'  }, 
         { title: '【返回入口】',nextChat: 'E8'  }, 
        ],
      },
   { 
        id: 'E9N2', desc: '什么都没有，你觉得这太傻了', 
        options: [ 
         { title: '【返回】',nextChat: 'E9'  }, 
        ],
      },
   { 
        id: 'E9N3', desc: '墙壁可以推动', 
        options: [ 
         { title: '【使劲推动】',nextChat: 'E10'  }, 
        ],
      },
   { 
        id: 'E10', desc: '这是一间密室，有一个闪烁微光的石门', 
        options: [ 
         { title: '【碰触石门】',dialogs: ['gameoverD6']  }, 
         { title: '【离开】',nextChat: 'E9'  }, 
        ],
      },

      { 
        id: 'E11', desc: '前面是一个通向山下的窄道', 
        options: [ 
         { title: '【顺路走下来】',nextChat: 'E12'   }, 
         { title: '【离开】',nextChat: 'E9'  }, 
        ],
      },
      { 
        id: 'E12', desc: '你出现在一个山坡上', 
        options: [ 
          #第一次进入 
          { title: '【走下山坡】',nextChat: 'C4'  }, 
        ],
      },









     #三合一分支界面=======================================================
    #  { 
     #   id: 'WZXX_M1_N1_C001B_V', desc: '选项', 
      #  options: [ 
       # { title: "【选择行动目标】", 
        #章节选择
        #            selector: {
         #     data: [
               # {
                #  title: "第一章 分支2",
               # body: " <<<<去寻找穿越带来的物品。>>>>\n终于摆脱了敌人，李森炎感觉自己身上一身轻松，这个时候终于能够好好的整理一下思路。\n现在的情况有些匪夷所思，看起来是遇到了一些小说中的穿越情况。",
                  #toChapter: "WZXX_M1_N1_C001B_[B1]",
                #},
        #        {
        #           title: "第一章 分支1",
        #           body: "<<<<去最近的城市,平川府白城>>>>\n明明不是自己所在的现实世界的逻辑，但记忆里，像是有两个截然不同的人生在交错缠杂，他甚至有些分不清谁是谁。说不定进城后能询问出更多线索。",
         #          toChapter: "WZXX_M1_N1_C001B_[A1]",
        #         },
        #         {
         #         title: "第一章 分支2",
         #          body: " <<<<跟踪杀手，寻找线索>>>>\n不知为什么，李森炎在这个时候觉得特别的冷静。\n分明是刚刚穿越而来，却发现现在不但有了脑中特殊的记忆，还多了一身功夫。\n甚至现在。这具身躯中多出额外的力量来。",
          #         # desc: "此段描述只有切换世界才用到",
          #         #toChapter: "WZXX_M1_N1_C001B_[C1]",
          #         toScene: 'C001C_V_MAP_point_0_0', 
          #       },
          #     ]
          #   },
      
       #  },

 
       #  ],
      # },
     #三合一分支界面结束==========================

        
        ],




      # 对话框 FullScreen全屏 HalfScreen 半屏
      dialogs:
        [
 
          { id: 'C2N1', style: 1,sections: ['树枝被踢到远处','现在路可以走了',], nextChat: 'C001B_EventSTART1' },
          { id: 'C2N2', style: 1,sections: ['为了绕路，你倒霉的滑了一跤','现在可以继续走了',], nextChat: 'C001B_EventSTART1' },
          { id: 'C2N3', style: 1,sections: ['棍子打着圈被扔到了树上。','哗啦哗啦','哗啦哗啦','一大堆虫子乱飞',你急忙跑开，这条路不能走了。], nextChat: 'C001B_EventSTART1' },
          { id: 'E6N1', style: 1,sections: ['在陡峭的山坡','随着山石滑落。','一个不小心','滑落到了山下，闹出一阵动静',],nextChat: 'E1' },

          #进入树林
          { id: 'C001B_START_shulin',
            style: 6, 
            title: '进入树林',
            dialogType: 'FullScreen', 
            textAnimationType: 'TextFadeIn', 
            sections: [
            { key: 'p1', content: ['地点，小树林。','李森炎小心翼翼的走着，生怕万一弄出太大动静，再把那倒霉的杀手引来。','不过，这还不是最大的问题','跑的时候不认识路，完全瞎跑。这想原路回去可就难了。','李森炎决定凭着模糊的印象摸索道路','……','一个分叉路口前',], btn: [{title: '选择道路', nextChat: 'C001B_EventSTART1',},]},
            ],
          },
          #通关树林
          { id: 'C001B_EventEND1',
            style: 6, 
            title: '树林大树下',
            dialogType: 'FullScreen', 
            textAnimationType: 'TextFadeIn', 
            sections: [
            { key: 'p1', content: ['树林大树下','你觉得这里似曾相识','仔细看去，这原来就是你最初藏东西的地方','终于找对了！',['盖章过关'],'……',], btn: [{title: '高兴', toChapter: "WZXX_M1_N1_C001B_[B2]",},]},
            ],
          },

                       
        #死亡0
         { id: 'gameover00',artId: 4,
           style: 7, 
           title: '你挂了',
           dialogType: 'FullScreen', 
           textAnimationType: 'TextFadeIn', 
           sections: [
           { key: 'p1', content: ['你挂了……',请选择'], btn: [{title: '不放弃，再来',toScene: 'WZXX_M1_N1_C001B_V',dropIds: ["WZXX_M1_N1_C001B_V_gameover01",],  }, {title: '回章节开头', toChapter: "WZXX_M1_N1_C001B",dropIds: ["WZXX_M1_N1_C001B_V_gameover01",],}]},
           ],
         },


        #死亡3
         { id: 'gameover01',style: 7, artId: 2,title: '迷路',  dialogType: 'HalfScreen', textAnimationType: 'TextFadeIn', sections: [
         { key: 'p1', content: ['和之前的森林不同','这部分森林似乎更加难以辨别道路……','原本的道路都不见了……','数天后，你依旧在树林里打转……','请选择'],btn: [{title: '不放弃，再来', toScene: 'WZXX_M1_N1_C001B_V',dropIds: ["WZXX_M1_N1_C001B_V_gameover01",], },{title: '回章节开头',toChapter: "WZXX_M1_N1_C001B",dropIds: ["WZXX_M1_N1_C001B_V_gameover01",],}]},
         ], 
         },
         #死亡3
         { id: 'gameoverD1',style: 7,artId: 2, title: '逃跑', dialogType: 'HalfScreen', textAnimationType: 'TextFadeIn', sections: [
         { key: 'p1', content: ['你慌忙惊吓跑路','怪不得刚才有那种不好的预感','早知道就不该走这条路的！','跑啊跑','慌忙中越来越心跳加速','突然觉得背后一痛','……你死了',],btn: [{title: '不放弃，再来', nextChat: 'C001B_EventSTART1' ,dropIds: ["WZXX_M1_N1_C001B_V_gameoverD1",],  },{title: '回章节开头',toChapter: "WZXX_M1_N1_C001B",dropIds: ["WZXX_M1_N1_C001B_V_gameoverD1",], }]},
         ], 
         },
         #死亡3
         { id: 'gameoverD2',style: 7, artId: 4,title: '战斗',dialogType: 'HalfScreen', textAnimationType: 'TextFadeIn', sections: [
         { key: 'p1', content: ['没办法，直接正面硬刚','你抬起手里的木棍甩了甩','对面的杀手抬起手中的剑甩了甩','？？？','你发现手中武器和对方比起来，只有一点点的小差距','你挂了','……'],btn: [{title: '不放弃，再来', nextChat: 'C001B_EventSTART1' ,dropIds: ["WZXX_M1_N1_C001B_V_gameoverD2",], },{title: '回章节开头',toChapter: "WZXX_M1_N1_C001B",dropIds: ["WZXX_M1_N1_C001B_V_gameoverD2",],}]},
         ], 
         },
          #死亡3
         { id: 'gameoverD3',style: 7,artId: 1, title: '遇袭',dialogType: 'HalfScreen', textAnimationType: 'TextFadeIn', sections: [
         { key: 'p1', content: ['正走着，你发现后背突然一凉','一阵剧痛袭来','你挂了','……'],btn: [{title: '不放弃，再来', nextChat: 'C001B_EventSTART1' ,dropIds: ["WZXX_M1_N1_C001B_V_gameoverD3",], },{title: '回章节开头',toChapter: "WZXX_M1_N1_C001B", dropIds: ["WZXX_M1_N1_C001B_V_gameoverD3",],}]},
         ], 
         },
           #死亡3
         { id: 'gameoverD4',style: 7,artId: 3, title: '迷路', dialogType: 'HalfScreen', textAnimationType: 'TextFadeIn', sections: [
         { key: 'p1', content: ['怪不得刚才有那种不好的预感','早知道就不该走这条路的','你慌忙惊吓跑路','跑啊跑','慌忙中越来越心跳加速','……',],btn: [{title: '不放弃，再来', nextChat: 'C001B_EventSTART1' ,dropIds: ["WZXX_M1_N1_C001B_V_gameoverD4",], },{title: '回章节开头',toChapter: "WZXX_M1_N1_C001B",dropIds: ["WZXX_M1_N1_C001B_V_gameoverD4",],}]},
         ], 
         },
           #死亡3
         { id: 'gameoverD5',style: 7, artId: 2,title: '野狼', dialogType: 'HalfScreen', textAnimationType: 'TextFadeIn', sections: [
         { key: 'p1', content: ['你看到了几只妖狼正向你的方向快速扑来','虽然你有一身跑路的本事','但两条腿跑不过四条腿的','……','你挂了',],btn: [{title: '不放弃，再来', nextChat: 'C001B_EventSTART1', dropIds: ["WZXX_M1_N1_C001B_V_gameoverD5",], },{title: '回章节开头',toChapter: "WZXX_M1_N1_C001B",dropIds: ["WZXX_M1_N1_C001B_V_gameoverD5",],}]},
         ], 
         },
           #死亡3
         { id: 'gameoverD6',style: 7,artId: 4, title: '好奇心害死猫', dialogType: 'HalfScreen', textAnimationType: 'TextFadeIn', sections: [
         { key: 'p1', content: ['碰触石门后','你觉得一阵眩晕','你被某个阵法杀死了','……',],btn: [{title: '不放弃，再来', nextChat: 'C001B_EventSTART1' ,dropIds: ["WZXX_M1_N1_C001B_V_gameoverD6",], },{title: '回章节开头',toChapter: "WZXX_M1_N1_C001B", dropIds: ["WZXX_M1_N1_C001B_V_gameoverD6",],}]},
         ], 
         },
 

 
        ],



    },



  ]
