scenes: [
    #
    {
      id: 'WZXX_M1_N1_ZC27_V',
      name: "定义对应标题名当前章节内的选项和变量",

      # 变量定义
      vars: [
      { id: "v1", min: 0, max: 1 },
      { id: "v2", min: 0, max: 1 },
      { id: "v3", min: 0, max: 1 },
      { id: "biaoqianv1", min: 0, max: 1 } ,
      { id: "biaoqianv2", min: 0, max: 1 } ,
      { id: "biaoqianv3", min: 0, max: 1 } ,
      { id: "biaoqianv4", min: 0, max: 1 } ,
      { id: "biaoqianv5", min: 0, max: 1 } ,
      { id: "biaoqianv6", min: 0, max: 1 } ,
      { id: "biaoqianv7", min: 0, max: 1 } ,
      { id: "biaoqianv8", min: 0, max: 1 } ,
 
      ],

      # 动作定义
      actions: [],

      # 事件定义
      # 故事中的场景事件暂时没什么意义
      events: [
      ],
    
      chats: [
      
      {
        id: 'WZXX_M1_N1_ZC27_V1', desc: '该怎么办', 
        options: [
          {
          title: "【大胆叫价 五百灵石】",dialogs: ['ZC27_1.1A'],varsOn: ['biaoqianv1',],
          icon: { id: 1, bindVar: 'biaoqianv1' }, 
          },

          # {
          # title: "【尽量争取 四百灵石】", andVarsOn: ['v1'],  varsOn: ['biaoqianv2',], dialogs: ['ZC27_1.1B'],
          # icon: { id: 1, bindVar: 'biaoqianv2' }, 
          # },

          # {
          # title: "【保守一点 三百灵石】",dialogs: ['ZC27A_1.1C'], andVarsOn: ['v2'],
          # icon: { id: 1, bindVar: 'biaoqianv3' }, varsOn: ['biaoqianv3']
          # },

          
        ],
      },
     

      ],

      # 对话框
      dialogs:
        [
         #选项对话
          { 
            id: 'ZC27_1.1A',style: 6, title: '大胆叫价 五百灵石', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
            sections: [
              {
                key: 'P1', 
                content: ['李森炎毫不犹豫报出五百灵石的价格。',
                '他报价无论如何对方都会砍价的，报高一点留给对方砍价的空间，起码把砍价的价格控制在双方都能接受的范围内。', '报低了，万一对方一口气同意了，那就心痒痒了。',
                '小姑娘显然面露难色，支支吾吾，“你这……绝对卖不到这个价格的。”','虽说卖不到但是也没说具体价格，李森炎做出为难的模样。',
                '“小姑娘，你也知道这紫阴神光花的稀有和来之不易。”',],
                btn: [
                {
                title: '尽量争取 四百灵石',
                 dialogs: ['ZC27_1.1B'],
                },
               
                ]
              },
            ]  
          }, 

          { 
            id: 'ZC27_1.1B',style: 6, title: '尽量争取 四百灵石', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
            sections: [
              {
                key: 'P1', 
                content: ['“三百灵石怎么的我不得赔个底掉？这买卖不划算啊，这样吧，我看你也不容易，四百五一口价怎么样？”',
                '听见四百五的价格，小姑娘并没有松口气，脸色依旧尴尬，“大哥你别为难我，我也是诚心要货，但是这株是幼苗，四百五我们也是绝对不行的。”', '李森炎蹙眉，默默将画卷卷了起来，作势出一副准备离开的样子。',
                '“哎大哥！”小姑娘赶紧将他叫住，“你要不再让点价，这东西我们真的是诚心想要，但四五百灵石实在是离谱了些，都不用去问掌柜的，我都能告诉你不行。”','李森炎依旧皱着眉头，沉默着不说话。',
                '小姑娘继续说，“大哥，买卖不成仁义在。我帮您争取个价格，三百二，我去帮你问问掌柜的？”','“或者你若是实在不满意，可以委托我们拍卖，我们只收半成收成。”',
                '看来保底就是三百了。','李森炎也不是什么犯难的人，只是想尽量出个高价。',],
                btn: [
                {
                title: '保守一点 三百灵石', dialogs: ['ZC27A_1.1C'],
                },
               
                ]
              },
            ]  
          }, 

          { 
            id: 'ZC27A_1.1C',style: 6, title: '保守一点 三百灵石', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
            sections: [
              {
                key: 'P1', 
                content: ['但是走拍卖显然不保险，生意也做不长久，若是和天机阁打好交道了，以后还是很可观的。',
                '李森炎佯装不悦眉这才缓缓舒展开，一副甚是勉为其难般点点头。', '这架势显然是把小姑娘给忽悠住了，小小的松了一口气，走进去问去了。',
                '很快，又带着笑容走出来了。','“大哥，这株紫阴神光花可以三百二颗灵石收。”',
                '小姑娘是笑了，不过李森炎依旧是两难的模样，思量着。','三百二显然还不达到李森炎的预期，灵光一现，想了到什么。',
                '“罢了罢了，医灵还说你们天机阁大气，我还是去别处看看吧。”李森炎挥手，转身离开。','说实话，多少有点演的成分，但是演的太逼真了。',
                '小姑娘真以为他要走，猛地冲上前要拦他。','而此时，身后也响起一个老者的声音，“小道友留步。”',
                '“咳咳，原来是医灵的朋友啊，既然如此，老顾客我们也要照顾一下，这样吧，最终价三百五，我们天机阁收了！”','李森炎嘴角微不可见的勾了勾，转身看着那说话的老者。',
                '这大概是天机阁的某个高管，比这小姑娘有话语权，估计是报医灵的名字，才给的面子。',],
                btn: [
                {
                title: '这就好说话了', toChapter: "WZXX_M1_N1_Z2C27",
                },
                ]
              },
            ]  
          }, 

        ],
    }
]
