scenes: [
    #
    {
      id: 'WZXX_M1_N1_C005_VA',
      name: "定义对应标题名当前章节内的选项和变量",

      # 变量定义
      vars: [
      { id: "v1", min: 0, max: 1 },
      { id: "biaoqianv1", min: 0, max: 1 } ,
      { id: "biaoqianv2", min: 0, max: 1 } ,
      ],

      # 动作定义
      actions: [],

      # 事件定义
      # 故事中的场景事件暂时没什么意义
      events: [],


    
      chats: [

       { 
        id: 'WZXX_M1_N1_C005_VA1', desc: '守夜', 
        options: [ 
          { title: "【守夜】",dialogs: ['C005A_shouyeA'],},
        ],
      },


        ],


      # 对话框
      dialogs:
        [
           #选项对话
          { id: 'C005A_shouyeA',style: 6, title: '守夜', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
          sections: [
          { key: 'P2', content: ['入夜，医灵房间外','“要不要叫人给你多烧几个火炉啊！”','帮人帮到底，送佛送到西','李森炎提议多添上几个火炉，不仅仅是为了医灵不被冻成冷鲜，更是为了自己，他整个后半身都快冻僵了！',
          '“你还是先管好你自己，别让我给你烧纸钱吧。”','房间里传出医灵冰冷的话语，李森炎撇了撇嘴，这属实是好心被当成驴肝肺了！','“公子啊，她不解风情，我就不一样了。”',['边缘闪烁红'],'耳边突然传来一声妩媚入骨的声音',[{ sounds: [{ soundId: 'SE_CQ_0015',}] }] ,'李森炎回过头，一个身穿红衣的女灵漂浮在他的面前，赤着双足，面容惨白，丝毫没有半点人色，眼窝深陷，双眼犹如两个黑洞，没有眼球',[{ sounds: [{ soundId: 'SE_CQ_0012',},],}, ],
          '这属实是比背影杀手还恐怖的声音杀手，一般人见了肯定要疯','不过李森炎早有心理准备，神情还算平静','幸好前世恐怖片看得多，精神早就经历过各种恐怖场面的洗礼，才能这般淡定','李森炎开口：“富强民主文明和谐自由平等公正法治爱国敬业友善。”','红衣女灵：“？？？”','“公子，你是在念咒语吗？我可不怕哦。”','红衣女灵轻笑一声',],
          btn: [{title: '继续念不要停',tokey: "P4",},
          {title: '不念了',toChapter: "WZXX_M1_N1_C012_[N1]",},]},

          { key: 'P4', content: ['李森炎：“富强民主文明和谐自由平等公正法治爱国敬业友善！”','“……？”','女灵有些不耐烦了：“公子，我说过了我不怕，你别念了。”',],
          btn: [{title: '再念一遍',tokey: "P5",},]},

          { key: 'P5', content: ['李森炎：“富强民主文明和谐自由平等公正法治爱国敬业友善！”','女灵脸色已经开始变了：“我叫你别念了！”',['边缘闪烁白'],],
          btn: [{title: '根本停不下来',toChapter: "WZXX_M1_N1_C012_[N2]",},]},
           ]  
        },
  ]
    }
]