scenes: [
    #策划手动配的
    {
      id: "WZXX_[Chapters]",
      name: "一些章节的变量放在这里集中管理",

      # 变量定义 ，每个章节默认对应一个变量，主要用于分支,章节解锁的检测,
      vars: [
           #
          { id: "WZXX_M1_N1_C001", min: 0, max: 1 },
          { id: "WZXX_M1_N1_C001FZ", min: 0, max: 1 },
          { id: "WZXX_M1_N1_C001A", min: 0, max: 1 },
          { id: "WZXX_M1_N1_C001AFZ", min: 0, max: 1 },

          { id: "WZXX_M1_N1_C001B_[A1]", min: 0, max: 1 },
          { id: "WZXX_M1_N1_C001B_[A1]FZ", min: 0, max: 1 },

          { id: "WZXX_M1_N1_C001B_[B1]", min: 0, max: 1 },
          { id: "WZXX_M1_N1_C001B_[B1]FZ", min: 0, max: 1 },
          { id: "WZXX_M1_N1_C001B_[B2]", min: 0, max: 1 },
          { id: "WZXX_M1_N1_C001B_[B2]FZ", min: 0, max: 1 },
          { id: "WZXX_M1_N1_C001B_[C1]", min: 0, max: 1 },
          { id: "WZXX_M1_N1_C001B_[C1]FZ", min: 0, max: 1 },
          { id: "WZXX_M1_N1_C001B", min: 0, max: 1 },
          { id: "WZXX_M1_N1_C001BFZ", min: 0, max: 1 },
          { id: "WZXX_M1_N1_C001C_[N1]", min: 0, max: 1 },
          { id: "WZXX_M1_N1_C001C_[N1]FZ", min: 0, max: 1 },
          { id: "WZXX_M1_N1_C001C_[N2]", min: 0, max: 1 },
          { id: "WZXX_M1_N1_C001C_[N2]FZ", min: 0, max: 1 },
          { id: "WZXX_M1_N1_C001C_[N3]", min: 0, max: 1 },
          { id: "WZXX_M1_N1_C001C_[N3]FZ", min: 0, max: 1 },

          { id: "WZXX_M1_N1_C001C", min: 0, max: 1 },
          { id: "WZXX_M1_N1_C001CFZ", min: 0, max: 1 },
           #
          { id: "WZXX_M1_N1_C002_[N1]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C002_[N1]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C002_[N2]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C002_[N2]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C002_[N3]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C002_[N3]FZ",min: 0, max: 1 },
            #
          { id: "WZXX_M1_N1_C003_[N1]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C003_[N1]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C003_[N2]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C003_[N2]FZ",min: 0, max: 1 },
            #
          { id: "WZXX_M1_N1_C004_[N1]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C004_[N1]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C004_[N2]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C004_[N2]FZ",min: 0, max: 1 },
            #
          { id: "WZXX_M1_N1_C005_[N1]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C005_[N1]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C005_[N2]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C005_[N2]FZ",min: 0, max: 1 },
            #
          { id: "WZXX_M1_N1_C006_[N0]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C006_[N0]FZ",min: 0, max: 1 },
            #
          { id: "WZXX_M1_N1_C007_[N0]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C007_[N0]FZ",min: 0, max: 1 },
            #
          { id: "WZXX_M1_N1_C008_[N0]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C008_[N0]FZ",min: 0, max: 1 },
            #
          { id: "WZXX_M1_N1_C009_[V2]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C009_[V2]FZ",min: 0, max: 1 },
            #
          { id: "WZXX_M1_N1_C010A_[N1]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C010A_[N1]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C010A_[N2]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C010A_[N2]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C010B_[N1]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C010B_[N1]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C010B_[N2]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C010B_[N2]FZ",min: 0, max: 1 },
            #
          { id: "WZXX_M1_N1_C011_[V0]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C011_[V0]FZ",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C012_[V0]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C012_[V0]FZ",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C013_[V0]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C013_[V0]FZ",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C015_[V0]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C015_[V0]FZ",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C016_[V0]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C016_[V0]FZ",min: 0, max: 1 },
          #
          { id: "WZXX_M1_N1_C017_[N1]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C017_[N1]FZ",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C017_[N2]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C017_[N2]FZ",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C018_[N1]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C018_[N1]FZ",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C018_[N2]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C018_[N2]FZ",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C019_[N1]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C019_[N1]FZ",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C019_[N2]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C019_[N2]FZ",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C020",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C020FZ",min: 0, max: 1 },
            #
          { id: "WZXX_M1_N1_C021",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C021FZ",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C022_[N1]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C022_[N1]FZ",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C022_[N2]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C022_[N2]FZ",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C023_[N1]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C023_[N1]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C024_[V1]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C024_[V1]FZ",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C025A_[V1]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C025A_[V1]FZ",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C025B_[V1]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C025B_[V1]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C026_[V1]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C026_[V1]FZ",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C027A_[V1]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C027A_[V1]FZ",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C027B_[V1]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C027B_[V1]FZ",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C027C_[V1]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C027C_[V1]FZ",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C028A_[V1]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C028A_[V1]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C029A_[V2]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C029A_[V2]FZ",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C029B_[V2]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C029B_[V2]FZ",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C030A_[V2]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C030A_[V2]FZ",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C037",min: 0, max: 1 },
        
        ],

      #
      # 动作定义
      actions: [],

      # 事件定义
      # 故事中的场景事件暂时没什么意义
      events: [],

      # 对话选项
      chats: [
          #
          { id: "WZXX_ChaptersVar ", desc: "选项", options: [] },
        ],

      # 对话框
      dialogs: [],
    },
  ]
