scenes: [
    #
    {
      id: 'WZXX_M1_N1_C009_V',
      #定义对应标题名当前章节内的选项和变量
      name: "落霞峰",
       #不显示时间
      worldTimeHidden: true,

      # 变量定义
      vars: [
      { id: "v1", min: 0, max: 1 },
      { id: "v2", min: 0, max: 1 },
      { id: "v3", min: 0, max: 1 },
      { id: "v4", min: 0, max: 1 },
      { id: "v5D", min: 0, max: 1 },
      { id: "v5E", min: 0, max: 1 },
      { id: "biaoqianv1", min: 0, max: 1 } ,
      { id: "biaoqianv2", min: 0, max: 1 } ,
      { id: "biaoqianv3", min: 0, max: 1 } ,
      { id: "biaoqianv4", min: 0, max: 1 } ,
      { id: "biaoqianv5", min: 0, max: 1 } ,
      { id: "biaoqianv6", min: 0, max: 1 } ,
      { id: "biaoqianv7", min: 0, max: 1 } ,
      { id: "biaoqianv8", min: 0, max: 1 } ,

      
      ],

      # 动作定义
      actions: [],

      # 事件定义
      # 故事中的场景事件暂时没什么意义
      events: [ 
      { type: 'enter',andVarsOff: ['v5D'], nextChat: 'WZXX_M1_N1_C009_V1',},
       { type: 'enter',andVarsOn: ['v5D', ], nextChat: 'WZXX_M1_N1_C009_V11',},
        ],


    
      chats: [
      #

      #   { 
      #   id: 'WZXX_M1_N1_C009_V', desc: '去山道看看', 
      #   options: [ 
      #     # { title: "【询问扛着锄头的村民】",dialogs: ['C009A_npcA'],},
      #     # { title: "【询问采花姑娘】",dialogs: ['C009A_npcB'],},
      #     { title: "【询问前面路过的砍柴的少年】",dialogs: ['C009A_npcC'],},
        
      #   ],
      # },

      { 
        id: 'WZXX_M1_N1_C009_V1', desc:  '得到所有线索，并且问清了线路之后，李森炎前往采集草药', 
        options: [ 
        #1015黄心叶
          { title: "【去迷雾森林中探索】", andVarsOff: ['v2'], varsOn: ['v2'],
           collect: '5',
          #  dropIds: ["WZXX_M1_N1_C009_V_Vdrop7",]
           },
          #1016百络花
          { title: "【前往北药山沟】", andVarsOn: ['v2'], andVarsOff: ['v3'], varsOn: ['v3',], 
          collect: '6',
          # dropIds: ["WZXX_M1_N1_C009_V_Vdrop8",]
          },
          
          #1017子星草
          { title: "【幽暗森林】",andVarsValue: ['@clues_liuyan6 == 1'], andVarsOn: ['v2', 'v3'], andVarsOff: ['v4'], varsOn: ['v4'], dialogs: ['mengshou'],   },

          { title: "【山谷里面查看查看】",andVarsValue: ['@clues_liuyan6 != 1'], andVarsOn: ['v2', 'v3'], varsOn: ['v5D'], collect: '7', nextChat: 'WZXX_M1_N1_C009_V2',
          # dropIds: ["WZXX_M1_N1_C009_V_Vdrop9",] 
           },

          { title: "【山谷里面查看查看】", andVarsOn: ['v2', 'v3','v4'], varsOn: ['v5D'],  collect: '7', nextChat: 'WZXX_M1_N1_C009_V2',
          # dropIds: ["WZXX_M1_N1_C00 9_V_Vdrop9",]  
          },
         
    
        ],
      },

      { 
        id: 'WZXX_M1_N1_C009_V11', desc:  '这里已经采集完毕了，去别的地方看看吧', 
        options: [ 
       
          { title: "【离开】", nextChat: 'WZXX_M1_N1_C009_V2',
          
          },
         
    
        ],
      },

      { 
        id: 'WZXX_M1_N1_C009_V2', desc: "将所有药材都采集完毕后，李森炎回到了落霞峰脚下村落\n此时正好遇见之前的那个采花女\n采花女热情的与李森炎打招呼\n“你回来了啊！怎么样，东西找到了没有？”\n“找到了，多谢！”\n“那太好了，我现在要回家了，一起走吗？”", 
        options: [ 
          { title: "【去】",dialogs: ['C009A_caihuaguniangA'],},
          { title: "【不去】",dialogs: ['C009A_caihuaguniangB'],},
         
        
        ],
      },
       
        { 
        id: 'WZXX_M1_N1_C009_V3', desc: '询问采药人', 
        options: [ 
          { title: "【上前和村民交谈】",dialogs: ['C009A_npcA'], icon: { id: 1, bindVar: 'biaoqianv1' }, varsOn: ['biaoqianv1']},
        ],
      },

      { 
        id: 'WZXX_M1_N1_C009_V4', desc: '询问采药人', 
        options: [ 
          { title: "【与采花姑娘交谈】",dialogs: ['C009A_npcB'], icon: { id: 1, bindVar: 'biaoqianv2' }, varsOn: ['biaoqianv2']},
        ],
      },

      { 
        id: 'WZXX_M1_N1_C009_V5', desc: '询问采药人', 
        options: [ 
          { title: "【询问砍柴的少年】",dialogs: ['C009A_npcC'], icon: { id: 1, bindVar: 'biaoqianv3' }, varsOn: ['biaoqianv3']},
        ],
      },

      { 
        id: 'WZXX_M1_N1_C009_V6', desc: '遇见老头', 
        options: [ 
          { title: "【前面有个老头上前问问情况】",dialogs: ['C009A_sycw'], icon: { id: 1, bindVar: 'biaoqianv4' }, varsOn: ['biaoqianv4']},
        ],
      },

       { 
        id: 'WZXX_M1_N1_C009_V7', desc: '云云飞行', 
        options: [ 
          { title: "【坐稳，出发】",dialogs: ['C009A_yunyun'],},
        ],
      },

      

 
     
        ],
  # 对话框
      dialogs:
        [
        
  #选项对话1
          { id: 'C009A_npcA',style: 6, title: '询问扛着锄头的村民', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
          sections: [
           { key: 'P1', 
          content: [
            '村民正在锄地，李森炎走了过去','“大爷，我想问……”',
            '“谁是你大爷！”','村民抬起头来，顶着一头白发：“我才二十五！”',
            '二十五啊，那是显老了点……','李森炎尴尬一笑，连忙改口叫大哥','接着问他知不知道那些药材的出处','村民没有立即回答，转而问起李森炎','“你姓什么？”','“我姓李。”','“哦，不是姓王就行，要是姓王的我肯定不告诉他！”','李森炎大汗，你对姓王的是有多大的怨念啊！',
            [{  
              toMsg: { 
                action: 'CluesModel/addClues', params: { addCluesId: ["liuyan4"] } 
              }, 
            }],
         '“黄心叶我知道，在北药山沟，山谷这两个地方都有，至于你说其他两个，我就不清楚了。”',
          ],
          btn: [{title: '成功收获一条流言',}]},
           ]  
        },

               
  #选项对话1
          { id: 'C009A_npcB',style: 6, title: '询问采花姑娘', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
          sections: [
            { key: 'P1', content: ['姑娘正在采集花叶，看到李森炎眼前一亮','“这位大哥，要不要去我家里坐坐？”',
          '李森炎颇感意外。','现在的姑娘，都这么大胆了吗？',
          '但是姑娘接下来的一句话，就让李森炎彻底打消了念头','“我家里有上好的茶叶。”','“不用了不用了！”',
          '李森炎担心她下一秒就要开始卖茶叶了','连忙截住她的话，说自己还有要事，顺带把自己的需求提出来',
          '姑娘眼中难掩失望','“你不去的话我就不告诉你。”','“你先告诉我，等我把药草拿到手了，我再回来找你。”','“真的吗？你不要骗我哦！”',
          '“真的，不骗你！”','采花姑娘点了点头，把她知道的地点告诉了李森炎',
          [{  
              toMsg: { 
                action: 'CluesModel/addClues', params: { addCluesId: ["liuyan5"] } 
              }, 
            }],
            '“如果我记得没错的话，北药山沟就有百络花。”',],
          btn: [{title: '再次获得一条流言'},]},
           ]  
        },

         #选项对话1
          { id: 'C009A_npcC',style: 6, title: '询问前面路过的砍柴的少年', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
          sections: [
             { key: 'P1', content: ['李森炎上前问话，少年看了李森炎一眼','灵动的双眸转了转',
          '提出如果李森炎帮他砍柴的话，就告诉他那些草药在哪',],
          btn: [{title: '帮忙砍柴',tokey: "P2"},{title: '不帮',tokey: "P3"},]},

          { key: 'P2', content: ['砍柴是个体力活，不过李森炎也不缺力气','挥起斧头，三下五除二把活儿干完了',
          '少年露出了微笑，说道：“谢谢大哥！”',
          [{  
              toMsg: { 
                action: 'CluesModel/addClues', params: { addCluesId: ["liuyan6"] } 
              }, 
            }],'“我知道子星草在迷雾森林。”',
        ],
          btn: [{title: '四周没有路人了，离开',}]},

           { key: 'P3', content: ['李森炎下意识觉得，这个少年是想骗他干活','然后信口胡诌一个地方',
          '这种伎俩，怎么能骗得了他？','李森炎没有搭理他，转身离开',
          ],
          btn: [{title: '继续走……',}]},
           ]  
        },   
        
          {
             id: 'mengshou', style: "9B", textAnimationType: 'TextSingle',
                 sections: [
                  {
                     key: 'p1',
                      content: ['根据砍柴少年给的线索','李森炎来到幽暗森林中寻找子星草',
                       '然而,他非但没有在幽暗森林中找到子星草',
                       '反而还遇到了猛虎', 
                       '不过幸好李森炎身手敏捷成功从猛兽口中脱险',
                       '……','李森炎寻遍幽暗森林，却毫无所获',
                       '这才确定','砍柴少年给的是条假线索！','小小年纪就这么狡猾！可恶！',
                       '李森炎狼狈离开幽暗森林，前往山谷寻子星草……', ],
                   },  
                   ]
                   },

          #选项对话2
        { id: 'C009A_sycw',style: 10, textAnimationType: 'TextSingle',
            sections: [
            { figureId: "01", location: "right", content: ['“大爷你好。”', ], },
            { figureId: "02", location: "left", content: ['“你好。”',], },
            { figureId: "01", location: "right", content: ['“大爷你知道黄心叶、百络花、子星草这些东西在哪吗？”',], },
            { figureId: "02", location: "left", content: ['“第一个是黄什么？”', ], },
            { figureId: "01", location: "right", content: ['“黄心叶。”',], },
            { figureId: "02", location: "left", content: ['“第二个呢？”', ], },
            { figureId: "01", location: "right", content: ['“百络花。”',], },
            { figureId: "02", location: "left", content: ['“第三个呢？”', ], },
            { figureId: "01", location: "right", content: ['“子星草。”',], },
            { figureId: "02", location: "left", content: ['“哦哦，那第一个呢？”', ], },
            { figureId: "01", location: "right", content: ['“……”','“第一个是黄心叶，第二个是百络花，第三个是子星草。”',], },
            { figureId: "02", location: "left", content: ['“哦哦，第一个是黄心叶，那第二个呢。”',], },
            { figureId: "01", location: "right", content: ['“……”','“大爷你好好歇着吧。”',], },
            { figureId: "02", location: "left", content: ['“好嘞。”', ], },
            ]
            },


              #选项对话2
          { id: 'C009A_caihuaguniangA',style: 6, title: '采花姑娘的邀约', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
          sections: [
          { key: 'P3', content: ['“好吧，那就去坐一会儿。','李森炎跟着她去到山间小屋。','“啊，你家在这啊？”','李森炎想起白天时候来到过这里',
          '“你家里是不是有个大爷？”','“对，那是我爷爷。”','“孙女回来啦。”','大爷从屋里走出，看到李森炎的瞬间，眼睛微微放大','“我记得你！”','李森炎苦笑，您老这个时候记性大可不必这么好！'
          ,'“哈哈哈，来来来，喝两杯茶再走。”','兴许是住在山野之中，极少有客来往',
          '大爷和姑娘都非常热情，李森炎这才知道是自己想多了','人家姑娘并不卖茶','离开的时候还给了李森炎一些不知名的草药的种子'],
          btn: [{title: '离开去寻找云云',toScene:  "WZXX_M1_N1_C002B_V",dropIds: ['WZXX_M1_N1_C009_V_Vdrop1'],}]},
        ],
    },

       #选项对话2
          { id: 'C009A_caihuaguniangB',style: 6, title: '采花姑娘的邀约', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
          sections: [
          { key: 'P3', content: ['“天色已晚，我觉得还是算了吧。”','“不是都说好了嘛！哼，果然男人都是骗子！”','采花姑娘负气而走，李森炎愣在原地，不由得苦笑起来','又走了一会儿，忽然李森炎路过山村的时候捡到了一些不知名的草药种子','虽然不知道是做什么的，但是收着说不定以后有用',
          ],
          btn: [{title: '离开去寻找云云',toScene: 'WZXX_M1_N1_C002B_V',dropIds: ['WZXX_M1_N1_C009_V_Vdrop2'],},]},
        ],
    },

     #选项对话2
          { 
            id: 'C009A_yunyun', style: 5, textAnimationType: 'TextSingle',
            sections: [
              { 
                type: 'TopToBottom',  loop: true,  play: true, videoId: 1, 
                content: ['地面渐行渐远，这个奇幻的世界逐渐展露出全貌', '世界的最外围被缭绕的云层裹挟着望不见尽头，视线向内延申，云层逐渐稀薄，隐约看见了冰蓝色的大海', 
                '海水环绕着中央的陆地，形成一道天然的屏障','在这样的视角下，陆地上行走的人和奇怪生物们宛如细密的蚂蚁，四处走动，体现着生命的旺盛','李森炎第一次看到这样的世界，大为震撼。',] 
              },
              { 
                type: "TopToBottom", bgImageId: 3, loop: true, play: true,
                content: ['飞行途中，云云开口说道：“你要留在这里，不准回去，这里需要你。”','李森炎心中一跳：“需要我干嘛？”','“大致说来，需要你不断修炼，得道成仙，在刑杌彻底启动据说会灭世的归元阵之前，杀死他。但具体该怎样做我也不清楚。”',
                '“总之，你要阻止魔祖毁灭灵修界，灵修界一旦被毁，则天道轮回，造化万世，皆陷于混沌。”','李森炎听完嘴角肌肉一阵抽动：“太扯了，你别闹了，你们一定是搞错了。”',
                '李森炎一心只想回去，根本不想包揽什么救世的重担，经历过现实的毒打之后，这种救世主的美梦，他早就不做了。','“知道你现在很弱，慢慢变强就是了，不是谁都能像我一样，生来就很强大。”','李森炎：“……”',
                '你和陶老，自卖自夸都有一手的','“我问你一个问题，如果有一天你发现自己根本敌不过那些魔头，你会怎么办？”','“打不过，就加入呗。”','李森炎无所谓地笑了笑，他觉得那些东西离他很远，根本没有设身处地认真去想这个问题。','反正自己也是要离开的，想那么多有什么用？','云云沉默了片刻，心想，这人以后一定是要修魔的。',
                '既然他都不愿意拯救灵修界于水火，心性又不坚定，说不定以后会是个大祸患。','还不如现在就弄死他。','“那行，你自便吧。”','下一刻。','云云直接翻了个身，李森炎完全没想到这朵云会突然害他，当场往下坠落',
                ],
              },
            ],
            toChapter: "WZXX_M1_N1_C007",
          },

        ]
      }
    ]

           
