scenes: [
    #
    {
      id: 'WZXX_[START]',
      name: "小说专属场景",

      # 变量定义
    vars: [
      { id: 'v1', min: 0, max: 1 },

      # 变量定义已读标签
      { id: 'WZXX_001_Option_Already_Read_V1', min: 0, max: 1 },

      
    ],

      # 动作定义
      actions: [],

      # 事件定义
      # 故事中的场景事件暂时没什么意义
      events: [],

      # 对话选项
      chats: [
          #
      #
      { 
        id: 'WZXX_[START]', desc: '选项', 
        options: [ 
          { title: "【开始阅读】", toChapter: "WZXX_M1_N1_C001" },
        ],
      },
      #
      { 
        id: 'WZXX_001', desc: '选项', 
        options: [ 
        #  { title: "【开始阅读333】", varsOn: ['WZXX_M1_N1_C001_[A1]'], },
          { title: "【去最近的城市，生存重要】", varsOn: "WZXX_M1_N1_C001_[A1]", },
          { title: "【去穿越的地点，也许能找到什么】", varsOn: "WZXX_M1_N1_C001_[A2]" },
          { title: "【跟踪对手，找到更多线索】", varsOn: "WZXX_M1_N1_C001_[A3]" },



        ],
      },
      { 
        id: 'WZXX_M1_N1_C999V', desc: '选项', 
        options: [ 
        #  { title: "【开始阅读333】", varsOn: ['WZXX_M1_N1_C001_[A1]'], },
          { title: "【回到开头】", toChapter: "WZXX_M1_N1_C001",},
          { title: "【去穿越的地点，也许能找到什么】", varsOn: "WZXX_M1_N1_C001_[A2]" },
          { title: "【跟踪对手，找到更多线索】", varsOn: "WZXX_M1_N1_C001_[A3]" },
        ],
      },

      #
          {
            id: "c4",
            desc: "",
            options: [{ title: "弹出对话框", dialogs: ["p1"] }],
          },
        ],

      # 对话框
      dialogs:
        [
 #
        ],
    },
  ]
