scenes: [
    #
    {
      id: 'WZXX_M1_N1_C002B_V',
      #定义对应标题名当前章节内的选项和变量
      name: "",

      # 变量定义
      vars: [
        { id: "v1", min: 0, max: 1 },
        { id: "biaoqianv1", min: 0, max: 1 } ,
        { id: "biaoqianv2", min: 0, max: 1 } ,
        { id: "biaoqianv3", min: 0, max: 1 } ,
        { id: "biaoqianv4", min: 0, max: 1 } ,
        { id: "biaoqianv5", min: 0, max: 1 } ,
        { id: "biaoqianv6", min: 0, max: 1 } ,
        { id: "biaoqianv7", min: 0, max: 1 } ,
        { id: "biaoqianv8", min: 0, max: 1 } ,
        { id: "biaoqianv9", min: 0, max: 1 } ,
        { id: "biaoqianv10", min: 0, max: 1 } ,
        { id: "biaoqianv11", min: 0, max: 1 } ,
        { id: "biaoqianv12", min: 0, max: 1 } ,
        { id: "biaoqianv13", min: 0, max: 1 } ,
        { id: "biaoqianv14", min: 0, max: 1 } ,
        { id: "biaoqianv15", min: 0, max: 1 } ,
        { id: "biaoqianv16", min: 0, max: 1 } ,
        { id: "biaoqianv17", min: 0, max: 1 } ,
        { id: "biaoqianv18", min: 0, max: 1 } ,
        { id: "biaoqianv19", min: 0, max: 1 } ,
        { id: "biaoqianv20", min: 0, max: 1 } ,
        { id: "biaoqianv21", min: 0, max: 1 } ,
        { id: "biaoqianv22", min: 0, max: 1 } ,
        { id: "biaoqianv23", min: 0, max: 1 } ,
        { id: "biaoqianv24", min: 0, max: 1 } ,
        { id: "biaoqianv25", min: 0, max: 1 } ,
        { id: "biaoqianv26", min: 0, max: 1 } ,
        { id: "biaoqianv27", min: 0, max: 1 } ,

        
      ],


      # 动作定义
      actions: [],

      # 事件定义
      # 故事中的场景事件暂时没什么意义
      events: [
      { type: 'enter', nextChat: 'WZXX_M1_N1_C002B_V3A',}, 
      ],


    
      chats: [
      #

      { 
        id: 'WZXX_M1_N1_C002B_V1', desc: '落霞峰', 
        options: [ 
          { title: "【只是现在……】",toChapter: "WZXX_M1_N1_C008"  },
        ],
      },

      { 
        id: 'WZXX_M1_N1_C002B_V2', desc: '落霞峰', 
        options: [ 
          { title: "【让云云教自己修炼】",dialogs: ['C002B_xiulianA'],}
        ],
      },

      { 
        id: 'WZXX_M1_N1_C002B_V3A', desc: '李森炎离开山道，回到原先的地点与云云碰面', 
        options: [ 
          { title: "【去找云云】",dialogs: ['C002B_quzhaoyunyunA'],},
        ],
      },

    
        { 
        id: 'WZXX_M1_N1_C002B_V3', desc: '坊市', 
        options: [ 
          { title: "【不去坊市】",dialogs: ['C002B_fangshiA'], icon: { id: 1, bindVar: 'biaoqianv23' }, varsOn: ['biaoqianv23']},
          { title: "【去坊市看看】",dialogs: ['C002B_fangshiB'], icon: { id: 1, bindVar: 'biaoqianv24' }, varsOn: ['biaoqianv24']}
        ],
      },

      { 
        id: 'WZXX_M1_N1_C002B_V4', desc: '神照', 
        options: [ 
          { title: "【修真秘法——神照】",toChapter: "WZXX_M1_N1_C011_[N1]"  },
        ],
      },


      # { 
      #   id: 'WZXX_M1_N1_C002B_V4', desc: '怎么了？', 
      #   options: [ 
      #     { title: "【！！出事了】",dialogs: ['C002B_elingA'], icon: { id: 1, bindVar: 'biaoqianv25' }, varsOn: ['biaoqianv25']}

      #   ],
      # },

      # { 
      #   id: 'WZXX_M1_N1_C002B_V5', desc: '恶灵', 
      #   options: [ 
      #     { title: "【！！出事了】",dialogs: ['C002B_elingA'], icon: { id: 1, bindVar: 'biaoqianv26' }, varsOn: ['biaoqianv26']}

      #   ],
      # },

      # { 
      #   id: 'WZXX_M1_N1_C002B_V6', desc: '打喷嚏', 
      #   options: [ 
      #     { title: "【啊湫】",dialogs: ['C002B_aqiuA'], icon: { id: 1, bindVar: 'biaoqianv27' }, varsOn: ['biaoqianv27']}

      #   ],
      # },
        ],


      # 对话框
      dialogs:
        [


          #选项对话1
          { id: 'C002B_xiulianA',style: 6, title: '云云', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
          sections: [
          { key: 'P5', content: ['请选择行动吸引云云注意，并成功让她教你修仙————',],
          btn: [
            {title: '打一套拳',tokey: "P6", icon: { id: 6, bindVar: 'biaoqianv1' }, },
            {title: '给它唱一段',tokey: "P7", icon: { id: 6, bindVar: 'biaoqianv2' }},
            {title: '故弄玄虚说一段',tokey: "P8", icon: { id: 7, bindVar: 'biaoqianv3' }}
          ]},

          { key: 'P6', content: [
          '打拳！','肯定能吸引云云注意！','但，打什么拳呢？','不……不太会啊。', '……','请选择行动——',],
          btn: [
            {title: '第三套广播体操', tokey: "P6A", icon: { id: 6, bindVar: 'biaoqianv4' }},
            {title: '太极拳',tokey: "P6B", icon: { id: 6, bindVar: 'biaoqianv5' }},
            {title: '军体拳',tokey: "P6C", icon: { id: 6, bindVar: 'biaoqianv6' }}
          ]},
         
          { key: 'P6A', content: ['想了想，你最熟悉的还是第三套广播体操！','虽说不是拳，但反正能吸引云云注意就行','预备开始……','伸展运动',
          '一二三四五六七八二二三四五六七八','……','这一招十分奏效，原本追着小飞鸟跑的云云，很快就被你吸引了过来','“你在炼体吗？这是什么炼体功法？”',
          '你颇有几分得意：“我自创的。”','“自创功法，好厉害哦……就是看起来有点挫。”',[{ sounds: [{ soundId: 'SE_HV_0012',}] }] ,'话音刚落，只听咔嚓一声',['震屏1'],'“噗嗤哈哈哈哈哈。”云云无情的嘲笑声。','你腰扭了需要休息几日，才能继续',],
          btn: [
            {title: '重新选择行为',tokey: "P5", varsOn: ['biaoqianv1','biaoqianv4',]},
            {title: '重新选拳', tokey: "P6", varsOn: ['biaoqianv4']}
          ]},

          { key: 'P6B', content: ['太极拳……','这玩意李森炎以前经常看见小区大爷们在花园里练','嘶……怎么练的来着？',
          '好像需要扎马步，手画圈？','不管了，随便打吧，反正云云也没见过','深呼吸，扎马步','第一招，来个——白鹤亮翅！',
          '嘿！你做出展翅的姿态','云云果然被吸引过来了，微微张嘴，“李森炎，你……”','哼，小样没见过，被我震惊的说不出来话了吧。',
          '再来个，手抱琵琶！','然后听见云云幽幽的声音传来，“李森炎，你是突然抽风了吗？”',[{ sounds: [{ soundId: 'SE_UE_0012',}] }] ,
          '“……”','这招对云云不奏效，而且还被她无情吐槽，姿势太过难看',],
          btn: [{title: '重新选择行为',tokey: "P5", varsOn: ['biaoqianv1','biaoqianv5',]},
          {title: '重新选拳',tokey: "P6", varsOn: ['biaoqianv5',]},]},

          { key: 'P6C', content: ['军体拳！','这玩意军训的时候常练，李森炎身为军训优秀份子，对这个那就是一个信手拈来，得心应手',
          '对，没错就它了！','给这小姑娘露一手','嘿，嘿，嘿','马步、弓步、虚步，一步不差，又繁到简，又从简到难','云云转过头来看了一会，又继续去玩了。',
          '它没有手，对打拳什么的并不感兴趣',[{ sounds: [{ soundId: 'SE_UE_0005',}] }] ,'还真是纱布擦屁股——漏了一手啊',],
          btn: [{title: '重新选择行为',tokey: "P5", varsOn: ['biaoqianv1','biaoqianv6',]},
          {title: '重新选拳',tokey: "P6", varsOn: ['biaoqianv6',]},]},

          { key: 'P7', content: ['以声音吸引，让她陶醉在你美妙的歌声之下','对，没错，就这么办！','你飞快的想了想','你决定唱——',],
         btn: [{title: '随便唱一首',tokey: "P7A", icon: { id: 6, bindVar: 'biaoqianv7' }},
         {title: '唱rap',tokey: "P7B", icon: { id: 6, bindVar: 'biaoqianv8' }},
         {title: '正经唱一首',tokey: "P7C", icon: { id: 6, bindVar: 'biaoqianv9' }}]},

          { key: 'P7A', content: ['唱什么好呢？','算了，想到什么唱什么吧','猪!你的鼻子有两个孔,感冒时的你还挂着鼻涕牛牛','猪!你有着黑漆漆的眼,望呀望呀望也看不到边','猪!你的耳朵是那么大,呼扇呼扇也听不到我在骂你傻',
          [{ sounds: [{ soundId: 'SE_UE_0012',}] }] ,'……','李森炎你唱的什么玩意！','只听云云一声怒喝，朝你冲来','哎哎哎！你干嘛，我只是在唱歌啊……','‘砰’……',['震屏1'],'你受伤了，需要调养几日',],
          btn: [{title: '重新选择行为',tokey: "P5", varsOn: ['biaoqianv2','biaoqianv7',]},
          {title: '重新选歌',tokey: "P7", varsOn: ['biaoqianv7',]}]},

          { key: 'P7B', content: ['你摸着下巴，仔细想了想','总所周知，只要会rap，无论古今中外，都会收获迷妹','嗯，就这么办',
          '药药药……切克闹……动次打次！！康姆昂北鼻够来死狗','盖塔奥、黑喂狗、闹太套~',[{ sounds: [{ soundId: 'SE_UE_0005',}] }] ,'“你在鬼叫什么，我刚追的朱鸟都被你吓跑了！李森炎！！你给我等着！！！”',],
          btn: [{title: '重新选择行为',tokey: "P5", varsOn: ['biaoqianv2','biaoqianv8',]},
          {title: '重新选歌',tokey: "P7", varsOn: ['biaoqianv8',]},]},

          { key: 'P7C', content: ['此情此景，此间情','好山好水，好无聊','对，没错就它了！','你有感开口','呀啦索 那就是青藏……','还没唱完，忽然你发现自己开不了口了',[{ sounds: [{ soundId: 'SE_UE_0005',}] }] ,'云云满脸嫌弃的看着你，“李森炎咱们都是一伙的，别开腔……”','“给你下了噤声咒，少说话。”','“……”','？？？真有那么难听吗',],
          btn: [{title: '重新选择行为',tokey: "P5", varsOn: ['biaoqianv2','biaoqianv9',]},
          {title: '重新选歌',tokey: "P7", varsOn: ['biaoqianv9',]},]},
        
          { key: 'P8', content: [' 云云这丫头，天性就爱玩','估计是平时和陶老那老头经常呆在一块，闷坏了，现在解放天性了','自己说点什么好玩的，或者吓唬吓唬她','嘿嘿嘿（很得意的奸笑）',],
         btn: [{title: '说个恐怖故事',tokey: "P8A", icon: { id: 6, bindVar: 'biaoqianv10' }},
         {title: '说个冷笑话',tokey: "P8B", icon: { id: 6, bindVar: 'biaoqianv11' }},
         {title: '说个脑经急转弯',tokey: "P8C", icon: { id: 7, bindVar: 'biaoqianv12' }}]},

          { key: 'P8A', content: ['“云云，你快过来，我给你说个故事。”','云云眨巴眨巴眼，看着李森炎一连神秘莫测的样子，凑了上去，“什么？”','“我有一个朋友。”你道',
          '“那个朋友不会是你自己吧。”云云笑着打断','“不是，你听我说嘛……说在一个午夜的山上，一对夫妻约定好上山游玩，可是在山顶的时候，夫妻闹矛盾，吵架了，那男的就先下山了，等到男人走到回到山脚下的时候，后悔了决定回去找自己的妻子，男人和妻子道歉，妻子也原谅了她，两人开车下山，忽然……”', '你做出恐怖阴森的模样',
          '“怎么了？”云云眨眨眼”',[{ sounds: [{ soundId: 'SE_ED_0021',}] }] ,'“他们看见一个穿着红色衣服的女孩，在路边，招手示意。但是男人没有停下来，而是赶紧带着妻子走了。”','忽然你拔高音量，试图吓一下云云，“你知道为什么吗？',
          '然而云云白乎乎的小胖脸一脸淡定','你只能继续说，“因为啊，那个小女孩长得……”','“是不是这样的？”云云开口',
          [{ sounds: [{ soundId: 'SE_CQ_0011',}] }] ,'你转身看向云云，倏然眼前凑上一个血糊糊的人脸……',['震屏1'],'“啊！！！！！！！！”',
          '“哈哈哈哈哈哈哈”你听见了云云捧腹的嘲笑声','云云修仙多年并不害怕恐怖故事……',],
          btn: [{title: '重新选择行为',tokey: "P5", varsOn: ['biaoqianv3','biaoqianv10',]},
          {title: '重新选故事',tokey: "P8", varsOn: ['biaoqianv10',]}]},

          { key: 'P8B', content: ['云云嘛，小孩心态，平时肯定是和陶老这种闷闷的老人呆在一起没什么乐趣','说不定，说几个笑话逗她开心了，她就愿意教自己了','“云云，你快过来，我给你讲个有意思的故事。”',
          '云云眨巴眨巴眼，看着李森炎一连神秘莫测的样子，凑了上去，“什么？”','“从前有一群凡人，被扔进雪地里了，他们走了好久好久，也没有走出去，一群人走的饥肠辘辘，此时有一个人看见一只冻成冰雕的狼，饿疯了的他准备上去舔，但此时他的同伴拉住了他，不让他去，你猜是为什么。”','云云仔细思考，严肃的说，“难道是因为冰融化之后，狼会把他们吃了？”','“不是。”你摇头','“那，那就是没有火，不能烤着吃。”','“也不是。”你又摇头','“那到底是因为什么啊？”云云更加好奇了','“因为，‘冰狼’不能吃，吃了会得口腔癌。哈哈哈哈哈哈哈。”',[{ sounds: [{ soundId: 'SE_UE_0012',}] }] ,'“……”','“哎哟，疼疼疼。”','你因为讲的笑话太冷了，被云云揍了一脑袋包',],
          btn: [{title: '重新选择行为',tokey: "P5", varsOn: ['biaoqianv3','biaoqianv11',]},
          {title: '重新选故事',tokey: "P8", varsOn: ['biaoqianv11',]},]},

          { key: 'P8C', content: ['思来想去，你觉得这个办法不错！','“云云我们来打赌吧，你要是赢了我就心甘情愿干三天活，我要是赢了你就得教我修仙。”','云云挑眉，“赌什么？”','你用手指敲了敲脑袋，“赌这儿。”','云云勾唇冷笑，“好啊，我这朵云别的不好使，但智慧这一块，我可是当仁不让！”','“好，现在开始，”你立刻开口，“请问，拿什么东西不用手？”','云云愣了下，“这是什么鬼问题。”','你不给她机会，“五四三……”','“哎，拿，拿……水？”','“错，是拿主意。”你继续，“什么字大家看了都说没用？”','“……错字？”','“错，是没用二字。”','你得意一笑，继续，“最后一个，谁知道天上到底有多少颗星星？”','“这谁知道啊？？？”云云逐渐暴走。','“天知道。”','“……？”',[{ sounds: [{ soundId: 'SE_UE_0001',}] }] ,'“好吧，我输了我心甘情愿教你修仙”', ['盖章过关']  ],
          btn: [{title: '不愧是我', toChapter: "WZXX_M1_N1_C009_[N1]",dropIds: ['WZXX_M1_N1_C002B_V_Vdrop2'], varsOn: ['biaoqianv3','biaoqianv12',]},]},      
           
        ],
    },

  #选项对话3A
          { id: 'C002B_quzhaoyunyunA',style: 6, title: '修炼丹药', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
          sections: [
          { key: 'P9', content: ['李森炎离开山道，回到原先的地点与云云碰面','采集到三种材料后，李森炎双手捧着，看向云云。','“草药都采集到了，现在你要我用手来炼丹吗？”','“我有药鼎，给你！”','话音刚落，一个小小药鼎从她身上掉了出来。','李森炎赶忙接住，药鼎模样很精致，就是体积小了点。','如此小巧玲珑的药鼎，一次性能够炼制的丹药不多，不过胜在便捷，方便携带。','“这个随身药鼎，你拿着，开炼吧。”','李森炎面露喜色，也不废话，当即开炉炼药。',],
          btn: [{title: '去炼丹',openUI: 'LianDanFang', tokey: "P10",},]},

          { key: 'P10', content: ['“成功了！我是不是还有点天分？”','“还行吧，马马虎虎。”','云云撇了撇嘴，吝啬她的赞美。','李森炎也不介意这点小事，取出护脉丹，观察了一下。','他现在不过初涉炼药，能有这种成功率，已经是极好的了。','就不再奢求高品质了。','一口吞服，喉咙传来一阵回甘，丹药在体内迅速化开，犹如一股暖流，游遍全身，仿若置身温泉之中。',],
          btn: [{title: '可以了，开始修炼！',openUI: 'XiuXing' ,toChapter: "WZXX_M1_N1_C009_[N2]"},]},

         
        ],
    },
     #选项对话3
          { id: 'C002B_fangshiA',style: 6, title: '不去坊市', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
          sections: [
          { key: 'P9', content: ['不过，初尝修炼甜头的李森炎却不为所动','“有时间当用来修炼才是，逛什么坊市，不去。”','话虽这么说，实则他心里在想，哥穷得叮当响，还想让我花钱，休想！','就这样，云云一直怂恿李森炎不成。','直至数日后——','“我还是没办法突破”','经过这一周的修行，却始终无法突破四重','他多次尝试冲击第四重，却都以失败告终','“你在这地方闷头修炼半个月了，都说了修炼要张弛有度，去附近坊市逛逛吧，换个地方换个心情，说不定还能淘到些对你修为有帮助的好东西呢。”','云云没有放弃，再一次怂恿。','这回李森炎没有再反抗了，毕竟修炼遇到瓶颈，总得想办法解决，当即点头答应了下来。',],
          btn: [{title: '去坊市',toChapter: "WZXX_M1_N1_C010"},]},

         
        ],
    },

     #选项对话4
          { id: 'C002B_fangshiB',style: 6, title: '去坊市看看', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
          sections: [
          { key: 'P10', content: ['李森炎想想觉得也行，毕竟他这些天的修行虽然升到了炼气三重了','不过却也，遇到了瓶颈了。','再想往上突破一层的话，没那么容易','而且修仙需要张弛有度，说不定去坊市还能淘到什么好东西',],
          btn: [{title: "去坊市", toChapter: "WZXX_M1_N1_C010",},]},
        ],
    },

    #  #选项对话5
    #       { id: 'C002B_elingA',style: 6, title: '恶灵', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
    #       sections: [
    #       { key: 'M1', content: ['李森炎惊疑：“什么脏东西？”','美女大夫的脸色这才有了一些细微的变化，她看向李森炎，“别的办法也不是不行，你帮我杀了外面那个恶灵，我可以给你这个灵药。”',
    #       '“恶灵？”','李森炎倒吸一口冷气，推了推旁边的云云，低声问，“喂，恶灵是什么鬼啊？”','“我没法跟你解释，反正就是比较恶心的东西，你去的话……”云云上下打量他一眼，“胜算，不大。”',
    #       '虽然李森炎现在突破了炼气三重，但依旧没什么实战经验，这出去，不知道是死是活了','请选择是否要帮美女大夫——',],
    #       btn: [{title: "帮",tokey: "M3",dropIds: [ 'WZXX_M1_N1_C002B_V_Vdrop3'],},
    #       {title: "不帮",tokey: "M2",dropIds: [ 'WZXX_M1_N1_C002B_V_Vdrop4'],}]},

    #       { key: 'M2', content: ['胜算不大，李森炎当然是不愿冒这个险','而且恶灵显然是冲着这女大夫来的，自己没必要趟这趟浑水','只要能坚持，出去另外寻医，说不定还有办法能救自己',
    #       '“大夫，我这小身板我是真打不过，在下告辞！”','李森炎看了云云一眼，云云什么也没说，载着他往外飞走',[{ animations: {id: 4} },],'云云带着他飘出医馆，半空中他依稀看清了那恶灵',
    #       '那是一个肉糊糊的玩意，能看出来个人形，却看不出人样，没有皮囊，身上的肉不停蠕动，每一块都像是活物，试图从它的身体里钻出来',],
    #       btn: [{title: "英雄救美，还是回去吧",tokey: "M4",dropIds: [ 'WZXX_M1_N1_C002B_V_Vdrop5']},
    #       {title: "苟命要紧，还好溜的早",tokey: "M5",dropIds: [ 'WZXX_M1_N1_C002B_V_Vdrop6'],}]},

    #       { key: 'M4', content: ['“云云，你说，那个大夫那么纤弱的样子她能打得过这恶灵吗？”','云云一下就猜到了他的心思，“怎么，你个炼气二重想回去英雄救美了吗？”',
    #       '李森炎：“……”好像是有点不切实际。','说话间，恶灵已经缓缓朝医馆走去，李森炎想了想还是咬牙，“罢了，还是回去吧，我这人就是心软，见不得美女受欺负。”','“你何止心软，你现在那哪都软。”',
    #       '云云趁机又损了他一句，随后又道：“算你还有点良心。”','转身带着他飘回去了','医馆内，女大夫神色倒是颇为平静，淡定得很',
    #       '看见李森炎，她皱了下眉，随后迅速从口袋中拿出药丹，“算你还有种，这个药丸可以暂缓你身上的疼痛，你要是出了门还想溜走的话，尽管请便，不过等药效过去，你再痛得死去活来的时候，就别想让我再救你了。”','清冷的话语，却威胁力度十足','李森炎心悸，“你放心吧，大丈夫一言既出驷马难追。”','云云在背后无情补刀：“你不是花样美少年吗，怎么又成大丈夫了？”','李森炎吃下丹药',],
    #       btn: [{title: "冲出去与恶灵搏斗",toChapter: "WZXX_M1_N1_C009_[V2]"},]},

    #       { key: 'M5', content: ['李森炎内心庆幸，还好溜得早，这肉糊糊的玩意看着就让人头皮发麻，他真是对付不了',
    #       '云云突然语气颇有些不满地说道：“你还真走啊，那娇滴滴的姑娘不管了吗？”','“我现在泥菩萨过江自身难保了，哪还能管得了她呀，哎呦，疼疼疼，是真的疼。”',
    #       '“疼死你算了，你个胆小鬼，你不去我自己去。”','说着云云直接翻了个身，把李森炎甩了下去，二话不说掉头冲回医馆',[{ sounds: [{ soundId: 'SE_HV_0008',}] }] ,
    #       '李森炎摔了个七荤八素，还好经过修炼之后，身子骨比以前硬朗不少，不然这一摔直接能让他领盒饭了','“搞什么鬼，你这臭云，是色迷心窍了还是怎么地……”','李森炎很是无奈，自己现在这个状态，一个人走几乎看不到活路，无奈之下，他只好忍痛使出凌云步回医馆','医馆内，女大夫神色倒是颇为平静，淡定得很','看见李森炎，她皱了下眉，随后迅速从口袋中拿出药丹，“算你还有种，这个药丸可以暂缓你身上的疼痛，你要是出了门还想溜走的话，尽管请便，不过等药效过去，你再痛得死去活来的时候，就别想让我再救你了。”',
    #       '清冷的话语，却威胁力度十足','李森炎心悸，“你放心吧，大丈夫一言既出驷马难追。”','云云在背后无情补刀：“你不是花样美少年吗，怎么又成大丈夫了？”','李森炎吃下丹药',],
    #       btn: [{title: "冲出去与恶灵搏斗",toChapter: "WZXX_M1_N1_C009_[V2]"}]},

    #       { key: 'M3', content: ['“好，一言为定！”他黑瞳里闪过一丝狡黠之色','美女大夫睐了他一眼，将药丸塞到他手上',
    #       '李森炎大喜，赶紧吞下，随后又听身后的美女大夫幽幽开口','“这个药丸只是暂缓你身上的疼痛，你要是出了门想溜走的话，尽管请便，不过等药效过去，你再痛得死去活来的时候，就别想让我再救你了。”',
    #       '清冷的话语，却威胁力度十足','李森炎心悸，“你放心吧，大丈夫一言既出驷马难追。”','云云在背后无情补刀：“你不是花样美少年吗，怎么又成大丈夫了？”',
    #       '李森炎不理她，直接冲出门外','药丹果然奏效，几乎是服下的瞬间，那些疼痛浑然消失！','医馆门外，李森炎见到一个肉糊糊的玩意，能看出来个人形，却看不出人样，没有皮囊，身上的肉不停蠕动，每一块都像是活物，试图从它的身体里钻出来',],
    #       btn: [{title: "和它拼了",toChapter: "WZXX_M1_N1_C009_[V2]"},]},

    #     ],
    # },
  ]
    }
]