scenes: [
    #
    {
      id: 'WZXX_M1_N1_C0021_V',
      name: "定义对应标题名当前章节内的选项和变量",

      # 变量定义
      vars: [{ id: "v1", min: 0, max: 1 } ,
      { id: "biaoqianv1", min: 0, max: 1 } ,
      
      ],

      # 动作定义
      actions: [],

      # 事件定义
      # 故事中的场景事件暂时没什么意义
      events: [],


    
      chats: [
      #

      { 
        id: 'WZXX_M1_N1_C0021_V1', desc: '这是要做什么', 
        options: [ 
          { title: "【这……难道是……】",toChapter: "WZXX_M1_N1_C022",},
        ],
      },

       { 
        id: 'WZXX_M1_N1_C0021_V1', desc: '这是要做什么', 
        options: [ 
          { title: "【……】",toChapter: "WZXX_M1_N1_C022",},
        ],
      },

      { 
        id: 'WZXX_M1_N1_C0021_V2', desc: '抉择', 
        options: [ 
          { title: "【选择分支】",dialogs: ['C0020A_buyaoA'],},
        ],
      },

      


        ],


      # 对话框
      dialogs:
        [
      { id: 'C0020A_buyaoA', style: 12,title: '抉择',
         sections: {
            content: '究竟是选择留下来待在医灵身边增加更多好感度，还是去寻找陶老专心修炼呢？',
            btn: [
          { title: "【跟着陶老修行】", toChapter: "WZXX_M1_N1_C022" },
          { title: "【寻找医灵修行】", toChapter: "WZXX_M1_N2_C016" },
            ]
        },  
       },



           #选项对话
          { id: 'C0021A_huafuA',style: 6, title: '画符', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
          sections: [
          { key: 'P1', content: ['李森炎向他行了一礼：“陶老折煞我了，陶老对我有大恩，万万不可如此，此事就揭过不提了吧。”','陶老点了点头，随后拿出一叠符纸：“他拉不下脸皮过来，托我送你些东西，略表歉意。”','这倒是让李森炎感到意外了，没想到自己怼了对方，对方竟然反而还送东西给他了。',
          '“该不会是陶老本尊为了缓和我和他之间的关系，自己拿出来故意说是他送的吧？”','李森炎心中如此想道。',
          ],
          btn: [{title: '收下符纸',tokey: "P2",dropIds: [ 'WZXX_M1_N1_C0021_V_Vdrop1'],},]},

          { key: 'P2', content: ['但面上却不动声色地收下了，不管怎样，这个台阶还是要给的。','李森炎摸了摸那一叠符纸的厚度，以他前世数钱的经验来看，大概有个二十张左右。','类型各不相同，有攻击用的火球符，疾雷符，用于提升身法的轻身符，凌空符，还有功能类的定身符，结界符等等……',
          '怎么没有隐身符……李森炎将所有灵符看了一遍，这是唯一一个他觉得有些遗憾的地方。',
          '“你可以先试用一下。”','陶老指导了下他灵符的使用方法。',
          '方法不难，无非是用灵力描摹灵符上的文字，成功激活灵符威能后，方可使用。',],
          btn: [{title: '先用最初的火球符试试',games: { id: 5, word: ["火",] }, toChapter: "WZXX_M1_N1_C022",}]},

       
           ]  
        },


  ]
    }
]