scenes: [
    #worldTimeHidden: true or false // 设定对话场景中是否显示世界时间。
    #sceneImage: xxx // 设定对话场景中的背景图片名称
    {
      id: 'WZXX_M1_N1_C001B_V',
      name: "城外密林",
      worldTimeHidden: true,
      sceneImage: SceneMap0001,
      # 变量定义
      vars: [
      { id: "v1", min: 0, max: 1 },
      ],

      # 动作定义
      actions: [
      ],

      # 事件定义 阅读器中的场景事件暂时没什么意义
      events: [
      { type: 'enter', nextChat: 'C001B_EventSTART1',dialogs: ['C001B_START_shulin']},
      ],

      # 对话选项
      chats: [
      #选择道路事件=================================================
      { 
        id: 'WZXX_M1_N1_C001B_VD', desc: '选项', 
        options: [ 
          { 
          title: "选择道路",
          toScene: 'WZXX_M1_N1_C001B_V', 
          },
        ],
      }, 
      #
      { 
        id: 'C001B_EventSTART1', desc: '一个分叉路在你眼前', 
        options: [ 
          #第一次进入 
          { title: '【向左走】',nextChat: 'L1'  }, 
          { title: '【向右走】',nextChat: 'R1'  }, 
        ],
      },
      #
      { 
        id: 'L1', desc: '乱石挡住了去路，前面无法通行', 
        options: [ 
          { title: '【返回】',nextChat: 'C001B_EventSTART2'  }, 
        ],
      },
      #
      { 
        id: 'C001B_EventSTART2', desc: '一个分叉路在你眼前，你感觉和之前有所不同', 
        options: [ 
          #第一次进入 
          { title: '【向左走】',nextChat: 'L1'  }, 
          { title: '【向右走】',nextChat: 'R1'  }, 
        ],
      },
      { 
        id: 'R1', desc: '这是一条一路通畅的小路', 
        options: [ 
          { title: '【前进】',nextChat: 'C001B_Event02'  }, 
        ],
      },

      { 
        id: 'C001B_EventR2', desc: '一个分叉路在你眼前', 
        options: [ 
          #第一次进入 
          { title: '【向左走】',nextChat: 'L2'  }, 
          { title: '【走中间】',nextChat: 'A2'  }, 
          { title: '【向右走】',nextChat: 'R2'  }, 
        ],
      },














      #
      { 
        id: 'dalukou_Event01Day3', desc: '民居院落依着斜坡而建，路边有一条小河沟，桥头有一些小吃摊位', 
        options: [ 
          { title: '>>>【落月镇西-大路口】', andVarsOn: ['v1'], toScene: 'dalukou' }, 
          { title: '<<<【落月镇西-胡同口】', andVarsOn: ['v1'], toScene: 'hutongkou' }, 
        ],
      },

     #三合一分支界面=======================================================
      { 
        id: 'WZXX_M1_N1_C001B_V', desc: '选项', 
        options: [ 
        { title: "【选择行动目标】", 
        #章节选择
                    selector: {
              data: [
                {
                  title: "第一章 分支2",
                  body: " <<<<去寻找穿越带来的物品。>>>>\n终于摆脱了敌人，李森炎感觉自己身上一身轻松，这个时候终于能够好好的整理一下思路。\n现在的情况有些匪夷所思，看起来是遇到了一些小说中的穿越情况。",
                  toChapter: "WZXX_M1_N1_C001B_[B1]",
                },
               {
                  title: "第一章 分支1",
                  body: "<<<<去最近的城市,平川府白城>>>>\n明明不是自己所在的现实世界的逻辑，但记忆里，像是有两个截然不同的人生在交错缠杂，他甚至有些分不清谁是谁。说不定进城后能询问出更多线索。",
                  toChapter: "WZXX_M1_N1_C001B_[A1]",
                },
                {
                 title: "第一章 分支3",
                  body: " <<<<跟踪杀手，寻找线索>>>>\n不知为什么，李森炎在这个时候觉得特别的冷静。\n分明是刚刚穿越而来，却发现现在不但有了脑中特殊的记忆，还多了一身功夫。\n甚至现在。这具身躯中多出额外的力量来。",
                  # desc: "此段描述只有切换世界才用到",
                  toChapter: "WZXX_M1_N1_C001B_[C1]",
                },
              ]
            },
      
        },

 
        ],
      },
     #三合一分支界面结束==========================

        
        ],




      # 对话框 FullScreen全屏 HalfScreen 半屏
      dialogs:
        [
       #进入小道

    { id: 'C001B_START_shulin', style: 1,sections: ['地点，小树林。','李森炎小心翼翼的走着，生怕万一弄出太大动静，再把那倒霉的杀手引来。','不过，这还不是最大的问题','跑的时候不认识路，完全瞎跑。这想原路回去可就难了。','李森炎决定凭着模糊的印象摸索道路','……','一个分叉路口前',], nextChat: 'C001B_EventSTART1' },


        #进入小道
         { id: 'gameover00',
           style: 6, 
           title: '你挂了',
           dialogType: 'FullScreen', 
           textAnimationType: 'TextFadeIn', 
           sections: [
           { key: 'p1', content: ['地点，小树林。','李森炎小心翼翼的走着，生怕万一弄出太大动静，再把那倒霉的杀手引来。','不过，这还不是最大的问题','跑的时候不认识路，完全瞎跑。这想原路回去可就难了。','李森炎决定凭着模糊的印象摸索道路','……','一个分叉路口前',], 
           btn: [{title: '选择道路',tokey: "next"}]},
           ],

         },












          #选项对话
          { id: 'Screen1',style: 6, title: '林间小道', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
          sections: [
          { key: 'p1', content: ['地点，小树林。','李森炎小心翼翼的走着，生怕万一弄出太大动静，再把那倒霉的杀手引来。','不过，这还不是最大的问题','跑的时候不认识路，完全瞎跑。这想原路回去可就难了。','李森炎决定凭着模糊的印象摸索道路','……','一个分叉路口前',],
          btn: [{title: '走左边的路',tokey: "p1A"},{title: '走右边的路', tokey: "p1B"},],
          },

          { key: 'p1A', content: ['前面的路被堵死了。','只能原路返回。',], 
          btn: [{title: '返回', tokey: "p1A2"},], },   

          { key: 'p1A2', content: ['？','好像和之前的路口不一样',],
          btn: [{title: '走左边的路',tokey: "p1A2A"},{title: '走右边的路', tokey: "p1A2B"},]},

          { key: 'p1A2B', content: ['前面的路被堵死了','这里好像之前来过？',], 
          btn: [{title: '返回', tokey: "p1A2"},], },   


          { key: 'p1B', content: ['记得不少穿越小说念了之后就天地变色！','我也来一段!','道可道，非常道；名可名，非常名', '然后呢，额，好像不记得了。','……','正常谁去背这个？？！',['边缘闪烁红'],'杀手：我就不该信你小子','……',],
            btn: [{title: '……', dialogs: ['gameover00'] ,},]},   

          { key: 'p1C', content: ['我这脑子，记得当时全开小差了','就选……这个！', ],
            btn: [{title: '咏鹅',tokey: "p1C1"},{title: '望庐山瀑布',tokey: "p1C2"},{title: '写作业',tokey: "p1C3"},{title: '返回',tokey: "p1"}]},   

          { key: 'p1C1', content: ['你看我给你背一首秘籍里的诗','鹅，鹅，鹅，曲项向天歌。','白毛浮绿水，红掌拨清波。', '李森炎……','……','杀手……','一阵尴尬……',['边缘闪烁红'],'……','李森炎挂了',],
               btn: [{title: '…………',dialogs: ['gameover00']}]},
 
          { key: 'p1C2', content: ['你看我给你背一首秘籍里的诗','日照香炉生紫烟,李白来到烤鸭店。','口水直流三千尺,一摸口袋没带钱。', '李森炎：哈哈哈哈隔……','……','杀手……','一阵尴尬……',['边缘闪烁红'],'……','李森炎挂了',],
               btn: [{title: '…………',dialogs: ['gameover00']}]},
 
          { key: 'p1C3', content: ['你看我给你背一首秘籍里的诗',君子坦荡荡，小人写作业。,'人生自古谁无死，来生继续写作业。', '李森炎：哈哈哈哈……','……','杀手……','一阵尴尬……',['边缘闪烁红'],'李森炎挂了',],
               btn: [{title: '…………',dialogs: ['gameover00']}]}, 
 
          { key: 'p1D', content: ['得想个办法','让这杀手知道我真有秘籍','这秘籍肯定不能说放在身上，何况身上也没有。','那么就说放在家里或者藏起来？',],
          btn: [{title: '秘籍放在家里',tokey: "p1D1"},{title: '秘籍藏起来了', tokey: "p1D2"},{title: '秘籍在别人手里', tokey: "p1D3"},{title: '干脆什么都不说', tokey: "p1D4"},]},

          { key: 'p1E', content: ['我这功法有些奇特，主要打基础，只要习得人人可炼体小成。','你看我--时代在召唤','一二三四','二二三四', '李森炎……怎么样','……','……没看懂','两边一阵尴尬沉默后，李森炎猝。',],
            btn: [{title: '……', dialogs: ['gameover00'] ,},]},   
 
          { key: 'p1D1', content: ['我秘籍就放在家里。','我可以带你们去拿','……','杀手很高兴的样子，李森炎松了一口气。','可以，你带路，杀手说','李森炎转身，一步，两步，三步！','……！',['震屏1'],'……李森炎挂了','杀手：既然知道在你家，我自己去找就行了','……'  ],
          btn: [{title: '…………',dialogs: ['gameover00'] }]},    

          { key: 'p1D2', content: ['秘籍我藏起来了','我可以带你们去拿','……','杀手很高兴的样子，李森炎松了一口气。','可以，不过为了你不乱跑，先绑起来！','……！',['震屏1'],'被绑住的李森炎没法逃跑','……被毒打审问后没了利用价值','最后还是挂了','……'  ],
          btn: [{title: '…………',dialogs: ['gameover00'] }]},    

          { key: 'p1D3', content: ['秘籍在别人手里','但我可以带你去找他','……','杀手：那么这人是谁？','……','算了，夜长梦多',['边缘闪烁红'],'这么麻烦的话，你还是去死好了……'  ],
           btn: [{title: '…………',dialogs: ['gameover00'] }]},     

          { key: 'p1D4', content: ['就这样','……'],
          btn: [{title: '向着有声音的地方走',toChapter: "WZXX_M1_N1_C001B", }]},    



          ],

        },
    
 
        #死亡0
         { id: 'gameover00',
           style: 6, 
           title: '你挂了',
           dialogType: 'FullScreen', 
           textAnimationType: 'TextFadeIn', 
           sections: [
           { key: 'p1', content: ['你挂了，请选择'], btn: [{title: '不放弃，再来',dialogs: ['Screen1'] }, {title: '回章节开头', toChapter: "WZXX_M1_N1_C001A",}]},
           ],
         },
       #死亡3
         { id: 'gameover01',style: 6, title: '你挂了', varsOn: ['v1'], dialogType: 'HalfScreen', textAnimationType: 'TextFadeIn', sections: [
         { key: 'p3', content: ['临死前听到一句话','我一个学武的，最讨厌你们这帮文人……','你挂了，请选择'],btn: [{title: '不放弃，再来',dialogs: ['Screen1']},{title: '回章节开头',toChapter: "WZXX_M1_N1_C001"}]},
         ], },
  
 


        ],



    },



  ]
