scenes: [

    #
   {
      id: 'WZXX_M1_N1_C000F_V',
      name: "定义对应标题名当前章节内的选项和变量",

      # 变量定义
      vars: [
      { id: "v1", min: 0, max: 1 },
   
      
      ],

      # 动作定义
      actions: [],
      #不显示时间
      worldTimeHidden: true,
      # 事件定义# 故事中的场景事件暂时没什么意义
      events: [],

      chats: [

      { 
        id: 'WZXX_M1_N1_C000F_V', desc: '去公园', 
        options: [ 
          { title: "【去公园】",toScene: 'C000F_V_MAP_0_2',   },
        ],
      }, 
        ],  
    },

 #===========事件场景==============
       {
  # NPC2
    id: 'C000F_V_MAP_0_2', name: '公园入口',
    # 指定场景为NPC或MAP场景
    isNpc: true,
    #横图显示
    sceneImage: 'BGT_78',
    #不显示时间
    worldTimeHidden: true,
    # 当前场景地图
    mapId: 'C000F_V_MAP_0_0',
    # 地图中心点，也是进入地图后的点
    mapCenterPoint: [0, 2],
    # 变量定义
    vars: [
    { id: "ONE_OPEN_0", min: 0, max: 1 },
    { id: "ONE_OPEN_1", min: 0, max: 1 },
    # { id: "v_icon_100E", min: 0, max: 1 },
    ],
    # 动作定义
    actions: [
    ],
    # 事件定义
    events: [
       { type: 'enter', nextChat: 'C1'  },
    ],
    # 对话选项
    chats: [
      {
        id: 'C1', desc: "李森炎独自一人走进公园\n这边热闹多了\n早晨有老人家打太极，时不时各种名校大学生过来交流学习\n所以各种展览也办的很多",
        options: [ 
         { title: '【公告栏】',toScene: 'C000F_V_MAP_0_3', }, 
         { title: '【植物园】',toScene: 'C000F_V_MAP_-1_3', }, 
         { title: '【动物园】',toScene: 'C000F_V_MAP_1_3', }, 
        ],
      },


    ],
  },

  #===========事件场景==============
       {
  # NPC2
    id: 'C000F_V_MAP_0_3', name: '公告栏',
    # 指定场景为NPC或MAP场景
    isNpc: true,
    #横图显示
    sceneImage: 'BGT_80',
    #不显示时间
    worldTimeHidden: true,
    # 当前场景地图
    mapId: 'C000F_V_MAP_0_0',
    # 地图中心点，也是进入地图后的点
    mapCenterPoint: [0, 3],
    # 变量定义
    vars: [
    { id: "ONE_OPEN_0", min: 0, max: 1 },
    { id: "ONE_OPEN_1", min: 0, max: 1 },
    # { id: "v_icon_100E", min: 0, max: 1 },
    ],
    # 动作定义
    actions: [
    ],
    # 事件定义
    events: [
       { type: 'enter', nextChat: 'C1'  },
    ],
    # 对话选项
    chats: [
      {
        id: 'C1', desc: "公告栏上会每天更新公园情况和活动\n很多人都围着一块探头探脑的看着\n看来最近有什么大型活动要举行",
        options: [ 
         { title: '【查看公告栏】',nextChat: 'C2' },
         { title: '【离开>>>】',nextChat: 'C3' },  
        ],
      },

       {
        id: 'C2', desc: "公告：\n一号清晨9:00，广场舞大会\n下午14:00：音乐学院的学生将会在音乐长廊举行音乐交流会\n同时观景地有美术学院的学生写生",
        options: [ 
         { title: '【离开>>>】',nextChat: 'C3' }, 
        ],
      },

      {
        id: 'C3', desc: "选择行动地址————",
        options: [ 
         { title: '【植物园】',toScene: 'C000F_V_MAP_-1_3', }, 
         { title: '【动物园】',toScene: 'C000F_V_MAP_1_3', }, 
        ],
      },



    ],
  },

  #===========事件场景==============
       {
  # NPC2
    id: 'C000F_V_MAP_-1_3', name: '植物园',
    # 指定场景为NPC或MAP场景
    isNpc: true,
    #横图显示
    sceneImage: 'BGT_86',
    #不显示时间
    worldTimeHidden: true,
    # 当前场景地图
    mapId: 'C000F_V_MAP_0_0',
    # 地图中心点，也是进入地图后的点
    mapCenterPoint: [-1, 3],
    # 变量定义
    vars: [
    { id: "ONE_OPEN_0", min: 0, max: 1 },
    { id: "ONE_OPEN_1", min: 0, max: 1 },
    # { id: "v_icon_100E", min: 0, max: 1 },
    ],
    # 动作定义
    actions: [
    ],
    # 事件定义
    events: [
       { type: 'enter', nextChat: 'C1'  },
    ],
    # 对话选项
    chats: [
      {
        id: 'C1', desc: "新开的植物园不少人参观，生机勃勃，花团锦簇\n吸引来了很多游客和美术学生的参观",
        options: [ 
         { title: '【进入参观】',nextChat: 'C2' }, 
         { title: '【离开>>>】',nextChat: 'C3' }, 
        ],
      },
      {
        id: 'C2', desc: "植物园太大了，一个下午逛到闭馆还没逛完\n期间还驻足看了一会儿有人在写生画画\n确实收获到了不少灵感和素材",
        options: [ 
         { title: '【离开>>>】',nextChat: 'C3' }, 
        ],
      },

      {
        id: 'C3', desc: "选择行动地址————",
        options: [ 
         { title: '【音乐走廊】',toScene: 'C000F_V_MAP_-1_4', }, 
         { title: '【中心广场】',toScene: 'C000F_V_MAP_-1_4', }, 
        ],
         },

    ],
  },

  #===========事件场景==============
       {
  # NPC2
    id: 'C000F_V_MAP_1_3', name: '动物园',
    # 指定场景为NPC或MAP场景
    isNpc: true,
    #横图显示
    sceneImage: 'BGT_79',
    #不显示时间
    worldTimeHidden: true,
    # 当前场景地图
    mapId: 'C000F_V_MAP_0_0',
    # 地图中心点，也是进入地图后的点
    mapCenterPoint: [1, 3],
    # 变量定义
    vars: [
    { id: "ONE_OPEN_0", min: 0, max: 1 },
    { id: "ONE_OPEN_1", min: 0, max: 1 },
    # { id: "v_icon_100E", min: 0, max: 1 },
    ],
    # 动作定义
    actions: [
    ],
    # 事件定义
    events: [
       { type: 'enter', nextChat: 'C1'  },
    ],
    # 对话选项
    chats: [
      {
        id: 'C1', desc: "动物园绿树葱茏，花团锦簇，景色宜人\n有许多家长带着孩子来玩\n也有不少大学生",
        options: [ 
         { title: '【进去看看】',nextChat: 'C2' }, 
         { title: '【离开>>>】',nextChat: 'C3' }, 
        ],
      },

      {
        id: 'C2', desc: "买票进入动物园\n逛了一下午，确实看到了许多新奇的动物\n平时工作加班连轴转，逛一逛确实觉得自己十分放松\n也收集到了很多灵感",
        options: [ 
         { title: '【离开>>>】',nextChat: 'C3' }, 
        ],
      },

      {
        id: 'C3', desc: "选择行动地址————",
        options: [ 
         { title: '【便利店】',toScene: 'C000F_V_MAP_1_4', }, 
         { title: '【动物园】',toScene: 'C000F_V_MAP_1_3', }, 
        ],
      },


    ],
  },

#=============================事件场景================================
       {
  # NPC2
    id: 'C000F_V_MAP_-1_4', name: '音乐走廊',
    # 指定场景为NPC或MAP场景
    isNpc: true,
    #横图显示
    sceneImage: 'BGT_82',
    #不显示时间
    worldTimeHidden: true,
    # 当前场景地图
    mapId: 'C000F_V_MAP_0_0',
    # 地图中心点，也是进入地图后的点
    mapCenterPoint: [-1, 4],
    # 变量定义
    vars: [
    { id: "ONE_OPEN_0", min: 0, max: 1 },
    { id: "ONE_OPEN_1", min: 0, max: 1 },
    # { id: "v_icon_100E", min: 0, max: 1 },
    ],
    # 动作定义
    actions: [
    ],
    # 事件定义
    events: [
       { type: 'enter', nextChat: 'C1'  },
    ],
    # 对话选项
    chats: [

      {
        id: 'C1', desc: "这边经常会有音乐学院的人来开交流会\n需要到公告栏查看时间才能遇到\n今天看来是没有了，只是有许多人在这边拍照打卡",
        options: [ 
         { title: '【在这边驻足看一会儿】',nextChat: 'C2' }, 
         { title: '【离开>>>】',nextChat: 'C3' }, 
        ],
      },
      {
        id: 'C2', desc: "买票进入动物园\n逛了一下午，确实看到了许多新奇的动物\n平时工作加班连轴转，逛一逛确实觉得自己十分放松\n也收集到了很多灵感",
        options: [ 
         { title: '【离开>>>】',nextChat: 'C3' }, 
        ],
      },

      {
        id: 'C3', desc: "选择行动地址————",
        options: [ 
         { title: '【便利店】',toScene: 'C000F_V_MAP_1_4', }, 
         { title: '【动物园】',toScene: 'C000F_V_MAP_1_3', }, 
        ],
      },


    ],
  },
#=============================事件场景==========================
       {
  # NPC2
    id: 'C000F_V_MAP_0_4', name: '中心广场',
    # 指定场景为NPC或MAP场景
    isNpc: true,
    #横图显示
    sceneImage: 'BGT_83',
    #不显示时间
    worldTimeHidden: true,
    # 当前场景地图
    mapId: 'C000F_V_MAP_0_0',
    # 地图中心点，也是进入地图后的点
    mapCenterPoint: [0, 4],
    # 变量定义
    vars: [
    { id: "ONE_OPEN_0", min: 0, max: 1 },
    { id: "ONE_OPEN_1", min: 0, max: 1 },
    # { id: "v_icon_100E", min: 0, max: 1 },
    ],
    # 动作定义
    actions: [
    ],
    # 事件定义
    events: [
       { type: 'enter', nextChat: 'C1'  },
    ],
    # 对话选项
    chats: [
      {
        id: 'C1', desc: "中心广场这边有许多人围在一块下棋聊天的\n今天没有什么活动，所以李森炎没待多久就走了",
        options: [ 
          { title: '【离开>>>】',nextChat: 'C2' }, 
        ],
      },

       {
        id: 'C2', desc: "选择行动地址————",
        options: [ 
         { title: '【便利店】',toScene: 'C000F_V_MAP_1_4', }, 
         { title: '【展览馆】',toScene: 'C000F_V_MAP_-1_5', }, 
        ],
      },



    ],
  },

  #===========事件场景==============
       {
  # NPC2
    id: 'C000F_V_MAP_1_4', name: '便利店',
    # 指定场景为NPC或MAP场景
    isNpc: true,
    #横图显示
    sceneImage: 'BGT_85',
    #不显示时间
    worldTimeHidden: true,
    # 当前场景地图
    mapId: 'C000F_V_MAP_0_0',
    # 地图中心点，也是进入地图后的点
    mapCenterPoint: [1, 4],
    # 变量定义
    vars: [
    { id: "ONE_OPEN_0", min: 0, max: 1 },
    { id: "ONE_OPEN_1", min: 0, max: 1 },
    # { id: "v_icon_100E", min: 0, max: 1 },
    ],
    # 动作定义
    actions: [
    ],
    # 事件定义
    events: [
       { type: 'enter', nextChat: 'C1'  },
    ],
    # 对话选项
    chats: [
      {
        id: 'C1', desc: "这便利店来往的人很多\n老板是个很富态的大叔，总是乐呵呵的\n李森炎经常会和他坐下来聊两句能获得很多新资讯",
        options: [ 
         { title: '【和便利店老板交流】',nextChat: 'C2' }, 
         { title: '【离开>>>】', nextChat: 'C3' }, 
        ],
      },

      {
        id: 'C2', desc: "现在是人群的高峰期\n便利店的客人很多，可能老板暂时忙不过来\n算了还是先不打扰老板了",
        options: [ 
         { title: '【区别的地方转转】', nextChat: 'C3' }, 
        ],
      },

      {
        id: 'C3', desc: "选择行动地址————",
        options: [ 
         { title: '【观景地】',toScene: 'C000F_V_MAP_1_5', }, 
         { title: '【展览馆】',toScene: 'C000F_V_MAP_-1_5', }, 
        ],
      },


    ],
  },

  #===========事件场景==============
       {
  # NPC2
    id: 'C000F_V_MAP_-1_5', name: '展览馆',
    # 指定场景为NPC或MAP场景
    isNpc: true,
    #横图显示
    sceneImage: 'BGT_84',
    #不显示时间
    worldTimeHidden: true,
    # 当前场景地图
    mapId: 'C000F_V_MAP_0_0',
    # 地图中心点，也是进入地图后的点
    mapCenterPoint: [-1, 5],
    # 变量定义
    vars: [
    { id: "ONE_OPEN_0", min: 0, max: 1 },
    { id: "ONE_OPEN_1", min: 0, max: 1 },
    # { id: "v_icon_100E", min: 0, max: 1 },
    ],
    # 动作定义
    actions: [
    ],
    # 事件定义
    events: [
       { type: 'enter', nextChat: 'C1'  },
    ],
    # 对话选项
    chats: [
      {
        id: 'C1', desc: "这边时常有各式各样奇异的展览开房观看\n不过今天貌似没有\n看起来空空如也",
        options: [ 
         { title: '【等有展览再来看看】',nextChat: 'C2' }, 
        ],
      },

       {
        id: 'C2', desc: "选择行动地址————",
        options: [ 
         { title: '【观景地】',toScene: 'C000F_V_MAP_1_5', }, 
         { title: '【公园入口】',toScene: 'C000F_V_MAP_0_2', }, 
        ],
      },


    ],
  },

  #===========事件场景==============
       {
  # NPC2
    id: 'C000F_V_MAP_1_5', name: '观景地',
    # 指定场景为NPC或MAP场景
    isNpc: true,
    #横图显示
    sceneImage: 'BGT_81',
    #不显示时间
    worldTimeHidden: true,
    # 当前场景地图
    mapId: 'C000F_V_MAP_0_0',
    # 地图中心点，也是进入地图后的点
    mapCenterPoint: [1, 5],
    # 变量定义
    vars: [
    { id: "ONE_OPEN_0", min: 0, max: 1 },
    { id: "ONE_OPEN_1", min: 0, max: 1 },
    # { id: "v_icon_100E", min: 0, max: 1 },
    ],
    # 动作定义
    actions: [
    ],
    # 事件定义
    events: [
       { type: 'enter', nextChat: 'C1'  },
    ],
    # 对话选项
    chats: [
       {
        id: 'C1', desc: "公园后山的风景着实不错\n有很多美术学院的学生在此写生",
        options: [ 
         { title: '【静坐观赏风景】',nextChat: 'C2' }, 
         { title: '【离开>>>】', nextChat: 'C3' }, 
        ],
      },

      {
        id: 'C2', desc: "李森炎坐了一会儿，忽然有美术学院的学生上前搭话\n随后就很快的聊了起来\n仅仅一下午李森炎凭借自己的聪慧和幽默和学生们打的火热",
        options: [ 
         { title: '【离开>>>】',nextChat: 'C3' }, 
        ],
      },

       {
        id: 'C3', desc: "选择行动地址————",
        options: [ 
         { title: '【公告栏】',toScene: 'C000F_V_MAP_0_3', }, 
         { title: '【公园入口】',toScene: 'C000F_V_MAP_0_2', }, 
        ],
      },


    ],
  },


          


#=================================场景地图的设置==================================
    maps: [
    {
            id: 'C000F_V_MAP_0_0',
            data: [
              { 
              point: [0, 2], title: '公园入口', 
              toScene: 'C000F_V_MAP_0_2', 
              links: [[0, 3], ] 
              },

              { 
              point: [0, 3], title: '公告栏',
              toScene: 'C000F_V_MAP_0_3',
              links: [[-1, 3],[1, 3] ] 
              },

              { 
              point: [-1, 3], title: '植物园', 
              toScene: 'C000F_V_MAP_-1_3',
              links: [[-1, 4],] 
              },

              { 
              point: [1, 3], title: '动物园', 
              toScene: 'C000F_V_MAP_1_3',
              links: [[1, 4]] 
              },

              { 
              point: [-1, 4], title: '音乐走廊', 
              toScene: 'C000F_V_MAP_-1_4',
              links: [[-1, 5]] 
              },

              { 
              point: [0, 4], title: '中心广场', 
              toScene: 'C000F_V_MAP_0_4',
              links: [[-1, 4],[1, 4]] 
              },

              { 
              point: [1, 4], title: '便利店', 
              toScene: 'C000F_V_MAP_1_4',
              links: [[-2, 1]] 
              },

              { 
              point: [-1, 5], title: '展览馆', 
              toScene: 'C000F_V_MAP_-1_5',
              links: [[1, 5]] 
              },

              { 
              point: [1, 5], title: '观景地', 
              toScene: 'C000F_V_MAP_1_5',
              links: [[-1, 5]] 
              },
            ]
          },
   ],
  ]
