scenes: [
    #
    {
      id: 'WZXX_M1_N1_C0027_V',
      name: "定义对应标题名当前章节内的选项和变量",

      # 变量定义
      vars: [{ id: "v1", min: 0, max: 1 }],

      # 动作定义
      actions: [],

      # 事件定义
      # 故事中的场景事件暂时没什么意义
      events: [],


    
      chats: [
      #

      { 
        id: 'WZXX_M1_N1_C0027_V1', desc: '石壁', 
        options: [ 
          { title: "【别吵了，过来看看】",dialogs: ['C0027A_shibiA']},
        ],
      },

      { 
        id: 'WZXX_M1_N1_C0027_V2', desc: '背叛', 
        options: [ 
          { title: "【你……】",dialogs: ['C0027A_beipanA']},
        ],
      },
       { 
        id: 'WZXX_M1_N1_C0027_V3', desc: '背叛!', 
        options: [ 
          { title: "【你……】",dialogs: ['C0027A_beipanB']},
        ],
      },


        ],

      # 对话框
      dialogs:
        [
           #选项对话
          { id: 'C0027A_shibiA',style: 6, title: '石壁', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
          sections: [
          { key: 'P1', content: ['听到李森炎的话，这时候赖崇信也停下了嘴炮，两人凑过来，顺着李森炎手指的方向望去。','“这地方我砸的，怎么了？”',
          '赖崇信盯着李森炎所指的石壁，他只看到那石壁被他砸出了一个坑，除此之外，就没有其他东西了。',
          '“你能不能别卖关子了？”','赖崇信看不出来其中端倪，杨真却突然目光一亮，伸手将那些碎石犹如剥鸡蛋般剥开，很快，那地方就显露出一层金属的色泽。',
          ],
          btn: [{title: '这……',tokey: "P2",},]},

          { key: 'P2', content: ['赖崇信就算再傻，这时候也能看明白其中关键了，这石壁下掩藏了一层类似金属的东西，很不寻常，“我明白了，此地必有蹊跷！”',
          '“你还真是个大聪明，说了等于没说。”',
          '“有空在这说废话，不如赶紧把这面石壁清理一下。”',
          '李森炎俨然成了团队里的指挥，发号施令者。',
          ],
          btn: [{title: '清理石壁',tokey: "P3",}]},


          { key: 'P3', content: ['两人也没有说什么，立马上前清理掉石壁表层，很快，一个金属圆盘出现在三人的视线中。',
          '“这个圆盘是干什么用的，难道是个机关？”',
          '赖崇信再一次发表他那睿智的言论。','没人搭理他。','李森炎心想有机关则意味着这洞窟是人为打造，有人会专门打造一个宝窟给人来探宝吗？',
          ],
          btn: [{title: '实在是有些蹊跷啊',tokey: "P4",}]},

           { key: 'P4', content: ['李森炎突然有股不详的预感，立马出声阻止，然而高雁兰这时候却根本听不进去他的话。',
          '下一刻，有利箭刺破长空的呼啸声响起。',
           [{ sounds: [{ soundId: 'SE_KO_0003',}] }] ,
          ],
          btn: [{title: '…………',toChapter: "WZXX_M1_N1_C025_[N2][V1]",}]},
           ]  
        },

#选项对话
          { id: 'C0027A_beipanA',style: 6, title: '背叛', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
          sections: [
          { key: 'B1', content: ['“你……”','赖崇信张口想说些什么，却呕出一大口血，手口都在抖，指着杨真，说不出一句完整的话来。',
          '手无力垂下，赖崇信至死都没有闭上眼睛。','这一幕，同样震惊了李森炎。','他没有想到，这人伪装得这么好，在此之前，他都没有看出对方有什么破绽。','“我该叫你杨真呢，还是杨假？”','杨真回过头来，露出笑容：“随你高兴就行，反正你也就比他多活一点时间。”',
          ],
          btn: [{title: '等等',tokey: "B2",},]},

          { key: 'B2', content: ['杨真准备动手，却被李森炎喊住：“等等，我想知道，为什么？”','李森炎一边将江依依小心放下，目光始终注视着对方。',
          '“难道仅仅是因为利益？”','杨真失笑道：“本来我也不必跟你多废话，不过现在我心情好，让你做个明白鬼，也行。”',
          '杨真手指向玉上寒凝髓，说道：“玉上寒凝髓虽然稀有，却不是关键，关键是玉上寒凝髓是冰灵之心的培植养料，这里面的冰灵之心，那才是真正的宝贝。”',
          ],
          btn: [{title: '冰灵之心……', tokey: "B3",}]},

          { key: 'B3', content: ['话音刚落。','杨真心念一动，玉上寒凝髓泛起微微波澜，一枚犹如精致小雪球般的圆润珠子慢慢漂浮而起。',
          '见到这珠子的一瞬间，杨真的眼中，立时出现浓浓的兴奋兼贪婪之色。','“冰灵之心只有一颗，我势在必得，为了避免争端，我只好忍痛把你们都杀了。”',
          '杨真一把将冰灵之心抓在手里，嘴角露出残忍的笑意。',
          '李森炎皱了皱眉，他实在看不出来，这颗珠子有什么特殊的：“这东西就值得你大开杀戒？”'
          ],
          btn: [{title: '就这……',tokey: "B4",}]},

          { key: 'B4', content: ['“你是真的没见识。”','杨真对李森炎的无知嗤之以鼻。','“冰灵之心是一颗种子，相传这颗种子一旦生根发芽，便能结出冰灵果，而冰灵果能够让一个没有灵根的人，有机会衍生出冰灵根！',
          '“而想要让冰灵之心生根发芽，需要极为苛刻的条件与环境，相传这玉上寒凝髓便是其中一种。”','“你这说的都是传言，你有没有想过，这所谓的冰灵之心，或许根本不会发芽？”',
          ],
          btn: [{title: '什么？！难道……',toChapter: "WZXX_M1_N1_C027_[N3][V1]",}]},
           ]  
        },

         { id: 'C0027A_beipanB',style: 6, title: '背叛!', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
          sections: [
          { key: 'B4', content: ['“你是真的没见识。”','杨真对李森炎的无知嗤之以鼻。','“冰灵之心是一颗种子，相传这颗种子一旦生根发芽，便能结出冰灵果，而冰灵果能够让一个没有灵根的人，有机会衍生出冰灵根！',
          '“而想要让冰灵之心生根发芽，需要极为苛刻的条件与环境，相传这玉上寒凝髓便是其中一种。”','“你这说的都是传言，你有没有想过，这所谓的冰灵之心，或许根本不会发芽？”',
          ],
          btn: [{title: '什么？！难道……',toChapter: "WZXX_M1_N1_C027_[N3][V1]",}]},
          ]  
        },

  ]
    }
]