scenes: [
    #
    {
      id: 'WZXX_M1_N1_C002V',
      name: "定义对应标题名当前章节内的选项和变量",

      # 变量定义
      vars: [{ id: "v1", min: 0, max: 1 }],

      # 动作定义
      actions: [],

      # 事件定义
      # 故事中的场景事件暂时没什么意义
      events: [],

      # 对话选项
      chats: [
      #
      { 
        id: 'WZXX_M1_N1_C002V', desc: '选择回家还是？', 
        options: [ 
          { title: "【直接回家，越快越好】", toChapter: "WZXX_M1_N1_C002A_[A1]" },
          { title: "【考虑变装一下的可能】", toChapter: "WZXX_M1_N1_C002A_[B1]" },
          { title: "【先去找人打听情报】", toChapter: "WZXX_M1_N1_C002A_[C1]" },
        ],
      },
   #
      { 
        id: 'WZXX_M1_N1_C001_[A1]V03000', desc: '选项', 
        options: [ 
        #  { title: "【开始阅读333】", varsOn: ['WZXX_M1_N1_C001_[A1]'], },
          { title: "【你想起，这个身体原身是修真世家出身】", toChapter: "WZXX_M1_N1_C001_[A1]" },
          { title: "【你想起，这个身体原身是个贫穷包子铺小子】", toChapter: "WZXX_M1_N1_C001_[A2]" },
          { title: "【你想起，这个身体原身是白府富户的私生子】", toChapter: "WZXX_M1_N1_C001_[A3]" },
        ],
      },



      #
        ],

      # 对话框
      dialogs:
        [
 
        ],
    },
  ]
