scenes: [
    #
    {
      id: 'WZXX_M1_N1_ZC008_V',
      name: "定义对应标题名当前章节内的选项和变量",

      # 变量定义
      vars: [{ id: "v1", min: 0, max: 1 },
      { id: "biaoqianv1", min: 0, max: 1 } ,
      { id: "biaoqianv2", min: 0, max: 1 } ,
      { id: "biaoqianv3", min: 0, max: 1 } ,
      { id: "biaoqianv4", min: 0, max: 1 } ,
      { id: "biaoqianv5", min: 0, max: 1 } ,
      { id: "biaoqianv6", min: 0, max: 1 } ,
      { id: "biaoqianv7", min: 0, max: 1 } ,
      { id: "biaoqianv8", min: 0, max: 1 } ,
 
      ],

      # 动作定义
      actions: [],

      # 事件定义
      # 故事中的场景事件暂时没什么意义
      events: [
      ],
    
      chats: [
      
      {
        id: 'WZXX_M1_N1_ZC008_V1', desc: '该怎么办', 
        options: [
          {
          title: "【让别人去探险】",dialogs: ['ZC08A_1.1A'],
          icon: { id: 1, bindVar: 'biaoqianv1' }, varsOn: ['biaoqianv1']
          },

          {
          title: "【这探险就我来吧】",dialogs: ['ZC08A_1.1B'],
          icon: { id: 1, bindVar: 'biaoqianv2' }, varsOn: ['biaoqianv2']
          },
        ],
      },
     

      ],

      # 对话框
      dialogs:
        [
         #选项对话
          { 
            id: 'ZC08A_1.1A',style: 6, title: '让别人去', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
            sections: [
              {
                key: 'P1', 
                content: ['刚到此地，人地生疏，若是独自去探险，恐怕那就不是探险了','而是自寻死路。', '往往是这种时刻，团队和队友的重要性便出现了','谁会有意愿去探险？问问？'],
                btn: [
                {
                title: '询问赵掌柜',dialogs: ['ZC08A_1.2A'],
                icon: { id: 1, bindVar: 'biaoqianv3' }, varsOn: ['biaoqianv3']
                },
                {
                title: '询问斗笠人',dialogs: ['ZC08A_1.2B'],
                icon: { id: 1, bindVar: 'biaoqianv4' }, varsOn: ['biaoqianv4']
                },
                {
                title: '询问胖商人',dialogs: ['ZC08A_1.2C'],
                icon: { id: 1, bindVar: 'biaoqianv5' }, varsOn: ['biaoqianv5']
                },
                {
                title: '询问白书生',dialogs: ['ZC08A_1.2D'],
                icon: { id: 1, bindVar: 'biaoqianv6' }, varsOn: ['biaoqianv6']
                },
                {
                title: '询问夏姑娘',dialogs: ['ZC08A_1.2E'],
                icon: { id: 1, bindVar: 'biaoqianv7' }, varsOn: ['biaoqianv7']
                },
                ]
              },
            ]  
          }, 

           { 
            id: 'ZC08A_1.2A',style: 6, title: '赵掌柜', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
            sections: [
              {
                key: 'P1', 
                content: ['别看赵掌柜虽然嘴挺碎，总爱唠扯些有的没的。','但方才那两发石灰粉的毒药，倒是令人另眼相看。', 
                '这人到关键时刻，绝对是靠谱的。','是个不错的选择。','李森炎将探险的事提了提，赵掌柜虽然面露难色，但还是答应下了。',
                '不过嘛，他要李森炎和他一块去。',
                ],
                btn: [
                {
                title: '那就一起吧', dialogs: ['ZC08A_1.5B'],
                }
                ]
              },
            ]  
          }, 

          { 
            id: 'ZC08A_1.2B',style: 6, title: '斗笠人', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
            sections: [
              {
                key: 'P1', 
                content: ['斗笠人倒是个不错的选择对象。','无论是外形还是气质，都给人一种沉稳、值得信赖的感觉。', 
                '也不知道他是否乐意。','李森炎将此事和他提了一句。','他竟答应的十分爽快，不过要求嘛，就是要他们俩一块去。',
                ],
                btn: [
                {
                title: '那就一起吧', dialogs: ['ZC08A_1.5A'],
                }
                ]
              },
            ]  
          }, 

          { 
            id: 'ZC08A_1.2C',style: 6, title: '胖商人', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
            sections: [
              {
                key: 'P1', 
                content: ['胖商人方才那‘澡’洗的，现在已是有点神志不清的样子了。','运功施法轰干衣服后，便恍惚的坐在一旁。', 
                '依他这状态，就算去了，恐怕也是无用。','帮不上忙另说，若是变成累赘那就大可不必了。','看看其他人。',
                ],
                btn: [
                {
                title: '选别人吧', dialogs: ['ZC08A_1.1A'],
                }
                ]
              },
            ]  
          }, 

          { 
            id: 'ZC08A_1.2D',style: 6, title: '白书生', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
            sections: [
              {
                key: 'P1', 
                content: ['白书生显然不太想离开，夏姑娘方才在缠斗中受了伤。','看他此时忧心忡忡的模样，多半是想留下来照顾夏姑娘。', 
                '李森炎想了想，还是没和他提此事。','毕竟夏小姐确实也需要有人照料。','还是选别人吧。',
                ],
                btn: [
                {
                title: '另选他人吧', dialogs: ['ZC08A_1.1A'],
                }
                ]
              },
            ]  
          }, 

           { 
            id: 'ZC08A_1.2E',style: 6, title: '夏姑娘', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
            sections: [
              {
                key: 'P1', 
                content: ['夏姑娘刚才在缠斗的时候受了伤。','本着怜香惜玉的原则，这时也不能再让夏姑娘去探索啊。', 
                '还是另寻他人吧。',
                ],
                btn: [
                {
                title: '重新选一个', dialogs: ['ZC08A_1.1A'],
                }
                ]
              },
            ]  
          }, 

           { 
            id: 'ZC08A_1.1B',style: 6, title: '还是自己独自探险吧', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
            sections: [
              {
                key: 'P1', 
                content: ['突然猛烈的运功施法过后，必然会产生巨大的疲倦感。','不过这也和修为的高低有关，对大佬而言，出手就像洒洒水那么简单。', 
                '但对于他们这些普通的修仙者，面对金丹期的妖兽，如此搏斗。','消耗掉的体力是巨大的。','大家都满脸疲惫，于是李森炎便提出自己先去别处探险一番，说不定能找到带有温泉的池子，或者是别的什么。',
                '总之能让他们清洗休歇一番就成。','夏姑娘递来赞许的眼神，不过还是担心的说，“人生地不熟的，你一个人去太危险了。”',
                ],
                btn: [
                {
                title: '无妨', dialogs: ['ZC08A_1.3A'],
                },
                {
                title: '说的也对', dialogs: ['ZC08A_1.3B'],
                }
                ]
              },
            ]  
          }, 

         { 
            id: 'ZC08A_1.3A',style: 6, title: '无妨，独自一人', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
            sections: [
              {
                key: 'P1', 
                content: ['夏姑娘的言外之意便是让谁陪着一起去。','扫视一圈，似乎无人表态。', 
                '不过李森炎开始就做好了一个人去的打算，摆摆手不在意，“只是找个池子而已，没有我就回来，无碍。”','说完，作势离开，但转身之际听见身后传来两道声音。','“我可以去。”',
                '“我随你去看看吧。”','竟然是斗笠人和赵掌柜？',
                ],
                btn: [
                {
                title: '斗笠人看上去更有安全感', dialogs: ['ZC08A_1.4A'],
                },
                {
                title: '赵掌柜说不定有别的法器', dialogs: ['ZC08A_1.4B'],
                },
                {
                title: '坚持独自前往', dialogs: ['ZC08A_1.4C'],
                }
                ]
              },
            ]  
          }, 

           { 
            id: 'ZC08A_1.3B',style: 6, title: '说的也对，找一个人一块去', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
            sections: [
              {
                key: 'P1', 
                content: ['夏姑娘的言外之意便是让谁陪着一起去。','扫视一圈，似乎无人表态。', 
                '不过李森炎开始就做好了一个人去的打算，摆摆手不在意，“只是找个池子而已，没有我就回来，无碍。”','说完，作势离开，但转身之际听见身后传来两道声音。','“我可以去。”',
                '“我随你去看看吧。”','竟然是斗笠人和赵掌柜？',
                ],
                btn: [
                {
                title: '斗笠人看上去更有安全感', dialogs: ['ZC08A_1.4A'],
                },

                {
                title: '赵掌柜说不定有别的法器', dialogs: ['ZC08A_1.4B'],
                },
                ]
              },
            ]  
          }, 

          {
            id: 'ZC08A_1.4A',style: 6, title: '斗笠人一同前往', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
            sections: [
              {
                key: 'P1', 
                content: ['斗笠人倒是个不错的选择对象。','无论是外形还是气质，都给人一种沉稳、值得信赖的感觉。', 
                '就他了。',
                ],
                btn: [
                {
                title: '走！', dialogs: ['ZC08A_1.5A'],
                },
                
                
                ]
              },
            ]  
          }, 

           { 
            id: 'ZC08A_1.4B',style: 6, title: '和赵掌柜一同前去', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
            sections: [
              {
                key: 'P1', 
                content: ['别看赵掌柜虽然嘴挺碎，总爱唠扯些有的没的。','但方才那两发石灰粉的毒药，倒是令人另眼相看。', 
                '这人到关键时刻，绝对是靠谱的。','是个不错的选择。',
                ],
                btn: [
                {
                title: '走！', dialogs: ['ZC08A_1.5B'],
                },
                
                
                ]
              },
            ]  
          }, 

           { 
            id: 'ZC08A_1.4C',style: 6, title: '还是选择独自前往', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
            sections: [
              {
                key: 'P1', 
                content: ['李森炎挥手，不用。','那有那么矫情，只是找个池子罢了。', 
                '“不行，不怕一万就怕万一。”夏姑娘凛声道，说完看向身旁忧心忡忡的白书生，“你反正没事，你和他一起去。”','白书生想拒绝，然而夏姑娘的凌厉并不容许他多嘴的。',
                '李森炎：“……”','这白书生还不如赵掌柜和斗笠人呢。',
                ],
                btn: [
                {
                title: '走吧……', dialogs: ['ZC08A_1.5C'],
                },
               
                ]
              },
            ]  
          }, 

          { 
            id: 'ZC08A_1.5A',style: 6, title: '与斗笠人一起探险', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
            sections: [
              {
                key: 'P1', 
                content: ['苍翠的群山重峦叠嶂，笼罩着一层白雾，更显朦胧之美。','如此美景，就是不知道里面的东西是否会和外面一样有魅力了。', 
                '李森炎和斗笠人并肩走进深山之中，越往里走越发阴森，因为树木多了，遮住了绝大部分的阳光，只有斑驳稀疏的光线透过枝叶照射进来。','前面闪着磷火，鬼影幢幢，越走越深，李森炎只感一股异样的寒意袭来，周遭还时不时传来奇怪的兽叫。',
                '这地方就连飞鸟都是筑基巅峰期的级别，此处的走兽恐怕级别也低不到哪里去。','还好是二人同行。',
                ],
                btn: [
                {
                title: '走吧……', tokey: "P2",
                },
               
                ]
              },

              {
                key: 'P2', 
                 content: ['“李兄弟，前面好像有东西？”斗笠人拍拍他的肩膀，示意他看过去。','李森炎抬头，顺着他的视线看去，只是影影绰绰的看见一道白光，时不时还有氤氲出雾气。', 
                '在这阴森诡秘的山林之中显得格格不入。','若不是有斗笠人在，安全感备增，他都得寻思寻思这是不是幻觉了。',
                ],
                btn: [
                {
                title: '前去查看',  dialogs: ['AP3'],
                },
               
                ]
              },

              # {
              #   key: 'P3', 
              #    content: ['二人走进了看，更被眼前的场景所震撼。','山间的青翠孕育了这眼泉水，阴森可怖的林子阻挡了外界的污气，让它吐纳着天真地秀。', 
              #   '李森炎试了试，这居然还是温泉，汩汩泉水清冽甜美，绝对是绝佳选择！','于是快速走出山林，赶紧告诉众人，一起享受这温泉。','……','就这样休整一夜。',
              #   '这里离坊市不远，没必要再搭飞舟过去，步行就可以了。','不过总归是没抵达的，白书生拿了些符箓发给众人，虽然不算什么高阶符箓，但也是份心意。',
              #   ],
              #   btn: [
              #   {
              #   title: '不错不错', toChapter: "WZXX_M1_N1_Z2C09",
              #   },
               
              #   ]
              # },
            ]  
          }, 

          {
               id: 'AP3', style: 5, textAnimationType: 'TextSingle',
               sections: [
               {
                type: 'TopToBottom', bgImageId: 8, loop: true,
                 content: [
              '二人走进了看，更被眼前的场景所震撼。','山间的青翠孕育了这眼泉水，阴森可怖的林子阻挡了外界的污气，让它吐纳着天真地秀。', 
                '李森炎试了试，这居然还是温泉，汩汩泉水清冽甜美，绝对是绝佳选择！','于是快速走出山林，赶紧告诉众人，一起享受这温泉。','……','就这样休整一夜。',
                '这里离坊市不远，没必要再搭飞舟过去，步行就可以了。','不过总归是没抵达的，白书生拿了些符箓发给众人，虽然不算什么高阶符箓，但也是份心意。',
               ],
               },
              ],toChapter: "WZXX_M1_N1_Z2C09",
               },

          { 
            id: 'ZC08A_1.5B',style: 6, title: '与赵掌柜一起探险', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
            sections: [
              {
                key: 'P1', 
                content: ['苍翠的群山重峦叠嶂，笼罩着一层白雾，更显朦胧之美。','如此美景，就是不知道里面的东西是否会和外面一样有魅力了。', 
                '李森炎和赵掌柜并肩走进深山之中，越往里走越发阴森，因为树木多了，遮住了绝大部分的阳光，只有斑驳稀疏的光线透过枝叶照射进来。','前面闪着磷火，鬼影幢幢，越走越深，李森炎只感一股异样的寒意袭来，周遭还时不时传来奇怪的兽叫。',
                '这地方就连飞鸟都是筑基巅峰期的级别，此处的走兽恐怕级别也低不到哪里去。',
                ],
                btn: [
                {
                title: '还好是二人同行', tokey: "P2",
                },
               
                ]
              },

              {
                key: 'P2', 
                 content: ['“这走了老半天了，这破林子都没走出去，我看此地神秘诡异，在这里肯定没好事。”','果然，赵掌柜很快打起退堂鼓。', 
                '这林子也确实可怕，李森炎咽了咽口水，心中犹豫。','“走吧走吧，臭一点无所谓，别把命搭上。”赵掌柜说着就要拉着他离开。',
                '但，李森炎眼前一亮，“等等，前面好像有什么东西……”',
                ],
                btn: [
                {
                title: '回去', tokey: "P4",
                },
                {
                title: '继续往前探索', dialogs: ['BP3'],
                },
               
                ]
              },

              # {
              #   key: 'P3', 
              #    content: ['二人走进了看，更被眼前的场景所震撼。','山间的青翠孕育了这眼泉水，阴森可怖的林子阻挡了外界的污气，让它吐纳着天真地秀。', 
              #   '李森炎试了试，这居然还是温泉，汩汩泉水清冽甜美，绝对是绝佳选择！','于是快速走出山林，赶紧告诉众人，一起享受这温泉。','……','就这样休整一夜。',
              #   '这里离坊市不远，没必要再搭飞舟过去，步行就可以了。','不过总归是没抵达的，白书生拿了些符箓发给众人，虽然不算什么高阶符箓，但也是份心意。',
              #   ],
              #   btn: [
              #   {
              #   title: '不错不错', toChapter: "WZXX_M1_N1_Z2C09",
              #   },
               
              #   ]
              # },

            

               {
                key: 'P4', 
                 content: ['李森炎打量一番，那前方影影绰绰的白光。','有点犹豫，寻思着这会不会是幻觉，便点头，“那回去吧。”', 
                '臭死总比暴毙强啊。','但这回，赵掌柜意外不同意了。','“前面是挺稀奇的，走我们去看看。”','李森炎汗颜，这回倒不怕了？',
                ],
                btn: [
                {
                title: '前去查看', dialogs: ['BP3'],
                },
               
                ]
              },
            ]  
          }, 

            {
               id: 'BP3', style: 5, textAnimationType: 'TextSingle',
               sections: [
               {
                type: 'TopToBottom', bgImageId: 8, loop: true,
                 content: [
              '二人走进了看，更被眼前的场景所震撼。','山间的青翠孕育了这眼泉水，阴森可怖的林子阻挡了外界的污气，让它吐纳着天真地秀。', 
                '李森炎试了试，这居然还是温泉，汩汩泉水清冽甜美，绝对是绝佳选择！','于是快速走出山林，赶紧告诉众人，一起享受这温泉。','……','就这样休整一夜。',
                '这里离坊市不远，没必要再搭飞舟过去，步行就可以了。','不过总归是没抵达的，白书生拿了些符箓发给众人，虽然不算什么高阶符箓，但也是份心意。',
               ],
               },
              ],toChapter: "WZXX_M1_N1_Z2C09",
               },

           { 
            id: 'ZC08A_1.5C',style: 6, title: '与白书生一起探险', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
            sections: [
              {
                key: 'P1', 
                content: ['苍翠的群山重峦叠嶂，笼罩着一层白雾，更显朦胧之美。','如此美景，就是不知道里面的东西是否会和外面一样有魅力了。', 
                '李森炎和白书生并肩走进深山之中，越往里走越发阴森，因为树木多了，遮住了绝大部分的阳光，只有斑驳稀疏的光线透过枝叶照射进来。','前面闪着磷火，鬼影幢幢，越走越深，李森炎只感一股异样的寒意袭来，周遭还时不时传来奇怪的兽叫。',
                '这地方就连飞鸟都是筑基巅峰期的级别，此处的走兽恐怕级别也低不到哪里去。','还好是二人同行。',
                ],
                btn: [
                {
                title: '走吧……', tokey: "P2",
                },
               
                ]
              },

              {
                key: 'P2', 
                 content: ['不知走了多久，根本没找到任何能休歇的地方，甚至就连这片阴森可怖的森林都还没走出去。','白书生眼看就不想往前面走了，拉着李森炎说，“其实臭点也就臭点，这边里坊市不远了，休息一晚上明天再去镇上休整吧。”', 
                '“你说得对，但是前面好像有什么东西……”',
                ],
                btn: [
                {
                title: '回去', tokey: "P4",
                },
                {
                title: '继续往前探索',dialogs: ['CP3'],
                },
                ]
              },

              # {
              #   key: 'P3', 
              #    content: ['二人走进了看，更被眼前的场景所震撼。','山间的青翠孕育了这眼泉水，阴森可怖的林子阻挡了外界的污气，让它吐纳着天真地秀。', 
              #   '李森炎试了试，这居然还是温泉，汩汩泉水清冽甜美，绝对是绝佳选择！','于是快速走出山林，赶紧告诉众人，一起享受这温泉。','……','就这样休整一夜。',
              #   '这里离坊市不远，没必要再搭飞舟过去，步行就可以了。','不过总归是没抵达的，白书生拿了些符箓发给众人，虽然不算什么高阶符箓，但也是份心意。',
              #   ],
              #   btn: [
              #   {
              #   title: '不错不错', toChapter: "WZXX_M1_N1_Z2C09",
              #   },
               
              #   ]
              # },

              {
                key: 'P4', 
                 content: ['李森炎打量一番，那前方影影绰绰的白光。','有点犹豫，寻思着这会不会是幻觉，便点头，“那回去吧。”', 
                '臭死总比暴毙强啊。','但这回，白书生意外不同意了。','“前面是挺稀奇的，走我们去看看。”','李森炎汗颜，这回倒不怕了？',
                ],
                btn: [
                {
                title: '前去查看', dialogs: ['CP3'],
                },
               
                ]
              },
            ]  
          }, 

           {
               id: 'CP3', style: 5, textAnimationType: 'TextSingle',
               sections: [
               {
                type: 'TopToBottom', bgImageId: 8, loop: true,
                 content: [
              '二人走进了看，更被眼前的场景所震撼。','山间的青翠孕育了这眼泉水，阴森可怖的林子阻挡了外界的污气，让它吐纳着天真地秀。', 
                '李森炎试了试，这居然还是温泉，汩汩泉水清冽甜美，绝对是绝佳选择！','于是快速走出山林，赶紧告诉众人，一起享受这温泉。','……','就这样休整一夜。',
                '这里离坊市不远，没必要再搭飞舟过去，步行就可以了。','不过总归是没抵达的，白书生拿了些符箓发给众人，虽然不算什么高阶符箓，但也是份心意。',
               ],
               },
              ],toChapter: "WZXX_M1_N1_Z2C09",
               },



        ],
    }
]
