scenes: [
    #
    {
      id: 'WZXX_M1_N1_C0022_V',
      name: "定义对应标题名当前章节内的选项和变量",

      # 变量定义
      vars: [{ id: "v1", min: 0, max: 1 },
      { id: "biaoqianv1", min: 0, max: 1 } ,
      { id: "biaoqianv2", min: 0, max: 1 } ,
      
      ],

      # 动作定义
      actions: [],

      # 事件定义
      # 故事中的场景事件暂时没什么意义
      events: [],


    
      chats: [
      #

      { 
        id: 'WZXX_M1_N1_C0022_V1', desc: '尖叫的女人', 
        options: [ 
          { title: "【前面发生什么事了？！】",dialogs: ['C0022A_jianjiaoA'], icon: { id: 1, bindVar: 'biaoqianv1' }, varsOn: ['biaoqianv1']},
        ],
      },
      
      { 
        id: 'WZXX_M1_N1_C0022_V2', desc: '耍帅', 
        options: [ 
          { title: "【结束战斗】",dialogs: ['C0022A_zhandouA'], icon: { id: 1, bindVar: 'biaoqianv2' }, varsOn: ['biaoqianv2']},
        ],
      },

      


        ],


      # 对话框
      dialogs:
        [
           #选项对话
          { id: 'C0022A_jianjiaoA',style: 6, title: '尖叫的女人', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
          sections: [
          { key: 'P1', content: ['神照忽然开启，李森炎一下洞察到，有一只体型庞大的人面白蛛，','正追着一个女子跑。',
          '他皱了下眉头，这是个什么玩意？为什么还张着一张人脸？','一个凌云步，李森炎腾跃而起，站在密林之中，很快便是见到那只人面白蜘。','体型十分庞大，浑身布满白色绒毛，身上八根蛛矛尖锐异常，凶悍并且行动迅猛，头上顶着一张人脸，那张人脸泛着疯狂而怪异的神采，裂开嘴发出怪异的笑声，直让人觉得汗毛倒竖，脊背发凉。',
          '此时，那发出惨叫的女子，右手滋滋冒血，想必是在刚才的打斗过程中受了伤，最关键的是身体被粘性极强的蛛网缚住，失去了反抗和逃走的可能了。',
          ],
          btn: [{title: '英雄救美，这波冲了',tokey: "P2",},{title: '观望一下，不要冲动',tokey: "P3",}]},


          { key: 'P2', content: ['身为一个血气方刚，英姿勃勃，顶天立地的九尺男儿，咳咳……虽然有点夸张的成分，但都不重要。','重要的是，那可是美女，大美女！','咳咳不是……','我辈中人，当扶危解困为己任！',
          ],
          btn: [{title: '冲！', toChapter: "WZXX_M1_N1_C022_[N2]",}]},

          { key: 'P3', content: ['先不要轻举妄动，不能被情绪冲昏了头脑。','就他现在的境界，没有云云在，冒然行动说不定还会得不偿失。',
          '人不为己天诛地灭，李森炎决定明哲保身。','谁曾想，那女子这时候看见了他，立马朝他呼喊，“拜托你救救我！我必有重谢！！！”','重谢？',
          '李森炎听到这话当即犹豫了一下，有好处的话性质就不一样了。','而就在这时候，那人面白蛛已张开朝着女子扑了过去。','李森炎当下有了决定，为了那女子的重谢，莽一波！',
          ],
          btn: [{title: '冲！',toChapter: "WZXX_M1_N1_C022_[N2]",}]},
           ]  
        },

         





 #选项对话
          { id: 'C0022A_zhandouA',style: 6, title: '耍帅', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
          sections: [
          { key: 'P1', content: ['“多谢你救了我。”','忽然，耳边传来轻柔的女声，那女人已挣脱了蛛网的束缚，手上的血也已经止住了。',
          '李森炎吹了口气，心想，这个时候不装什么时候装啊。','刚想做出一副云淡风轻，毫不费力，甚至有点想梳一下头发，来个邪魅一笑的时候……',[{ sounds: [{ soundId: 'SE_HV_0003',}] }] ,'‘咔嚓’',
          ],
          btn: [{title: '什么情况？',tokey: "P2",},]},

          { key: 'P2', content: ['刚刚用力太猛了……有些超出身体所能承受的极限。','江依依见状，当即上前以灵力帮他温养手臂，疼痛感立减。',
          '神之右手，又回来了！','随后，江依依将她身上的储物袋递给他：“救命之恩，无以为报，我身上的东西都在这储物袋里，请恩人收下，不知恩人名讳……”','“我姓李。”',
          ],
          btn: [{title: '交流一番', tokey: "P3",}]},

          { key: 'P3', content: ['通过交谈，李森炎知道了她是个散修。','整个储物袋里面也没有太多有价值的东西。',
          '同是天涯沦落人呐。','李森炎只收了些许灵石，就把储物袋还给她，他不是贪得无厌的人，当个打手收取点报酬应该的，不过也不能狮子大开口，否则容易没朋友。',
          '江依依更是感恩戴德，此时的她脸上颇具憔悴之色，还沾了些泥灰，不过那双漂亮的澄眸闪烁着，很有灵气，好看。',
          '李森炎挠挠头发，“话说回来，你是怎么会惹上这种东西的，这到底是什么？人不像是人，妖兽不像是妖兽的。”'
          ],
          btn: [{title: '……',tokey: "P4",}]},

          { key: 'P4', content: ['“这是精怪，是妖兽吞噬人魂后，在某些特定的条件下形成的变种。”','江依依有些意外他竟不知精怪，眸光微动，随后说道。',
          '“我加入了一个修行者小队一起探宝，在一个宝窟中，遭遇了人面蛛群，和小队里的人分散逃走，这才被追到此处……”','李森炎点了点头：“原来如此。”',
          '江依依看了一眼李森炎，忽然开口：“李大哥，冒昧问一句，是一个人在这里历练吗？”',
          '“差不多吧，怎么了？”','本来是还有一朵云的，只可惜，现在莫得了。','闻言，江依依目光一亮，“不如你和我一起回小队吧！咱们一起历练寻宝，多一个人就多一分力量！”'
          ],
          btn: [{title: '反正无聊，不如去见识见识',toChapter: "WZXX_M1_N1_C023_[N1]",}]},
           ]  
        }

  ]
    }
]