scenes: [
    #
    {
      id: 'WZXX_M1_N1_C0020_V',
      name: "定义对应标题名当前章节内的选项和变量",

      # 变量定义
      vars: [{ id: "v1", min: 0, max: 1 }],

      # 动作定义
      actions: [],

      # 事件定义
      # 故事中的场景事件暂时没什么意义
      events: [],


    
      chats: [
      #

      { 
        id: 'WZXX_M1_N1_C0020_V1', desc: '要，还是不要', 
        options: [ 
          { title: "【使不得使不得】",dialogs: ['C0020A_buyaoA']},
          { title: "【我全都要】",dialogs: ['C0020A_quanyaoA']},
        ],
      },

      


        ],


      # 对话框
      dialogs:
        [




           #选项对话
          { id: 'C0020A_buyaoA',style: 6, title: '使不得使不得', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
          sections: [
          { key: 'P1', content: ['“你以为我跟你一样？是那种趁机敲诈勒索的小人？”','李森炎瞥了一眼她手中的灵石，嗤之以鼻道','女人吓得直接跪下了，李森炎不收她的东西，她更害怕',
          '因为那意味着李森炎不愿意放过她！','“是我有眼不识泰山，冲撞了大哥你，这些灵石是我自愿献给大哥，只为赔罪！没有别的意思！”','女人以头抢地，恳请李森炎收下灵石','等到她头都快磕晕过去，李森炎这才慢悠悠地笑纳了',[{ sounds: [{ soundId: 'SE_CQ_0008',}] }] ,
          '获得灵石+16',
          ],
          btn: [{title: '未完待续……',tokey: "P2"},]},

       
           ]  
        },

        
           #选项对话
          { id: 'C0020A_quanyaoA',style: 6, title: '我全都要', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
          sections: [
          { key: 'P1', content: ['“这怎么好意思，搞得我像敲诈勒索一样。”','说着将灵石收了起来。','女子笑得比哭的还惨：“不会不会，这都是我诚心给的，算是为我的灵犬赔罪，给你们添麻烦了！”',
          '“你给我添的麻烦倒是其次，最主要是我的挚爱亲朋受到了惊吓，你说怎么办吧？”','李森炎指了指云云说道。',
          ],
          btn: [{title: '嘿嘿，坑她一笔',tokey: "P2"},]},

          { key: 'P2', content: ['“刚不是……”','女子想说刚不是已经把灵石都给你了吗？话刚开口又连忙止住。','什么叫狮子大开口？这才是！',
          '你们这些围观吃瓜的家伙，都睁眼好好看看啊！',
          '女子苦笑着，又把自己身上值钱的金饰摘下来。','“我身上值钱的，也就只有世俗之物了，不知道大哥你这位挚爱亲朋能不能看得上？”','“她不喜欢金子”，李森炎替云云回答，“不过我喜欢，就先替她收着了。”',
          '云云：“……”','你做人，也是挺狗的。',[{ sounds: [{ soundId: 'SE_CQ_0008',}] }] ,'获得灵石+16','获得黄金饰品+3',],
          btn: [{title: '未完待续……',tokey: "P1"}]},

         




           ]  
        },




















      

  ]
    }
]