scenes: [
    #
    {
      id: 'WZXX_M1_N1_C001A_V',
      name: "定义对应标题名当前章节内的选项和变量",

      # 变量定义
      vars: [
      { id: "v1", min: 0, max: 1 },
      { id: "v2", min: 0, max: 1 } ,
      { id: "v3", min: 0, max: 1 } ,
      { id: "biaoqianv1", min: 0, max: 1 } ,
      { id: "biaoqianv2", min: 0, max: 1 } ,
      { id: "biaoqianv3", min: 0, max: 1 } ,
      { id: "biaoqianv4", min: 0, max: 1 } ,
      { id: "biaoqianv5", min: 0, max: 1 } ,
      { id: "biaoqianv6", min: 0, max: 1 } ,
      { id: "biaoqianv7", min: 0, max: 1 } ,
      { id: "biaoqianv8", min: 0, max: 1 } ,
      { id: "biaoqianv9", min: 0, max: 1 } ,
      { id: "biaoqianv10", min: 0, max: 1 } ,
      { id: "biaoqianv11", min: 0, max: 1 } ,
      { id: "biaoqianv12", min: 0, max: 1 } ,
      { id: "biaoqianv13", min: 0, max: 1 } ,
      { id: "biaoqianv14", min: 0, max: 1 } ,
      { id: "biaoqianv15", min: 0, max: 1 } ,

       

      ],

      # 动作定义
      actions: [],

      # 事件定义
      # 故事中的场景事件暂时没什么意义
      events: [],

      # 对话选项
      chats: [
      #
      { 
        id: 'WZXX_M1_N1_C001A_V', desc: '选项', 
        options: [ 
          { title: "【秘籍的解释】", dialogs: ['Screen1'], icon: { id: 1, bindVar: 'biaoqianv15' }, varsOn: ['biaoqianv15']}
        ],
      },
      #
        ],




      # 对话框 FullScreen全屏 HalfScreen 半屏
      dialogs:
        [
           #选项对话
          { id: 'Screen1',style: 6, title: '证明自己有秘籍', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
          sections: [
          { key: 'p1', content: ['得想个办法','让这杀手知道我真有秘籍',],
          btn: [
          {title: '不行，再想想', tokey: "p1D" , icon: { id: 7, bindVar: 'biaoqianv3' }, dropIds: ['WZXX_M1_N1_C001A_V_Vdrop2',], },

          #{title: '草，想不出来！（理直气壮）',tokey: "p1A"},
          {title: '不如念一段道德经？', tokey: "p1B", icon: { id: 6, bindVar: 'biaoqianv1' }},
          {title: '用小学课本里看到的诗句！', tokey: "p1C",  icon: { id: 6, bindVar: 'biaoqianv2' }},
          #{title: '做几个广播体操的动作', tokey: "p1E"},
          ]},

          #{ key: 'p1A', content: ['李森炎露出自信的笑容，牙齿仿佛在闪闪发光！','…………？','杀手：你傻笑什么？','李森炎：没事，我这是自信!'], 
          #btn: [{title: '我这是自信!别打我！', tokey: "p1"},], },   

          { key: 'p1B', content: ['记得不少穿越小说念了之后就天地变色！','我也来一段!','道可道，非常道；名可名，非常名', '然后呢，额，好像不记得了。','……','正常谁去背这个？？！',['边缘闪烁红'],'杀手：我就不该信你小子','……',],
            btn: [{title: '……', dialogs: ['gameover00'] , varsOn: ['biaoqianv1',]},]},   

          { key: 'p1C', content: ['我这脑子，记得当时全开小差了','就选……这个！', ],
            btn: [{title: '咏鹅',tokey: "p1C1",  icon: { id: 6, bindVar: 'biaoqianv8' }},{title: '望庐山瀑布',tokey: "p1C2",  icon: { id: 6, bindVar: 'biaoqianv9' }},
            #{title: '写作业',tokey: "p1C3"},
            {title: '谁会选这些啊！返回',tokey: "p1", varsOn: ['biaoqianv2',]}]},   

          { key: 'p1C1', content: ['你看我给你背一首秘籍里的诗','鹅，鹅，鹅，曲项向天歌。','白毛浮绿水，红掌拨清波。',[{ sounds: [{ soundId: 'SE_UE_0012',}] }] , '李森炎……','……','杀手……','一阵尴尬……',['边缘闪烁红'],'……','李森炎挂了',],
               btn: [{title: '…………',dialogs: ['gameover00'], varsOn: ['biaoqianv2','biaoqianv8',]}]},
 
          { key: 'p1C2', content: ['你看我给你背一首秘籍里的诗','日照香炉生紫烟,李白来到烤鸭店。','口水直流三千尺,一摸口袋没带钱。', '李森炎：哈哈哈哈隔……','……','杀手……','一阵尴尬……',['边缘闪烁红'],'……','李森炎挂了',],
               btn: [{title: '…………',dialogs: ['gameover00'], varsOn: ['biaoqianv2','biaoqianv9',]}]},

          #{ key: 'p1C3', content: ['你看我给你背一首秘籍里的诗',君子坦荡荡，小人写作业。,'人生自古谁无死，来生继续写作业。', '李森炎：哈哈哈哈……','……','杀手……','一阵尴尬……',['边缘闪烁红'],'李森炎挂了',[{ sounds: [{ soundId: 'SE_KO_0016',}] }] ,],
           #    btn: [{title: '…………',dialogs: ['gameover00']}]}, 
 
          { key: 'p1D', content: ['得想个办法','让这杀手知道我真有秘籍','这秘籍肯定不能说放在身上，何况身上也没有。','那么就说放在家里或者藏起来？',],
          btn: [
          {title: '干脆什么都不说', tokey: "p1D4",  icon: { id: 7, bindVar: 'biaoqianv7' }},
          {title: '秘籍放在家里',tokey: "p1D1",  icon: { id: 6, bindVar: 'biaoqianv4' }},
          {title: '秘籍藏起来了', tokey: "p1D2",  icon: { id: 6, bindVar: 'biaoqianv5' }},
          {title: '秘籍在别人手里', tokey: "p1D3",  icon: { id: 6, bindVar: 'biaoqianv6' }},
          
          ]},
        

          #{ key: 'p1E', content: ['我这功法有些奇特，主要打基础，只要习得人人可炼体小成。','你看我--时代在召唤','一二三四','二二三四', '李森炎……怎么样','……','……没看懂','两边一阵尴尬沉默后，李森炎猝。',],
          #btn: [{title: '……', dialogs: ['gameover00'] ,},]},   
 
          { key: 'p1D1', content: ['我秘籍就放在家里。','我可以带你们去拿','……','杀手很高兴的样子，李森炎松了一口气。','可以，你带路，杀手说','李森炎转身，一步，两步，三步！',[{ sounds: [{ soundId: 'SE_KO_0016',}] }] ,'……！',['震屏1'],'……李森炎挂了','杀手：既然知道在你家，我自己去找就行了','……'  ],
          btn: [{title: '…………',dialogs: ['gameover00'] , varsOn: ['biaoqianv4','biaoqianv3',]}]},    

          { key: 'p1D2', content: ['秘籍我藏起来了','我可以带你们去拿','……','杀手很高兴的样子，李森炎松了一口气。','可以，不过为了你不乱跑，先绑起来！','……！',['震屏1'],'被绑住的李森炎没法逃跑','……被毒打审问后没了利用价值',[{ sounds: [{ soundId: 'SE_KO_0016',}] }] ,'最后还是挂了','……'  ],
          btn: [{title: '…………',dialogs: ['gameover00'], varsOn: ['biaoqianv5','biaoqianv3',] }]},    

          { key: 'p1D3', content: ['秘籍在别人手里','但我可以带你去找他','……','杀手：那么这人是谁？','……','算了，夜长梦多',['边缘闪烁红'],'这么麻烦的话，你还是去死好了……',[{ sounds: [{ soundId: 'SE_KO_0016',}] }] ,  ],
           btn: [{title: '…………',dialogs: ['gameover00'] , varsOn: ['biaoqianv6','biaoqianv3',]}]},     

          { key: 'p1D4', content: ['什么都不说','说多错多','干脆让对方脑补','……','杀手：这小子看起来这么自信，难道真有料不成？',['盖章过关'],'……'],
          btn: [
          {title: '有戏',toChapter: "WZXX_M1_N1_C001B",  dropIds: ['WZXX_M1_N1_C001A_V_Vdrop1',],  varsOn: ['biaoqianv7','biaoqianv3',]}
          ]
          },    
          ],
        },
    
 
        #死亡0
         { id: 'gameover00',
           style: 7, artId: 2, 
           title: '你挂了',
           dialogType: 'FullScreen', 
           textAnimationType: 'TextFadeIn', 
           sections: [
           { key: 'p1', content: ['你挂了，请选择'], btn: [{title: '不放弃，再来',dialogs: ['Screen1'],dropIds: ["WZXX_M1_N1_C001A_V_gameover01",], }, {title: '回章节开头', toChapter: "WZXX_M1_N1_C001A",dropIds: ["WZXX_M1_N1_C001A_V_gameover01",],}]},
           ],
         },
       #死亡3
         { id: 'gameover01',style: 7,artId: 4, title: '你挂了', varsOn: ['v1'], dialogType: 'HalfScreen', textAnimationType: 'TextFadeIn', sections: [
         { key: 'p3', content: ['临死前听到一句话','我一个学武的，最讨厌你们这帮文人……','你挂了，请选择'],btn: [{title: '不放弃，再来',dialogs: ['Screen1'], dropIds: ["WZXX_M1_N1_C001A_V_gameover02",],},{title: '回章节开头',toChapter: "WZXX_M1_N1_C001", dropIds: ["WZXX_M1_N1_C001A_V_gameover02",],}]},
         ], },

        ],



    },



  ]
