scenes: [
    #
    {
      id: 'WZXX_M1_N1_ZC005_V',
      name: "定义对应标题名当前章节内的选项和变量",

      # 变量定义
      vars: [{ id: "v1", min: 0, max: 1 },
      { id: "biaoqianv1", min: 0, max: 1 } ,
      { id: "biaoqianv2", min: 0, max: 1 } ,
      { id: "biaoqianv3", min: 0, max: 1 } ,
      { id: "biaoqianv4", min: 0, max: 1 } ,
      ],

      # 动作定义
      actions: [],

      # 事件定义
      # 故事中的场景事件暂时没什么意义
      events: [
      ],


    
      chats: [
      #
      { 
        id: 'WZXX_M1_N1_ZC005_V1', desc: '灵茶', 
        options: [ 
          { 
          title: "【再喝一杯】",toChapter: "WZXX_M1_N1_Z2C06",
          icon: { id: 1, bindVar: 'biaoqianv1' }, varsOn: ['biaoqianv1']
          },

          {
          title: "【再喝三杯】",toChapter: "WZXX_M1_N1_Z2C06",
          icon: { id: 1, bindVar: 'biaoqianv2' }, varsOn: ['biaoqianv2']
          },

          {
          title: "【能喝多少喝多少】",toChapter: "WZXX_M1_N1_Z2C06",
          icon: { id: 1, bindVar: 'biaoqianv3' }, varsOn: ['biaoqianv3']
          },

          { 
          title: "【还是不要喝了】",toChapter: "WZXX_M1_N1_Z2C06",
          icon: { id: 1, bindVar: 'biaoqianv4' }, varsOn: ['biaoqianv4']
          },
        ],
      },
      ],

      # 对话框
      dialogs:
        [


         

         
        ],


    }
]
