scenes: [
    #
    {
      id: 'WZXX_M1_N1_C0024_V',
      name: "定义对应标题名当前章节内的选项和变量",

      # 变量定义
      vars: [{ id: "v1", min: 0, max: 1 }],

      # 动作定义
      actions: [],

      # 事件定义
      # 故事中的场景事件暂时没什么意义
      events: [],


    
      chats: [
      #

      { 
        id: 'WZXX_M1_N1_C0024_V1', desc: '遇害', 
        options: [ 
          { title: "【蛛王……！】",dialogs: ['C0024A_zhandouA']},
        ],
      },

      


        ],

      # 对话框
      dialogs:
        [
           #选项对话
          { id: 'C0024A_zhandouA',style: 6, title: '遇害', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
          sections: [
          { key: 'P1', content: ['赖崇信惊叫出声，这时壮汉钟大山冲过去，抡起手中千斤重的大锤，照着蛛王的脸砸落。','“白痴！”',
          '见到这一幕，李森炎大摇其头，这壮汉真是四肢发达头脑简单，这种直球的进攻方式不是妥妥的活靶子？','果然，蛛王张口接连吐出数面蛛网，钟大山的双锤落在蛛网上，瞬间便有一种击打在棉花上的感觉，',
          '蛛网的柔韧性极强，最不惧的就是这种纯粹的力量攻击。',
          '钟大山非但没有解救到赖崇信，反而把自己也给搭进去了，这一幕直接把李森炎人都看傻了。','看着被蛛网缚住的两人，李森炎忍不住看向杨真，张口就是一句吐槽：“你这是从哪招来的卧龙凤雏？',
          ],
          btn: [{title: '……',tokey: "P2",},]},

          { key: 'P2', content: ['杨真尴尬地笑了笑，他虽然没太懂李森炎这句话，但也知道那绝不是一句好话。','“你们两个废材，还得是我来。”',
          '高雁兰翻了个白眼，手中赤色长鞭挥舞不停，那鞭形如长蛇，材质便是用的是某种妖兽皮囊所制，颇有重量，从外观上来看更是比寻常鞭子要粗壮不少。',
          [{ sounds: [{ soundId: 'SE_MS_0041',}] }] ,
          ],
          btn: [{title: '这是……火云绕？',toChapter: "WZXX_[Chapters]/WZXX_M1_N1_C025_[N1][V1]",}]},

           ]  
        },


  ]
    }
]