scenes: [
    #
    {
      id: 'WZXX_M1_N1_C0018_VA',
      name: "定义对应标题名当前章节内的选项和变量",

      # 变量定义
      vars: [{ id: "v1", min: 0, max: 1 },
      { id: "biaoqianv1", min: 0, max: 1 } ,
      ],

      # 动作定义
      actions: [],

      # 事件定义
      # 故事中的场景事件暂时没什么意义
      events: [],


    
      chats: [
      #


       { 
        id: 'WZXX_M1_N1_C0018_VA1', desc: '对话', 
        options: [ 
          { title: "【继续联系】",dialogs: ['C0018A_duihuaB'], icon: { id: 1, bindVar: 'biaoqianv1' }, varsOn: ['biaoqianv1']},

      
        ],
      },




        ],


      # 对话框
      dialogs:
        [



     {   id: 'C0018A_duihuaB',
          style: 8, title: '陶老对话', textAnimationType: 'TextSingle', dialogType: 'HalfScreen', isBubbleColor: true,
          sections: [
            {
              key: 'p1',
              dialog: [
                { id: '01', content: ['@吾才是本尊','我是李森炎，你是不是骗了我？没做标记的那些锻骨灵液才是你给的对吧？',], },
                { id: '05', content: ['是又怎么样？',], },
               
              ],
              btn: [
              { title: '我们无冤无仇，你为什么要这样做？',dropIds: ['WZXX_M1_N1_C0018_VA_Vdrop1'], tokey: "p2"},
              { title: '我差点死了！你这是赤果果的谋杀！', dropIds: ['WZXX_M1_N1_C0018_VA_Vdrop2'],tokey: "p3"},
              { title: '没想到我没事吧？想害我？没那么容易',dropIds: ['WZXX_M1_N1_C0018_VA_Vdrop3'], tokey: "p4"},
              ]
            },
            {
              key: 'p2',
              dialog: [
                { id: '01', content: ['我们无冤无仇，你为什么要这样做？',], },
                { id: '02', content: ['@吾才是本尊，你都干了些什么？',], },
                { id: '05', content: ['我设了个局，让他用了筑基期才能使用的锻骨灵液',], },
                { id: '02', content: ['？？？你怎能如此丧心病狂？！',], },
                { id: '03', content: ['@吾才是本尊，这就是你的不对了，虽然我不认同他，但也没必要这么搞他。',], },
                { id: '05', content: ['我本来可以直接换了你的锻骨灵液，不过还是用了个小小伎俩，想看看你会不会相信我，果然，事实证明，你根本不相信我说的话。',], },
                { id: '02', content: ['欲使人信，必先有信。',], },
                { id: '03', content: ['+1',], },
                { id: '04', content: ['+1',], },
                { id: '05', content: ['你们不用这样，我并不觉得自己有什么错。李森炎，我就问你一个问题，你现在是不是没死？是不是比之前大有进步？',], },
                { id: '01', content: ['确实有……','但这过程未免也太痛苦了吧','我可是差点死掉了啊喂！',], },
                { id: '05', content: ['@陶老本尊@为老不尊，我告诉你们，像他这样的，只要练了死不了，就往死了练，必须下猛药，毕竟留给我们的时间不多了！',], },
                { id: '01', content: ['@吾才是本尊，你有没有想过，万一我这人被你练废了呢？',], },
                { id: '05', content: ['那再练一个就是了。',], },

              ],
              btn: [
              { title: '但你也不能拿我的命来开玩笑', dropIds: ['WZXX_M1_N1_C0018_VA_Vdrop4'],tokey: "p5"},
              { title: '再练一个难道就不需时间吗？', dropIds: ['WZXX_M1_N1_C0018_VA_Vdrop5'], tokey: "p6"},
              { title: '用什么方式来修炼是我的自由！', dropIds: ['WZXX_M1_N1_C0018_VA_Vdrop6'], tokey: "p7"},
              ]

              
            },

            {
              key: 'p3',
              dialog: [
                { id: '01', content: ['我差点死了！你这是赤果果的谋杀！',], },
                { id: '02', content: ['@吾才是本尊，你都干了些什么？',], },
                { id: '05', content: ['我设了个局，让他用了筑基期才能使用的锻骨灵液',], },
                { id: '02', content: ['？？？你怎能如此丧心病狂？！',], },
                { id: '03', content: ['@吾才是本尊，这就是你的不对了，虽然我不认同他，但也没必要这么搞他。',], },
                { id: '05', content: ['我本来可以直接换了你的锻骨灵液，不过还是用了个小小伎俩，想看看你会不会相信我，果然，事实证明，你根本不相信我说的话。',], },
                { id: '02', content: ['欲使人信，必先有信。',], },
                { id: '03', content: ['+1',], },
                { id: '04', content: ['+1',], },
                { id: '05', content: ['你们不用这样，我并不觉得自己有什么错。李森炎，我就问你一个问题，你现在是不是没死？是不是比之前大有进步？',], },
                { id: '01', content: ['确实有……','但这过程未免也太痛苦了吧','我可是差点死掉了啊喂！',], },
                { id: '05', content: ['@陶老本尊@为老不尊，我告诉你们，像他这样的，只要练了死不了，就往死了练，必须下猛药，毕竟留给我们的时间不多了！',], },
                { id: '01', content: ['@吾才是本尊，你有没有想过，万一我这人被你练废了呢？',], },
                { id: '05', content: ['那再练一个就是了。',], },
              ],
              btn: [
              { title: '但你也不能拿我的命来开玩笑', dropIds: ['WZXX_M1_N1_C0018_VA_Vdrop4'], tokey: "p5"},
              { title: '再练一个难道就不需时间吗？', dropIds: ['WZXX_M1_N1_C0018_VA_Vdrop5'], tokey: "p6"},
              { title: '用什么方式来修炼是我的自由！',dropIds: ['WZXX_M1_N1_C0018_VA_Vdrop6'],  tokey: "p7"},
              ]
            },

            {
              key: 'p4',
              dialog: [
                { id: '01', content: ['没想到我没事吧？想害我？没那么容易',], },
                { id: '02', content: ['@吾才是本尊，你都干了些什么？',], },
                { id: '05', content: ['我设了个局，让他用了筑基期才能使用的锻骨灵液',], },
                { id: '02', content: ['？？？你怎能如此丧心病狂？！',], },
                { id: '03', content: ['@吾才是本尊，这就是你的不对了，虽然我不认同他，但也没必要这么搞他。',], },
                { id: '05', content: ['我本来可以直接换了你的锻骨灵液，不过还是用了个小小伎俩，想看看你会不会相信我，果然，事实证明，你根本不相信我说的话。',], },
                { id: '02', content: ['欲使人信，必先有信。',], },
                { id: '03', content: ['+1',], },
                { id: '04', content: ['+1',], },
                { id: '05', content: ['你们不用这样，我并不觉得自己有什么错。李森炎，我就问你一个问题，你现在是不是没死？是不是比之前大有进步？',], },
                { id: '01', content: ['确实有……','但这过程未免也太痛苦了吧','我可是差点死掉了啊喂！',], },
                { id: '05', content: ['@陶老本尊@为老不尊，我告诉你们，像他这样的，只要练了死不了，就往死了练，必须下猛药，毕竟留给我们的时间不多了！',], },
                { id: '01', content: ['@吾才是本尊，你有没有想过，万一我这人被你练废了呢？',], },
                { id: '05', content: ['那再练一个就是了。',], },

              ],
              btn: [
              { title: '但你也不能拿我的命来开玩笑',dropIds: ['WZXX_M1_N1_C0018_VA_Vdrop4'], tokey: "p5"},
              { title: '再练一个难道就不需时间吗？',dropIds: ['WZXX_M1_N1_C0018_VA_Vdrop5'], tokey: "p6"},
              { title: '用什么方式来修炼是我的自由！', dropIds: ['WZXX_M1_N1_C0018_VA_Vdrop6'], tokey: "p7"},
              ]

              
            },

             {
              key: 'p5',
              dialog: [
                { id: '01', content: ['@吾才是本尊，但你也不能拿我的命来开玩笑',], },
                { id: '05', content: ['……',], },
                { id: '03', content: ['怎么说，这种拿别人命来开玩笑的事情就是不对。',], },
                { id: '03', content: ['……',], },
                { id: '02', content: ['……',], },
              ],
              btn: [
              { title: '解气！', toChapter: "WZXX_M1_N1_C018_[N2]"},
              ]
            },

            {
              key: 'p6',
              dialog: [

                { id: '01', content: ['再练一个难道就不需时间吗？你不是说时间不多了吗？',],},
                { id: '03', content: ['也是，他说的是事实',], },
                { id: '02', content: ['众所周知，练号是最废时间的一件事，尤其是练大号',], },
                { id: '05', content: ['……',], },
              ],
              btn: [
              { title: '解气！', toChapter: "WZXX_M1_N1_C018_[N2]"},
              ]
            },

            {
              key: 'p7',
              dialog: [

                { id: '01', content: ['用什么方式来修炼由我自己来选择，不需要你帮我做决定！',],},
                { id: '03', content: ['确实，人家想用快捷的方法还是循序渐进的方法都是人家的事情',], },
                { id: '02', content: ['修仙一途最忌过度干涉',], },
                { id: '05', content: ['……',], },
              ],
              btn: [
              { title: '解气！', toChapter: "WZXX_M1_N1_C018_[N2]"},
              ]
            },
            
          ]
        }


        

  ]

  
    }
]