scenes: [
    #
    {
      id: 'WZXX_M1_N1_CC035_V',
      name: "定义对应标题名当前章节内的选项和变量",

      # 变量定义
      vars: [
      { id: "v1", min: 0, max: 1 },
      { id: "v2", min: 0, max: 1 },
      { id: "v3", min: 0, max: 1 },
      { id: "biaoqianv1", min: 0, max: 1 } ,
      { id: "biaoqianv2", min: 0, max: 1 } ,
      { id: "biaoqianv3", min: 0, max: 1 } ,
      { id: "biaoqianv4", min: 0, max: 1 } ,
      { id: "biaoqianv5", min: 0, max: 1 } ,
      { id: "biaoqianv6", min: 0, max: 1 } ,
      { id: "biaoqianv7", min: 0, max: 1 } ,
      { id: "biaoqianv8", min: 0, max: 1 } ,
      ],

      # 动作定义
      actions: [],

      # 事件定义
      # 故事中的场景事件暂时没什么意义
      events: [
      ],
    
      chats: [
      
      {
        id: 'WZXX_M1_N1_CC035_V1', desc: '柳家', 
        options: [
          {
          title: "【随便说一个】",dialogs: ['ZC35_1.1A'],varsOn: ['biaoqianv1',],
          icon: { id: 1, bindVar: 'biaoqianv1' }, 
          },

          {
          title: "【表明是为了抑灵丹方而来】",  varsOn: ['biaoqianv2',], dialogs: ['ZC35_1.1B'],
          icon: { id: 1, bindVar: 'biaoqianv2' }, 
          },

          {
          title: "【打探一下金丹粉的秘密】",dialogs: ['ZC35_1.1C'], 
          icon: { id: 1, bindVar: 'biaoqianv3' }, varsOn: ['biaoqianv3']
          },

        ],
      },

    
      ],


      # 对话框
      dialogs:
        [
         #选项对话
          { 
            id: 'ZC35_1.1A',style: 6, title: '随便说一个', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
            sections: [
              {
                key: 'P1', 
                content: ['“什么金丹粉？弄金丹灵液的？我不感兴趣。”李森炎说。',
                '还不知道这抑灵丹方对于柳家来说算不算秘宝。', '且看柳探才方才提到金丹粉那震怒的样子，万一这抑灵丹是个更加珍稀的宝贝，还不得……',
                '所以他决定暂不暴露，等打探清楚再交底也不迟。',],
                btn: [
                {
                title: '问一问金丹粉',
                dialogs: ['ZC35_1.1C'], 
                },
                ]
              },
            ]  
          }, 

          { 
            id: 'ZC35_1.1B',style: 6, title: '表明是为了抑灵丹方而来', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
            sections: [
              {
                key: 'P1', 
                content: ['李森炎摆摆手，“不，我此行并非是为了金丹粉而来。”',
                '闻言，柳探才颇为意外，方才怒火的脸也稍纵温和了些。',
                '“那你真的是来拜师的？”','此人算得上是奇才，若是成为自己的同僚也是不错。',
                '李森炎摇摇头，“那倒也不是，我此次前来是听闻柳府有一神丹丹方，名为抑灵丹。”','这三字一出口，柳探才瞬间脸色大变，看向李森炎的眼底深了深。',
                '见状，李森炎并未继续往下说，淡淡的看着他。','“你是为了此物而来？”',
                '李森炎点头，“有什么问题吗？”','“抑灵丹方？原来你是想要这个，你早说啊，五个灵石一份。”','李森炎：“……那你刚才这么激动作甚？！”','柳探才：“嘿嘿，吓唬吓唬你。”',],
                btn: [
                {title: '交钱，走人', 
                dialogs: ['ZC35_1.3A'] ,useProps: ['886,5'], },
                ]
              },
            ]  
          }, 

          { 
            id: 'ZC35_1.1C',style: 6, title: '打探一下金丹粉的秘密', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
            sections: [
              {
                key: 'P1', 
                content: ['李森炎皱起眉头，佯装起对金丹粉毫不知情的样子，“什么金丹粉，这是什么东西？”。',
                '柳探凝着他，颇为意外，“你不知道金丹粉？”', '李森炎耸耸肩，“自然，不如你和我说说，此物为何让你如此生气？难道柳家家主的离开也和此物有关系？”',
                '闻言，柳探才叹了一口气。','将事情缓缓道出。',],
                btn: [
                {
                title: '仔细聆听', tokey: "P2",
                },
                ]
              },

              {
                key: 'P2',
                content: ['因为金丹粉的出世，柳家成为了众矢之的，各大宗门家族上门讨要，武斗文争不断。',
                '柳氏一族无法抗衡，全票通过，将金丹粉直接归顺青岚宗了事。', '近日青岚宗派几名大弟子同他族人长老一起在众生山脉狩猎，准备赠送几枚极品元婴期妖兽的内丹给他们，作为归顺回报，同时也额外吸纳三名家族弟子作为正式弟子。',
                '须知，青岚宗是九大宗门，上三宗的最大宗门。其余两个上三宗，万曜宗，蓬莱仙宗加起来，也没青岚宗的实力强大。',],
                btn: [
                {
                title: '说到青岚宗……', tokey: "P3",
                },
                ]
              },

              {
                key: 'P3', 
                content: ['青岚宗原本是个名不见经传的修真门派，但造化神青帝陨灭时，他的一个极为信任的下属，借着青帝的神元普照的神威，似乎也是燃尽了一身修为，与普罗地的九个宗门达成契约——从此终身不修魔，永久保护青帝的后代子孙，换取这九个宗门的修士，不受魔修法则的影响，可以正常修真。',
                '怪不得杜海那小子要去青岚宗。', '不过，想远了，这和他又有什么关系。',
                '李森炎摇了摇头，他此行来又不是为了这所谓的金丹粉。',
                '“原来如此，情况确实复杂，不过，我只是想要抑灵丹方。”',
                '“抑灵丹方？原来你是想要这个，你早说啊，五个灵石一份。”',],
                btn: [
                {
                title: '……付钱',dialogs: ['ZC35_1.3A'] ,useProps: ['886,5'],
                },
                ]
              },

            ]  
          }, 

          #做成五号dialog （视频背景需求）
          # { 
          #   id: 'ZC35_1.3A',style: 6, title: '坊市', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
          #   sections: [
          #     {
          #       key: 'P1', 
          #       content: ['李森炎哽住，早知道这么容易，他还废这么大功夫做什么。',
          #       '拿到药方，他速速回到坊市。', '可李森炎却没想到，等到他回到坊市的时候，看到的居然是这样一副景象。',
          #       '整个坊市被狂风席卷残蚀过一般，房屋坍塌，没有一处好地，和他离开时的模样截然不同。',
          #       '昔日的房屋变成了残垣断壁，往日的山清水秀变成人间炼狱，此前车水马龙的街道现在却冷冷清清，平日的母慈子孝变成天人永隔。',
          #       '看见这景象，李森炎愣住，猛然脑海中浮现医灵的脸，他不顾一切的朝着药炉的方向狂奔而去。',
          #       '可……','药炉竟变成了一片废墟，李森炎不敢相信，使用法力在废墟中翻找。','却是什么都没有找到。',
          #       '就连医灵的气息甚至都没有了。','或者应该说，偌大的坊市，没有一丝人的气息。','寂静，无边的寂静弥漫开来，他甚至能听到自己的心跳声。',
          #       '半空中飞过一只渡鸦，仿佛在诉说这坊市的结局。','整个坊市，变成了一座，死城。','巨大的冲击，让李森炎傻站在原地，坊市到底经历了什么？',
          #       '医灵又何去何从？','他又该怎么办？',],
          #       btn: [
          #       {
          #       title: '未完待续……',
          #       },
          #       ]
          #     },
          #   ]  
          # }, 



            { 
            id: 'ZC35_1.3A',style: 5, textAnimationType: 'TextSingle',
          sections: [
              { 
                type: "TopToBottom", bgImageId: 5, loop: true, play: true,
                content: [李森炎哽住，早知道这么容易，他还废这么大功夫做什么。',
                '拿到药方，他速速回到坊市。', '可李森炎却没想到，等到他回到坊市的时候，看到的居然是这样一副景象。',
                '整个坊市被狂风席卷残蚀过一般，房屋坍塌，没有一处好地，和他离开时的模样截然不同。',
                '昔日的房屋变成了残垣断壁，往日的山清水秀变成人间炼狱，此前车水马龙的街道现在却冷冷清清，平日的母慈子孝变成天人永隔。',
                '看见这景象，李森炎愣住，猛然脑海中浮现医灵的脸，他不顾一切的朝着药炉的方向狂奔而去。',] 
              },

              { 
                type: "TopToBottom", bgImageId: 6, loop: true, play: true,
                content: ['可……','药炉竟变成了一片废墟，李森炎不敢相信，使用法力在废墟中翻找。','却是什么都没有找到。',
                '就连医灵的气息甚至都没有了。','或者应该说，偌大的坊市，没有一丝人的气息。','寂静，无边的寂静弥漫开来，他甚至能听到自己的心跳声。',
                '半空中飞过一只渡鸦，仿佛在诉说这坊市的结局。','整个坊市，变成了一座，死城。','巨大的冲击，让李森炎傻站在原地，坊市到底经历了什么？',
                '医灵又何去何从？','他又该怎么办？',
                ],
              },
            ],
             dialogs: ['gameover00'] ,
           
          },

          { id: 'gameover00',
           style: 7, artId: 2, 
           title: '坏结局',
           dialogType: 'FullScreen', 
           textAnimationType: 'TextFadeIn', 
           sections: [
           { key: 'p1', content: ['坏结局'], btn: [{title: '确定（后续剧情敬请期待）',}, ]},
           ],
         },

        ],
    }
]
