scenes: [
    #
    {
      id: 'WZXX_M1_N1_ZC11_V',
      name: "定义对应标题名当前章节内的选项和变量",

      # 变量定义
      vars: [{ id: "v1", min: 0, max: 1 },
      { id: "biaoqianv1", min: 0, max: 1 } ,
      { id: "biaoqianv2", min: 0, max: 1 } ,
      { id: "biaoqianv3", min: 0, max: 1 } ,
      { id: "biaoqianv4", min: 0, max: 1 } ,
      { id: "biaoqianv5", min: 0, max: 1 } ,
      { id: "biaoqianv6", min: 0, max: 1 } ,
      { id: "biaoqianv7", min: 0, max: 1 } ,
      { id: "biaoqianv8", min: 0, max: 1 } ,
      ],

      # 动作定义
      actions: [],

      # 事件定义
      # 故事中的场景事件暂时没什么意义
      events: [
      ],


    
      chats: [
      #
      { 
        id: 'WZXX_M1_N1_ZC11_V1', desc: '味道', 
        options: [ 
          { 
          title: "【这次是谁】",dialogs: ['C0051A_1.1A'],
           icon: { id: 1, bindVar: 'biaoqianv1' }, varsOn: ['biaoqianv1']
          },
        ],
      },

     

     

        ],

      # 对话框
      dialogs:
        [


         #选项对话
          { 
            id: 'C0051A_1.1A',style: 6, title: '是谁？', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
            sections: [
              {
                key: 'P1', 
                content: ['李森炎，觉得那种气味越来越怪。','这气味儿本身并不重', 
                '只是修行者的敏锐让人不得不在意。',
                '直接神识扫描可是扫描不到气味的，你要真能发现那就只能靠闻。','但别瞎说了，怎么可能刻意去闻啊！！！',
                '虽然会有些得罪人，要不，猜一个？',],
                btn: [
                {
                title: '赵掌柜，是你吗？',dialogs: ['C0051A_1.2A'],
                icon: { id: 1, bindVar: 'biaoqianv2' }, varsOn: ['biaoqianv2']
                },
                {
                title: '斗笠人，是你吗？',dialogs: ['C0051A_1.2B'],
                icon: { id: 1, bindVar: 'biaoqianv3' }, varsOn: ['biaoqianv3']
                },
                {
                title: '胖商人，是你吗？',dialogs: ['C0051A_1.2C'],
                icon: { id: 1, bindVar: 'biaoqianv4' }, varsOn: ['biaoqianv4']
                },
                {
                title: '白书生，是你吗？',dialogs: ['C0051A_1.2D'],
                icon: { id: 1, bindVar: 'biaoqianv5' }, varsOn: ['biaoqianv5']
                },
                {
                title: '夏姑娘，是你吗？',dialogs: ['C0051A_1.2E'],
                icon: { id: 1, bindVar: 'biaoqianv6' }, varsOn: ['biaoqianv6']
                },
                ]
              },
            ]  
          },

          { 
            id: 'C0051A_1.1B',style: 6, title: '是谁？', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
            sections: [
              {
                key: 'P1', 
                content: [
                '虽然会有些得罪人，要不，猜一个？','到底会是谁呢？',],
                btn: [
                {
                title: '赵掌柜，是你吗？',dialogs: ['C0051A_1.2A'],
                icon: { id: 1, bindVar: 'biaoqianv2' }, varsOn: ['biaoqianv2']
                },
                {
                title: '斗笠人，是你吗？',dialogs: ['C0051A_1.2B'],
                icon: { id: 1, bindVar: 'biaoqianv3' }, varsOn: ['biaoqianv3']
                },
                {
                title: '胖商人，是你吗？',dialogs: ['C0051A_1.2C'],
                icon: { id: 1, bindVar: 'biaoqianv4' }, varsOn: ['biaoqianv4']
                },
                {
                title: '白书生，是你吗？',dialogs: ['C0051A_1.2D'],
                icon: { id: 1, bindVar: 'biaoqianv5' }, varsOn: ['biaoqianv5']
                },
                {
                title: '夏姑娘，是你吗？',dialogs: ['C0051A_1.2E'],
                icon: { id: 1, bindVar: 'biaoqianv6' }, varsOn: ['biaoqianv6']
                },
                ]
              },
            ]  
          },

          { 
            id: 'C0051A_1.2A',style: 6, title: '赵掌柜，是你吗？', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
            sections: [
              {
                key: 'P1', 
                content: ['“赵掌柜，是你吗？”','要说距离李森炎最近的，就数赵掌柜莫属。', 
                '怕不是刚才赵掌柜那念咒没念成功？','有可能啊，极有可能。','但要真这样，你去揭穿不就是给赵掌柜丢面子？',
                '你个棒槌，别人面子有了关我李森炎什么事。','开喷。','“那什么，赵掌柜啊，你确定刚才的法术成功了吗？”','赵掌柜：？？什么情况。',
                '“我为什么觉得这味道还有呢。”','赵掌柜一听，随即拿手一闻，没有味道啊……',
                '“等下，虽然我没有味道，但是还有味！”','赵掌柜紧张的望向李森炎。',],
                btn: [
                {
                title: '重选<<<',dialogs: ['C0051A_1.1B'],
                },
                
                ]
              },
            ]  
          },

          { 
            id: 'C0051A_1.2B',style: 6, title: '斗笠人，是你吗？', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
            sections: [
              {
                key: 'P1', 
                content: ['李森炎望向斗笠人，这人是个不喜欢说话的。','如果不是刻意遮掩，这人也不会那么显眼。', 
                '难道是因为不善沟通，身上有味就不说了吗？','这就太搞了。','这斗笠人一看就不好惹，搞不好会被打一顿的样子。',
                '“这位戴斗笠的兄弟，你身上有味道吗？”','开喷。','……','被瞪眼！……',
                '不好意思啊。','……',
                '应该不是的样子！',],
                btn: [
                {
                title: '重选<<<',dialogs: ['C0051A_1.1B'],
                },
                
                ]
              },
            ]  
          },

           { 
            id: 'C0051A_1.2C',style: 6, title: '胖商人，是你吗？', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
            sections: [
              {
                key: 'P1', 
                content: ['仔细想想，李森炎刚刚和胖商人学了清洁法术。','这次的味道会是胖商人吗？', 
                '难道是刚才的清洁术无效？','这就很坑了啊。','反正是瞎蒙的，先找关系好的问一下不亏。',
                '想好了。','李森炎发问。','“你的清洁术是不是没效果啊？”','胖商人一脸疑惑，“我不刚教会你使用吗？”',
                '“你不也用过了？”','“怎么就没效了？”',
                '李森炎：“要不您再闻闻身上气味看看？”','胖商人有些不爽，“你这是瞧不起我。”','虽说如此胖商人还是闻了下衣服。'
                ,'怎么，怎么又有味道了？',
                '李森炎：……？',],
                btn: [
                {
                title: '就是你',toChapter: "WZXX_M1_N1_Z2C12",
                },
                
                ]
              },
            ]  
          },

          { 
            id: 'C0051A_1.2D',style: 6, title: '白书生，是你吗？', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
            sections: [
              {
                key: 'P1', 
                content: ['李森炎把目光朝向了白书生。','这人刚才就离席了。', 
                '那么现在会不会。','白书生：“不是我。”','李森炎？',
                '白书生：“看你眼神我就知道你想什么。”','李森炎欲言又止。',],
                btn: [
                {
                title: '重选<<<',dialogs: ['C0051A_1.1B'],
                },
                
                ]
              },
            ]  
          },

          { 
            id: 'C0051A_1.2E',style: 6, title: '夏姑娘，是你吗？', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
            sections: [
              {
                key: 'P1', 
                content: ['李森炎目光望向夏姑娘。','夏姑娘从开始的疑惑变为气愤。', 
                '“你小子竟然怀疑到姑奶奶我头上。”','“哎呀！”','李森炎脑子被敲了个脑瓜崩。',
                '竟然没法躲！','这夏姑娘也是个强人。','这下亏大了。','哎呦！','“不再打你下，感觉不解恨！”',],
                btn: [
                {
                title: '重选<<<',dialogs: ['C0051A_1.1B'],
                },
                
                ]
              },
            ]  
          },
         

         
        ],


    }
]
