scenes: [
    #策划手动配的
    {
      id: "WZXX_[Chapters]",
      name: "一些章节的变量放在这里集中管理",

      # 变量定义 ，每个章节默认对应一个变量，主要用于分支,章节解锁的检测,
      vars: [
           #第一卷
          { id: "WZXX_M1_N1_C001", min: 0, max: 1 },
          { id: "WZXX_M1_N1_C001FZ", min: 0, max: 1 },

          { id: "WZXX_M1_N1_C001A", min: 0, max: 1 },
          { id: "WZXX_M1_N1_C001AFZ", min: 0, max: 1 },

          { id: "WZXX_M1_N1_C001B_[A1]", min: 0, max: 1 },
          { id: "WZXX_M1_N1_C001B_[A1]FZ", min: 0, max: 1 },

          { id: "WZXX_M1_N1_C001B_[B1]", min: 0, max: 1 },
          { id: "WZXX_M1_N1_C001B_[B1]FZ", min: 0, max: 1 },

          { id: "WZXX_M1_N1_C001B_[B2]", min: 0, max: 1 },
          { id: "WZXX_M1_N1_C001B_[B2]FZ", min: 0, max: 1 },

          { id: "WZXX_M1_N1_C001B_[C1]", min: 0, max: 1 },
          { id: "WZXX_M1_N1_C001B_[C1]FZ", min: 0, max: 1 },

          { id: "WZXX_M1_N1_C001B_[C2]", min: 0, max: 1 },
          { id: "WZXX_M1_N1_C001B_[C2]FZ", min: 0, max: 1 },

          { id: "WZXX_M1_N1_C001B_[C3]", min: 0, max: 1 },
          { id: "WZXX_M1_N1_C001B_[C3]FZ", min: 0, max: 1 },
     

          { id: "WZXX_M1_N1_C001B_[N1]", min: 0, max: 1 },
          { id: "WZXX_M1_N1_C001B_[N1]FZ", min: 0, max: 1 },

          { id: "WZXX_M1_N1_C001B", min: 0, max: 1 },
          { id: "WZXX_M1_N1_C001BFZ", min: 0, max: 1 },

          { id: "WZXX_M1_N1_C001C_[N1]", min: 0, max: 1 },
          { id: "WZXX_M1_N1_C001C_[N1]FZ", min: 0, max: 1 },

          { id: "WZXX_M1_N1_C001C_[N2]", min: 0, max: 1 },
          { id: "WZXX_M1_N1_C001C_[N2]FZ", min: 0, max: 1 },

          { id: "WZXX_M1_N1_C001C_[N3]", min: 0, max: 1 },
          { id: "WZXX_M1_N1_C001C_[N3]FZ", min: 0, max: 1 },

          { id: "WZXX_M1_N1_C001C", min: 0, max: 1 },
          { id: "WZXX_M1_N1_C001CFZ", min: 0, max: 1 },
           #
          { id: "WZXX_M1_N1_C002_[N1]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C002_[N1]FZ",min: 0, max: 1 },

          # { id: "WZXX_M1_N1_C002_[N2]",min: 0, max: 1 },
          # { id: "WZXX_M1_N1_C002_[N2]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C002_[N3]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C002_[N3]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C002_[N4]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C002_[N4]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C002_[N5]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C002_[N5]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C002_[N6]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C002_[N6]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C002_[N7]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C002_[N7]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C002_[N8]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C002_[N8]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C002_[N9]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C002_[N9]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C002_[N10]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C002_[N10]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C003_[N1]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C003_[N1]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C003_[N2]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C003_[N2]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C003_[N3]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C003_[N3]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C004_[N1]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C004_[N1]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C004_[N2]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C004_[N2]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C005",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C005FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C005A",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C005AFZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C005B",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C005BFZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C005C",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C005CFZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C005D",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C005DFZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C006",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C006FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C007",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C007FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C007A",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C007AFZ",min: 0, max: 1 },

            #
          { id: "WZXX_M1_N1_C008_[N0]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C008_[N0]FZ",min: 0, max: 1 },
            #
          { id: "WZXX_M1_N1_C009_[N1]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C009_[N1]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C009_[N2]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C009_[N2]FZ",min: 0, max: 1 },

          # { id: "WZXX_M1_N1_C009_[N3]",min: 0, max: 1 },
          # { id: "WZXX_M1_N1_C009_[N3]FZ",min: 0, max: 1 },

            #
          { id: "WZXX_M1_N1_C010_[N1]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C010_[N1]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C010_[N2]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C010_[N2]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C010_[N3]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C010_[N3]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C010_[N4]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C010_[N4]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C010_[N5]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C010_[N5]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C010_[N6]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C010_[N6]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C010_[N7]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C010_[N7]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C010_[N8]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C010_[N8]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C010_[N9]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C010_[N9]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C010_[N10]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C010_[N10]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C010_[N11]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C010_[N11]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C010_[N12]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C010_[N12]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C010_[N13]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C010_[N13]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C011_[N1]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C011_[N1]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C011_[N2]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C011_[N2]FZ",min: 0, max: 1 },
        
          { id: "WZXX_M1_N1_C012_[N1]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C012_[N1]FZ",min: 0, max: 1 },
          
          { id: "WZXX_M1_N1_C012_[N2]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C012_[N2]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C013_[N1]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C013_[N1]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C013_[N2]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C013_[N2]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C013_[N3]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C013_[N3]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C013_[N4]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C013_[N4]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C014_[N1]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C014_[N1]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C014A",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C014AFZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C015_[N1]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C015_[N1]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C015_[N2]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C015_[N2]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C015_[N3]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C015_[N3]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C015_[N4]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C015_[N4]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C015_[N5]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C015_[N5]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C015_[V1]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C015_[V1]FZ",min: 0, max: 1 },


          { id: "WZXX_M1_N1_C016_[N1]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C016_[N1]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C016_[N2]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C016_[N2]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C016_[N3]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C016_[N3]FZ",min: 0, max: 1 },
          #
          { id: "WZXX_M1_N1_C017_[N1]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C017_[N1]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C017_[N2]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C017_[N2]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C018_[N1]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C018_[N1]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C018_[N2]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C018_[N2]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C019_[N1]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C019_[N1]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C019_[N2]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C019_[N2]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C020",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C020FZ",min: 0, max: 1 },
            #
          { id: "WZXX_M1_N1_C021",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C021FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C022_[N1]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C022_[N1]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C023_[N1]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C023_[N1]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C023_[N2]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C023_[N2]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C024_[N1]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C024_[N1]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C025",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C025FZ",min: 0, max: 1 },

        #现实世界
          { id: "WZXX_M1_N1_C988",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C988FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C989",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C989FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C990",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C990FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C991",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C991FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C992",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C992FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C993",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C993FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C994",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C994FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C995",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C995FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C996",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C996FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C997",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C997FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C998",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C998FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C999",min: 0, max: 1 },

          { id: "WZXX_M1_N1_C1000",min: 0, max: 1 },
          { id: "WZXX_M1_N1_C1000FZ",min: 0, max: 1 },


         #第二卷
          
          { id: "WZXX_M1_N1_Z2C01",min: 0, max: 1 },
          { id: "WZXX_M1_N1_Z2C01FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_Z2C02",min: 0, max: 1 },
          { id: "WZXX_M1_N1_Z2C02FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_Z2C03",min: 0, max: 1 },
          { id: "WZXX_M1_N1_Z2C03FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_Z2C04_[N1]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_Z2C04_[N1]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_Z2C04_[N2]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_Z2C04_[N2]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_Z2C05",min: 0, max: 1 },
          { id: "WZXX_M1_N1_Z2C05FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_Z2C06",min: 0, max: 1 },
          { id: "WZXX_M1_N1_Z2C06FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_Z2C07",min: 0, max: 1 },
          { id: "WZXX_M1_N1_Z2C07FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_Z2C08",min: 0, max: 1 },
          { id: "WZXX_M1_N1_Z2C08FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_Z2C09",min: 0, max: 1 },
          { id: "WZXX_M1_N1_Z2C09FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_Z2C10",min: 0, max: 1 },
          { id: "WZXX_M1_N1_Z2C10FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_Z2C11",min: 0, max: 1 },
          { id: "WZXX_M1_N1_Z2C11FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_Z2C12",min: 0, max: 1 },
          { id: "WZXX_M1_N1_Z2C12FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_Z2C13",min: 0, max: 1 },
          { id: "WZXX_M1_N1_Z2C13FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_Z2C14",min: 0, max: 1 },
          { id: "WZXX_M1_N1_Z2C14FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_Z2C15",min: 0, max: 1 },
          { id: "WZXX_M1_N1_Z2C15FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_Z2C16",min: 0, max: 1 },
          { id: "WZXX_M1_N1_Z2C16FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_Z2C17",min: 0, max: 1 },
          { id: "WZXX_M1_N1_Z2C17FZ",min: 0, max: 1 },



           #第三卷

          { id: "WZXX_M1_N1_Z3C01",min: 0, max: 1 },
          { id: "WZXX_M1_N1_Z3C01FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_Z3C02",min: 0, max: 1 },
          { id: "WZXX_M1_N1_Z3C02FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_Z3C03",min: 0, max: 1 },
          { id: "WZXX_M1_N1_Z3C03FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_Z3C04",min: 0, max: 1 },
          { id: "WZXX_M1_N1_Z3C04FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_Z3C05",min: 0, max: 1 },
          { id: "WZXX_M1_N1_Z3C05FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_Z3C10_[N1]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_Z3C10_[N1]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_Z3C10_[N2]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_Z3C10_[N2]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_Z3C11",min: 0, max: 1 },
          { id: "WZXX_M1_N1_Z3C11FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_Z3C12",min: 0, max: 1 },
          { id: "WZXX_M1_N1_Z3C12FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_Z3C13",min: 0, max: 1 },
          { id: "WZXX_M1_N1_Z3C13FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_Z3C14",min: 0, max: 1 },
          { id: "WZXX_M1_N1_Z3C14FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_Z3C15",min: 0, max: 1 },
          { id: "WZXX_M1_N1_Z3C15FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_Z3C16",min: 0, max: 1 },
          { id: "WZXX_M1_N1_Z3C16FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_Z3C17",min: 0, max: 1 },
          { id: "WZXX_M1_N1_Z3C17FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_Z3C18",min: 0, max: 1 },
          { id: "WZXX_M1_N1_Z3C18FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_Z3C20",min: 0, max: 1 },
          { id: "WZXX_M1_N1_Z3C20FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_Z3C21",min: 0, max: 1 },
          { id: "WZXX_M1_N1_Z3C21FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_Z3C22",min: 0, max: 1 },
          { id: "WZXX_M1_N1_Z3C22FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_Z3C23",min: 0, max: 1 },
          { id: "WZXX_M1_N1_Z3C23FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_Z3C24",min: 0, max: 1 },
          { id: "WZXX_M1_N1_Z3C24FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_Z3C25",min: 0, max: 1 },
          { id: "WZXX_M1_N1_Z3C25FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_Z3C26",min: 0, max: 1 },
          { id: "WZXX_M1_N1_Z3C26FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_Z3C27",min: 0, max: 1 },
          { id: "WZXX_M1_N1_Z3C27FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_Z3C28",min: 0, max: 1 },
          { id: "WZXX_M1_N1_Z3C28FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_Z3C30",min: 0, max: 1 },
          { id: "WZXX_M1_N1_Z3C30FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_Z3C31_[N1]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_Z3C31_[N1]FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_Z3C31_[N2]",min: 0, max: 1 },
          { id: "WZXX_M1_N1_Z3C31_[N2]FZ",min: 0, max: 1 },


          { id: "WZXX_M1_N1_Z3C93",min: 0, max: 1 },
          { id: "WZXX_M1_N1_Z3C93FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_Z3C94",min: 0, max: 1 },
          { id: "WZXX_M1_N1_Z3C94FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_Z3C95",min: 0, max: 1 },
          { id: "WZXX_M1_N1_Z3C95FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_Z3C96",min: 0, max: 1 },
          { id: "WZXX_M1_N1_Z3C96FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_Z3C97",min: 0, max: 1 },
          { id: "WZXX_M1_N1_Z3C97FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_Z3C98",min: 0, max: 1 },
          { id: "WZXX_M1_N1_Z3C98FZ",min: 0, max: 1 },

          { id: "WZXX_M1_N1_Z3C99",min: 0, max: 1 },
          { id: "WZXX_M1_N1_Z3C99FZ",min: 0, max: 1 },
        
        ],

      #
      # 动作定义
      actions: [],

      # 事件定义
      # 故事中的场景事件暂时没什么意义
      events: [],

      # 对话选项
      chats: [
          #
          { id: "WZXX_ChaptersVar ", desc: "选项", options: [] },
        ],

      # 对话框
      dialogs: [],
    },
  ]
