scenes: [
    #
    {
      id: 'WZXX_M1_N1_C005_VA',
      name: "定义对应标题名当前章节内的选项和变量",

      # 变量定义
      vars: [{ id: "v1", min: 0, max: 1 }],

      # 动作定义
      actions: [],

      # 事件定义
      # 故事中的场景事件暂时没什么意义
      events: [],


    
      chats: [
      #

      { 
        id: 'WZXX_M1_N1_C005_VA1', desc: '挽留云云', 
        options: [ 
          { title: "【挽留云云】",dialogs: ['C005A_yunyunA']},
          { title: "【爱走走，我一人足矣】",dialogs: ['C005A_yunyunB']},
        ],
      },


        ],


      # 对话框
      dialogs:
        [




           #选项对话
          { id: 'C005A_yunyunA',style: 6, title: '守夜', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
          sections: [
          { key: 'P1', content: ['阿云别走！','留下来！','陪我！',
          '你深情挽留，却直接被云云无视，她直接开窗，飘向北方','看着义薄如纸的云云离自己远去，你只能独自一人守在医灵的闺房门口','明明没有风，却感觉很凉','心凉','但很快，你就不只是心凉了',
          [{ sounds: [{ soundId: 'SE_CQ_0010',}] }] ,'陡然间，有一股阴寒之气，从你身后的门缝窜出来，沿着你的双脚向上攀升','像一双冰冷的手，轻轻抚上你的后背',['边缘闪烁白'],'你打了个激灵，这股阴寒之气，显然是里面的医灵传出来的','不愧是阴灵根，果然够阴！','请选择是否关心医灵——',
          ],
          btn: [{title: '关心',tokey: "P2"},{title: '不关心',tokey: "P3"}]},

          { key: 'P2', content: ['“要不要叫人给你多烧几个火炉啊！”','（医灵好感度+1）','帮人帮到底，送佛送到西，你提议多添上几个火炉','不仅仅是为了医灵不被冻成冷鲜，更是为了自己，你整个后半身都快冻僵了！',
          '“你还是先管好你自己，别让我给你烧纸钱吧。”','房间里传出医灵冰冷的话语，你撇了撇嘴，这属实是好心被当成驴肝肺了！','“公子啊，她不解风情，我就不一样了。”',['边缘闪烁红'],'耳边突然传来一声妩媚入骨的声音',[{ sounds: [{ soundId: 'SE_CQ_0015',}] }] ,'你回过头，一个身穿红衣的女灵漂浮在他的面前，赤着双足，面容惨白，丝毫没有半点人色，眼窝深陷，双眼犹如两个黑洞，没有眼球',[{ sounds: [{ soundId: 'SE_CQ_0012',},],}, ],
          '这属实是比背影杀手还恐怖的声音杀手，一般人见了肯定要疯','不过你早有心理准备，神情还算平静','幸好前世恐怖片看得多，精神早就经历过各种恐怖场面的洗礼，才能这般淡定','你开口：“富强民主文明和谐自由平等公正法治爱国敬业友善。”','红衣女灵：“？？？”','“公子，你是在念咒语吗？我可不怕哦。”','红衣女灵轻笑一声',],
          btn: [{title: '继续念不要停',tokey: "P4",},{title: '不念了',toChapter: "WZXX_M1_N1_C010_[V1][N2]"},]},

          { key: 'P3', content: ['你缩了缩身子，冷的打了个颤','“公子啊，你冷不冷啊~”',['边缘闪烁红'],'耳边突然传来一声妩媚入骨的声音',[{ sounds: [{ soundId: 'SE_CQ_0015',}] }] ,'你回过头，一个身穿红衣的女灵漂浮在他的面前，赤着双足，面容惨白，丝毫没有半点人色，眼窝深陷，双眼犹如两个黑洞，没有眼球',
          '这属实是比背影杀手还恐怖的声音杀手，一般人见了肯定要疯','不过你早有心理准备，神情还算平静','幸好前世恐怖片看得多，精神早就经历过各种恐怖场面的洗礼，才能这般淡定','你开口：“富强民主文明和谐自由平等公正法治爱国敬业友善。”','红衣女灵：“？？？”','“公子，你是在念咒语吗？我可不怕哦。”','红衣女灵轻笑一声',],
          btn: [{title: '继续念不要停',tokey: "P4",},{title: '不念了',toChapter: "WZXX_M1_N1_C010_[V1][N2]"},]},

          { key: 'P4', content: ['你：“富强民主文明和谐自由平等公正法治爱国敬业友善！”','“……？”','女灵有些不耐烦了：“公子，我说过了我不怕，你别念了。”',],
          btn: [{title: '再念一遍',tokey: "P5",},]},

          { key: 'P5', content: ['你：“富强民主文明和谐自由平等公正法治爱国敬业友善！”','女灵脸色已经开始变了：“我叫你别念了！”',['边缘闪烁白'],],
          btn: [{title: '根本停不下来',toChapter: "WZXX_M1_N1_C010_[V2][N2]"},]},

         
           ]  
        },



          #选项对话2
          { id: 'C005A_yunyunB',style: 6, title: '守夜2', dialogType: 'FullScreen', textAnimationType: 'TextFadeIn',
          sections: [
          { key: 'P6', content: ['看着云云从窗口直接飘向北方，你面无表情',
          '还能怎么样，只能祝她“平安”了','可千万不要遇到什么阴风怪风，把她给吹散了！','你叹了口气，这破云是指望不上了，还得靠自己', [{ sounds: [{ soundId: 'SE_CQ_0010',}] }] ,'陡然间，有一股阴寒之气，从你身后的门缝窜出来，沿着你的双脚向上攀升','像一双冰冷的手，轻轻抚上你的后背','你打了个激灵，这股阴寒之气，显然是里面的医灵传出来的','不愧是阴灵根，果然够阴！','请选择是否关心医灵——',
          ],
          btn: [{title: '关心',tokey: "P2"},{title: '不关心',tokey: "P3"}]},

          { key: 'P2', content: ['“要不要叫人给你多烧几个火炉啊！”','（医灵好感度+1）','帮人帮到底，送佛送到西，你提议多添上几个火炉','不仅仅是为了医灵不被冻成冷鲜，更是为了自己，你整个后半身都快冻僵了！',
          '“你还是先管好你自己，别让我给你烧纸钱吧。”','房间里传出医灵冰冷的话语，你撇了撇嘴，这属实是好心被当成驴肝肺了！','“公子啊，她不解风情，我就不一样了。”',['边缘闪烁红'],'耳边突然传来一声妩媚入骨的声音',[{ sounds: [{ soundId: 'SE_CQ_0015',}] }] ,'你回过头，一个身穿红衣的女灵漂浮在他的面前，赤着双足，面容惨白，丝毫没有半点人色，眼窝深陷，双眼犹如两个黑洞，没有眼球',
          [{ sounds: [{ soundId: 'SE_CQ_0012',},],}, {animations: {id: 3} }],'这属实是比背影杀手还恐怖的声音杀手，一般人见了肯定要疯','不过你早有心理准备，神情还算平静','幸好前世恐怖片看得多，精神早就经历过各种恐怖场面的洗礼，才能这般淡定','你开口：“富强民主文明和谐自由平等公正法治爱国敬业友善。”','红衣女灵：“？？？”','“公子，你是在念咒语吗？我可不怕哦。”','红衣女灵轻笑一声',],
          btn: [{title: '继续念不要停',tokey: "P4",},{title: '不念了',toChapter: "WZXX_M1_N1_C010_[V1][N2]"}]},

          { key: 'P3', content: ['你缩了缩身子，冷的打了个颤','“公子啊，你冷不冷啊~”',['边缘闪烁红'],'耳边突然传来一声妩媚入骨的声音',[{ sounds: [{ soundId: 'SE_CQ_0015',}] }] ,'你回过头，一个身穿红衣的女灵漂浮在他的面前，赤着双足，面容惨白，丝毫没有半点人色，眼窝深陷，双眼犹如两个黑洞，没有眼球',
          '这属实是比背影杀手还恐怖的声音杀手，一般人见了肯定要疯','不过你早有心理准备，神情还算平静','幸好前世恐怖片看得多，精神早就经历过各种恐怖场面的洗礼，才能这般淡定','你开口：“富强民主文明和谐自由平等公正法治爱国敬业友善。”','红衣女灵：“？？？”','“公子，你是在念咒语吗？我可不怕哦。”','红衣女灵轻笑一声',],
          btn: [{title: '继续念不要停',tokey: "P4",},{title: '不念了',toChapter: "WZXX_M1_N1_C010_[V1][N2]"},]},

          { key: 'P4', content: ['李森炎：“富强民主文明和谐自由平等公正法治爱国敬业友善！”','“……？”','女灵有些不耐烦了：“公子，我说过了我不怕，你别念了。”',],
          btn: [{title: '再念一遍',tokey: "P5",},]},

          { key: 'P5', content: ['李森炎：“富强民主文明和谐自由平等公正法治爱国敬业友善！”','女灵脸色已经开始变了：“我叫你别念了！”',],
          btn: [{title: '根本停不下来',toChapter: "WZXX_M1_N1_C010_[V2][N2]"},]},

  
           
        ],
    },


 


  ]
    }
]