scenes: [
    #
    {
      id: 'WZXX_M1_N1_C0028_V',
      name: "定义对应标题名当前章节内的选项和变量",

      # 变量定义
      vars: [{ id: "v1", min: 0, max: 1 }],

      # 动作定义
      actions: [],

      # 事件定义
      # 故事中的场景事件暂时没什么意义
      events: [],


    
      chats: [
      #

      { 
        id: 'WZXX_M1_N1_C0028_V1', desc: '雷画符', 
        options: [ 
          { title: "【准备动手准备动手】", games: { id: 5, word: ["雷"], toChapter: "WZXX_M1_N1_C028_[N1][V1]", },}
        ],
      },

      
  ]
    }
]